"""テスト説明データ（HTMLレポート表示用）"""

DESCRIPTIONS = {
    "test_base.py::TestAgentType::test_leader_types": "AgentType.CONCEPT_LEADERが'concept_leader'、DESIGN_LEADERが'design_leader'を返す",
    "test_base.py::TestAgentType::test_worker_types": "AgentType.RESEARCH_WORKERが'research_worker'、CODE_WORKERが'code_worker'を返す",
    "test_base.py::TestAgentStatus::test_all_statuses": "6種類のステータス値が存在し、それぞれの文字列値が一致する",
    "test_base.py::TestAgentContext::test_basic_context": "必須3項目(project_id, agent_id, agent_type)のみでAgentContextを生成できる",
    "test_base.py::TestAgentContext::test_context_with_options": "project_conceptとprevious_outputsを含むAgentContextを生成し値を取得できる",
    "test_base.py::TestAgentOutput::test_completed_output": "status=COMPLETEDのAgentOutputはerrorがNone、output/tokens_usedに値が入る",
    "test_base.py::TestAgentOutput::test_failed_output": "status=FAILEDのAgentOutputはerrorに文字列が入る",
    "test_base.py::TestQualityCheckSettings::test_defaults": "引数なしで生成するとenabled=True、max_retries=3になる",
    "test_base.py::TestQualityCheckSettings::test_to_dict": "to_dict()でmax_retriesがmaxRetriesにキー名変換される",
    "test_base.py::TestQualityCheckSettings::test_from_dict": "from_dict()でmaxRetriesがmax_retriesに、isHighCostがis_high_costに変換される",
    "test_exceptions.py::TestProviderUnavailableError::test_basic": "provider_id='anthropic'で生成→str()に'anthropic'を含み、recoverable=True",
    "test_exceptions.py::TestProviderUnavailableError::test_with_reason": "reason引数を渡すとstr()とreason属性にその値が含まれる",
    "test_exceptions.py::TestContextValidationError::test_basic": "ContextValidationErrorはrecoverable=False（リトライ不可）",
    "test_exceptions.py::TestContextValidationError::test_with_missing_fields": "missing_fields引数で不足フィールド名のリストを保持できる",
    "test_exceptions.py::TestCheckpointTimeoutError::test_basic": "checkpoint_id,timeout_secondsを渡すとstr()に含まれ、recoverable=True",
    "test_exceptions.py::TestQualityCheckFailedError::test_recoverable": "retry_count=1（閾値未満）の場合はrecoverable=True",
    "test_exceptions.py::TestQualityCheckFailedError::test_not_recoverable": "retry_count=3（閾値到達）の場合はrecoverable=False",
    "test_exceptions.py::TestMaxRetriesExceededError::test_basic": "operation名とmax_retriesを渡すとstr()に含まれ、recoverable=False",
    "test_exceptions.py::TestRateLimitError::test_basic": "provider_idのみで生成→recoverable=True、retry_after=None",
    "test_exceptions.py::TestRateLimitError::test_with_retry_after": "retry_after=60を渡すとstr()に'60秒後'を含み、retry_after属性=60",
    "test_retry_strategy.py::TestRetryConfig::test_defaults": "引数なしで生成→max_retries=3、base_delay=1.0、jitter=True",
    "test_retry_strategy.py::TestRetryConfig::test_custom_config": "max_retries=5,base_delay=2.0,jitter=Falseを渡すとその値が設定される",
    "test_retry_strategy.py::TestIsRetryableError::test_retryable_exceptions": "ProviderUnavailableError/RateLimitError/ConnectionError/TimeoutErrorはTrue",
    "test_retry_strategy.py::TestIsRetryableError::test_non_retryable_exception": "ContextValidationError/ValueErrorはFalse",
    "test_retry_strategy.py::TestIsRetryableError::test_retryable_by_message": "メッセージに'rate limit'/'timeout'/'503'を含むExceptionはTrue",
    "test_retry_strategy.py::TestCalculateDelay::test_exponential_backoff": "base_delay=1.0,exponential_base=2.0,jitter=Falseでattempt0→1.0、1→2.0、2→4.0",
    "test_retry_strategy.py::TestCalculateDelay::test_max_delay": "max_delay=30.0の場合、計算値が30を超えても30.0を返す",
    "test_retry_strategy.py::TestCalculateDelay::test_retry_after": "retry_after=60を渡すと計算値に関係なく60.0を返す",
    "test_retry_strategy.py::TestRetryWithBackoff::test_success_first_try": "初回成功時→リトライなしで結果を返し、呼び出し回数は1回",
    "test_retry_strategy.py::TestRetryWithBackoff::test_success_after_retry": "1回目ConnectionError、2回目成功→結果を返し、呼び出し回数は2回",
    "test_retry_strategy.py::TestRetryWithBackoff::test_max_retries_exceeded": "全回失敗→MaxRetriesExceededErrorを送出",
    "test_retry_strategy.py::TestRetryWithBackoff::test_non_retryable_error": "ValueErrorはリトライせず即座にValueErrorを送出",
    "test_retry_strategy.py::TestRetryWithBackoff::test_on_retry_callback": "リトライ時にon_retryコールバックが(attempt=1, エラー型, delay)で呼ばれる",
    "test_retry_strategy.py::TestRetrySyncWithBackoff::test_success_first_try": "同期版: 初回成功時→結果'success'を返す",
    "test_retry_strategy.py::TestRetrySyncWithBackoff::test_success_after_retry": "同期版: 1回目TimeoutError、2回目成功→結果'success'を返す",
    "test_retry_strategy.py::TestRetryContext::test_record_error": "record_error()でattempt+1、total_delayに加算、errorsにエラー追加",
    "test_retry_strategy.py::TestRetryContext::test_should_retry": "max_retries=2でattempt=0→True、attempt=2→False",
    "test_retry_strategy.py::TestRetryContext::test_get_summary": "get_summary()でtotal_attempts,total_delay_seconds,errorsを含む辞書を返す",
    "test_base.py::TestChatMessage::test_to_dict": "to_dict()で{'role':'user','content':'テスト'}形式の辞書を返す",
    "test_base.py::TestChatMessage::test_system_role": "MessageRole.SYSTEMを指定するとrole属性がMessageRole.SYSTEMになる",
    "test_base.py::TestChatResponse::test_creation": "content,model,input_tokens,output_tokens,total_tokensを指定して生成できる",
    "test_base.py::TestHealthCheckResult::test_available": "available=True,latency_ms=150で生成→各属性が取得できる",
    "test_base.py::TestHealthCheckResult::test_unavailable_with_error": "available=False,error='接続エラー'で生成→error属性が取得できる",
    "test_base.py::TestHealthCheckResult::test_to_dict": "to_dict()でavailable,latency_ms,checked_at(ISO形式)を含む辞書を返す",
    "test_base.py::TestModelInfo::test_basic_model": "supports_visionを指定しない場合はFalseになる",
    "test_base.py::TestModelInfo::test_vision_model": "supports_vision=Trueを指定すると属性がTrueになる",
    "test_base.py::TestAIProviderConfig::test_defaults": "引数なしで生成→api_key=None、timeout=60、max_retries=2",
    "test_base.py::TestAIProviderConfig::test_custom_config": "api_key,base_url,timeoutを指定すると各属性に反映される",
    "test_health_monitor.py::TestProviderHealthMonitor::test_singleton": "get_health_monitor()を2回呼ぶと同一インスタンスを返す",
    "test_health_monitor.py::TestProviderHealthMonitor::test_get_all_health_status_empty": "_health_states={}の状態でget_all_health_status()→空辞書を返す",
    "test_health_monitor.py::TestProviderHealthMonitor::test_update_health_state": "_update_health_state()後にget_health_status()で同じ値を取得できる",
    "test_health_monitor.py::TestProviderHealthMonitor::test_health_change_callback": "set_health_change_callback()で登録した関数が_update_health_state()時に呼ばれる",
    "test_health_monitor.py::TestProviderHealthMonitor::test_socketio_emit": "set_socketio()後に_update_health_state()→'provider_health_changed'イベントが発行される",
    "test_health_monitor.py::TestProviderHealthMonitor::test_check_interval": "set_check_interval(30)→30、set_check_interval(3)→最小値5に制限",
    "test_registry.py::TestProviderRegistry::test_register_provider": "register(MockProvider)後にis_registered('mock')→True",
    "test_registry.py::TestProviderRegistry::test_get_provider": "get('mock')→provider_id='mock'のインスタンスを返す",
    "test_registry.py::TestProviderRegistry::test_get_nonexistent_provider": "未登録のIDでget()→Noneを返す",
    "test_registry.py::TestProviderRegistry::test_list_providers": "list_providers()→[{'id':'mock',...}]形式のリストを返す",
    "test_registry.py::TestProviderRegistry::test_clear_cache": "clear_cache()で_instancesが空になる",
    "test_registry.py::TestProviderRegistry::test_get_fresh": "get_fresh()→キャッシュと異なる新規インスタンスを返す",
    "test_registry.py::TestRegisterAllProviders::test_all_providers_registered": "register_all_providers()でanthropicからdeepseekまで7種類が登録される",
    "test_registry.py::TestShortcuts::test_get_provider_shortcut": "get_provider('mock')→ProviderRegistry.get('mock')と同じ結果",
    "test_registry.py::TestShortcuts::test_list_providers_shortcut": "list_providers()→ProviderRegistry.list_providers()と同じ結果",
    "test_api_key.py::TestApiKeyRepository::test_save_new_key": "save('anthropic','sk-test-key-12345')→key_hint='sk-...345',is_valid=False",
    "test_api_key.py::TestApiKeyRepository::test_save_update_existing": "同じprovider_idで2回save→2回目の値で上書きされる",
    "test_api_key.py::TestApiKeyRepository::test_get_nonexistent": "存在しないprovider_idでget()→Noneを返す",
    "test_api_key.py::TestApiKeyRepository::test_get_all": "2件save後にget_all()→長さ2のリストを返す",
    "test_api_key.py::TestApiKeyRepository::test_get_all_hints": "get_all_hints()→{'anthropic':{'hint':'sk-...key',...}}形式の辞書を返す",
    "test_api_key.py::TestApiKeyRepository::test_delete": "save後にdelete()→True、その後get()→None",
    "test_api_key.py::TestApiKeyRepository::test_delete_nonexistent": "存在しないprovider_idでdelete()→False",
    "test_api_key.py::TestApiKeyRepository::test_get_decrypted_key": "save()した値とget_decrypted_key()の戻り値が一致する",
    "test_api_key.py::TestApiKeyRepository::test_update_validation_status": "update_validation_status(True)後→is_valid=True、last_validated_atが設定される",
    "test_project_ai_config.py::TestProjectAiConfigRepository::test_save_new_config": "save()でproject_id,provider_id,model_idが保存される",
    "test_project_ai_config.py::TestProjectAiConfigRepository::test_save_update_existing": "同じproject_id+usage_categoryで2回save→2回目の値で上書き",
    "test_project_ai_config.py::TestProjectAiConfigRepository::test_get_nonexistent": "存在しないusage_categoryでget()→None",
    "test_project_ai_config.py::TestProjectAiConfigRepository::test_get_by_project": "2つのカテゴリでsave後にget_by_project()→長さ2のリスト",
    "test_project_ai_config.py::TestProjectAiConfigRepository::test_delete": "save後にdelete()→True、その後get()→None",
    "test_project_ai_config.py::TestProjectAiConfigRepository::test_delete_nonexistent": "存在しないusage_categoryでdelete()→False",
    "test_project_ai_config.py::TestProjectAiConfigRepository::test_delete_all_for_project": "2件save後にdelete_all_for_project()→削除件数2、get_by_project()→空リスト",
    "test_project_ai_config.py::TestProjectAiConfigRepository::test_custom_params": "custom_params={'temperature':0.8}でsave→get()で同じ値を取得",
    "test_encryption.py::TestEncryption::test_encrypt_decrypt_roundtrip": "encrypt_api_key()→decrypt_api_key()で元の文字列と一致する",
    "test_encryption.py::TestEncryption::test_different_keys_different_ciphertext": "異なる入力→異なる暗号文を返す",
    "test_encryption.py::TestEncryption::test_empty_string": "空文字''を暗号化→復号化→空文字''を返す",
    "test_encryption.py::TestEncryption::test_unicode_key": "日本語を含む文字列を暗号化→復号化→元の文字列と一致",
    "test_encryption.py::TestEncryption::test_long_key": "1000文字の長い文字列を暗号化→復号化→元の文字列と一致",
    "test_encryption.py::TestKeyHint::test_normal_key": "24文字のキー→先頭3文字+'...'+末尾3文字形式('sk-...ijk')を返す",
    "test_encryption.py::TestKeyHint::test_short_key": "5文字のキー→'***'を返す（8文字以下は隠蔽）",
    "test_encryption.py::TestKeyHint::test_exact_boundary": "8文字のキー→'***'を返す（境界値）",
    "test_encryption.py::TestKeyHint::test_just_over_boundary": "9文字のキー→'123...789'を返す（境界値+1）",
    "test_project_routes.py::TestProjectCRUD::test_list_projects_empty": "プロジェクト0件時にGET /api/projects→空配列を返す",
    "test_project_routes.py::TestProjectCRUD::test_create_project": "POST /api/projects→status=201、status='draft'のプロジェクトを作成",
    "test_project_routes.py::TestProjectCRUD::test_list_projects_with_data": "2件作成後にGET→長さ2の配列を返す",
    "test_project_routes.py::TestProjectCRUD::test_update_project": "PATCH /api/projects/{id}→名前が更新される",
    "test_project_routes.py::TestProjectCRUD::test_update_project_not_found": "存在しないIDでPATCH→404を返す",
    "test_project_routes.py::TestProjectCRUD::test_delete_project": "DELETE /api/projects/{id}→204を返し、一覧から削除される",
    "test_project_routes.py::TestProjectCRUD::test_delete_project_not_found": "存在しないIDでDELETE→404を返す",
    "test_project_routes.py::TestProjectLifecycle::test_start_project_from_draft": "draft状態でPOST /start→status='running'になる",
    "test_project_routes.py::TestProjectLifecycle::test_start_project_not_found": "存在しないIDでPOST /start→404を返す",
    "test_project_routes.py::TestProjectLifecycle::test_start_project_invalid_status": "running状態でPOST /start→400を返す",
    "test_project_routes.py::TestProjectLifecycle::test_pause_project": "running状態でPOST /pause→status='paused'になる",
    "test_project_routes.py::TestProjectLifecycle::test_pause_project_not_running": "draft状態でPOST /pause→400を返す",
    "test_project_routes.py::TestProjectLifecycle::test_resume_project": "paused状態でPOST /resume→status='running'になる",
    "test_project_routes.py::TestProjectLifecycle::test_resume_project_not_paused": "draft状態でPOST /resume→400を返す",
    "test_project_routes.py::TestProjectLifecycle::test_initialize_project": "POST /initialize→status='draft'にリセットされる",
    "test_project_routes.py::TestProjectLifecycle::test_initialize_project_not_found": "存在しないIDでPOST /initialize→404を返す",
    "test_project_routes.py::TestProjectAIServices::test_get_ai_services": "GET /ai-services→AI設定を返す",
    "test_project_routes.py::TestProjectAIServices::test_get_ai_services_not_found": "存在しないIDでGET /ai-services→404を返す",
    "test_project_routes.py::TestProjectAIServices::test_update_ai_services": "PUT /ai-services→AI設定が更新される",
    "test_project_routes.py::TestProjectAIServices::test_update_ai_service": "PATCH /ai-services/{type}→個別AI設定が更新される",
    "test_project_routes.py::TestProjectAIServices::test_update_ai_service_not_found_project": "存在しないIDでPATCH→404を返す",
    "test_project_routes.py::TestBrushup::test_brushup_completed_project": "completed状態でPOST /brushup→status='draft'になる",
    "test_project_routes.py::TestBrushup::test_brushup_not_completed": "draft状態でPOST /brushup→400を返す",
    "test_project_routes.py::TestBrushup::test_brushup_not_found": "存在しないIDでPOST /brushup→404を返す",
    "test_checkpoint_routes.py::TestListCheckpoints::test_list_checkpoints_empty": "チェックポイント0件時にGET→空配列を返す",
    "test_checkpoint_routes.py::TestListCheckpoints::test_list_checkpoints_with_data": "2件追加後にGET→長さ2の配列を返す",
    "test_checkpoint_routes.py::TestListCheckpoints::test_list_checkpoints_project_not_found": "存在しないプロジェクトでGET→404を返す",
    "test_checkpoint_routes.py::TestResolveCheckpoint::test_approve_checkpoint": "resolution='approved'でPOST→status='resolved'になる",
    "test_checkpoint_routes.py::TestResolveCheckpoint::test_reject_checkpoint": "resolution='rejected'+feedback→feedbackが保存される",
    "test_checkpoint_routes.py::TestResolveCheckpoint::test_revision_requested": "resolution='revision_requested'→修正依頼が保存される",
    "test_checkpoint_routes.py::TestResolveCheckpoint::test_invalid_resolution": "不正なresolutionでPOST→400を返す",
    "test_checkpoint_routes.py::TestResolveCheckpoint::test_checkpoint_not_found": "存在しないIDでPOST→404を返す",
    "test_checkpoint_routes.py::TestWebSocketEmission::test_resolve_emits_event": "resolve後にcheckpoint:resolvedイベントが発行される",
    "test_websocket.py::TestSocketManagerSubscription::test_add_subscription": "add_subscription()でsubscriptionsに追加される",
    "test_websocket.py::TestSocketManagerSubscription::test_remove_subscription": "remove_subscription()でsubscriptionsから削除される",
    "test_websocket.py::TestSocketManagerSubscription::test_remove_all_subscriptions": "remove_all_subscriptions()で全プロジェクトから削除される",
    "test_websocket.py::TestSocketManagerSubscription::test_get_subscribers": "get_subscribers()で購読者一覧を取得できる",
    "test_websocket.py::TestSocketManagerSubscription::test_get_subscribers_empty": "存在しないプロジェクト→空セットを返す",
    "test_websocket.py::TestWebSocketHandlers::test_register_handlers": "register_websocket_handlers()で5つのハンドラが登録される",
    "test_websocket.py::TestWebSocketHandlers::test_connect_emits_state_sync": "connect時にconnection:state_syncイベントが発行される",
    "test_websocket.py::TestWebSocketHandlers::test_disconnect_removes_subscriptions": "disconnect時にサブスクリプションが削除される",
    "test_websocket.py::TestWebSocketHandlers::test_subscribe_project_success": "subscribe:project→ルーム参加+状態同期イベント発行",
    "test_websocket.py::TestWebSocketHandlers::test_subscribe_project_not_found": "存在しないプロジェクト→error:stateイベント発行",
    "test_websocket.py::TestWebSocketHandlers::test_unsubscribe_project": "unsubscribe:project→ルーム退出+サブスクリプション削除",
    "test_websocket.py::TestCheckpointResolveHandler::test_resolve_approved": "checkpoint:resolve(approved)→checkpoint:resolvedイベント発行",
    "test_websocket.py::TestCheckpointResolveHandler::test_resolve_rejected": "checkpoint:resolve(rejected)+feedback→feedbackが含まれる",
    "test_websocket.py::TestCheckpointResolveHandler::test_resolve_invalid_resolution": "不正なresolution→error:state(INVALID_RESOLUTION)発行",
    "test_websocket.py::TestCheckpointResolveHandler::test_resolve_checkpoint_not_found": "存在しないチェックポイント→error:state(CHECKPOINT_NOT_FOUND)発行",
    "test_websocket.py::TestNavigatorMessage::test_broadcast_to_project": "broadcast_navigator_message()でプロジェクトルームに送信",
    "test_websocket.py::TestNavigatorMessage::test_broadcast_global": "project_id='global'→全クライアントに送信",
    "test_websocket.py::TestNavigatorMessage::test_broadcast_with_priority": "priority='critical'→priorityフィールドに反映",
}
