(function (PF) {
'use strict';
PF.GENRE_POOLS = PF.GENRE_POOLS || {};

// TODO: 各poolは目標件数に未達。agent の session limit 復帰後に追記する。
PF.GENRE_POOLS.asmr = {
  speaker: [
    { ja: 'おねぇさん', en: 'ONEESAN' }, { ja: '後輩', en: 'KOUHAI' }, { ja: '先輩', en: 'SENPAI' },
    { ja: '幼馴染', en: 'OSANANAJIMI' }, { ja: 'メイド', en: 'MAID' }, { ja: '執事', en: 'BUTLER' },
    { ja: '女医', en: 'JOI' }, { ja: '保健の先生', en: 'HOKEN NO SENSEI' }, { ja: '隣人', en: 'RINJIN' },
    { ja: '占い師', en: 'URANAISHI' }, { ja: '常連の店員', en: 'JOUREN NO TENIN' },
    { ja: '年上の従姉', en: 'TOSHIUE NO ITOKO' }, { ja: '図書委員', en: 'TOSHOIIN' },
    { ja: '同居人', en: 'DOUKYONIN' }, { ja: '家庭教師', en: 'KATEIKYOUSHI' },
    { ja: '美容師', en: 'BIYOUSHI' }, { ja: '整体師', en: 'SEITAISHI' }, { ja: 'バーテンダー', en: 'BARTENDER' },
    { ja: '看護師', en: 'KANGOSHI' }, { ja: '薬剤師', en: 'YAKUZAISHI' }, { ja: '司書', en: 'SHISHO' },
    { ja: '受付のお姉さん', en: 'UKETSUKE' }, { ja: '喫茶店のマスター', en: 'KISSATEN MASTER' },
    { ja: '和菓子屋の娘', en: 'WAGASHIYA NO MUSUME' }, { ja: '仕立屋', en: 'SHITATEYA' },
    { ja: '古書店の店主', en: 'KOSHOTEN NO TENSHU' }, { ja: '銭湯の番台', en: 'SENTOU NO BANDAI' },
    { ja: '旅館の女将', en: 'RYOKAN NO OKAMI' }, { ja: '駅員', en: 'EKIIN' },
    { ja: '灯台守', en: 'TOUDAIMORI' }, { ja: '船乗り', en: 'FUNANORI' }, { ja: '庭師', en: 'NIWASHI' },
    { ja: '調香師', en: 'CHOUKOUSHI' }, { ja: '時計職人', en: 'TOKEI SHOKUNIN' },
    { ja: '写真家', en: 'SHASHINKA' }, { ja: '声楽家', en: 'SEIGAKUKA' }, { ja: '朗読家', en: 'ROUDOKUKA' },
    { ja: '天文部の先輩', en: 'TENMONBU NO SENPAI' }, { ja: '茶道部の先輩', en: 'SADOUBU NO SENPAI' },
    { ja: '寮母さん', en: 'RYOUBO' }, { ja: '管理人さん', en: 'KANRININ' },
    { ja: '夜勤明けの同僚', en: 'YAKINAKE NO DOURYOU' }, { ja: '部長', en: 'BUCHOU' },
    { ja: '新人の後輩', en: 'SHINJIN NO KOUHAI' }, { ja: '双子の妹', en: 'FUTAGO NO IMOUTO' },
    { ja: '双子の姉', en: 'FUTAGO NO ANE' }, { ja: '義理の姉', en: 'GIRI NO ANE' },
    { ja: '許嫁', en: 'IINAZUKE' }, { ja: '文通相手', en: 'BUNTSUU AITE' },
    { ja: '転校生', en: 'TENKOUSEI' }, { ja: '留学生', en: 'RYUUGAKUSEI' },
    { ja: '練習相手', en: 'RENSHUU AITE' }, { ja: '相席のひと', en: 'AISEKI NO HITO' },
    { ja: '通りすがりの人', en: 'TOORISUGARI' }, { ja: '常連さん', en: 'JOUREN' },
    { ja: '担当の看護師', en: 'TANTOU NO KANGOSHI' }, { ja: '担任の先生', en: 'TANNIN NO SENSEI' },
    { ja: '部活の後輩', en: 'BUKATSU NO KOUHAI' }, { ja: '寮の同室', en: 'RYOU NO DOUSHITSU' },
    { ja: '姫', en: 'HIME' }, { ja: '巫女', en: 'MIKO' }, { ja: '狐の化身', en: 'KITSUNE' },
    { ja: '吸血鬼', en: 'KYUUKETSUKI' }, { ja: '魔女', en: 'MAJO' }, { ja: '人魚', en: 'NINGYO' },
    { ja: '天使', en: 'TENSHI' }, { ja: '案内人', en: 'ANNAININ' }, { ja: '守り神', en: 'MAMORIGAMI' },
    { ja: '極上おねぇさん', en: 'GOKUJOU ONEESAN' }, { ja: 'ダウナー系お姉さん', en: 'DOWNER ONEESAN' },
    { ja: '甘えん坊の後輩', en: 'AMAENBOU NO KOUHAI' }, { ja: 'クールな先輩', en: 'COOL SENPAI' },
    { ja: '世話焼きの幼馴染', en: 'SEWAYAKI NO OSANANAJIMI' }, { ja: '無口な同居人', en: 'MUKUCHI NO DOUKYONIN' },
    { ja: '低音の執事', en: 'TEION NO BUTLER' }, { ja: '眠そうな司書', en: 'NEMUSOU NA SHISHO' }
  ],
  honorific: [
    'ご主人さま', 'お客さま', 'せんぱい', 'きみ', 'あなた', 'お兄ちゃん', 'お姉ちゃん',
    'だんなさま', 'お嬢さま', '若さま', '旦那', 'あんた', 'きみたち', 'そこのきみ',
    'かわいい人', 'いい子', 'がんばりや', 'おつかれさん', 'ねぼすけさん', '甘えん坊さん',
    'わがままさん', 'さみしがりや', '素直じゃない人', '正直者', '働きすぎのあなた',
    'まだ起きてる人', '眠れない人', '疲れた人', '今日もよくやった人', 'いつものあなた'
  ],
  relation: [
    'ふたりきり', '2人きり', 'はじめて', '久しぶり', '内緒', '毎晩', '今夜だけ',
    'いつも', 'ここだけ', '約束', '週に一度', '眠る前だけ',
    '雨の日だけ', '休みの前の日', '帰り道', '仕事のあと', '深夜だけ',
    'あなただけ', 'わたしだけ', 'ふたり', '三人', '差し向かい',
    '肩が触れる距離', '息がかかる距離', '手が届く距離', '声だけ', '朝まで',
    '夜通し', '再会', '別れる前', '最後の夜', 'ひと晩じゅう', '週末だけ',
    '目覚めるまで', '眠るまで', '今日かぎり', 'この夜かぎり', '二度目',
    '数年ぶり', '出会ってはじめて', '寝る前だけ', '休みの日だけ'
  ],
  mood: [
    '甘々', 'とろとろ', 'しっとり', 'ひそひそ', 'まったり', 'ひたすら', 'ぎゅっと',
    'ゆったり', 'そっと', 'やさしく', 'たっぷり', 'じっくり', 'のんびり', 'ぐっすり',
    'うとうと', 'ふわふわ', 'ほんわか', 'ぬくぬく', 'もふもふ', 'さらさら',
    'ぽかぽか', 'しんしん', 'ひんやり', 'あたたかい', 'くすぐったい', 'こそばゆい',
    'なめらか', 'やわらか', 'かすかな', 'ささやかな', 'ひかえめな', '控えめに',
    '思いきり', '心ゆくまで', 'いつまでも', 'とめどなく', '飽きるまで', '眠るまで',
    '無心に', '一心に', '丁寧に', '念入りに', '手加減なしで', 'あますところなく'
  ],
  scene: [
    { ja: 'お泊りデート', en: 'OTOMARI DATE' }, { ja: '深夜の通話', en: 'SHINYA TSUUWA' },
    { ja: '雨宿り', en: 'AMAYADORI' }, { ja: '耳かき屋さん', en: 'MIMIKAKIYA' },
    { ja: '添い寝', en: 'SOINE' }, { ja: '寝かしつけ', en: 'NEKASHITSUKE' },
    { ja: '帰り道', en: 'KAERIMICHI' }, { ja: '保健室', en: 'HOKENSHITSU' },
    { ja: '図書室', en: 'TOSHOSHITSU' }, { ja: '放課後の教室', en: 'HOUKAGO NO KYOUSHITSU' },
    { ja: '屋上', en: 'OKUJOU' }, { ja: '縁側', en: 'ENGAWA' }, { ja: '炬燵', en: 'KOTATSU' },
    { ja: '露天風呂', en: 'ROTENBURO' }, { ja: '夜行バス', en: 'YAKOU BUS' },
    { ja: '終電のホーム', en: 'SHUUDEN NO HOME' }, { ja: '雪の日の部屋', en: 'YUKI NO HI' },
    { ja: '台風の夜', en: 'TAIFUU NO YORU' }, { ja: '停電の夜', en: 'TEIDEN NO YORU' },
    { ja: '看病', en: 'KANBYOU' }, { ja: '朝の身支度', en: 'ASA NO MIJITAKU' },
    { ja: '夜更かし', en: 'YOFUKASHI' }, { ja: '二度寝', en: 'NIDONE' },
    { ja: '休憩室', en: 'KYUUKEISHITSU' }, { ja: '仮眠室', en: 'KAMINSHITSU' },
    { ja: '灯台のふもと', en: 'TOUDAI NO FUMOTO' }, { ja: '夏祭りの帰り', en: 'NATSUMATSURI' },
    { ja: '花火のあと', en: 'HANABI NO ATO' }, { ja: 'こたつでみかん', en: 'KOTATSU MIKAN' },
    { ja: '真夜中の台所', en: 'MAYONAKA NO DAIDOKORO' }, { ja: '書斎', en: 'SHOSAI' },
    { ja: '温室', en: 'ONSHITSU' }, { ja: 'プラネタリウム', en: 'PLANETARIUM' },
    { ja: '観測小屋', en: 'KANSOKU GOYA' }, { ja: '古書店の奥', en: 'KOSHOTEN NO OKU' },
    { ja: '喫茶店の隅', en: 'KISSATEN NO SUMI' }, { ja: '仕立屋の作業場', en: 'SHITATEYA' },
    { ja: '調香室', en: 'CHOUKOUSHITSU' }, { ja: '整体院', en: 'SEITAIIN' },
    { ja: '美容室', en: 'BIYOUSHITSU' }, { ja: '和室の昼下がり', en: 'WASHITSU' },
    { ja: '宿直室', en: 'SHUKUCHOKUSHITSU' }, { ja: '合宿の夜', en: 'GASSHUKU NO YORU' },
    { ja: '相部屋', en: 'AIBEYA' }, { ja: '客間', en: 'KYAKUMA' }, { ja: '船室', en: 'SENSHITSU' }
  ],
  act: [
    { ja: 'よしよし', en: 'YOSHIYOSHI' }, { ja: 'お耳のお掃除', en: 'OMIMI NO OSOUJI' },
    { ja: '耳かき', en: 'MIMIKAKI' }, { ja: '髪すき', en: 'KAMISUKI' }, { ja: '膝枕', en: 'HIZAMAKURA' },
    { ja: 'カウント', en: 'COUNT' }, { ja: '子守唄', en: 'KOMORIUTA' }, { ja: '耳ふー', en: 'MIMIFU' },
    { ja: '肩ほぐし', en: 'KATAHOGUSHI' }, { ja: '頭なで', en: 'ATAMANADE' },
    { ja: '寝かしつけ', en: 'NEKASHITSUKE' }, { ja: '読み聞かせ', en: 'YOMIKIKASE' },
    { ja: '添い寝', en: 'SOINE' }, { ja: '囁き', en: 'SASAYAKI' }, { ja: '深呼吸の誘導', en: 'SHINKOKYUU' },
    { ja: '爪みがき', en: 'TSUMEMIGAKI' }, { ja: '髪かわかし', en: 'KAMIKAWAKASHI' },
    { ja: '寝返り介助', en: 'NEGAERI' }, { ja: '手のマッサージ', en: 'TE NO MASSAGE' },
    { ja: '目もとのケア', en: 'MEMOTO NO CARE' }, { ja: 'ブラッシング', en: 'BRUSHING' },
    { ja: '毛布かけ', en: 'MOUFUKAKE' }, { ja: '髪結い', en: 'KAMIYUI' },
    { ja: '頭皮マッサージ', en: 'TOUHI MASSAGE' }, { ja: '首のストレッチ', en: 'KUBI STRETCH' },
    { ja: '足つぼ', en: 'ASHITSUBO' }, { ja: 'ハンドクリーム塗り', en: 'HAND CREAM' },
    { ja: 'おでこトントン', en: 'ODEKO TONTON' }, { ja: '背中さすり', en: 'SENAKA SASURI' },
    { ja: '手つなぎ', en: 'TETSUNAGI' }, { ja: 'ぎゅー', en: 'GYUU' }, { ja: 'なでなで', en: 'NADENADE' },
    { ja: 'とんとん', en: 'TONTON' }, { ja: 'おまじない', en: 'OMAJINAI' },
    { ja: '数え歌', en: 'KAZOEUTA' }, { ja: '寝息あわせ', en: 'NEIKI AWASE' },
    { ja: '呼吸あわせ', en: 'KOKYUU AWASE' }, { ja: '耳もとカウントダウン', en: 'COUNTDOWN' },
    { ja: 'おやすみの挨拶', en: 'OYASUMI NO AISATSU' }, { ja: '寝る前のお話', en: 'NERU MAE NO OHANASHI' },
    { ja: '肩たたき', en: 'KATATATAKI' }, { ja: '腕まくら', en: 'UDEMAKURA' },
    { ja: 'ホットタオルの手当て', en: 'HOT TOWEL' }, { ja: 'お茶の用意', en: 'OCHA NO YOUI' },
    { ja: '看病', en: 'KANBYOU' }, { ja: '検温', en: 'KENON' }, { ja: '手当て', en: 'TEATE' },
    { ja: '着替えの手伝い', en: 'KIGAE NO TETSUDAI' }, { ja: '髪ふき', en: 'KAMIFUKI' },
    { ja: '身支度の手伝い', en: 'MIJITAKU NO TETSUDAI' }, { ja: '寝室への案内', en: 'SHINSHITSU E' }
  ],
  ambient: [
    { ja: '雨音', en: 'AMAOTO' }, { ja: '焚き火', en: 'TAKIBI' },
    { ja: '古時計の秒針', en: 'FURUDOKEI NO BYOUSHIN' }, { ja: '水槽のろ過音', en: 'SUISOU NO ROKAON' },
    { ja: '暖炉のはぜる音', en: 'DANRO' }, { ja: '雨戸を打つ雨', en: 'AMADO' },
    { ja: '焙煎の音', en: 'BAISEN' }, { ja: '心音', en: 'SHINON' }, { ja: '衣擦れ', en: 'KINUZURE' },
    { ja: 'ページをめくる音', en: 'PAGE' }, { ja: 'タイピング音', en: 'TYPING' },
    { ja: '深夜ラジオ', en: 'SHINYA RADIO' }, { ja: '寝息', en: 'NEIKI' },
    { ja: '風鈴の音', en: 'FUURIN' }, { ja: '虫の音', en: 'MUSHI NO NE' },
    { ja: '波の音', en: 'NAMI NO OTO' }, { ja: '雪を踏む音', en: 'YUKI WO FUMU OTO' },
    { ja: '薪のはぜる音', en: 'MAKI' }, { ja: '湯を注ぐ音', en: 'YU WO SOSOGU' },
    { ja: '鉛筆の音', en: 'ENPITSU' }, { ja: '万年筆の音', en: 'MANNENHITSU' },
    { ja: '布団のこすれる音', en: 'FUTON' }, { ja: '扇風機の風', en: 'SENPUUKI' },
    { ja: '換気扇の音', en: 'KANKISEN' }, { ja: '遠くの踏切', en: 'FUMIKIRI' },
    { ja: '夜行列車の走行音', en: 'YAKOU RESSHA' }, { ja: '船のエンジン', en: 'FUNE NO ENGINE' },
    { ja: '汽笛', en: 'KITEKI' }, { ja: '滴る水', en: 'SHITATARU MIZU' },
    { ja: '静けさ', en: 'SHIZUKESA' }, { ja: '無音', en: 'MUON' }, { ja: '遠雷', en: 'ENRAI' },
    { ja: '木の軋み', en: 'KI NO KISHIMI' }, { ja: '砂を踏む音', en: 'SUNA' },
    { ja: '毛布の擦れ', en: 'MOUFU' }, { ja: '鳥の声', en: 'TORI NO KOE' },
    { ja: '朝の台所', en: 'ASA NO DAIDOKORO' }, { ja: '図書室の静寂', en: 'TOSHOSHITSU NO SEIJAKU' },
    { ja: '足音が遠ざかる音', en: 'ASHIOTO' }, { ja: '柱時計の鐘', en: 'HASHIRADOKEI' }
  ],
  ending: [
    'いたします。', 'してあげる', 'してくれる', 'しませんか', 'されちゃう', 'します',
    'してあげます', 'いたしますね', 'しましょうか', 'させてください', 'させてね',
    'してもいい？', 'してほしい', 'してみて', 'してごらん', 'してあげようか',
    'してくれますか', 'いたしましょう', 'しておきますね', 'しておきました',
    'するからね', 'するよ', 'するね', 'しよっか', 'しちゃおう', 'しちゃった',
    'してあげたい', 'してあげたくて', 'したくなる', 'したくなる夜'
  ],
  tagWord: [
    'バイノーラル', 'ハイレゾ', 'ダミーヘッド', '立体音響', '耳かき', '添い寝', '囁き',
    '睡眠導入', '全編囁き', '環境音', '癒し', '安眠', '低音ボイス', 'おやすみ',
    '限定特典', '長時間', '実演収録', '両耳', '無音区間なし',
    '寝落ち', '耳のお掃除', '甘やかし', '添い寝密着', '癒し特化', '無自覚',
    'ダウナー', 'テンションゆるめ', '起伏なし', '喋りすぎない', '眠くなる声',
    '実写音源', '生活音多め', '雑談多め', '効果音控えめ', 'モノローグ主体',
    '長尺', '短尺', 'ループ収録', '目覚まし付', '起床導入', '入眠導入',
    '呼吸誘導', 'カウントダウン', '数え歌', 'ハーブの香り', '温感表現'
  ],
  circleName: [
    'ゆるり音工房', 'こもれびレコーズ', '夜想スタジオ', 'ねむり堂', 'SILENT PILLOW',
    'うたたね工房', '星屑オーディオ', 'まくらの森', 'とろとろ製作所',
    'ねむのき', 'ゆりかご堂', 'MOONLIT EAR', 'とろけ堂', 'ひつじの数え方',
    '寝落ち堂', '安眠舎', 'LULLABY LANE', '毛布の国', 'SLEEP SIGNAL',
    '深夜工房', 'よなよな音社', 'WHISPER ROOM', '子守唄製作所', '静音舎',
    'ゆめみ堂', 'DREAM DIAL', '枕元レコーズ', 'まどろみ社', 'NIGHT DESK',
    '耳もと工房', 'EAR CANDY', 'しずく音響', 'PILLOW TALK STUDIO', '灯火堂',
    'よるのこえ', 'SOFT VOLUME', 'ぬくもり工房', 'HUSH LABEL', '寝息社',
    'とばり堂', 'VELVET EAR', 'あくび堂', 'SLOW BREATH', '眠り木工房'
  ],
  binaural: [
    'バイノーラル録音', 'ダミーヘッド収録', 'ハイレゾ音源', '立体音響', '96kHz/24bit',
    '無指向性マイク使用', '環境音同時収録', 'ヘッドホン推奨', '左右耳別録り',
    'ノイズレス収録', '実演収録', 'ロスレス配信対応',
    '両耳独立収録', '実耳測定済', '32bit float 収録', '無響室収録', 'ヘッドホン最適化',
    '人頭模型使用', '距離感再現収録', '定位重視ミックス', '生録音', '一発録り',
    '編集最小限', '呼吸音そのまま収録', '至近距離収録', '囁き専用マイク',
    '低ノイズプリアンプ使用', '深夜収録', '防音室収録', '実環境収録'
  ],
  voiceRole: ['CV', '出演', 'Voice', '声の出演', 'ボイス', 'ナレーション', '語り', 'キャスト'],
  nounHead: [
    { ja: '耳', en: 'EAR' }, { ja: '息', en: 'BREATH' }, { ja: '囁', en: 'WHISPER' },
    { ja: '鼓動', en: 'HEARTBEAT' }, { ja: '微睡', en: 'SLUMBER' }, { ja: '枕', en: 'PILLOW' },
    { ja: '毛布', en: 'BLANKET' }, { ja: '静寂', en: 'STILLNESS' }, { ja: '雫', en: 'DROPLET' },
    { ja: '灯', en: 'LAMPLIGHT' }, { ja: '夜', en: 'NIGHTFALL' }, { ja: '声', en: 'VOICE' },
    { ja: '指先', en: 'FINGERTIP' }, { ja: '寝床', en: 'BEDDING' }, { ja: '睫毛', en: 'EYELASH' }
  ],
  nounTail: [
    { ja: 'ぬくもり', en: 'WARMTH' }, { ja: 'おやすみ', en: 'GOODNIGHT' }, { ja: '子守唄', en: 'LULLABY' },
    { ja: '吐息', en: 'SIGH' }, { ja: '余韻', en: 'AFTERTONE' }, { ja: '眠り', en: 'SLEEP' },
    { ja: 'まどろみ', en: 'DROWSE' }, { ja: '耳もと', en: 'EARSIDE' }, { ja: '寝息', en: 'SLEEPBREATH' },
    { ja: '静けさ', en: 'QUIETUDE' }, { ja: 'ひととき', en: 'INTERLUDE' }, { ja: '時間', en: 'HOURS' },
    { ja: '夜更け', en: 'LATEHOUR' }, { ja: '寝入りばな', en: 'FIRSTSLEEP' }, { ja: '夢のふち', en: 'DREAMEDGE' }
  ],
  adj: [
    { ja: 'そっと触れる', en: 'FEATHERLIGHT' }, { ja: '眠くなる', en: 'DROWSY' },
    { ja: 'ちいさな', en: 'TINY' }, { ja: 'ふわりとした', en: 'AIRY' },
    { ja: '息だけの', en: 'BREATHONLY' }, { ja: '耳もとで囁く', en: 'EARWHISPERED' },
    { ja: 'とろけるような', en: 'MELTING' }, { ja: 'あたたかな', en: 'WARMTHFUL' },
    { ja: 'やわらかな', en: 'SOFTLY' }, { ja: 'しずかな', en: 'HUSHED' },
    { ja: '甘やかす', en: 'INDULGENT' }, { ja: '寄り添う', en: 'CLOSEBY' }
  ]
};

})(window.PF = window.PF || {});
