(function (PF) {
'use strict';
PF.GENRE_POOLS = PF.GENRE_POOLS || {};

// TODO: 各poolは目標件数に未達。agent の session limit 復帰後に追記する。
PF.GENRE_POOLS.gravure = {
  feelingWord: [
    { ja: 'ひとりじめ', en: 'ALL MINE' }, { ja: 'はじめまして', en: 'FIRST HELLO' },
    { ja: 'ときめき', en: 'FLUTTER' }, { ja: 'なつやすみ', en: 'SUMMER BREAK' },
    { ja: 'おひさま', en: 'SUNSHINE' }, { ja: 'ふたりごと', en: 'JUST US TWO' },
    { ja: 'よりみち', en: 'DETOUR' }, { ja: 'まどろみ', en: 'DROWSE' },
    { ja: 'きまぐれ', en: 'WHIM' }, { ja: 'ないしょばなし', en: 'SECRET TALK' },
    { ja: 'てのひら', en: 'PALM' }, { ja: 'はだしのまま', en: 'BAREFOOT' },
    { ja: 'あまやどり', en: 'RAIN SHELTER' }, { ja: 'しおかぜ', en: 'SEA BREEZE' },
    { ja: 'ゆうなぎ', en: 'EVENING CALM' }, { ja: 'あさぼらけ', en: 'DAYBREAK' },
    { ja: 'ひだまり', en: 'SUNSPOT' }, { ja: 'こもれび', en: 'DAPPLED LIGHT' },
    { ja: 'みずたまり', en: 'PUDDLE' }, { ja: 'かたおもい', en: 'ONE SIDED' },
    { ja: 'おさんぽ', en: 'STROLL' }, { ja: 'おでかけ', en: 'OUTING' },
    { ja: 'おひるね', en: 'NAP' }, { ja: 'ねぼすけ', en: 'SLEEPYHEAD' },
    { ja: 'わすれもの', en: 'LEFT BEHIND' }, { ja: 'まちあわせ', en: 'RENDEZVOUS' },
    { ja: 'かえりみち', en: 'WAY HOME' }, { ja: 'とおまわり', en: 'LONG WAY' },
    { ja: 'ふりむいて', en: 'LOOK BACK' }, { ja: 'そばにいて', en: 'STAY CLOSE' },
    { ja: 'てをつないで', en: 'HOLD HANDS' }, { ja: 'めをとじて', en: 'EYES CLOSED' },
    { ja: 'いまだけ', en: 'ONLY NOW' }, { ja: 'きょうだけ', en: 'JUST TODAY' },
    { ja: 'あともうすこし', en: 'A LITTLE MORE' }, { ja: 'もうすこしだけ', en: 'JUST A BIT' },
    { ja: 'はじめてのなつ', en: 'FIRST SUMMER' }, { ja: 'さいごのなつ', en: 'LAST SUMMER' },
    { ja: 'こいのよかん', en: 'HINT OF LOVE' }, { ja: 'なつのおと', en: 'SOUND OF SUMMER' },
    { ja: 'うみのいろ', en: 'COLOR OF SEA' }, { ja: 'そらのいろ', en: 'COLOR OF SKY' },
    { ja: 'かぜのおと', en: 'SOUND OF WIND' }, { ja: 'なみのおと', en: 'SOUND OF WAVES' },
    { ja: 'ゆびさきに', en: 'AT FINGERTIPS' }, { ja: 'まつげのさき', en: 'LASH TIP' },
    { ja: 'ほおづえ', en: 'CHIN ON HAND' }, { ja: 'つまさきだち', en: 'ON TIPTOE' },
    { ja: 'くちびるに', en: 'ON LIPS' }, { ja: 'かたごしに', en: 'OVER SHOULDER' },
    { ja: 'すきまかぜ', en: 'DRAFT' }, { ja: 'あさのひかり', en: 'MORNING LIGHT' },
    { ja: 'ゆうやけいろ', en: 'SUNSET HUE' }, { ja: 'よあけまえ', en: 'BEFORE DAWN' },
    { ja: 'ほしぞらのした', en: 'UNDER STARS' }, { ja: 'つきあかり', en: 'MOONLIGHT' },
    { ja: 'あまいじかん', en: 'SWEET TIME' }, { ja: 'しずかなじかん', en: 'QUIET TIME' },
    { ja: 'ゆるやかなひ', en: 'GENTLE DAY' }, { ja: 'なにげないひ', en: 'ORDINARY DAY' },
    { ja: 'とくべつなひ', en: 'SPECIAL DAY' }, { ja: 'たいせつなひ', en: 'PRECIOUS DAY' },
    { ja: 'わすれないひ', en: 'DAY TO KEEP' }, { ja: 'かえらないひ', en: 'DAY GONE BY' },
    { ja: 'はにかみ', en: 'BASHFUL' }, { ja: 'えくぼ', en: 'DIMPLE' },
    { ja: 'すあし', en: 'BARE FEET' }, { ja: 'すっぴん', en: 'NO MAKEUP' },
    { ja: 'ねぐせ', en: 'BED HAIR' }, { ja: 'よこがお', en: 'PROFILE' },
    { ja: 'うしろすがた', en: 'FROM BEHIND' }, { ja: 'まなざし', en: 'GAZE' },
    { ja: 'ためいき', en: 'SIGH' }, { ja: 'わらいごえ', en: 'LAUGHTER' },
    { ja: 'ひとやすみ', en: 'A REST' }, { ja: 'きゅうけいちゅう', en: 'ON BREAK' },
    { ja: 'おきにいり', en: 'FAVORITE' }, { ja: 'とっておき', en: 'SPECIAL ONE' },
    { ja: 'はつこうかい', en: 'FIRST REVEAL' }, { ja: 'みせたことない', en: 'NEVER SHOWN' }
  ],
  colorSeason: [
    { ja: '夏色', en: 'SUMMER HUE' }, { ja: '潮風色', en: 'SEA BREEZE HUE' },
    { ja: '木もれ日', en: 'DAPPLED SUN' }, { ja: '水彩', en: 'WATERCOLOR' },
    { ja: 'とろけ空', en: 'MELTING SKY' }, { ja: '朝焼け色', en: 'SUNRISE HUE' },
    { ja: '夕凪色', en: 'CALM HUE' }, { ja: '砂浜色', en: 'SAND HUE' },
    { ja: '若草色', en: 'FRESH GREEN' }, { ja: '空色', en: 'SKY BLUE' },
    { ja: '桜色', en: 'CHERRY PINK' }, { ja: '菫色', en: 'VIOLET' },
    { ja: '珊瑚色', en: 'CORAL' }, { ja: '真珠色', en: 'PEARL' },
    { ja: '琥珀色', en: 'AMBER' }, { ja: '蜜色', en: 'HONEY' },
    { ja: '氷菓色', en: 'SORBET' }, { ja: 'ラムネ色', en: 'SODA BLUE' },
    { ja: '麦わら色', en: 'STRAW' }, { ja: '日焼け色', en: 'SUNTAN' },
    { ja: '木陰色', en: 'SHADE' }, { ja: '雨上がり色', en: 'AFTER RAIN' },
    { ja: '春先色', en: 'EARLY SPRING' }, { ja: '初夏色', en: 'EARLY SUMMER' },
    { ja: '晩夏色', en: 'LATE SUMMER' }, { ja: '秋口色', en: 'EARLY AUTUMN' },
    { ja: '冬晴れ色', en: 'WINTER CLEAR' }, { ja: '雪明かり', en: 'SNOW GLOW' },
    { ja: '花冷え色', en: 'BLOSSOM CHILL' }, { ja: '青葉色', en: 'GREEN LEAF' },
    { ja: '南風色', en: 'SOUTH WIND' }, { ja: '入道雲色', en: 'THUNDERHEAD' },
    { ja: '線香花火色', en: 'SPARKLER' }, { ja: '風鈴色', en: 'WIND CHIME' },
    { ja: '海月色', en: 'JELLYFISH' }, { ja: '貝殻色', en: 'SEASHELL' },
    { ja: '波打ち際色', en: 'SHORELINE' }, { ja: '灯台色', en: 'LIGHTHOUSE' },
    { ja: '船室色', en: 'CABIN' }, { ja: '甲板色', en: 'DECK' },
    { ja: '汽笛色', en: 'STEAM WHISTLE' }, { ja: '朝露色', en: 'MORNING DEW' },
    { ja: '陽炎色', en: 'HEAT HAZE' }, { ja: '打ち水色', en: 'SPRINKLED' },
    { ja: '氷柱色', en: 'ICICLE' }, { ja: '霜柱色', en: 'FROST COLUMN' },
    { ja: '新緑色', en: 'NEW GREEN' }, { ja: '紅葉色', en: 'AUTUMN LEAF' },
    { ja: '銀杏色', en: 'GINKGO' }, { ja: '枯野色', en: 'WITHERED FIELD' }
  ],
  callWord: [
    'きみとなら', 'ふたりだけ', 'となりで', 'いっしょに', 'そばにいて',
    'まっててね', 'いってきます', 'おかえりなさい', 'ただいま', 'またあした',
    'ここにいるよ', 'みつけてね', 'よんでみて', 'きこえてる', 'わらってみせて',
    'てをのばして', 'ふりむかないで', 'いかないで', 'つれていって', 'おいでよ',
    'すこしだけ', 'もうちょっと', 'あとすこし', 'いまだけね', 'ないしょだよ',
    'だれにもいわないで', 'ふたりのひみつ', 'きみにだけ', 'あなたにだけ', 'わたしだけの',
    'きみのとなり', 'あなたのそば', 'このままで', 'このゆびとまれ', 'てをつなご',
    'めをとじて', 'みていてね', 'きいていてね', 'おぼえていて', 'わすれないで',
    'ゆめでまた', 'あしたもね', 'つぎのなつも', 'いつかまた', 'さよならのまえに',
    'おやすみのまえに', 'おはようのあとで', 'ひるさがりに', 'ゆうぐれどきに', 'よるがくるまえに'
  ],
  nounHead: [
    { ja: '陽', en: 'SUNLIGHT' }, { ja: '潮', en: 'TIDE' }, { ja: '汗', en: 'DEW' },
    { ja: '素足', en: 'BAREFOOT' }, { ja: '麦わら', en: 'STRAWHAT' }, { ja: '木漏れ日', en: 'SUNBEAM' },
    { ja: '水しぶき', en: 'SPLASH' }, { ja: '微睡み', en: 'DOZE' }, { ja: '寄り道', en: 'DETOUR' },
    { ja: '海風', en: 'SEAWIND' }, { ja: '砂浜', en: 'BEACH' }, { ja: '日傘', en: 'PARASOL' },
    { ja: '氷菓', en: 'SORBET' }, { ja: '浮輪', en: 'FLOAT' }, { ja: '貝殻', en: 'SHELL' },
    { ja: '波音', en: 'WAVESOUND' }, { ja: '風鈴', en: 'CHIME' }, { ja: '団扇', en: 'FAN' },
    { ja: '浴衣', en: 'YUKATA' }, { ja: '線香花火', en: 'SPARKLER' }, { ja: '西瓜', en: 'MELON' },
    { ja: '麦茶', en: 'BARLEYTEA' }, { ja: '縁側', en: 'VERANDA' }, { ja: '網戸', en: 'SCREEN' },
    { ja: '扇風機', en: 'ELECTRICFAN' }, { ja: '打ち水', en: 'SPRINKLE' }, { ja: '朝露', en: 'DEWDROP' },
    { ja: '陽炎', en: 'HEATHAZE' }, { ja: '入道雲', en: 'THUNDERHEAD' }, { ja: '夕立', en: 'SHOWER' },
    { ja: '虹', en: 'RAINBOW' }, { ja: '海月', en: 'JELLYFISH' }, { ja: '磯', en: 'ROCKYSHORE' },
    { ja: '桟橋', en: 'PIER' }, { ja: '帆', en: 'SAIL' }, { ja: '汽笛', en: 'WHISTLE' },
    { ja: '甲板', en: 'DECK' }, { ja: '舷', en: 'GUNWALE' }, { ja: '錨', en: 'ANCHOR' },
    { ja: '灯', en: 'LANTERN' }, { ja: '涼', en: 'COOLNESS' }, { ja: '薫', en: 'FRAGRANCE' }
  ],
  nounTail: [
    { ja: 'ひととき', en: 'MOMENT' }, { ja: 'まなざし', en: 'GAZE' }, { ja: 'ときめき', en: 'FLUTTER' },
    { ja: 'ないしょ', en: 'SECRET' }, { ja: 'おでかけ', en: 'OUTING' }, { ja: '休日', en: 'HOLIDAY' },
    { ja: '昼寝', en: 'NAP' }, { ja: '思い出', en: 'KEEPSAKE' }, { ja: '三日間', en: 'THREE DAYS' },
    { ja: '午後', en: 'AFTERNOON' }, { ja: '寄り道', en: 'SIDETRIP' }, { ja: '横顔', en: 'PROFILE' },
    { ja: '素顔', en: 'BAREFACE' }, { ja: '寝顔', en: 'SLEEPFACE' }, { ja: '笑顔', en: 'SMILE' },
    { ja: '足あと', en: 'FOOTPRINT' }, { ja: '木陰', en: 'TREESHADE' }, { ja: '砂の城', en: 'SANDCASTLE' },
    { ja: '夕暮れ', en: 'DUSK' }, { ja: '朝ごはん', en: 'BREAKFAST' }, { ja: '待ち時間', en: 'WAITING' },
    { ja: '帰り道', en: 'WAYBACK' }, { ja: '窓辺', en: 'WINDOWSIDE' }, { ja: '車窓', en: 'TRAINVIEW' },
    { ja: '缶ジュース', en: 'CANNEDDRINK' }, { ja: '日焼け跡', en: 'TANLINE' }, { ja: 'はしゃぎ声', en: 'GLEE' },
    { ja: 'ひとやすみ', en: 'BREATHER' }, { ja: '内緒話', en: 'WHISPERTALK' }, { ja: 'ゆびきり', en: 'PINKYSWEAR' },
    { ja: '寝起き', en: 'JUSTWOKE' }, { ja: '身支度', en: 'GETTINGREADY' }, { ja: '着替え中', en: 'CHANGING' },
    { ja: '髪ほどき', en: 'HAIRDOWN' }, { ja: 'つま先', en: 'TIPTOE' }, { ja: '手のひら', en: 'PALM' }
  ],
  adj: [
    { ja: 'やわらかな', en: 'TENDER' }, { ja: 'きらめく', en: 'SHIMMERING' },
    { ja: '屈託のない', en: 'CAREFREE' }, { ja: 'まぶしい', en: 'DAZZLING' },
    { ja: 'ゆるやかな', en: 'UNHURRIED' }, { ja: '息を切らした', en: 'BREATHLESS' },
    { ja: 'はずんだ', en: 'BOUNCY' }, { ja: 'あたたかな', en: 'WARM' },
    { ja: 'すきとおる', en: 'CLEAR' }, { ja: 'しっとりした', en: 'MOIST' },
    { ja: 'さらさらの', en: 'SILKY' }, { ja: 'ふんわりした', en: 'FLUFFY' },
    { ja: 'ほんのりした', en: 'FAINT' }, { ja: 'まっさらな', en: 'BRANDNEW' },
    { ja: 'うつむいた', en: 'DOWNCAST' }, { ja: '照れくさそうな', en: 'SHEEPISH' },
    { ja: 'いたずらな', en: 'MISCHIEVOUS' }, { ja: 'おだやかな', en: 'SERENE' },
    { ja: 'のびやかな', en: 'RELAXED' }, { ja: 'すこやかな', en: 'HEALTHY' },
    { ja: 'あどけない', en: 'INNOCENT' }, { ja: 'たおやかな', en: 'GRACEFUL' },
    { ja: 'ういういしい', en: 'FRESH' }, { ja: 'なつかしい', en: 'NOSTALGIC' },
    { ja: 'ひかえめな', en: 'MODEST' }, { ja: 'おおらかな', en: 'EASYGOING' }
  ],
  place: [
    '常夏の島', '白い砂浜', '静かな入江', '南の離島', '海沿いのホテル', '夕暮れの防波堤',
    '高原のペンション', '早朝のプール', '木漏れ日の並木', '夏の終わりの港', '島の小さな商店',
    '波打ち際', '灯台のある岬', '朝焼けの車窓', '麦わら帽子の丘', '風のとおる縁側',
    '朝もやの棚田', '無人の海水浴場', '島の分校', '灯りの落ちた水族館', '夕凪の桟橋',
    '砂丘の稜線', '古い灯台の階段', '潮だまりの岩場', '民宿の二階', '漁協の倉庫前',
    '渡し船の待合所', '駅前の商店街', '無人駅のベンチ', '線路沿いの小道', '踏切のむこう',
    '夏祭りの露店', '神社の石段', '境内の木陰', '土手の上', '河原のテント',
    '湖畔のボート', '吊り橋のたもと', '山あいのバス停', '峠の茶屋', '牧場の柵',
    '果樹園の小径', '温室のなか', '花畑のまんなか', '風車のふもと', '灯台下の草地',
    'プールサイドの日陰', 'ホテルのバルコニー', '朝の厨房', '縁側の日だまり', '畳の上',
    '窓辺のカーテン越し', '古い旅館の廊下', '露天風呂の湯けむり', '朝市のかご', '港の朝'
  ],
  emotion: [
    'ふわりとした', 'くすぐったい', '照れくさい', 'ひとりじめの', '寝起きの', '内緒話みたいな',
    'すこし大人な', 'はしゃいだ', 'とろけそうな', '夏の匂いがする',
    'ねぼけまなこの', 'こそばゆい', 'すこし強がった', 'はにかみながらの', '足をぶらぶらさせた',
    'ほおづえをついた', 'つま先立ちの', '髪をほどいた', '振り向きざまの', '目を細めた',
    '笑いをこらえた', '息をひそめた', 'うとうとした', '伸びをした', '肩をすくめた',
    'くちびるをとがらせた', '首をかしげた', '手を振った', '駆け出した', '立ち止まった',
    'ふりむいた', 'うつむいた', '見上げた', '目を合わせた', '目をそらした',
    'すこし濡れた', '日に焼けた', '風になびいた', '汗ばんだ', '涼しげな',
    '眠たげな', '夢見心地の', '上機嫌な', 'ごきげんななめの', 'そわそわした',
    'のんびりした', 'ゆったりした', 'まったりした', 'ぼんやりした', 'うっとりした'
  ],
  bonus: [
    '特典映像60分収録', '完全撮り下ろし', 'メイキング完全収録', '初回限定ブックレット封入',
    '未公開カット追加', '4Kリマスター', 'デジタル写真集ダウンロード付', '描き下ろしポストカード付',
    'オーディオコメンタリー収録', '特典ディスク同梱', '本人直筆メッセージ入り',
    '水着オフショット追加収録', '撮影地マップ封入', '本人ナレーション版収録',
    '未使用カット収録', 'オフショット集同梱', '撮影日記封入', 'ピンナップ付',
    '生写真ランダム封入', 'スチール写真集付', '特製クリアファイル付', 'ステッカー封入',
    'ミニカレンダー付', '複製サイン入り', '応募券封入', 'イベント優先申込券付',
    '本人セレクトカット収録', 'ロングバージョン収録', 'ノーカット版同梱', '別アングル収録',
    'インタビュー追加収録', '撮影裏側完全公開', 'スタッフコメンタリー付', '未公開ロケ地収録',
    '朝から夜までの密着映像', '着替えシーンのメイキング', '本編未収録シーン追加', '特典写真データ付'
  ],
  labelName: [
    'AQUA BREEZE', '蒼波企画', 'スカイライン映像', 'ゆるり工房', 'MARINE POCKET',
    '白波スタジオ', 'SUNDIAL WORKS', '潮風舎',
    '渚エンタテインメント', 'BLUE HOUR PICTURES', '汐見スタジオ', 'PALM RECORDS', '陽だまり映像',
    'SEASIDE LABEL', '夏空工房', 'CORAL FILMS', '砂丘レコーズ', 'ひなたビジョン',
    'SUNSET LANE', '波音制作所', 'LAGOON WORKS', '青空舎', 'SHELL PICTURES',
    '灯台フィルム', 'BREEZE LINE', 'みなも企画', 'TIDE POOL', '海鳴スタジオ',
    'SUMMER DIAL', '風待ち工房', 'HORIZON BLUE', '白帆映像', 'SANDBAR WORKS',
    '涼風レーベル', 'DAYBREAK FILMS', '朝凪企画', 'PEARL LINE', '碧海スタジオ'
  ],
  formatMark: [
    'DVD', 'Blu-ray', 'DVD & Blu-ray 同時リリース', 'Blu-ray Disc', 'DVD-Video',
    'UHD Blu-ray', 'Blu-ray BOX', 'DVD 2枚組', 'デジタル配信', '4K UHD'
  ]
};

})(window.PF = window.PF || {});
