(function (PF) {
'use strict';

// TODO: latinTag / festival / studioWord / role / recommendRole は目標件数に未達。
// agent の session limit 復帰後に追記する。
Object.assign(PF.GENRE_POOLS.cinema, {
  latinTag: [
    'A FILM BY', 'ORIGINAL MOTION PICTURE', 'OFFICIAL SELECTION', 'IN THEATERS',
    'PRESENTED BY', 'BASED ON A TRUE STORY', "DIRECTOR'S CUT", 'THE FINAL CHAPTER',
    'A MOTION PICTURE EVENT', 'COMING SOON', 'NOW SHOWING', 'AN ORIGINAL SCREENPLAY',
    'BASED ON TRUE EVENTS', 'THE STORY YOU NEVER HEARD', 'RESTORED IN 4K',
    'AN UNFORGETTABLE MOTION PICTURE', 'THE COMPLETE EDITION', 'A TRUE STORY',
    'IN SELECTED THEATERS', 'THE MOTION PICTURE', 'A NEW VISION', 'THE LAST STAND',
    'NOTHING IS WHAT IT SEEMS', 'THE TRUTH WILL SURFACE', 'NO WAY BACK',
    'ONE NIGHT CHANGES EVERYTHING', 'THE HUNT BEGINS', 'JUSTICE HAS A PRICE',
    'EVERY SECOND COUNTS', 'SOME DOORS STAY SHUT', 'THE SILENCE BREAKS',
    'A STORY OF SURVIVAL', 'WITNESS THE BEGINNING', 'THE FINAL RECKONING',
    'BEYOND THE HORIZON', 'WHAT REMAINS UNSAID', 'THE WEIGHT OF MEMORY',
    'A PORTRAIT OF LOSS', 'THE LONG WAY HOME', 'NOTHING STAYS BURIED',
    'AN UNTOLD CHAPTER', 'THE COST OF LOYALTY', 'A QUESTION OF FAITH',
    'THE EDGE OF REASON', 'WHERE THE ROAD ENDS', 'A MATTER OF TIME',
    'THE ONES WHO STAYED', 'NO WITNESSES', 'THE LAST TRANSMISSION',
    'A SEASON OF ASH', 'THE FINAL SUMMONS', 'INTO THE UNKNOWN',
    'THE RECKONING COMES', 'A DEBT UNPAID', 'THE VERDICT STANDS',
    'BEFORE THE STORM', 'AFTER THE FALL', 'THE QUIET BETWEEN',
    'A LIFE INTERRUPTED', 'THE NAMES WE KEEP', 'NOTHING WAS PROMISED',
    'THE ROAD IS CLOSED', 'A COUNTRY OF STRANGERS', 'THE HOUR OF RETURN',
    'SOME TRUTHS COST EVERYTHING', 'THE LINE IS DRAWN', 'A WINTER WITHOUT END',
    'THE LAST WITNESS SPEAKS', 'NO ONE IS COMING', 'THE PRICE OF SILENCE',
    'A STORY OF TWO NIGHTS', 'THE MAP ENDS HERE', 'WHAT THE RIVER TOOK',
    'THE SECOND TESTIMONY', 'A CROWN OF SALT', 'THE HOURS BEFORE DAWN',
    'NOTHING TO DECLARE', 'THE FINAL DEPOSITION', 'A CITY WITHOUT MERCY',
    'THE ORDER WAS GIVEN', 'ALL ROADS LEAD BACK', 'THE LAST TRAIN OUT',
    'A MATTER OF RECORD', 'THE DEBT COMES DUE', 'WHERE THE LIGHT FAILS',
    'AN ACT OF CONSCIENCE', 'THE CASE REOPENS', 'NO SAFE PASSAGE',
    'THE SUM OF OUR CHOICES', 'A HARVEST OF ASHES', 'THE THIRD WITNESS',
    'BEFORE THE VERDICT', 'A LETTER NEVER SENT', 'THE FINAL CROSSING',
    'WHAT WE LEFT BEHIND', 'THE LONG SILENCE', 'A PROMISE IN WINTER',
    'NOTHING BUT THE TRUTH', 'THE LAST GOOD DAY', 'A QUESTION OF LOYALTY',
    'THE SHAPE OF GRIEF', 'AN HONEST MISTAKE', 'THE CLOCK RUNS OUT',
    'A HOUSE DIVIDED', 'THE OTHER SIDE OF NIGHT', 'NO ONE LEAVES CLEAN',
    'THE EVIDENCE REMAINS', 'A SEASON IN EXILE', 'THE FINAL APPEAL',
    'WHAT THE FIRE SPARED', 'THE NAMES ON THE LIST', 'A DEBT OF BLOOD',
    'THE WITNESS PROTECTION', 'BEYOND ALL DOUBT', 'THE LAST ORDER',
    'A COUNTRY IN MOURNING', 'THE SENTENCE STANDS', 'NOTHING IS FORGIVEN',
    'THE RETURN OF THE ACCUSED', 'A MATTER OF SURVIVAL', 'THE FINAL HEARING'
  ],
  festival: [
    '群青', '北欧', '極東', '砂丘', '硝子塔', '灯台', '運河', '塩湖', '高原', '峡谷', '無名',
    '白夜', '氷河', '黒森', '内海', '塩野', '汐見', '海鳴', '北天', '蒼波', '極夜',
    '流氷', '断崖', '湿原', '溶岩', '珊瑚', '氷原', '玄武', '白樺', '山脈', '瀬戸',
    '大河', '古都', '城塞', '要塞', '渡り鳥', '北緯', '南緯', '子午線', '地峡', '半島',
    '入江', '鉱山', '製鉄', '煉瓦', '運河都市', '港湾', '旧市街', '大聖堂', '修道院',
    '砂漠', '緑洲', '塩田', '棚田', '茶畑', '葡萄畑', '牧草', '樹海', '洞窟', '断層',
    '火口', '温泉郷', '雪原', '氷穴', '滝壺', '瀑布', '三角州', '河口', '干潟', '砂州',
    '孤島', '群島', '環礁', '岬', '灯明', '波止', '船着', '造船', '漁港', '市場',
    '国境', '検問', '関所', '駅前', '操車場', '廃線', '鉄橋', '隧道', '峠', '街道',
    '宿場', '門前', '参道', '石畳', '広場', '噴水', '時計台', '鐘楼', '天文台', '気象台',
    '灯籠', '碑', '墓地', '追悼', '記念', '博物', '美術', '図書', '文書', '記録'
  ],
  studioWord: [
    { ja: '群青', en: 'GUNJO' }, { ja: '北天', en: 'HOKUTEN' }, { ja: '硝子', en: 'GARASU' },
    { ja: '極東', en: 'KYOKUTO' }, { ja: '灯台', en: 'TOUDAI' }, { ja: '無名', en: 'MUMEI' },
    { ja: '蒼波', en: 'SOUHA' }, { ja: '砂丘', en: 'SAKYU' }, { ja: '白夜', en: 'HAKUYA' },
    { ja: '氷河', en: 'HYOGA' }, { ja: '内海', en: 'UCHIUMI' }, { ja: '黒森', en: 'KUROMORI' },
    { ja: '塩野', en: 'SHIONO' }, { ja: '汐見', en: 'SHIOMI' }, { ja: '海鳴', en: 'UMINARI' },
    { ja: '流氷', en: 'RYUHYO' }, { ja: '玄武', en: 'GENBU' }, { ja: '白樺', en: 'SHIRAKABA' },
    { ja: '瀬戸', en: 'SETO' }, { ja: '大河', en: 'TAIGA' }, { ja: '古都', en: 'KOTO' },
    { ja: '城塞', en: 'JOSAI' }, { ja: '北緯', en: 'HOKUI' }, { ja: '子午線', en: 'SHIGOSEN' },
    { ja: '半島', en: 'HANTO' }, { ja: '入江', en: 'IRIE' }, { ja: '鉱山', en: 'KOZAN' },
    { ja: '煉瓦', en: 'RENGA' }, { ja: '港湾', en: 'KOWAN' }, { ja: '旧市街', en: 'KYUSHIGAI' },
    { ja: '砂漠', en: 'SABAKU' }, { ja: '塩田', en: 'ENDEN' }, { ja: '棚田', en: 'TANADA' },
    { ja: '樹海', en: 'JUKAI' }, { ja: '断層', en: 'DANSO' }, { ja: '火口', en: 'KAKO' },
    { ja: '雪原', en: 'SETSUGEN' }, { ja: '瀑布', en: 'BAKUFU' }, { ja: '河口', en: 'KAKOU' },
    { ja: '干潟', en: 'HIGATA' }, { ja: '孤島', en: 'KOTOU' }, { ja: '群島', en: 'GUNTO' },
    { ja: '環礁', en: 'KANSHO' }, { ja: '灯明', en: 'TOMYO' }, { ja: '波止', en: 'HATO' },
    { ja: '造船', en: 'ZOSEN' }, { ja: '漁港', en: 'GYOKO' }, { ja: '国境', en: 'KOKKYO' },
    { ja: '関所', en: 'SEKISHO' }, { ja: '操車', en: 'SOSHA' }, { ja: '廃線', en: 'HAISEN' },
    { ja: '鉄橋', en: 'TEKKYO' }, { ja: '隧道', en: 'ZUIDO' }, { ja: '街道', en: 'KAIDO' },
    { ja: '宿場', en: 'SHUKUBA' }, { ja: '門前', en: 'MONZEN' }, { ja: '石畳', en: 'ISHIDATAMI' },
    { ja: '噴水', en: 'FUNSUI' }, { ja: '時計台', en: 'TOKEIDAI' }, { ja: '鐘楼', en: 'SHORO' },
    { ja: '天文台', en: 'TENMONDAI' }, { ja: '気象台', en: 'KISHODAI' }, { ja: '灯籠', en: 'TORO' },
    { ja: '追悼', en: 'TSUITO' }, { ja: '記録', en: 'KIROKU' }, { ja: '文書', en: 'BUNSHO' },
    { ja: '青嵐', en: 'SEIRAN' }, { ja: '夜航', en: 'YAKO' }, { ja: '白鯨', en: 'HAKUGEI' },
    { ja: '銀河', en: 'GINGA' }, { ja: '無限', en: 'MUGEN' }, { ja: '暁光', en: 'GYOKO' },
    { ja: '残照', en: 'ZANSHO' }, { ja: '朔北', en: 'SAKUHOKU' }, { ja: '西海', en: 'SAIKAI' },
    { ja: '東雲', en: 'SHINONOME' }, { ja: '曙', en: 'AKEBONO' }, { ja: '黎明', en: 'REIMEI' },
    { ja: '常夜', en: 'TOKOYO' }, { ja: '幽谷', en: 'YUKOKU' }, { ja: '深緑', en: 'SHINRYOKU' },
    { ja: '蒼穹', en: 'SOKYU' }, { ja: '天頂', en: 'TENCHO' }, { ja: '極光', en: 'KYOKKO' },
    { ja: '星霜', en: 'SEISO' }, { ja: '磁北', en: 'JIHOKU' }, { ja: '経緯', en: 'KEII' },
    { ja: '航跡', en: 'KOSEKI' }, { ja: '羅針', en: 'RASHIN' }, { ja: '六分儀', en: 'ROKUBUNGI' },
    { ja: '海図', en: 'KAIZU' }, { ja: '測量', en: 'SOKURYO' }, { ja: '基準点', en: 'KIJUNTEN' },
    { ja: '水準', en: 'SUIJUN' }, { ja: '三角点', en: 'SANKAKUTEN' }, { ja: '標高', en: 'HYOKO' }
  ],
  role: [
    '監督', '脚本', '撮影', '音楽', '編集', '美術', '製作総指揮', '照明', '録音', '衣装', '原作', '主演',
    '助監督', '記録', '美術監督', '視覚効果', '音響効果', '製作', 'プロデューサー', 'キャスティング',
    '装飾', '小道具', '大道具', '特殊メイク', '結髪', '床山', '振付', '殺陣', 'スタント調整',
    '車輌', '操演', '造形', '絵コンテ', '色彩設計', '整音', '効果', '選曲', '音楽プロデューサー',
    '主題歌', '挿入歌', '演奏', '指揮', '楽器監修', '方言指導', '所作指導', '医事監修', '法律監修',
    '軍事監修', '時代考証', '風俗考証', '建築考証', '料理監修', '書道', '題字', '字幕',
    '翻訳', '吹替演出', '整音助手', '撮影助手', '照明助手', '録音助手', '編集助手', '美術助手',
    '制作担当', '制作進行', '製作担当', 'ラインプロデューサー', '共同製作', '企画', '原案',
    '構成', '脚色', '潤色', 'スクリプター', 'カラリスト', 'デジタル合成', 'モーション',
    '背景', '技術監督', '撮影監督', '照明監督', '録音監督', '編集監督', '特撮監督', 'アクション監督',
    '衣装デザイン', '美術デザイン', 'コンセプトアート', 'ロケーション', '海外撮影', '航空撮影',
    '水中撮影', '特機', 'クレーン', 'ドリー', '移動車', 'グリップ', '電飾', '発電',
    '安全管理', '医療班', '通訳', '経理', '宣伝', '配給', '興行', '票券', '広報'
  ],
  recommendRole: [
    '映画評論家', '作家', 'ミュージシャン', '脚本家', '写真家', '俳優', '編集者', '劇作家',
    '哲学者', '演出家', '報道記者', '書店員', 'ノンフィクション作家', '詩人', '翻訳家',
    '文芸評論家', '美術評論家', '音楽評論家', '演劇評論家', '建築家', 'デザイナー',
    '漫画家', 'イラストレーター', '装丁家', '書評家', '古書店主', '映画館支配人',
    '大学教授', '社会学者', '歴史学者', '心理学者', '精神科医', '弁護士', '検事',
    '裁判官', '新聞記者', '雑誌編集長', '放送作家', 'ラジオパーソナリティ', '声優',
    '落語家', '狂言師', '舞踏家', '振付家', '作曲家', '指揮者', '演奏家', '歌手',
    '写真評論家', '映像作家', 'ドキュメンタリー監督', 'アニメーション監督', '特撮監督',
    '料理研究家', '建築評論家', '都市計画家', '造園家', '登山家', '探検家', '冒険家',
    '天文学者', '生物学者', '地質学者', '気象予報士', '医師', '看護師', '教師',
    '図書館司書', '学芸員', '文書館員', '記録映画作家', '通訳', '外交官', '編集委員',
    '書店主', '出版社社長', '文学賞選考委員', '国語教師', '読書会主宰', '朗読家'
  ],
  ratingMark: ['G', 'PG12', 'R15+', 'R18+'],
  billing: [
    '{studioWord.en} PICTURES 提供　IN ASSOCIATION WITH {studioWord.en} FILMS',
    'A {person.en} PRODUCTION　A FILM BY {person.en}',
    '{person.en}　{person.en}　{person.en}',
    'CASTING BY {person.en}　COSTUMES BY {person.en}　EDITED BY {person.en}',
    'PRODUCTION DESIGNER {person.en}　DIRECTOR OF PHOTOGRAPHY {person.en}',
    'MUSIC BY {person.en}',
    'EXECUTIVE PRODUCERS {person.en}　{person.en}',
    'PRODUCED BY {person.en}',
    'SCREENPLAY BY {person.en}',
    'DIRECTED BY {person.en}'
  ]
});

})(window.PF = window.PF || {});
