(function (PF) {
'use strict';
PF.GENRE_POOLS = PF.GENRE_POOLS || {};
PF.GENRE_POOLS.cinema = {
  subjectKanji: [
    { ja: '懺悔', en: 'PENITENCE' }, { ja: '悔恨', en: 'REMORSE' }, { ja: '慟哭', en: 'LAMENT' },
    { ja: '号泣', en: 'WAILING' }, { ja: '嗚咽', en: 'SOBBING' }, { ja: '憤怒', en: 'WRATH' },
    { ja: '激昂', en: 'OUTRAGE' }, { ja: '憎悪', en: 'HATRED' }, { ja: '嫉妬', en: 'JEALOUSY' },
    { ja: '猜疑', en: 'MISTRUST' }, { ja: '疑念', en: 'DOUBT' }, { ja: '侮蔑', en: 'CONTEMPT' },
    { ja: '軽蔑', en: 'DISDAIN' }, { ja: '憐憫', en: 'PITY' }, { ja: '慈悲', en: 'MERCY' },
    { ja: '寛恕', en: 'CLEMENCY' }, { ja: '恐怖', en: 'FEAR' }, { ja: '戦慄', en: 'TERROR' },
    { ja: '畏怖', en: 'AWE' }, { ja: '焦燥', en: 'IMPATIENCE' }, { ja: '不安', en: 'UNEASE' },
    { ja: '動揺', en: 'AGITATION' }, { ja: '混乱', en: 'CONFUSION' }, { ja: '錯乱', en: 'DERANGEMENT' },
    { ja: '狂気', en: 'MADNESS' }, { ja: '妄想', en: 'DELUSION' }, { ja: '幻覚', en: 'HALLUCINATION' },
    { ja: '恍惚', en: 'RAPTURE' }, { ja: '陶酔', en: 'INTOXICATION' }, { ja: '高揚', en: 'ELATION' },
    { ja: '歓喜', en: 'JUBILATION' }, { ja: '愉悦', en: 'DELIGHT' }, { ja: '安堵', en: 'RELIEF' },
    { ja: '落胆', en: 'DISAPPOINTMENT' }, { ja: '失意', en: 'DEJECTION' }, { ja: '絶望', en: 'DESPAIR' },
    { ja: '悲嘆', en: 'GRIEF' }, { ja: '哀惜', en: 'SORROW' }, { ja: '憂愁', en: 'MELANCHOLY' },
    { ja: '憂鬱', en: 'GLOOM' }, { ja: '郷愁', en: 'NOSTALGIA' }, { ja: '望郷', en: 'HOMESICKNESS' },
    { ja: '憧憬', en: 'YEARNING' }, { ja: '渇望', en: 'CRAVING' }, { ja: '欲望', en: 'DESIRE' },
    { ja: '情熱', en: 'PASSION' }, { ja: '衝動', en: 'IMPULSE' }, { ja: '執着', en: 'ATTACHMENT' },
    { ja: '妄執', en: 'OBSESSION' }, { ja: '懊悩', en: 'ANGUISH' },
    { ja: '罪業', en: 'SINFULNESS' }, { ja: '罪責', en: 'CULPABILITY' }, { ja: '咎', en: 'BLAME' },
    { ja: '過ち', en: 'TRANSGRESSION' }, { ja: '失態', en: 'BLUNDER' }, { ja: '不覚', en: 'LAPSE' },
    { ja: '汚名', en: 'STIGMA' }, { ja: '汚辱', en: 'IGNOMINY' }, { ja: '屈辱', en: 'HUMILIATION' },
    { ja: '恥辱', en: 'SHAME' }, { ja: '名誉', en: 'HONOR' }, { ja: '矜持', en: 'SELF RESPECT' },
    { ja: '誇り', en: 'PRIDE' }, { ja: '意地', en: 'OBSTINACY' }, { ja: '節操', en: 'INTEGRITY' },
    { ja: '信義', en: 'GOOD FAITH' }, { ja: '忠誠', en: 'ALLEGIANCE' }, { ja: '背信', en: 'PERFIDY' },
    { ja: '不実', en: 'INFIDELITY' }, { ja: '虚偽', en: 'FALSEHOOD' }, { ja: '虚栄', en: 'VANITY' },
    { ja: '欺瞞', en: 'DECEIT' }, { ja: '詭弁', en: 'SOPHISTRY' }, { ja: '建前', en: 'PRETENSE' },
    { ja: '本音', en: 'TRUE INTENT' }, { ja: '偽善', en: 'HYPOCRISY' }, { ja: '独善', en: 'SELF RIGHTEOUSNESS' },
    { ja: '傲慢', en: 'ARROGANCE' }, { ja: '謙譲', en: 'HUMILITY' }, { ja: '廉潔', en: 'PROBITY' },
    { ja: '潔白', en: 'INNOCENCE' }, { ja: '純潔', en: 'PURITY' }, { ja: '堕落', en: 'DEGRADATION' },
    { ja: '頽廃', en: 'DECADENCE' }, { ja: '腐敗', en: 'CORRUPTION' }, { ja: '悪徳', en: 'VICE' },
    { ja: '美徳', en: 'VIRTUE' }, { ja: '大義', en: 'JUST CAUSE' }, { ja: '正義', en: 'JUSTICE' },
    { ja: '不義', en: 'IMPROPRIETY' }, { ja: '道義', en: 'MORALITY' }, { ja: '倫理', en: 'ETHICS' },
    { ja: '良心', en: 'CONSCIENCE' }, { ja: '罪悪', en: 'GUILT' }, { ja: '悔悟', en: 'CONTRITION' },
    { ja: '改悛', en: 'REPENTANCE' }, { ja: '更生', en: 'REHABILITATION' }, { ja: '免罪', en: 'ABSOLUTION' },
    { ja: '糾弾', en: 'DENUNCIATION' }, { ja: '弾劾', en: 'IMPEACHMENT' },
    { ja: '生涯', en: 'LIFETIME' }, { ja: '半生', en: 'HALF A LIFE' }, { ja: '余生', en: 'LATTER DAYS' },
    { ja: '晩年', en: 'TWILIGHT YEARS' }, { ja: '遺志', en: 'LAST WILL' }, { ja: '遺影', en: 'MEMORIAL PORTRAIT' },
    { ja: '命日', en: 'ANNIVERSARY OF DEATH' }, { ja: '弔い', en: 'MOURNING' }, { ja: '葬列', en: 'CORTEGE' },
    { ja: '埋葬', en: 'BURIAL' }, { ja: '火葬', en: 'CREMATION' }, { ja: '墓標', en: 'GRAVEMARKER' },
    { ja: '遺灰', en: 'ASHES' }, { ja: '訃報', en: 'OBITUARY' }, { ja: '追悼', en: 'MEMORIAL' },
    { ja: '別離', en: 'PARTING' }, { ja: '訣別', en: 'RUPTURE' }, { ja: '惜別', en: 'FAREWELL' },
    { ja: '送別', en: 'SENDOFF' }, { ja: '再会', en: 'REUNION' }, { ja: '旅立ち', en: 'DEPARTURE' },
    { ja: '門出', en: 'SETTING OUT' }, { ja: '帰郷', en: 'HOMECOMING' }, { ja: '帰路', en: 'WAY HOME' },
    { ja: '上京', en: 'TO THE CAPITAL' }, { ja: '出奔', en: 'ABSCONDING' }, { ja: '放浪', en: 'WANDERING' },
    { ja: '流浪', en: 'VAGRANCY' }, { ja: '漂流', en: 'DRIFTING' }, { ja: '遭難', en: 'DISTRESS' },
    { ja: '遠征', en: 'EXPEDITION' }, { ja: '巡礼', en: 'PILGRIMAGE' }, { ja: '道行き', en: 'JOURNEY' },
    { ja: '岐路', en: 'CROSSROADS' }, { ja: '越境', en: 'CROSSING OVER' }, { ja: '歳月', en: 'YEARS' },
    { ja: '年月', en: 'SEASONS PAST' }, { ja: '余命', en: 'DAYS LEFT' }, { ja: '寿命', en: 'LIFESPAN' },
    { ja: '一夜', en: 'ONE NIGHT' }, { ja: '一瞬', en: 'INSTANT' }, { ja: '刹那', en: 'SPLIT SECOND' },
    { ja: '永劫', en: 'ETERNITY' }, { ja: '未明', en: 'PREDAWN' }, { ja: '黄昏', en: 'TWILIGHT' },
    { ja: '薄暮', en: 'DUSK' }, { ja: '宵闇', en: 'NIGHTFALL' }, { ja: '夜半', en: 'MIDNIGHT HOUR' },
    { ja: '明け方', en: 'DAYBREAK' }, { ja: '日暮れ', en: 'SUNDOWN' },
    { ja: '血縁', en: 'BLOOD TIE' }, { ja: '血脈', en: 'BLOODLINE' }, { ja: '家系', en: 'FAMILY LINE' },
    { ja: '系図', en: 'GENEALOGY' }, { ja: '一族', en: 'CLAN' }, { ja: '血筋', en: 'STOCK' },
    { ja: '生誕', en: 'NATIVITY' }, { ja: '出自', en: 'PARENTAGE' }, { ja: '素性', en: 'IDENTITY' },
    { ja: '家督', en: 'HEADSHIP' }, { ja: '相続', en: 'INHERITANCE' }, { ja: '遺産', en: 'ESTATE' },
    { ja: '家訓', en: 'HOUSE PRECEPT' }, { ja: '本家', en: 'MAIN HOUSE' }, { ja: '分家', en: 'BRANCH HOUSE' },
    { ja: '養子', en: 'ADOPTED CHILD' }, { ja: '里子', en: 'FOSTER CHILD' }, { ja: '継嗣', en: 'SUCCESSOR' },
    { ja: '嫡子', en: 'LEGITIMATE HEIR' }, { ja: '庶子', en: 'BASEBORN CHILD' }, { ja: '双子', en: 'TWINS' },
    { ja: '兄弟', en: 'BROTHERS' }, { ja: '姉妹', en: 'SISTERS' }, { ja: '親子', en: 'PARENT AND CHILD' },
    { ja: '夫婦', en: 'HUSBAND AND WIFE' }, { ja: '婚姻', en: 'MATRIMONY' }, { ja: '離縁', en: 'DIVORCE' },
    { ja: '絶縁', en: 'ESTRANGEMENT' }, { ja: '勘当', en: 'DISOWNING' }, { ja: '家出', en: 'RUNNING AWAY' },
    { ja: '里帰り', en: 'RETURN TO THE FAMILY' }, { ja: '故郷', en: 'HOMELAND' }, { ja: '郷里', en: 'NATIVE PLACE' },
    { ja: '在所', en: 'HOME VILLAGE' }, { ja: '旧居', en: 'FORMER HOME' }, { ja: '実家', en: 'PARENTAL HOME' },
    { ja: '生家', en: 'BIRTH HOUSE' }, { ja: '空き家', en: 'EMPTY HOUSE' }, { ja: '仏間', en: 'ALTAR ROOM' },
    { ja: '仏壇', en: 'HOUSEHOLD ALTAR' }, { ja: '位牌', en: 'MEMORIAL TABLET' }, { ja: '墓所', en: 'GRAVESITE' },
    { ja: '菩提寺', en: 'FAMILY TEMPLE' }, { ja: '法要', en: 'MEMORIAL SERVICE' }, { ja: '香典', en: 'CONDOLENCE GIFT' },
    { ja: '形見', en: 'MEMENTO' }, { ja: '遺品', en: 'EFFECTS OF THE DEAD' }, { ja: '家宝', en: 'HEIRLOOM' },
    { ja: '表札', en: 'NAMEPLATE' }, { ja: '縁組', en: 'BETROTHAL' },
    { ja: '回想', en: 'RECOLLECTION' }, { ja: '想起', en: 'REMEMBRANCE' }, { ja: '忘却', en: 'OBLIVION' },
    { ja: '健忘', en: 'AMNESIA' }, { ja: '幻聴', en: 'PHANTOM SOUND' }, { ja: '既視感', en: 'SEEN BEFORE' },
    { ja: '走馬灯', en: 'REVOLVING LANTERN' }, { ja: '断片', en: 'SHARD' }, { ja: '痕跡', en: 'TRACE' },
    { ja: '名残', en: 'VESTIGE' }, { ja: '面影', en: 'SEMBLANCE' }, { ja: '残像', en: 'AFTERIMAGE' },
    { ja: '反響', en: 'ECHO' }, { ja: '木霊', en: 'ECHOING' }, { ja: '独語', en: 'SOLILOQUY' },
    { ja: '述懐', en: 'REMINISCENCE' }, { ja: '告解', en: 'CONFESSION' }, { ja: '白状', en: 'OWNING UP' },
    { ja: '弁明', en: 'VINDICATION' }, { ja: '弁解', en: 'EXCUSE' }, { ja: '釈明', en: 'CLARIFICATION' },
    { ja: '陳述', en: 'STATEMENT' }, { ja: '供述', en: 'DEPOSITION' }, { ja: '問答', en: 'DIALOGUE' },
    { ja: '対話', en: 'CONVERSATION' }, { ja: '沈黙', en: 'SILENCE' }, { ja: '無言', en: 'WORDLESSNESS' },
    { ja: '失語', en: 'APHASIA' }, { ja: '訛り', en: 'ACCENT' }, { ja: '方言', en: 'DIALECT' },
    { ja: '暗号', en: 'CIPHER' }, { ja: '符牒', en: 'CODEWORD' }, { ja: '隠語', en: 'ARGOT' },
    { ja: '落書き', en: 'GRAFFITI' }, { ja: '走り書き', en: 'SCRAWL' }, { ja: '署名', en: 'SIGNATURE' },
    { ja: '筆跡', en: 'HANDWRITING' }, { ja: '日誌', en: 'DAYBOOK' }, { ja: '備忘録', en: 'AIDE MEMOIRE' },
    { ja: '議事録', en: 'MINUTES' }, { ja: '速記', en: 'SHORTHAND' }, { ja: '録音', en: 'RECORDING' },
    { ja: '音源', en: 'SOUND SOURCE' }, { ja: '映写', en: 'PROJECTION' }, { ja: '現像', en: 'DEVELOPING' },
    { ja: '焼増し', en: 'REPRINT' }, { ja: '密録', en: 'SECRET TAPE' }, { ja: '盗撮', en: 'COVERT FILMING' },
    { ja: '伝聞', en: 'HEARSAY' }, { ja: '風聞', en: 'RUMOR' },
    { ja: '豪雨', en: 'DOWNPOUR' }, { ja: '驟雨', en: 'CLOUDBURST' }, { ja: '氷雨', en: 'SLEET' },
    { ja: '霧雨', en: 'DRIZZLE' }, { ja: '長雨', en: 'LONG RAIN' }, { ja: '夜雨', en: 'NIGHT RAIN' },
    { ja: '雨脚', en: 'RAINFALL' }, { ja: '豪雪', en: 'HEAVY SNOW' }, { ja: '吹雪', en: 'BLIZZARD' },
    { ja: '粉雪', en: 'POWDER SNOW' }, { ja: '霜柱', en: 'FROST COLUMNS' }, { ja: '凍土', en: 'FROZEN GROUND' },
    { ja: '氷点', en: 'FREEZING POINT' }, { ja: '極寒', en: 'BITTER COLD' }, { ja: '猛暑', en: 'SEVERE HEAT' },
    { ja: '炎天', en: 'BLAZING SKY' }, { ja: '旱魃', en: 'DROUGHT' }, { ja: '洪水', en: 'FLOOD' },
    { ja: '氾濫', en: 'INUNDATION' }, { ja: '決壊', en: 'BREACH' }, { ja: '津波', en: 'TSUNAMI' },
    { ja: '高潮', en: 'STORM SURGE' }, { ja: '地震', en: 'EARTHQUAKE' }, { ja: '余震', en: 'AFTERSHOCK' },
    { ja: '噴火', en: 'ERUPTION' }, { ja: '落雷', en: 'LIGHTNING STRIKE' }, { ja: '雷鳴', en: 'THUNDERCLAP' },
    { ja: '稲妻', en: 'LIGHTNING BOLT' }, { ja: '暴風', en: 'GALE' }, { ja: '突風', en: 'GUST' },
    { ja: '凪', en: 'CALM' }, { ja: '潮騒', en: 'SOUND OF THE TIDE' }, { ja: '川霧', en: 'RIVER MIST' },
    { ja: '朝靄', en: 'MORNING HAZE' }, { ja: '夕凪', en: 'EVENING CALM' }, { ja: '蜃気楼', en: 'MIRAGE' },
    { ja: '極光', en: 'AURORA' }, { ja: '日食', en: 'SOLAR ECLIPSE' }, { ja: '月食', en: 'LUNAR ECLIPSE' },
    { ja: '流星', en: 'METEOR' }, { ja: '彗星', en: 'COMET' }, { ja: '星屑', en: 'STARDUST' },
    { ja: '満潮', en: 'HIGH TIDE' }, { ja: '干潮', en: 'LOW TIDE' }, { ja: '渦潮', en: 'WHIRLPOOL' },
    { ja: '断崖', en: 'PRECIPICE' }, { ja: '溶岩', en: 'LAVA' }, { ja: '火口', en: 'CRATER' },
    { ja: '雪崩', en: 'AVALANCHE' }, { ja: '山崩れ', en: 'LANDSLIDE' },
    { ja: '初雪', en: 'FIRST SNOW' }, { ja: '名残雪', en: 'LINGERING SNOW' }, { ja: '雪解け', en: 'THAW' },
    { ja: '芽吹き', en: 'BUDDING' }, { ja: '遅霜', en: 'LATE FROST' }, { ja: '若葉', en: 'NEW LEAVES' },
    { ja: '青嵐', en: 'GREEN GALE' }, { ja: '五月雨', en: 'EARLY SUMMER RAIN' }, { ja: '梅雨明け', en: 'END OF THE RAINS' },
    { ja: '蟬時雨', en: 'CICADA CHORUS' }, { ja: '炎昼', en: 'BLAZING NOON' }, { ja: '夕立', en: 'EVENING SHOWER' },
    { ja: '涼風', en: 'COOL BREEZE' }, { ja: '秋雨', en: 'AUTUMN RAIN' }, { ja: '野分', en: 'AUTUMN GALE' },
    { ja: '稲刈り', en: 'HARVEST' }, { ja: '落穂', en: 'GLEANINGS' }, { ja: '紅葉', en: 'AUTUMN LEAVES' },
    { ja: '落葉', en: 'FALLEN LEAVES' }, { ja: '枯野', en: 'WITHERED FIELD' }, { ja: '冬支度', en: 'WINTER PREPARATION' },
    { ja: '木枯らし', en: 'WINTRY WIND' }, { ja: '初霜', en: 'FIRST FROST' }, { ja: '氷柱', en: 'ICICLE' },
    { ja: '寒波', en: 'COLD WAVE' }, { ja: '節分', en: 'SEASONAL DIVIDE' }, { ja: '彼岸', en: 'EQUINOCTIAL WEEK' },
    { ja: '盂蘭盆', en: 'FESTIVAL OF THE DEAD' }, { ja: '灯籠流し', en: 'FLOATING LANTERNS' }, { ja: '祭囃子', en: 'FESTIVAL MUSIC' },
    { ja: '神楽', en: 'SACRED DANCE' }, { ja: '縁日', en: 'TEMPLE FAIR' }, { ja: '花火', en: 'FIREWORKS' },
    { ja: '夜店', en: 'NIGHT STALL' }, { ja: '盆踊り', en: 'BON DANCE' }, { ja: '初詣', en: 'NEW YEAR VISIT' },
    { ja: '年越し', en: 'YEAR CROSSING' }, { ja: '大晦日', en: 'LAST DAY OF THE YEAR' }, { ja: '元旦', en: 'NEW YEAR MORNING' },
    { ja: '松の内', en: 'NEW YEAR DAYS' }, { ja: '田植え', en: 'RICE PLANTING' }, { ja: '稲穂', en: 'EARS OF RICE' },
    { ja: '案山子', en: 'SCARECROW' }, { ja: '畦道', en: 'FIELD PATH' }, { ja: '棚田', en: 'TERRACED PADDIES' },
    { ja: '段々畑', en: 'TERRACED FARM' }, { ja: '里山', en: 'VILLAGE WOODS' }, { ja: '藁束', en: 'STRAW BUNDLE' },
    { ja: '納屋', en: 'BARN' }, { ja: '水車', en: 'WATERWHEEL' },
    { ja: '出稼ぎ', en: 'MIGRANT LABOR' }, { ja: '日雇い', en: 'DAY LABOR' }, { ja: '賃金', en: 'WAGES' },
    { ja: '借金', en: 'DEBT' }, { ja: '借財', en: 'LIABILITY' }, { ja: '質草', en: 'PAWN' },
    { ja: '抵当', en: 'MORTGAGE' }, { ja: '差押え', en: 'SEIZURE' }, { ja: '競売', en: 'AUCTION' },
    { ja: '立退き', en: 'EVICTION' }, { ja: '倒産', en: 'BANKRUPTCY' }, { ja: '解雇', en: 'DISMISSAL' },
    { ja: '失業', en: 'UNEMPLOYMENT' }, { ja: '争議', en: 'LABOR DISPUTE' }, { ja: '罷業', en: 'STRIKE' },
    { ja: '組合', en: 'UNION' }, { ja: '徒弟', en: 'APPRENTICESHIP' }, { ja: '修業', en: 'TRAINING' },
    { ja: '家業', en: 'FAMILY TRADE' }, { ja: '廃業', en: 'CLOSING SHOP' }, { ja: '開業', en: 'OPENING SHOP' },
    { ja: '商い', en: 'TRADE' }, { ja: '行商', en: 'PEDDLING' }, { ja: '露店', en: 'STALL' },
    { ja: '市場', en: 'MARKETPLACE' }, { ja: '帳簿', en: 'LEDGER' }, { ja: '手形', en: 'PROMISSORY NOTE' },
    { ja: '印鑑', en: 'SEAL' }, { ja: '領収', en: 'RECEIPT' }, { ja: '送金', en: 'REMITTANCE' },
    { ja: '為替', en: 'EXCHANGE' }, { ja: '密輸', en: 'SMUGGLING' }, { ja: '闇市', en: 'BLACK MARKET' },
    { ja: '手間賃', en: 'PIECE RATE' }, { ja: '供出', en: 'REQUISITION' }, { ja: '買い出し', en: 'FOOD RUN' },
    { ja: '賄い', en: 'STAFF MEAL' }, { ja: '炊出し', en: 'SOUP KITCHEN' }, { ja: '洗濯', en: 'LAUNDRY' },
    { ja: '繕い', en: 'MENDING' }, { ja: '針仕事', en: 'NEEDLEWORK' }, { ja: '内職', en: 'PIECEWORK' },
    { ja: '夜業', en: 'NIGHT WORK' }, { ja: '徹夜', en: 'ALL NIGHT VIGIL' }, { ja: '残業', en: 'OVERTIME' },
    { ja: '通勤', en: 'COMMUTE' }, { ja: '転勤', en: 'TRANSFER' }, { ja: '左遷', en: 'DEMOTION' },
    { ja: '栄転', en: 'PROMOTION' }, { ja: '夜勤', en: 'NIGHT SHIFT' },
    { ja: '負傷', en: 'INJURY' }, { ja: '重傷', en: 'GRAVE WOUND' }, { ja: '裂傷', en: 'LACERATION' },
    { ja: '火傷', en: 'BURN' }, { ja: '凍傷', en: 'FROSTBITE' }, { ja: '骨折', en: 'FRACTURE' },
    { ja: '打撲', en: 'CONTUSION' }, { ja: '縫合', en: 'SUTURE' }, { ja: '手術', en: 'SURGERY' },
    { ja: '麻酔', en: 'ANESTHESIA' }, { ja: '輸血', en: 'TRANSFUSION' }, { ja: '移植', en: 'TRANSPLANT' },
    { ja: '摘出', en: 'EXCISION' }, { ja: '切断', en: 'AMPUTATION' }, { ja: '義足', en: 'PROSTHETIC LEG' },
    { ja: '義手', en: 'PROSTHETIC ARM' }, { ja: '車椅子', en: 'WHEELCHAIR' }, { ja: '松葉杖', en: 'CRUTCHES' },
    { ja: '包帯', en: 'BANDAGE' }, { ja: '点滴', en: 'INTRAVENOUS DRIP' }, { ja: '病床', en: 'SICKBED' },
    { ja: '病棟', en: 'WARD' }, { ja: '検疫', en: 'QUARANTINE' }, { ja: '疫病', en: 'PLAGUE' },
    { ja: '感染', en: 'INFECTION' }, { ja: '発熱', en: 'FEVER' }, { ja: '喀血', en: 'HEMOPTYSIS' },
    { ja: '吐血', en: 'BLOOD VOMIT' }, { ja: '昏睡', en: 'COMA' }, { ja: '昏倒', en: 'COLLAPSE' },
    { ja: '痙攣', en: 'CONVULSION' }, { ja: '麻痺', en: 'PARALYSIS' }, { ja: '失明', en: 'BLINDNESS' },
    { ja: '難聴', en: 'HEARING LOSS' }, { ja: '失声', en: 'LOSS OF VOICE' }, { ja: '不眠', en: 'INSOMNIA' },
    { ja: '悪夢', en: 'NIGHTMARE' }, { ja: '譫妄', en: 'DELIRIUM' }, { ja: '衰弱', en: 'DEBILITY' },
    { ja: '余病', en: 'COMPLICATION' }, { ja: '危篤', en: 'CRITICAL CONDITION' }, { ja: '臨終', en: 'DEATHBED' },
    { ja: '蘇生', en: 'RESUSCITATION' }, { ja: '延命', en: 'LIFE PROLONGING' }, { ja: '看取り', en: 'DEATHWATCH' },
    { ja: '快癒', en: 'RECOVERY' }, { ja: '後遺症', en: 'AFTEREFFECT' }, { ja: '脈拍', en: 'PULSE' },
    { ja: '体温', en: 'BODY HEAT' }, { ja: '息切れ', en: 'SHORTNESS OF BREATH' },
    { ja: '戸籍', en: 'FAMILY REGISTER' }, { ja: '住民票', en: 'RESIDENCE RECORD' }, { ja: '身分証', en: 'IDENTITY PAPERS' },
    { ja: '旅券', en: 'PASSPORT' }, { ja: '査証', en: 'VISA' }, { ja: '国籍', en: 'NATIONALITY' },
    { ja: '無国籍', en: 'STATELESSNESS' }, { ja: '徴兵', en: 'CONSCRIPTION' }, { ja: '徴用', en: 'LABOR DRAFT' },
    { ja: '動員', en: 'MOBILIZATION' }, { ja: '疎開', en: 'EVACUATION' }, { ja: '引揚げ', en: 'REPATRIATION' },
    { ja: '開拓', en: 'FRONTIER SETTLEMENT' }, { ja: '入植', en: 'HOMESTEADING' }, { ja: '干拓', en: 'LAND RECLAMATION' },
    { ja: '埋立', en: 'LANDFILL' }, { ja: '収用', en: 'EXPROPRIATION' }, { ja: '補償', en: 'COMPENSATION' },
    { ja: '陳情', en: 'PETITION' }, { ja: '請願', en: 'APPEAL' }, { ja: '訴訟', en: 'LITIGATION' },
    { ja: '和解', en: 'SETTLEMENT' }, { ja: '調停', en: 'MEDIATION' }, { ja: '仲裁', en: 'ARBITRATION' },
    { ja: '示談', en: 'PRIVATE ACCORD' }, { ja: '賠償', en: 'REPARATION' }, { ja: '慰謝料', en: 'SOLATIUM' },
    { ja: '保険金', en: 'INSURANCE PAYOUT' }, { ja: '年金', en: 'PENSION' }, { ja: '施設', en: 'INSTITUTION' },
    { ja: '収容', en: 'INTERNMENT' }, { ja: '措置', en: 'DISPOSITION' }, { ja: '通達', en: 'DIRECTIVE' },
    { ja: '条例', en: 'ORDINANCE' }, { ja: '法令', en: 'STATUTE' }, { ja: '布告', en: 'PROCLAMATION' },
    { ja: '戒厳', en: 'MARTIAL LAW' }, { ja: '非常事態', en: 'STATE OF EMERGENCY' }, { ja: '灯火管制', en: 'BLACKOUT' },
    { ja: '空襲警報', en: 'AIR RAID ALARM' }, { ja: '避難', en: 'TAKING SHELTER' }, { ja: '防空壕', en: 'AIR RAID SHELTER' },
    { ja: '復興', en: 'RECONSTRUCTION' }, { ja: '移住', en: 'MIGRATION' }, { ja: '定住', en: 'SETTLING DOWN' },
    { ja: '強制', en: 'COERCION' }, { ja: '免除', en: 'EXEMPTION' }, { ja: '特例', en: 'SPECIAL CASE' },
    { ja: '恩典', en: 'DISPENSATION' }, { ja: '権利', en: 'RIGHTS' },
    { ja: '祈祷', en: 'PRAYER RITE' }, { ja: '祈願', en: 'SUPPLICATION' }, { ja: '願掛け', en: 'VOW OF PETITION' },
    { ja: '誓願', en: 'PLEDGE' }, { ja: '参籠', en: 'RITUAL SECLUSION' }, { ja: '断食', en: 'FASTING' },
    { ja: '苦行', en: 'ASCETICISM' }, { ja: '修行', en: 'ASCETIC PRACTICE' }, { ja: '得度', en: 'ORDINATION' },
    { ja: '剃髪', en: 'TONSURE' }, { ja: '出家', en: 'RENUNCIATION' }, { ja: '還俗', en: 'RETURN TO LAY LIFE' },
    { ja: '破戒', en: 'BREAKING THE PRECEPTS' }, { ja: '戒律', en: 'PRECEPTS' }, { ja: '経文', en: 'SUTRA' },
    { ja: '読経', en: 'CHANTING' }, { ja: '念仏', en: 'INVOCATION' }, { ja: '供養', en: 'MEMORIAL OFFERING' },
    { ja: '御霊', en: 'SPIRIT OF THE DEAD' }, { ja: '怨霊', en: 'VENGEFUL SPIRIT' }, { ja: '祟り', en: 'CURSE' },
    { ja: '憑依', en: 'POSSESSION' }, { ja: '祓い', en: 'EXORCISM' }, { ja: '禊', en: 'ABLUTION' },
    { ja: '清め', en: 'PURIFICATION' }, { ja: '神託', en: 'ORACLE' }, { ja: '託宣', en: 'DIVINE MESSAGE' },
    { ja: '占い', en: 'DIVINATION' }, { ja: '卜占', en: 'AUGURY' }, { ja: '呪符', en: 'TALISMAN' },
    { ja: '護符', en: 'AMULET' }, { ja: '奉納', en: 'DEDICATION' }, { ja: '神事', en: 'SACRED RITE' },
    { ja: '例祭', en: 'ANNUAL FESTIVAL' }, { ja: '遷宮', en: 'SHRINE RELOCATION' }, { ja: '参道', en: 'APPROACH PATH' },
    { ja: '鳥居', en: 'SHRINE GATE' }, { ja: '社殿', en: 'SHRINE HALL' }, { ja: '本堂', en: 'MAIN HALL' },
    { ja: '鐘楼', en: 'BELL TOWER' }, { ja: '梵鐘', en: 'TEMPLE BELL' }, { ja: '除夜', en: 'NEW YEAR EVE BELL' },
    { ja: '曼荼羅', en: 'MANDALA' }, { ja: '涅槃', en: 'NIRVANA' }, { ja: '輪廻', en: 'SAMSARA' },
    { ja: '転生', en: 'REBIRTH' }, { ja: '極楽', en: 'PURE LAND' }, { ja: '地獄', en: 'INFERNO' },
    { ja: '賽銭', en: 'OFFERTORY COIN' }, { ja: '山門', en: 'TEMPLE GATE' },
    { ja: '別れ', en: 'GOODBYE' }, { ja: '惑い', en: 'BEWILDERMENT' }, { ja: '揺らぎ', en: 'WAVER' },
    { ja: '綻び', en: 'UNRAVELING' }, { ja: '歪み', en: 'DISTORTION' }, { ja: '淀み', en: 'STAGNATION' },
    { ja: '滲み', en: 'SEEPAGE' }, { ja: '兆し', en: 'OMEN' }, { ja: '翳り', en: 'SHADING' },
    { ja: '濁り', en: 'MURK' }, { ja: '渇き', en: 'THIRST' }, { ja: '飢え', en: 'HUNGER' },
    { ja: '痛み', en: 'PAIN' }, { ja: '疼き', en: 'THROB' }, { ja: '軋み', en: 'CREAK' },
    { ja: '呻き', en: 'GROAN' }, { ja: '呟き', en: 'MURMUR' }, { ja: '叫び', en: 'SCREAM' },
    { ja: '足音', en: 'FOOTSTEPS' }, { ja: '靴音', en: 'CLACK OF SHOES' }, { ja: '息遣い', en: 'BREATHING' },
    { ja: '手触り', en: 'TEXTURE' }, { ja: '佇まい', en: 'BEARING' }, { ja: '面立ち', en: 'FEATURES' },
    { ja: '肩越し', en: 'OVER THE SHOULDER' }, { ja: '爪痕', en: 'CLAW MARK' }, { ja: '傷跡', en: 'SCAR' },
    { ja: '縫い目', en: 'SEAM' }, { ja: '結び目', en: 'KNOT' }, { ja: '端切れ', en: 'SCRAP OF CLOTH' },
    { ja: '忘れ物', en: 'LEFT BEHIND' }, { ja: '落し物', en: 'LOST ARTICLE' }, { ja: '手向け', en: 'FLORAL TRIBUTE' },
    { ja: '心残り', en: 'REGRET' }, { ja: '独り言', en: 'TALKING ALONE' }, { ja: '寝言', en: 'SLEEP TALK' },
    { ja: '空耳', en: 'MISHEARING' }, { ja: '見誤り', en: 'MISSEEING' }, { ja: '行き違い', en: 'CROSSED PATHS' },
    { ja: '巡り合い', en: 'CHANCE MEETING' }, { ja: '成り行き', en: 'COURSE OF EVENTS' }, { ja: '引き際', en: 'TIME TO WITHDRAW' },
    { ja: '潮時', en: 'RIGHT MOMENT' }, { ja: '幕引き', en: 'CURTAIN FALL' }, { ja: '始末', en: 'DISPOSAL' },
    { ja: '後始末', en: 'CLEANING UP' }, { ja: '帳尻', en: 'BALANCE OF ACCOUNTS' }, { ja: '抜け道', en: 'BYWAY' },
    { ja: '逃げ道', en: 'ESCAPE ROUTE' }, { ja: '回り道', en: 'ROUNDABOUT WAY' }
  ],
  humanWord: [
    { ja: '刑事', en: 'DETECTIVE' }, { ja: '巡査', en: 'PATROLMAN' }, { ja: '巡査部長', en: 'SERGEANT' },
    { ja: '警部', en: 'INSPECTOR' }, { ja: '警部補', en: 'ASSISTANT INSPECTOR' }, { ja: '警視', en: 'SUPERINTENDENT' },
    { ja: '署長', en: 'STATION CHIEF' }, { ja: '捜査官', en: 'INVESTIGATOR' }, { ja: '捜査一課長', en: 'HEAD OF HOMICIDE' },
    { ja: '鑑識官', en: 'FORENSIC OFFICER' }, { ja: '検視官', en: 'CORONER' }, { ja: '検事', en: 'PROSECUTOR' },
    { ja: '検事正', en: 'CHIEF PROSECUTOR' }, { ja: '副検事', en: 'DEPUTY PROSECUTOR' }, { ja: '判事', en: 'JUDGE' },
    { ja: '裁判長', en: 'PRESIDING JUDGE' }, { ja: '陪審員', en: 'JUROR' }, { ja: '書記官', en: 'COURT CLERK' },
    { ja: '弁護人', en: 'DEFENSE COUNSEL' }, { ja: '主任弁護人', en: 'LEAD COUNSEL' }, { ja: '国選弁護人', en: 'APPOINTED COUNSEL' },
    { ja: '弁護士', en: 'ATTORNEY' }, { ja: '執行官', en: 'BAILIFF' }, { ja: '監察官', en: 'INSPECTOR GENERAL' },
    { ja: '保護司', en: 'PROBATION OFFICER' }, { ja: '刑務官', en: 'PRISON OFFICER' }, { ja: '看守', en: 'WARDER' },
    { ja: '典獄', en: 'WARDEN' }, { ja: '死刑囚', en: 'DEATH ROW INMATE' }, { ja: '受刑者', en: 'CONVICT' },
    { ja: '元受刑者', en: 'EX CONVICT' }, { ja: '逃亡者', en: 'FUGITIVE' }, { ja: '指名手配犯', en: 'WANTED MAN' },
    { ja: '容疑者', en: 'SUSPECT' }, { ja: '被告人', en: 'DEFENDANT' }, { ja: '原告', en: 'PLAINTIFF' },
    { ja: '証人', en: 'WITNESS' }, { ja: '参考人', en: 'PERSON OF INTEREST' }, { ja: '通報者', en: 'CALLER' },
    { ja: '密告者', en: 'INFORMER' }, { ja: '情報屋', en: 'TIPSTER' }, { ja: '内通者', en: 'MOLE' },
    { ja: '二重スパイ', en: 'DOUBLE AGENT' }, { ja: '諜報員', en: 'INTELLIGENCE AGENT' }, { ja: '工作員', en: 'OPERATIVE' },
    { ja: '潜入捜査官', en: 'UNDERCOVER OFFICER' }, { ja: '監視員', en: 'WATCHER' }, { ja: '尾行者', en: 'TAIL' },
    { ja: '護衛官', en: 'BODYGUARD' }, { ja: '警備員', en: 'SECURITY GUARD' }, { ja: '交通課員', en: 'TRAFFIC OFFICER' },
    { ja: '鑑定人', en: 'EXPERT WITNESS' }, { ja: '通訳人', en: 'COURT INTERPRETER' }, { ja: '家裁調査官', en: 'FAMILY COURT OFFICER' },
    { ja: '検察事務官', en: 'PROSECUTION CLERK' }, { ja: '司法書士', en: 'JUDICIAL SCRIVENER' }, { ja: '公証人', en: 'NOTARY' },
    { ja: '調査官', en: 'EXAMINER' }, { ja: '取調官', en: 'INTERROGATOR' }, { ja: '押送官', en: 'ESCORT OFFICER' },
    { ja: '医師', en: 'PHYSICIAN' }, { ja: '外科医', en: 'SURGEON' }, { ja: '内科医', en: 'INTERNIST' },
    { ja: '法医学者', en: 'FORENSIC PATHOLOGIST' }, { ja: '検死医', en: 'MEDICAL EXAMINER' }, { ja: '看護師', en: 'NURSE' },
    { ja: '助産師', en: 'MIDWIFE' }, { ja: '救急隊員', en: 'PARAMEDIC' }, { ja: '薬剤師', en: 'PHARMACIST' },
    { ja: '精神科医', en: 'PSYCHIATRIST' }, { ja: '臨床心理士', en: 'CLINICAL PSYCHOLOGIST' }, { ja: '介護士', en: 'CAREGIVER' },
    { ja: '患者', en: 'PATIENT' }, { ja: '入院患者', en: 'INPATIENT' }, { ja: '移植待機者', en: 'TRANSPLANT CANDIDATE' },
    { ja: '麻酔医', en: 'ANESTHETIST' }, { ja: '産科医', en: 'OBSTETRICIAN' }, { ja: '小児科医', en: 'PEDIATRICIAN' },
    { ja: '主治医', en: 'ATTENDING DOCTOR' }, { ja: '開業医', en: 'GENERAL PRACTITIONER' }, { ja: '往診医', en: 'HOUSE CALL DOCTOR' },
    { ja: '衛生士', en: 'HYGIENIST' }, { ja: '理学療法士', en: 'PHYSIOTHERAPIST' }, { ja: '献血者', en: 'BLOOD DONOR' },
    { ja: '提供者', en: 'DONOR' },
    { ja: '記者', en: 'REPORTER' }, { ja: '新聞記者', en: 'NEWSPAPERMAN' }, { ja: '通信員', en: 'CORRESPONDENT' },
    { ja: '特派員', en: 'FOREIGN CORRESPONDENT' }, { ja: '編集長', en: 'EDITOR IN CHIEF' }, { ja: '整理部員', en: 'COPY DESK STAFF' },
    { ja: '報道カメラマン', en: 'NEWS CAMERAMAN' }, { ja: '写真記者', en: 'PHOTOJOURNALIST' }, { ja: 'フリーライター', en: 'FREELANCE WRITER' },
    { ja: 'ルポライター', en: 'FIELD WRITER' }, { ja: '論説委員', en: 'EDITORIAL WRITER' }, { ja: '解説委員', en: 'COMMENTATOR' },
    { ja: '編集委員', en: 'SENIOR EDITOR' }, { ja: '記者クラブ幹事', en: 'PRESS CLUB SECRETARY' }, { ja: '号外売り', en: 'EXTRA EDITION HAWKER' },
    { ja: '校閲者', en: 'FACT CHECKER' }, { ja: '記録映画作家', en: 'DOCUMENTARIAN' }, { ja: '放送記者', en: 'BROADCAST REPORTER' },
    { ja: '中継班', en: 'OUTSIDE BROADCAST CREW' }, { ja: '音声係', en: 'SOUND ASSISTANT' }, { ja: '番組制作者', en: 'PROGRAM MAKER' },
    { ja: '司会者', en: 'HOST' }, { ja: '実況者', en: 'PLAY BY PLAY ANNOUNCER' }, { ja: '通信社記者', en: 'WIRE SERVICE REPORTER' },
    { ja: '情報提供者', en: 'SOURCE' },
    { ja: '傭兵', en: 'MERCENARY' }, { ja: '兵士', en: 'SOLDIER' }, { ja: '志願兵', en: 'VOLUNTEER SOLDIER' },
    { ja: '徴集兵', en: 'CONSCRIPT' }, { ja: '下士官', en: 'NONCOMMISSIONED OFFICER' }, { ja: '将校', en: 'OFFICER' },
    { ja: '中尉', en: 'LIEUTENANT' }, { ja: '大尉', en: 'CAPTAIN' }, { ja: '少佐', en: 'MAJOR' },
    { ja: '大佐', en: 'COLONEL' }, { ja: '将軍', en: 'GENERAL' }, { ja: '参謀', en: 'STAFF OFFICER' },
    { ja: '副官', en: 'ADJUTANT' }, { ja: '軍医', en: 'ARMY DOCTOR' }, { ja: '従軍記者', en: 'WAR CORRESPONDENT' },
    { ja: '衛生兵', en: 'MEDIC' }, { ja: '狙撃手', en: 'MARKSMAN' }, { ja: '斥候', en: 'SCOUT' },
    { ja: '工兵', en: 'ENGINEER SOLDIER' }, { ja: '通信兵', en: 'SIGNALMAN' }, { ja: '憲兵', en: 'MILITARY POLICE' },
    { ja: '捕虜', en: 'PRISONER OF WAR' }, { ja: '脱走兵', en: 'DESERTER' }, { ja: '残留兵', en: 'HOLDOUT' },
    { ja: '復員兵', en: 'DEMOBILIZED SOLDIER' }, { ja: '傷痍軍人', en: 'DISABLED VETERAN' }, { ja: '砲手', en: 'GUNNER' },
    { ja: '操縦士', en: 'PILOT' }, { ja: '整備兵', en: 'MECHANIC SOLDIER' }, { ja: '機関銃手', en: 'MACHINE GUNNER' },
    { ja: '爆薬技師', en: 'DEMOLITION ENGINEER' }, { ja: '潜水艦乗り', en: 'SUBMARINER' }, { ja: '水兵', en: 'SAILOR' },
    { ja: '艦長', en: 'SHIP COMMANDER' }, { ja: '航海長', en: 'NAVIGATION OFFICER' }, { ja: '機関長', en: 'CHIEF ENGINEER' },
    { ja: '甲板員', en: 'DECKHAND' }, { ja: '輜重兵', en: 'BAGGAGE TRAIN SOLDIER' }, { ja: '補給係', en: 'QUARTERMASTER' },
    { ja: '監視哨員', en: 'LOOKOUT SENTRY' }, { ja: '特務曹長', en: 'WARRANT OFFICER' }, { ja: '志願看護婦', en: 'VOLUNTEER NURSE' },
    { ja: '従軍画家', en: 'WAR ARTIST' }, { ja: '通訳将校', en: 'INTERPRETER OFFICER' }, { ja: '軍属', en: 'CIVILIAN ATTACHE' },
    { ja: '教誨師', en: 'PRISON CHAPLAIN' }, { ja: '神父', en: 'PRIEST' }, { ja: '牧師', en: 'PASTOR' },
    { ja: '修道女', en: 'NUN' }, { ja: '修道士', en: 'MONK' }, { ja: '僧侶', en: 'BUDDHIST PRIEST' },
    { ja: '住職', en: 'HEAD PRIEST' }, { ja: '尼僧', en: 'BUDDHIST NUN' }, { ja: '宣教師', en: 'MISSIONARY' },
    { ja: '巡礼者', en: 'PILGRIM' }, { ja: '祈祷師', en: 'FAITH HEALER' }, { ja: '神職', en: 'SHINTO PRIEST' },
    { ja: '巫女', en: 'SHRINE MAIDEN' }, { ja: '説教師', en: 'PREACHER' }, { ja: '托鉢僧', en: 'MENDICANT' },
    { ja: '隠者', en: 'HERMIT' }, { ja: '行者', en: 'ASCETIC' }, { ja: '拝み屋', en: 'SPIRIT MEDIUM' },
    { ja: '寺男', en: 'TEMPLE SERVANT' }, { ja: '墓守', en: 'GRAVEKEEPER' },
    { ja: '遺族', en: 'BEREAVED FAMILY' }, { ja: '遺児', en: 'ORPHANED CHILD' }, { ja: '孤児', en: 'ORPHAN' },
    { ja: '未亡人', en: 'WIDOW' }, { ja: '寡婦', en: 'RELICT' }, { ja: '実父', en: 'BIRTH FATHER' },
    { ja: '継父', en: 'STEPFATHER' }, { ja: '継母', en: 'STEPMOTHER' }, { ja: '養父', en: 'ADOPTIVE FATHER' },
    { ja: '養母', en: 'ADOPTIVE MOTHER' }, { ja: '里親', en: 'FOSTER PARENT' }, { ja: '兄', en: 'ELDER BROTHER' },
    { ja: '妹', en: 'YOUNGER SISTER' }, { ja: '長男', en: 'ELDEST SON' }, { ja: '末娘', en: 'YOUNGEST DAUGHTER' },
    { ja: '一人娘', en: 'ONLY DAUGHTER' }, { ja: '婿', en: 'SON IN LAW' }, { ja: '嫁', en: 'DAUGHTER IN LAW' },
    { ja: '舅', en: 'FATHER IN LAW' }, { ja: '姑', en: 'MOTHER IN LAW' }, { ja: '甥', en: 'NEPHEW' },
    { ja: '姪', en: 'NIECE' }, { ja: '祖父', en: 'GRANDFATHER' }, { ja: '祖母', en: 'GRANDMOTHER' },
    { ja: '曾祖父', en: 'GREAT GRANDFATHER' }, { ja: '血縁者', en: 'BLOOD RELATION' }, { ja: '親権者', en: 'LEGAL GUARDIAN' },
    { ja: '保証人', en: 'GUARANTOR' }, { ja: '身元引受人', en: 'SPONSOR' }, { ja: '後見人', en: 'WARD KEEPER' },
    { ja: '相続人', en: 'HEIR' }, { ja: '受遺者', en: 'LEGATEE' }, { ja: '家長', en: 'PATRIARCH' },
    { ja: '当主', en: 'HOUSE HEAD' }, { ja: '隠居', en: 'RETIRED ELDER' }, { ja: '家政婦', en: 'HOUSEKEEPER' },
    { ja: '乳母', en: 'WET NURSE' }, { ja: '子守', en: 'NURSEMAID' }, { ja: '使用人', en: 'SERVANT' },
    { ja: '執事', en: 'BUTLER' },
    { ja: '教師', en: 'TEACHER' }, { ja: '校長', en: 'PRINCIPAL' }, { ja: '教頭', en: 'VICE PRINCIPAL' },
    { ja: '用務員', en: 'JANITOR' }, { ja: '司書', en: 'LIBRARIAN' }, { ja: '学芸員', en: 'CURATOR' },
    { ja: '研究者', en: 'RESEARCHER' }, { ja: '技師', en: 'ENGINEER' }, { ja: '設計士', en: 'DRAFTSMAN' },
    { ja: '建築士', en: 'ARCHITECT' }, { ja: '大工', en: 'CARPENTER' }, { ja: '左官', en: 'PLASTERER' },
    { ja: '鳶職', en: 'STEEPLEJACK' }, { ja: '船大工', en: 'SHIPWRIGHT' }, { ja: '漁師', en: 'FISHERMAN' },
    { ja: '船長', en: 'SKIPPER' }, { ja: '航海士', en: 'MATE' }, { ja: '機関士', en: 'ENGINE DRIVER' },
    { ja: '灯台守', en: 'LIGHTHOUSE KEEPER' }, { ja: '潜水士', en: 'DIVER' }, { ja: '猟師', en: 'HUNTER' },
    { ja: '山守', en: 'FOREST WARDEN' }, { ja: '樵', en: 'WOODCUTTER' }, { ja: '炭鉱夫', en: 'COAL MINER' },
    { ja: '坑夫', en: 'PITMAN' }, { ja: '製鉄工', en: 'IRONWORKER' }, { ja: '旋盤工', en: 'LATHE OPERATOR' },
    { ja: '溶接工', en: 'WELDER' }, { ja: '整備士', en: 'MECHANIC' }, { ja: '運転士', en: 'MOTORMAN' },
    { ja: '車掌', en: 'CONDUCTOR' }, { ja: '駅員', en: 'STATION HAND' }, { ja: '郵便配達員', en: 'POSTMAN' },
    { ja: '電話交換手', en: 'SWITCHBOARD OPERATOR' }, { ja: '電気工', en: 'ELECTRICIAN' }, { ja: '配管工', en: 'PLUMBER' },
    { ja: '清掃員', en: 'CLEANER' }, { ja: '廃品回収業者', en: 'RAG AND BONE MAN' }, { ja: '古物商', en: 'ANTIQUE DEALER' },
    { ja: '仲買人', en: 'BROKER' }, { ja: '行商人', en: 'PEDDLER' }, { ja: '露天商', en: 'STALLHOLDER' },
    { ja: '板前', en: 'CHEF' }, { ja: '料理人', en: 'COOK' }, { ja: '給仕', en: 'WAITER' },
    { ja: '女将', en: 'INNKEEPER' }, { ja: '仲居', en: 'INN ATTENDANT' }, { ja: '湯守', en: 'BATH KEEPER' },
    { ja: '理髪師', en: 'BARBER' }, { ja: '仕立屋', en: 'TAILOR' }, { ja: '靴職人', en: 'SHOEMAKER' },
    { ja: '時計職人', en: 'WATCHMAKER' }, { ja: '鍛冶屋', en: 'BLACKSMITH' }, { ja: '陶工', en: 'POTTER' },
    { ja: '硝子職人', en: 'GLASSBLOWER' }, { ja: '活版工', en: 'TYPESETTER' }, { ja: '製本工', en: 'BOOKBINDER' },
    { ja: '印刷工', en: 'PRINTER' }, { ja: '校正者', en: 'PROOFREADER' }, { ja: '翻訳者', en: 'TRANSLATOR' },
    { ja: '代筆屋', en: 'SCRIBE' }, { ja: '小説家', en: 'NOVELIST' }, { ja: '詩人', en: 'POET' },
    { ja: '劇作家', en: 'PLAYWRIGHT' }, { ja: '画家', en: 'PAINTER' }, { ja: '彫刻家', en: 'SCULPTOR' },
    { ja: '写真家', en: 'PHOTOGRAPHER' }, { ja: '作曲家', en: 'COMPOSER' }, { ja: '指揮者', en: 'CONDUCTOR OF ORCHESTRA' },
    { ja: '演奏家', en: 'MUSICIAN' }, { ja: '調律師', en: 'PIANO TUNER' }, { ja: '舞台監督', en: 'STAGE MANAGER' },
    { ja: '大道具方', en: 'SET HAND' }, { ja: '照明技師', en: 'LIGHTING TECHNICIAN' }, { ja: '役者', en: 'PLAYER' },
    { ja: '旅芸人', en: 'TRAVELING PERFORMER' }, { ja: '興行師', en: 'IMPRESARIO' }, { ja: '手品師', en: 'CONJURER' },
    { ja: '曲芸師', en: 'ACROBAT' }, { ja: '楽士', en: 'BANDSMAN' }, { ja: '農夫', en: 'FARMER' },
    { ja: '牧夫', en: 'HERDSMAN' }, { ja: '養蜂家', en: 'BEEKEEPER' }, { ja: '杜氏', en: 'MASTER BREWER' },
    { ja: '蔵人', en: 'BREWERY HAND' }, { ja: '塩焼き', en: 'SALT MAKER' }, { ja: '海女', en: 'SEA DIVER' },
    { ja: '網元', en: 'FISHERY MASTER' }, { ja: '桶屋', en: 'COOPER' }, { ja: '渡し守', en: 'FERRYMAN' },
    { ja: '殺し屋', en: 'HITMAN' }, { ja: '賞金稼ぎ', en: 'BOUNTY HUNTER' }, { ja: '用心棒', en: 'HIRED SWORD' },
    { ja: '運び屋', en: 'COURIER' }, { ja: '売人', en: 'PUSHER' }, { ja: '故買屋', en: 'FENCE' },
    { ja: '偽造屋', en: 'FORGER' }, { ja: '金貸し', en: 'MONEYLENDER' }, { ja: '取立て屋', en: 'DEBT COLLECTOR' },
    { ja: '高利貸し', en: 'USURER' }, { ja: '賭博師', en: 'GAMBLER' }, { ja: '胴元', en: 'BOOKMAKER' },
    { ja: '掏摸', en: 'PICKPOCKET' }, { ja: '空き巣', en: 'BURGLAR' }, { ja: '強盗', en: 'ROBBER' },
    { ja: '詐欺師', en: 'SWINDLER' }, { ja: '恐喝屋', en: 'BLACKMAILER' }, { ja: '密輸業者', en: 'SMUGGLER' },
    { ja: '密航者', en: 'STOWAWAY' }, { ja: '密漁者', en: 'POACHER' }, { ja: '盗掘者', en: 'TOMB ROBBER' },
    { ja: '闇医者', en: 'BACK ALLEY DOCTOR' }, { ja: '始末屋', en: 'CLEANER OF TRACES' }, { ja: '情婦', en: 'MISTRESS' },
    { ja: '顔役', en: 'BOSS FIGURE' }, { ja: '親分', en: 'GANG CHIEF' }, { ja: '若頭', en: 'UNDERBOSS' },
    { ja: '舎弟', en: 'YOUNGER MEMBER' }, { ja: '破門者', en: 'EXPELLED MAN' }, { ja: '流れ者', en: 'DRIFTER' },
    { ja: '渡世人', en: 'WANDERING GAMBLER' }, { ja: '博徒', en: 'DICE PLAYER' }, { ja: '香具師', en: 'FAIRGROUND TOUT' },
    { ja: '地上げ屋', en: 'LAND SHARK' }, { ja: '白タク', en: 'UNLICENSED CABBIE' }, { ja: '密造酒屋', en: 'MOONSHINER' },
    { ja: '偽証屋', en: 'PERJURER FOR HIRE' }, { ja: '身代わり屋', en: 'STAND IN FOR HIRE' }, { ja: '掃除屋', en: 'DISPOSAL MAN' },
    { ja: '追い剥ぎ', en: 'HIGHWAYMAN' }, { ja: '押し込み', en: 'HOME INVADER' }, { ja: '人買い', en: 'SLAVER' },
    { ja: '女衒', en: 'PROCURER' }, { ja: '密偵', en: 'SPY' }, { ja: '影武者', en: 'BODY DOUBLE' },
    { ja: '替え玉', en: 'SUBSTITUTE' }, { ja: '闇両替商', en: 'BLACK MARKET CHANGER' },
    { ja: '市長', en: 'MAYOR' }, { ja: '町長', en: 'TOWN HEAD' }, { ja: '村長', en: 'VILLAGE HEAD' },
    { ja: '議員', en: 'ASSEMBLYMAN' }, { ja: '秘書', en: 'SECRETARY' }, { ja: '官僚', en: 'BUREAUCRAT' },
    { ja: '事務次官', en: 'VICE MINISTER' }, { ja: '局長', en: 'BUREAU CHIEF' }, { ja: '課長', en: 'SECTION CHIEF' },
    { ja: '出納係', en: 'TELLER' }, { ja: '収税吏', en: 'TAX COLLECTOR' }, { ja: '徴税官', en: 'REVENUE OFFICER' },
    { ja: '検査官', en: 'AUDITOR' }, { ja: '監査役', en: 'STATUTORY AUDITOR' }, { ja: '調査委員', en: 'COMMISSION MEMBER' },
    { ja: '委員長', en: 'CHAIRMAN' }, { ja: '外交官', en: 'DIPLOMAT' }, { ja: '領事', en: 'CONSUL' },
    { ja: '大使', en: 'AMBASSADOR' }, { ja: '通訳官', en: 'OFFICIAL INTERPRETER' }, { ja: '密使', en: 'SECRET ENVOY' },
    { ja: '助役', en: 'DEPUTY MAYOR' }, { ja: '収入役', en: 'TREASURER' }, { ja: '駐在員', en: 'RESIDENT OFFICER' },
    { ja: '総督', en: 'GOVERNOR GENERAL' }, { ja: '代官', en: 'MAGISTRATE' }, { ja: '名主', en: 'VILLAGE ELDER' },
    { ja: '庄屋', en: 'HEADMAN' }, { ja: '区長', en: 'DISTRICT HEAD' }, { ja: '駐在', en: 'VILLAGE CONSTABLE' },
    { ja: '目撃者', en: 'EYEWITNESS' }, { ja: '生存者', en: 'SURVIVOR' }, { ja: '犠牲者', en: 'CASUALTY' },
    { ja: '被害者', en: 'VICTIM' }, { ja: '加害者', en: 'PERPETRATOR' }, { ja: '当事者', en: 'PARTY CONCERNED' },
    { ja: '傍観者', en: 'BYSTANDER' }, { ja: '依頼人', en: 'CLIENT' }, { ja: '債権者', en: 'CREDITOR' },
    { ja: '債務者', en: 'DEBTOR' }, { ja: '保険調査員', en: 'INSURANCE INVESTIGATOR' }, { ja: '探偵', en: 'SLEUTH' },
    { ja: '私立探偵', en: 'PRIVATE EYE' }, { ja: '亡命者', en: 'DEFECTOR' }, { ja: '難民', en: 'REFUGEE' },
    { ja: '引揚者', en: 'REPATRIATE' }, { ja: '家出人', en: 'RUNAWAY' }, { ja: '失踪者', en: 'MISSING PERSON' },
    { ja: '語り部', en: 'STORYKEEPER' }, { ja: '立会人', en: 'ATTESTING WITNESS' }
  ],
  placeName: [
    { ja: '白岬', en: 'SHIRAMISAKI' }, { ja: '黒森町', en: 'KUROMORI' }, { ja: '赤崎村', en: 'AKASAKI' },
    { ja: '青塚町', en: 'AOTSUKA' }, { ja: '蒼井浦', en: 'AOIURA' }, { ja: '紅沢', en: 'BENISAWA' },
    { ja: '灰島', en: 'HAIJIMA' }, { ja: '銀嶺町', en: 'GINREI' }, { ja: '金堀村', en: 'KANEHORI' },
    { ja: '黒瀬川', en: 'KUROSEGAWA' }, { ja: '白鷺町', en: 'SHIRASAGI' }, { ja: '朱雀橋', en: 'SUZAKUBASHI' },
    { ja: '碧沼', en: 'MIDORINUMA' }, { ja: '藍浦', en: 'AIURA' }, { ja: '墨谷峠', en: 'SUMIDANI PASS' },
    { ja: '白樺台', en: 'SHIRAKABADAI' }, { ja: '黒松浜', en: 'KUROMATSUHAMA' }, { ja: '赤石沢', en: 'AKAISHIZAWA' },
    { ja: '青柳町', en: 'AOYAGI' }, { ja: '黄檗坂', en: 'OUBAKUZAKA' }, { ja: '緋沼', en: 'HINUMA' },
    { ja: '蒼鷺岬', en: 'AOSAGI POINT' }, { ja: '白骨谷', en: 'SHIRAHONE VALLEY' }, { ja: '黒羽根島', en: 'KUROBANE ISLE' },
    { ja: '銀杏坂', en: 'ICHOZAKA' }, { ja: '錆浦', en: 'SABIURA' }, { ja: '鉛谷', en: 'NAMARIDANI' },
    { ja: '硫黄崎', en: 'IOUZAKI' }, { ja: '塩見町', en: 'SHIOMI' }, { ja: '汐入', en: 'SHIOIRI' },
    { ja: '潮見崎', en: 'SHIOMI POINT' }, { ja: '波切浜', en: 'NAMIKIRI BEACH' }, { ja: '磯部浦', en: 'ISOBEURA' },
    { ja: '荒磯岬', en: 'ARAISO CAPE' }, { ja: '石割峠', en: 'ISHIWARI PASS' }, { ja: '楢山村', en: 'NARAYAMA' },
    { ja: '杉沢', en: 'SUGISAWA' }, { ja: '桐谷', en: 'KIRIDANI' }, { ja: '柏木町', en: 'KASHIWAGI' },
    { ja: '榎坂', en: 'ENOKIZAKA' }, { ja: '樅ノ木町', en: 'MOMINOKI' }, { ja: '蓮沼', en: 'HASUNUMA' },
    { ja: '萱野原', en: 'KAYANOHARA' }, { ja: '笹倉', en: 'SASAKURA' }, { ja: '竹ノ内', en: 'TAKENOUCHI' },
    { ja: '梅ヶ枝町', en: 'UMEGAE' }, { ja: '桜堤', en: 'SAKURAZUTSUMI' }, { ja: '柳橋町', en: 'YANAGIBASHI' },
    { ja: '松風台', en: 'MATSUKAZEDAI' }, { ja: '楓ヶ丘', en: 'KAEDEGAOKA' }, { ja: '椿沢', en: 'TSUBAKIZAWA' },
    { ja: '霧ヶ浦', en: 'KIRIGAURA' }, { ja: '雪嶺峠', en: 'SETSUREI PASS' }, { ja: '岩淵町', en: 'IWABUCHI' },
    { ja: '砂原村', en: 'SUNAHARA' }, { ja: '崖下町', en: 'GAKESHITA' }, { ja: '鴉谷', en: 'KARASUDANI' },
    { ja: '狐塚', en: 'KITSUNEZUKA' }, { ja: '狼沢', en: 'OOKAMIZAWA' }, { ja: '鷺沼', en: 'SAGINUMA' },
    { ja: '第七埠頭', en: 'PIER SEVEN' }, { ja: '第三倉庫', en: 'WAREHOUSE THREE' }, { ja: '第五桟橋', en: 'JETTY FIVE' },
    { ja: '第二工区', en: 'WORK ZONE TWO' }, { ja: '第八号棟', en: 'BLOCK EIGHT' }, { ja: '第四作業場', en: 'WORKSHOP FOUR' },
    { ja: '第六隔離棟', en: 'ISOLATION WING SIX' }, { ja: '第一発電所', en: 'POWER STATION ONE' }, { ja: '第九分署', en: 'PRECINCT NINE' },
    { ja: '第十二保管庫', en: 'VAULT TWELVE' }, { ja: '第三検問所', en: 'CHECKPOINT THREE' }, { ja: '第二浄水場', en: 'WATERWORKS TWO' },
    { ja: '第十坑道', en: 'SHAFT TEN' }, { ja: '第四埠頭', en: 'PIER FOUR' }, { ja: '第五格納庫', en: 'HANGAR FIVE' },
    { ja: '第六詰所', en: 'POST SIX' }, { ja: '第二病棟', en: 'WARD TWO' }, { ja: '第七監房', en: 'CELL BLOCK SEVEN' },
    { ja: '第一収容棟', en: 'DETENTION BLOCK ONE' }, { ja: '第三観測所', en: 'OBSERVATORY THREE' }, { ja: '第八貯水槽', en: 'CISTERN EIGHT' },
    { ja: '第九貨物線', en: 'FREIGHT LINE NINE' }, { ja: '第五分校', en: 'BRANCH SCHOOL FIVE' }, { ja: '第十一号踏切', en: 'CROSSING ELEVEN' },
    { ja: '第二税関', en: 'CUSTOMS HOUSE TWO' },
    { ja: '旧鉱山', en: 'THE OLD MINE' }, { ja: '旧坑道', en: 'THE OLD SHAFT' }, { ja: '旧火薬庫', en: 'THE OLD MAGAZINE' },
    { ja: '旧測候所', en: 'THE OLD WEATHER STATION' }, { ja: '旧分校', en: 'THE OLD BRANCH SCHOOL' }, { ja: '旧診療所', en: 'THE OLD CLINIC' },
    { ja: '旧郵便局', en: 'THE OLD POST OFFICE' }, { ja: '旧集会所', en: 'THE OLD ASSEMBLY HALL' }, { ja: '旧図書室', en: 'THE OLD READING ROOM' },
    { ja: '旧貯水池', en: 'THE OLD RESERVOIR' }, { ja: '旧軌道跡', en: 'THE OLD TRAMWAY' }, { ja: '旧渡船場', en: 'THE OLD FERRY LANDING' },
    { ja: '旧灯台', en: 'THE OLD LIGHTHOUSE' }, { ja: '旧官舎', en: 'THE OLD OFFICIAL QUARTERS' }, { ja: '旧兵舎', en: 'THE OLD BARRACKS' },
    { ja: '旧税関', en: 'THE OLD CUSTOMS HOUSE' }, { ja: '旧検疫所', en: 'THE OLD QUARANTINE STATION' }, { ja: '旧製糸場', en: 'THE OLD SILK MILL' },
    { ja: '旧倉庫街', en: 'THE OLD WAREHOUSE ROW' }, { ja: '旧線路敷', en: 'THE OLD TRACKBED' }, { ja: '旧刑務所', en: 'THE OLD PRISON' },
    { ja: '旧市民病院', en: 'THE OLD CITY HOSPITAL' }, { ja: '旧配水塔', en: 'THE OLD WATER TOWER' }, { ja: '旧劇場', en: 'THE OLD THEATER' },
    { ja: '旧映画館', en: 'THE OLD PICTURE HOUSE' }, { ja: '旧遊園地', en: 'THE OLD FUNFAIR' }, { ja: '旧競馬場', en: 'THE OLD RACECOURSE' },
    { ja: '旧公会堂', en: 'THE OLD PUBLIC HALL' }, { ja: '旧寄宿舎', en: 'THE OLD DORMITORY' }, { ja: '旧火葬場', en: 'THE OLD CREMATORIUM' },
    { ja: '国境検問所', en: 'BORDER CHECKPOINT' }, { ja: '出入国管理所', en: 'IMMIGRATION OFFICE' }, { ja: '気象観測所', en: 'WEATHER STATION' },
    { ja: '地震観測所', en: 'SEISMIC STATION' }, { ja: '中央市場', en: 'CENTRAL MARKET' }, { ja: '卸売市場', en: 'WHOLESALE MARKET' },
    { ja: '屠畜場', en: 'SLAUGHTERHOUSE' }, { ja: '精錬所', en: 'SMELTER' }, { ja: '製材所', en: 'SAWMILL' },
    { ja: '造船所', en: 'SHIPYARD' }, { ja: '乾ドック', en: 'DRY DOCK' }, { ja: '引込線', en: 'SIDING' },
    { ja: '操車場', en: 'MARSHALLING YARD' }, { ja: '車両基地', en: 'ROLLING STOCK DEPOT' }, { ja: '転車台', en: 'TURNTABLE' },
    { ja: '保線区', en: 'TRACK SECTION' }, { ja: '信号所', en: 'SIGNAL BOX' }, { ja: '無人駅舎', en: 'UNSTAFFED STATION' },
    { ja: '待避線', en: 'PASSING LOOP' }, { ja: '貨物ヤード', en: 'FREIGHT YARD' }, { ja: '冷凍倉庫', en: 'COLD STORE' },
    { ja: '危険物倉庫', en: 'HAZARD STORE' }, { ja: '火薬庫', en: 'POWDER MAGAZINE' }, { ja: '弾薬庫', en: 'AMMUNITION STORE' },
    { ja: '兵器廠', en: 'ARSENAL' }, { ja: '演習場', en: 'TRAINING GROUND' }, { ja: '射撃場', en: 'FIRING RANGE' },
    { ja: '監視塔', en: 'WATCHTOWER' }, { ja: '望楼', en: 'LOOKOUT TOWER' }, { ja: '見張所', en: 'SENTRY POST' },
    { ja: '霧笛舎', en: 'FOG SIGNAL HOUSE' }, { ja: '検潮所', en: 'TIDE GAUGE STATION' }, { ja: '揚水機場', en: 'PUMPING STATION' },
    { ja: '排水機場', en: 'DRAINAGE STATION' }, { ja: '水門', en: 'FLOODGATE' }, { ja: '閘門', en: 'LOCK GATE' },
    { ja: '堰堤', en: 'WEIR' }, { ja: '沈殿池', en: 'SETTLING POND' }, { ja: '焼却炉', en: 'INCINERATOR' },
    { ja: '最終処分場', en: 'LANDFILL SITE' }, { ja: '埋立地', en: 'RECLAIMED LAND' }, { ja: '干拓地', en: 'POLDER' },
    { ja: '遊水池', en: 'RETENTION BASIN' }, { ja: '廃鉱', en: 'ABANDONED MINE' }, { ja: '露天掘り', en: 'OPENCAST PIT' },
    { ja: '選鉱場', en: 'ORE DRESSING PLANT' }, { ja: '立坑', en: 'VERTICAL SHAFT' }, { ja: '斜坑', en: 'INCLINED SHAFT' },
    { ja: '通気坑', en: 'AIR SHAFT' }, { ja: '貯炭場', en: 'COAL YARD' }, { ja: '索道', en: 'AERIAL ROPEWAY' },
    { ja: '鉱山鉄道', en: 'MINE RAILWAY' }, { ja: '精油所', en: 'REFINERY' }, { ja: '貯油槽', en: 'OIL TANK' },
    { ja: '送電鉄塔', en: 'PYLON' }, { ja: '変電所', en: 'SUBSTATION' }, { ja: '導水路', en: 'HEADRACE' },
    { ja: '隧道', en: 'TUNNEL' }, { ja: '拘置支所', en: 'DETENTION BRANCH' }, { ja: '少年院', en: 'REFORMATORY' },
    { ja: '更生施設', en: 'HALFWAY HOUSE' }, { ja: '収容所', en: 'INTERNMENT CAMP' }, { ja: '検疫棟', en: 'QUARANTINE WING' },
    { ja: '隔離病棟', en: 'ISOLATION WARD' }, { ja: '療養所', en: 'SANATORIUM' }, { ja: '養護施設', en: 'CHILDRENS HOME' },
    { ja: '孤児院', en: 'ORPHANAGE' }, { ja: '救護院', en: 'ALMSHOUSE' }, { ja: '簡易宿泊所', en: 'FLOPHOUSE' },
    { ja: '木賃宿', en: 'CHEAP INN' }, { ja: '遊郭跡', en: 'FORMER PLEASURE QUARTER' }, { ja: '賭場', en: 'GAMBLING DEN' },
    { ja: '闇市跡', en: 'FORMER BLACK MARKET' }, { ja: '長屋', en: 'ROW TENEMENT' }, { ja: '官舎群', en: 'OFFICIAL QUARTERS' },
    { ja: '社宅街', en: 'COMPANY HOUSING' }, { ja: '炭住街', en: 'MINERS ROW' }, { ja: '引揚寮', en: 'REPATRIATION HOSTEL' },
    { ja: '開拓村', en: 'PIONEER VILLAGE' }, { ja: '屯田村', en: 'GARRISON VILLAGE' }, { ja: '入植地', en: 'SETTLEMENT' },
    { ja: '分教場', en: 'SATELLITE SCHOOLHOUSE' }, { ja: '郷土資料館', en: 'LOCAL MUSEUM' }, { ja: '郷倉', en: 'VILLAGE GRANARY' },
    { ja: '蔵屋敷', en: 'STOREHOUSE ESTATE' }, { ja: '陣屋跡', en: 'FORMER GARRISON' }, { ja: '城址', en: 'CASTLE RUINS' },
    { ja: '番所跡', en: 'FORMER GUARD POST' }, { ja: '一里塚', en: 'MILEPOST MOUND' }, { ja: '渡し場', en: 'FERRY CROSSING' },
    { ja: '舟溜まり', en: 'BOAT BASIN' },
    { ja: '干潟', en: 'TIDAL FLAT' }, { ja: '砂州', en: 'SANDBAR' }, { ja: '洲崎', en: 'SANDSPIT' },
    { ja: '暗礁帯', en: 'REEF FIELD' }, { ja: '沈船', en: 'SUNKEN SHIP' }, { ja: '塩田跡', en: 'FORMER SALT FIELD' },
    { ja: '定置網', en: 'SET NET' }, { ja: '海女小屋', en: 'DIVERS HUT' }, { ja: '生簀', en: 'FISH PEN' },
    { ja: '漁協倉庫', en: 'FISHERY STORE' }, { ja: '風穴', en: 'WIND CAVE' }, { ja: '鍾乳洞', en: 'LIMESTONE CAVE' },
    { ja: '湧水池', en: 'SPRING POND' }, { ja: '沼沢地', en: 'MARSHLAND' }, { ja: '湿原', en: 'MOOR' },
    { ja: '泥炭地', en: 'PEAT BOG' }, { ja: '樹海', en: 'SEA OF TREES' }, { ja: '原生林', en: 'OLD GROWTH FOREST' },
    { ja: '防風林', en: 'WINDBREAK' }, { ja: '砂丘列', en: 'DUNE FIELD' }, { ja: '河原', en: 'RIVERBED' },
    { ja: '中州', en: 'RIVER ISLET' }, { ja: '三角州', en: 'DELTA' }, { ja: '河口堰', en: 'ESTUARY BARRAGE' },
    { ja: '分水嶺', en: 'WATERSHED' }, { ja: '峠道', en: 'PASS ROAD' }, { ja: '崖道', en: 'CLIFF ROAD' },
    { ja: '獣道', en: 'ANIMAL TRAIL' }, { ja: '廃道', en: 'ABANDONED ROAD' }, { ja: '廃線跡', en: 'DISUSED RAILWAY' },
    { ja: '廃村', en: 'ABANDONED VILLAGE' }, { ja: '無人島', en: 'UNINHABITED ISLAND' }, { ja: '孤島', en: 'REMOTE ISLE' },
    { ja: '岬灯台', en: 'CAPE LIGHT' },
    { ja: '商店街', en: 'SHOPPING ARCADE' }, { ja: '露地裏', en: 'BACK ALLEY' }, { ja: '貧民窟', en: 'SLUM' },
    { ja: '花街', en: 'PLEASURE DISTRICT' }, { ja: '寄場', en: 'DAY LABOR MARKET' }, { ja: '屋台横丁', en: 'STALL LANE' },
    { ja: '歓楽街', en: 'ENTERTAINMENT DISTRICT' }, { ja: '飲み屋横丁', en: 'TAVERN LANE' }, { ja: '中央通り', en: 'MAIN STREET' },
    { ja: '停車場前', en: 'STATION SQUARE' }, { ja: '駅裏', en: 'BEHIND THE STATION' }, { ja: '高架下', en: 'UNDER THE VIADUCT' },
    { ja: '陸橋', en: 'OVERPASS' }, { ja: '地下道', en: 'UNDERPASS' }, { ja: '河岸通り', en: 'QUAYSIDE STREET' },
    { ja: '倉庫街', en: 'WAREHOUSE DISTRICT' }, { ja: '造成地', en: 'GRADED LOT' }, { ja: '分譲地', en: 'SUBDIVISION' },
    { ja: '団地', en: 'HOUSING ESTATE' }, { ja: '給水塔', en: 'WATER TOWER' }, { ja: '屋上庭園', en: 'ROOF GARDEN' },
    { ja: '非常階段', en: 'FIRE ESCAPE' }, { ja: '地下駐車場', en: 'UNDERGROUND GARAGE' }, { ja: '立体駐車場', en: 'PARKING TOWER' },
    { ja: '廃工場', en: 'DERELICT FACTORY' }, { ja: '廃倉庫', en: 'DERELICT WAREHOUSE' }, { ja: '廃校舎', en: 'CLOSED SCHOOL' },
    { ja: '廃病院', en: 'CLOSED HOSPITAL' }, { ja: '廃旅館', en: 'CLOSED INN' }, { ja: '廃団地', en: 'DESERTED ESTATE' },
    { ja: '空港跡地', en: 'FORMER AIRFIELD' }, { ja: '滑走路跡', en: 'OLD RUNWAY' }, { ja: '格納庫', en: 'HANGAR' },
    { ja: '管制塔', en: 'CONTROL TOWER' }, { ja: '兵站基地', en: 'SUPPLY BASE' }, { ja: '補給廠', en: 'SUPPLY DEPOT' },
    { ja: '通信所', en: 'SIGNAL STATION' }, { ja: '無線塔', en: 'RADIO MAST' }, { ja: '灯明台', en: 'BEACON' },
    { ja: '検問線', en: 'CHECKPOINT LINE' }, { ja: '境界標', en: 'BOUNDARY MARKER' }, { ja: '緩衝地帯', en: 'BUFFER ZONE' },
    { ja: '立入禁止区域', en: 'RESTRICTED ZONE' }, { ja: '演習林', en: 'RESEARCH FOREST' }, { ja: '保安林', en: 'PROTECTED FOREST' },
    { ja: '官林', en: 'STATE FOREST' }, { ja: '御料地', en: 'CROWN LAND' }, { ja: '開墾地', en: 'CLEARED LAND' },
    { ja: '牧草地', en: 'PASTURE' }, { ja: '果樹園跡', en: 'FORMER ORCHARD' }, { ja: '桑畑', en: 'MULBERRY FIELD' },
    { ja: '茶畑', en: 'TEA FIELD' }, { ja: '麦畑', en: 'WHEAT FIELD' }, { ja: '蓮田', en: 'LOTUS FIELD' },
    { ja: '塩湖畔', en: 'SALT LAKESHORE' }, { ja: '温泉場', en: 'HOT SPRING RESORT' }, { ja: '湯治場', en: 'CURE BATHS' },
    { ja: '湯本', en: 'SPRING SOURCE' }, { ja: '番屋', en: 'FISHERMANS HUT' }, { ja: '山小屋', en: 'MOUNTAIN HUT' },
    { ja: '避難小屋', en: 'SHELTER HUT' }, { ja: '番小屋', en: 'WATCHMANS HUT' }, { ja: '木戸口', en: 'GATEWAY' }
  ],
  actionTe: [
    '追いかけて', '見送って', '数えて', '埋めて', '探して', '訪ねて', '抱いて', '背負って',
    '担いで', '運んで', '届けて', '手放して', '捨てて', '拾って', '拭って', '焼いて',
    '燃やして', '沈めて', '流して', '隠して', '暴いて', '剥がして', '裂いて', '断って',
    '絶って', '継いで', '繋いで', '結んで', '解いて', '縛って', '閉じて', '開けて',
    '叩いて', '押して', '引いて', '支えて', '庇って', '守って', '奪って', '盗んで',
    '返して', '償って', '許して', '責めて', '咎めて', '裁いて', '訴えて', '告げて',
    '迎えて', '送って', '見つめて', '見届けて', '見失って', '置いて', '残して', '忘れて',
    '覚えて', '思い出して', '名づけて', '呼んで', '尋ねて', '問いかけて', '答えて', '誓って',
    '裏切って', '疑って', '信じて', '委ねて', '託して', '預けて', '引き受けて', '引き取って',
    '引き渡して', '差し出して', '突き放して', '突き止めて', '突き詰めて', '探り当てて', '掘り起こして', '拾い集めて',
    '積み上げて', '崩して', '壊して', '直して', '繕って', '縫って', '織って', '編んで',
    '削って', '磨いて', '研いで', '撃って', '狙って', '構えて', '渡って', '越えて',
    '潜って', '昇って', '降りて', '振り返って', '見上げて', '見下ろして', '書き留めて', '書き換えて',
    '消して', '塗り潰して', '描いて', '撮って', '記して', '綴って', '読んで', '訳して',
    '語って', '諭して', '促して', '導いて', '従って', '逆らって', '抗って', '挑んで',
    '迫って', '退けて', '引き返して', '連れ帰って', '立ち去って', '離れて', '遠ざかって', '近づいて',
    '触れて', '掴んで', '握って', '放して', '抱きしめて', '撫でて', '拭いて', '洗って',
    '濯いで', '干して', '畳んで', '仕舞って', '並べて', '揃えて', '整えて', '数え直して',
    '選んで', '分けて', '混ぜて', '注いで', '灯して', '封じて', '閉ざして', '遮って',
    '阻んで', '塞いで', '覆って', '被せて', '剥ぎ取って', '引き裂いて', '断ち切って', '切り離して',
    '引き離して', '押しのけて', '押し込めて', '閉じ込めて', '締め出して', '追い出して', '追い返して', '追い払って',
    '追い詰めて', '追い越して', '追い抜いて', '待ち伏せて', '出し抜いて', '欺いて', '騙して', '陥れて',
    '仕組んで', '仕掛けて', '企てて', '謀って', '持ち出して', '持ち帰って', '持ち込んで', '運び去って',
    '積み込んで', '降ろして', '引き上げて', '吊るして', '掲げて', '翻して', '立てて', '建てて',
    '築いて', '据えて', '敷いて', '張って', '巡らせて', '囲って', '隔てて', '分かち合って',
    '譲って', '授けて', '与えて', '贈って', '手渡して', '受け取って', '受け止めて', '受け入れて',
    '拒んで', '背けて', '伏せて', '俯いて', '仰いで', '傾けて', '寄せて', '重ねて',
    '挟んで', '差し込んで', '抜いて', '抜き取って', '引き抜いて', '突き刺して', '貫いて', '穿って',
    '掘って', '埋め戻して', '撒いて', '蒔いて', '育てて', '摘んで', '刈って', '束ねて',
    '紡いで', '染めて', '晒して', '乾かして', '温めて', '冷やして', '凍らせて', '溶かして',
    '煮て', '炊いて', '焙って', '燻して', '潰して', '砕いて', '挽いて', '濾して',
    '量って', '測って', '印して', '刻んで', '彫って', '見張って', '見守って', '見比べて',
    '見極めて', '見透かして', '見抜いて', '聞き取って', '聞き分けて', '聞き流して', '嗅ぎ分けて', '探り出して',
    '洗い出して', '割り出して', '突き合わせて', '照らし合わせて', '呼び戻して', '呼び寄せて', '呼び止めて', '引き止めて',
    '食い止めて', '持ち堪えて', '耐え抜いて', '生き抜いて', '逃げ延びて', '落ち延びて', '潜り抜けて', '切り抜けて',
    '乗り越えて', '打ち勝って', '打ち破って', '討ち取って', '撃ち抜いて', '撃ち落として', '仕留めて', '葬って',
    '弔って', '供えて', '祈って', '願って', '詫びて', '謝って', '労って', '慰めて',
    '励まして', '待ちながら', '迷いながら', '震えながら', '泣きながら', '笑いながら', '祈りながら', '数えながら',
    '隠しながら', '逃げながら', '探しながら', '眠りながら', '歩きながら', '抱えながら', '耐えながら', '悔やみながら',
    '願いながら', '見つめながら', '語りながら', '黙りながら', '走りながら', '追いながら', '恐れながら', '疑いながら',
    '信じながら', '憎みながら', '赦しながら', '惑いながら', '待ち侘びながら', '呼びながら', '叫びながら', '囁きながら',
    '拒みながら', '受け入れながら', '抗いながら', '従いながら', '背きながら', '守りながら', '奪いながら', '償いながら',
    '悼みながら', '弔いながら', '覚えながら', '忘れながら', '記しながら', '描きながら', '撮りながら', '聴きながら',
    '待ち続けながら', '生きながら', '知らずに', '告げずに', '名乗らずに', '振り返らずに', '気づかずに', '許さずに',
    '忘れずに', '帰らずに', '逃げずに', '泣かずに', '語らずに', '問わずに', '答えずに', '迷わずに',
    '恐れずに', '抗わずに', '触れずに', '呼ばずに', '待たずに', '数えずに', '埋めずに', '焼かずに',
    '捨てずに', '拾わずに', '渡さずに', '明かさずに', '悔やまずに', '諦めずに', '終わらせずに', '振り切って'
  ],
  nounHead: [
    { ja: '銃', en: 'GUN' }, { ja: '罪', en: 'SIN' }, { ja: '硝煙', en: 'GUNSMOKE' },
    { ja: '鋼', en: 'STEEL' }, { ja: '獄', en: 'PRISON' }, { ja: '戦', en: 'WAR' },
    { ja: '掟', en: 'CODE' }, { ja: '極夜', en: 'POLARNIGHT' }, { ja: '硫黄', en: 'SULFUR' },
    { ja: '刃', en: 'BLADE' }, { ja: '弾', en: 'BULLET' }, { ja: '銃身', en: 'BARREL' },
    { ja: '銃口', en: 'MUZZLE' }, { ja: '薬莢', en: 'CARTRIDGE' }, { ja: '火薬', en: 'POWDER' },
    { ja: '導火', en: 'FUSE' }, { ja: '爆薬', en: 'EXPLOSIVE' }, { ja: '地雷', en: 'LANDMINE' },
    { ja: '機雷', en: 'SEA MINE' }, { ja: '砲', en: 'CANNON' }, { ja: '砲身', en: 'GUN BARREL' },
    { ja: '戦車', en: 'TANK' }, { ja: '軍靴', en: 'ARMY BOOT' }, { ja: '軍旗', en: 'REGIMENTAL FLAG' },
    { ja: '軍服', en: 'UNIFORM' }, { ja: '勲章', en: 'MEDAL' }, { ja: '徽章', en: 'INSIGNIA' },
    { ja: '階級', en: 'RANK' }, { ja: '号令', en: 'COMMAND' }, { ja: '号砲', en: 'SIGNAL GUN' },
    { ja: '進軍', en: 'ADVANCE' }, { ja: '行軍', en: 'MARCH' }, { ja: '退路', en: 'LINE OF RETREAT' },
    { ja: '敵陣', en: 'ENEMY LINE' }, { ja: '陣', en: 'ENCAMPMENT' }, { ja: '塹壕', en: 'TRENCH' },
    { ja: '掩体', en: 'BUNKER' }, { ja: '防壁', en: 'RAMPART' }, { ja: '城壁', en: 'CITY WALL' },
    { ja: '関門', en: 'BARRIER GATE' }, { ja: '検問', en: 'CHECKPOINT' }, { ja: '関所', en: 'TOLL BARRIER' },
    { ja: '国境', en: 'FRONTIER' }, { ja: '前線', en: 'FRONT LINE' }, { ja: '後方', en: 'REAR' },
    { ja: '補給', en: 'SUPPLY' }, { ja: '兵站', en: 'LOGISTICS' }, { ja: '糧食', en: 'RATIONS' },
    { ja: '法', en: 'LAW' }, { ja: '律', en: 'STATUTE' }, { ja: '令', en: 'EDICT' },
    { ja: '罰', en: 'PENALTY' }, { ja: '刑', en: 'SENTENCE' }, { ja: '獄舎', en: 'GAOL' },
    { ja: '牢', en: 'CELL' }, { ja: '縄目', en: 'BONDS' }, { ja: '手錠', en: 'HANDCUFFS' },
    { ja: '足枷', en: 'SHACKLES' }, { ja: '監房', en: 'CELLBLOCK' }, { ja: '独房', en: 'SOLITARY' },
    { ja: '鉄格子', en: 'IRON BARS' }, { ja: '令状', en: 'WARRANT' }, { ja: '手配', en: 'MANHUNT' },
    { ja: '前科', en: 'CRIMINAL RECORD' }, { ja: '余罪', en: 'OTHER OFFENSES' }, { ja: '共犯', en: 'ACCOMPLICE' },
    { ja: '主犯', en: 'RINGLEADER' }, { ja: '従犯', en: 'ACCESSORY' }, { ja: '教唆', en: 'INCITEMENT' },
    { ja: '幇助', en: 'ABETTING' }, { ja: '現場', en: 'THE SCENE' }, { ja: '凶器', en: 'MURDER WEAPON' },
    { ja: '遺留', en: 'LEFT EVIDENCE' }, { ja: '指紋', en: 'FINGERPRINT' }, { ja: '足跡', en: 'FOOTPRINT' },
    { ja: '血液', en: 'BLOOD SAMPLE' }, { ja: '毛髪', en: 'HAIR STRAND' }, { ja: '繊維', en: 'FIBER' },
    { ja: '弾丸', en: 'SLUG' }, { ja: '薬物', en: 'DRUG' }, { ja: '毒物', en: 'POISON' },
    { ja: '毒薬', en: 'VENOM' }, { ja: '麻薬', en: 'NARCOTIC' }, { ja: '阿片', en: 'OPIUM' },
    { ja: '覚醒剤', en: 'STIMULANT' }, { ja: '贓物', en: 'STOLEN GOODS' }, { ja: '偽札', en: 'COUNTERFEIT NOTE' },
    { ja: '印章', en: 'SEAL STAMP' }, { ja: '密書', en: 'SECRET LETTER' }, { ja: '暗号文', en: 'CIPHERTEXT' },
    { ja: '名簿', en: 'ROSTER' }, { ja: '台帳', en: 'REGISTER' }, { ja: '記録簿', en: 'LOGBOOK' },
    { ja: '供述書', en: 'WRITTEN STATEMENT' }, { ja: '調書', en: 'CASE FILE' }, { ja: '鑑定書', en: 'EXPERT REPORT' },
    { ja: '診断書', en: 'MEDICAL CERTIFICATE' }, { ja: '遺言書', en: 'LAST TESTAMENT' }, { ja: '契約書', en: 'CONTRACT' },
    { ja: '借用書', en: 'DEBT NOTE' }, { ja: '領収書', en: 'RECEIPT SLIP' }, { ja: '委任状', en: 'POWER OF ATTORNEY' },
    { ja: '誓約書', en: 'WRITTEN OATH' }, { ja: '覚書', en: 'MEMO' }, { ja: '念書', en: 'WRITTEN PLEDGE' },
    { ja: '始末書', en: 'LETTER OF ACCOUNT' }, { ja: '詫び状', en: 'APOLOGY LETTER' }, { ja: '果たし状', en: 'CHALLENGE LETTER' },
    { ja: '錫', en: 'TIN' }, { ja: '鉛', en: 'LEAD' }, { ja: '銅', en: 'COPPER' },
    { ja: '鋳鉄', en: 'CAST IRON' }, { ja: '鋼線', en: 'STEEL WIRE' }, { ja: '鉄骨', en: 'STEEL FRAME' },
    { ja: '鉄条', en: 'IRON BAR' }, { ja: '溶鉱', en: 'SMELTING' }, { ja: '鉱滓', en: 'SLAG' },
    { ja: '石炭', en: 'COAL' }, { ja: '石油', en: 'CRUDE OIL' }, { ja: '重油', en: 'HEAVY OIL' },
    { ja: '瀝青', en: 'BITUMEN' }, { ja: '硫酸', en: 'SULFURIC ACID' }, { ja: '硝酸', en: 'NITRIC ACID' },
    { ja: '塩酸', en: 'HYDROCHLORIC ACID' }, { ja: '水銀', en: 'MERCURY' }, { ja: '弾倉', en: 'MAGAZINE' },
    { ja: '弾帯', en: 'AMMO BELT' }, { ja: '弾道', en: 'TRAJECTORY' }, { ja: '弾痕', en: 'BULLET HOLE' },
    { ja: '銃創', en: 'GUNSHOT WOUND' }, { ja: '傷痕', en: 'WOUND MARK' }, { ja: '血糊', en: 'CLOTTED BLOOD' },
    { ja: '血痕', en: 'BLOODSTAIN' }, { ja: '屍', en: 'CORPSE' }, { ja: '遺体', en: 'BODY' },
    { ja: '白骨', en: 'SKELETON' }, { ja: '頭蓋', en: 'SKULL' }, { ja: '肋', en: 'RIB' },
    { ja: '腱', en: 'TENDON' }, { ja: '臓', en: 'ORGAN' }, { ja: '肺', en: 'LUNG' },
    { ja: '肝', en: 'LIVER' }, { ja: '喉', en: 'THROAT' }, { ja: '顎', en: 'JAW' },
    { ja: '拳', en: 'FIST' }, { ja: '拳銃', en: 'PISTOL' }, { ja: '刀', en: 'SWORD' },
    { ja: '短刀', en: 'DAGGER' }, { ja: '匕首', en: 'STILETTO' }, { ja: '出刃', en: 'CLEAVER' },
    { ja: '斧', en: 'AXE' }, { ja: '鎌', en: 'SICKLE' }, { ja: '錐', en: 'AWL' },
    { ja: '鑿', en: 'CHISEL' }, { ja: '鉈', en: 'HATCHET' }, { ja: '鞭', en: 'WHIP' },
    { ja: '縄', en: 'ROPE' }, { ja: '綱', en: 'CABLE' }, { ja: '錠', en: 'LOCK' },
    { ja: '枷', en: 'FETTER' }, { ja: '鋲', en: 'RIVET' }, { ja: '釘', en: 'NAIL' },
    { ja: '鋸', en: 'SAW' }, { ja: '楔', en: 'WEDGE' }, { ja: '螺子', en: 'SCREW' },
    { ja: '歯車', en: 'GEAR' }, { ja: '軸受', en: 'BEARING' }, { ja: '発条', en: 'SPRING' },
    { ja: '蒸気', en: 'STEAM' }, { ja: '煤', en: 'SOOT' }, { ja: '排気', en: 'EXHAUST' },
    { ja: '廃液', en: 'WASTE FLUID' }, { ja: '汚泥', en: 'SLUDGE' }, { ja: '瓦礫', en: 'RUBBLE' },
    { ja: '残骸', en: 'WRECKAGE' }, { ja: '残滓', en: 'DREGS' }, { ja: '灰燼', en: 'EMBERS' },
    { ja: '焼跡', en: 'BURNT RUINS' }, { ja: '廃坑', en: 'DISUSED PIT' }, { ja: '廃線', en: 'DEFUNCT LINE' },
    { ja: '廃屋', en: 'RUINED HOUSE' }, { ja: '廃船', en: 'HULK' }, { ja: '座礁', en: 'GROUNDING' },
    { ja: '難破', en: 'SHIPWRECK' }, { ja: '軌条', en: 'RAIL' }, { ja: '枕木', en: 'SLEEPER' },
    { ja: '鉄橋', en: 'IRON BRIDGE' }, { ja: '鉄路', en: 'IRON ROAD' }, { ja: '亀裂', en: 'CRACK' },
    { ja: '罅', en: 'FISSURE' }, { ja: '溝', en: 'GROOVE' }, { ja: '淵', en: 'DEEP POOL' },
    { ja: '鉄扉', en: 'IRON DOOR' }, { ja: '鉄柵', en: 'IRON FENCE' }, { ja: '鉄条網', en: 'BARBED WIRE' },
    { ja: '金網', en: 'WIRE MESH' }, { ja: '通風口', en: 'VENT' }, { ja: '排水溝', en: 'DRAIN' },
    { ja: '側溝', en: 'GUTTER' }, { ja: '暗渠', en: 'CULVERT' }, { ja: '下水', en: 'SEWER' },
    { ja: '汚水', en: 'FOUL WATER' }, { ja: '油膜', en: 'OIL FILM' }, { ja: '重機', en: 'HEAVY MACHINE' },
    { ja: '鉄槌', en: 'SLEDGEHAMMER' }, { ja: '万力', en: 'VISE' }, { ja: '滑車', en: 'PULLEY' },
    { ja: '巻上機', en: 'WINCH' }, { ja: '鉄棒', en: 'IRON ROD' }, { ja: '木刀', en: 'WOODEN SWORD' },
    { ja: '竹刀', en: 'BAMBOO SWORD' }, { ja: '鉄拳', en: 'IRON FIST' }, { ja: '銃架', en: 'GUN RACK' },
    { ja: '銃眼', en: 'EMBRASURE' }, { ja: '望遠鏡', en: 'TELESCOPE' }, { ja: '双眼鏡', en: 'BINOCULARS' },
    { ja: '照準', en: 'SIGHT' }, { ja: '引金', en: 'TRIGGER' }, { ja: '撃鉄', en: 'HAMMER' },
    { ja: '遊底', en: 'BOLT' }, { ja: '消音器', en: 'SILENCER' }, { ja: '実包', en: 'LIVE ROUND' },
    { ja: '空包', en: 'BLANK ROUND' }, { ja: '榴弾', en: 'SHELL' }, { ja: '砲弾', en: 'ARTILLERY SHELL' },
    { ja: '破片', en: 'SHRAPNEL' }, { ja: '閃光', en: 'FLASH' }, { ja: '轟音', en: 'ROAR' },
    { ja: '銃音', en: 'REPORT OF A GUN' }, { ja: '硝子片', en: 'GLASS SHARD' }, { ja: '焼夷', en: 'INCENDIARY' },
    { ja: '導線', en: 'LEAD WIRE' }, { ja: '起爆', en: 'DETONATION' }, { ja: '信管', en: 'DETONATOR' },
    { ja: '時限', en: 'TIMER' }, { ja: '発煙', en: 'SMOKE SCREEN' }, { ja: '催涙', en: 'TEAR GAS' },
    { ja: '防毒', en: 'GAS MASK' }, { ja: '鉄兜', en: 'HELMET' }, { ja: '防弾', en: 'BULLETPROOF' },
    { ja: '銃剣', en: 'BAYONET' }, { ja: '鞘', en: 'SCABBARD' }, { ja: '柄', en: 'HILT' },
    { ja: '鍔', en: 'SWORD GUARD' }, { ja: '刃先', en: 'EDGE' }, { ja: '峰', en: 'BACK OF BLADE' },
    { ja: '血刀', en: 'BLOODIED BLADE' }, { ja: '軍鶏', en: 'GAMECOCK' }, { ja: '猟犬', en: 'HOUND' },
    { ja: '軍馬', en: 'WARHORSE' }, { ja: '駄馬', en: 'PACKHORSE' }, { ja: '荷車', en: 'HANDCART' },
    { ja: '荷馬車', en: 'WAGON' }, { ja: '橇', en: 'SLEDGE' }, { ja: '筏', en: 'RAFT' },
    { ja: '艀', en: 'BARGE' }, { ja: '帆船', en: 'SAILING SHIP' }, { ja: '曳船', en: 'TUGBOAT' },
    { ja: '砕氷船', en: 'ICEBREAKER' }, { ja: '潜水艦', en: 'SUBMARINE' }, { ja: '駆逐艦', en: 'DESTROYER' },
    { ja: '輸送船', en: 'TRANSPORT SHIP' }, { ja: '貨物船', en: 'FREIGHTER' }, { ja: '漁船', en: 'FISHING BOAT' },
    { ja: '救命艇', en: 'LIFEBOAT' }, { ja: '浮標', en: 'BUOY' }, { ja: '錨鎖', en: 'ANCHOR CHAIN' },
    { ja: '舵', en: 'RUDDER' }, { ja: '羅針盤', en: 'COMPASS' }, { ja: '海図', en: 'SEA CHART' },
    { ja: '無線', en: 'WIRELESS' }, { ja: '電文', en: 'TELEGRAM' }, { ja: '暗電', en: 'CODED CABLE' },
    { ja: '受話器', en: 'RECEIVER' }, { ja: '交換台', en: 'SWITCHBOARD' }, { ja: '発信機', en: 'TRANSMITTER' },
    { ja: '盗聴器', en: 'LISTENING DEVICE' }, { ja: '録音機', en: 'RECORDER' }, { ja: '映写機', en: 'PROJECTOR' },
    { ja: '暗室', en: 'DARKROOM' }, { ja: '現像液', en: 'DEVELOPER' }, { ja: '陰画', en: 'NEGATIVE' },
    { ja: '陽画', en: 'POSITIVE PRINT' }, { ja: '謄写版', en: 'MIMEOGRAPH' }, { ja: '活字', en: 'MOVABLE TYPE' }
  ],
  nounTail: [
    { ja: '追跡', en: 'PURSUIT' }, { ja: '逃亡', en: 'FLIGHT' }, { ja: '審判', en: 'JUDGMENT' },
    { ja: '贖罪', en: 'ATONEMENT' }, { ja: '遺言', en: 'TESTAMENT' }, { ja: '銃声', en: 'GUNSHOT' },
    { ja: '序章', en: 'PROLOGUE' }, { ja: '終幕', en: 'FINALE' }, { ja: '復讐', en: 'VENGEANCE' },
    { ja: '亡命', en: 'EXILE' }, { ja: '密約', en: 'PACT' }, { ja: '証言', en: 'TESTIMONY' },
    { ja: '断罪', en: 'CONDEMNATION' }, { ja: '包囲', en: 'SIEGE' },
    { ja: '逃走', en: 'GETAWAY' }, { ja: '遁走', en: 'ABSCONDMENT' }, { ja: '追捕', en: 'PURSUIT AND SEIZURE' },
    { ja: '捕縛', en: 'CAPTURE' }, { ja: '拘束', en: 'DETENTION' }, { ja: '護送', en: 'TRANSFER UNDER GUARD' },
    { ja: '脱獄', en: 'JAILBREAK' }, { ja: '脱走', en: 'BREAKOUT' }, { ja: '逃避行', en: 'FLIGHT TOGETHER' },
    { ja: '帰還', en: 'RETURN' }, { ja: '生還', en: 'COMING BACK ALIVE' }, { ja: '転落', en: 'DOWNFALL' },
    { ja: '失墜', en: 'LOSS OF STANDING' }, { ja: '没落', en: 'RUIN' }, { ja: '破滅', en: 'PERDITION' },
    { ja: '崩壊', en: 'COLLAPSE' }, { ja: '壊滅', en: 'DEVASTATION' }, { ja: '全滅', en: 'TOTAL LOSS' },
    { ja: '殲滅', en: 'EXTERMINATION' }, { ja: '掃討', en: 'MOPPING UP' }, { ja: '制圧', en: 'SUPPRESSION' },
    { ja: '鎮圧', en: 'QUELLING' }, { ja: '平定', en: 'PACIFICATION' }, { ja: '征服', en: 'CONQUEST' },
    { ja: '支配', en: 'DOMINION' }, { ja: '統治', en: 'GOVERNANCE' }, { ja: '独裁', en: 'DICTATORSHIP' },
    { ja: '専横', en: 'TYRANNY' }, { ja: '圧政', en: 'OPPRESSIVE RULE' }, { ja: '弾圧', en: 'CRACKDOWN' },
    { ja: '抑圧', en: 'REPRESSION' }, { ja: '迫害', en: 'PERSECUTION' }, { ja: '排斥', en: 'EXCLUSION' },
    { ja: '追放', en: 'BANISHMENT' }, { ja: '流刑', en: 'PENAL EXILE' }, { ja: '幽閉', en: 'CONFINEMENT' },
    { ja: '監禁', en: 'IMPRISONMENT' }, { ja: '軟禁', en: 'HOUSE ARREST' }, { ja: '隔絶', en: 'ISOLATION' },
    { ja: '封鎖', en: 'BLOCKADE' }, { ja: '遮断', en: 'CUTOFF' }, { ja: '断絶', en: 'EXTINCTION OF A LINE' },
    { ja: '決裂', en: 'BREAKDOWN' }, { ja: '破約', en: 'BROKEN PROMISE' }, { ja: '離反', en: 'DEFECTION' },
    { ja: '造反', en: 'REVOLT' }, { ja: '謀反', en: 'INSURRECTION' }, { ja: '叛逆', en: 'TREASON' },
    { ja: '抵抗', en: 'RESISTANCE' }, { ja: '抗戦', en: 'ARMED RESISTANCE' }, { ja: '決起', en: 'RISING UP' },
    { ja: '蜂起', en: 'INSURGENCE' }, { ja: '暴発', en: 'ACCIDENTAL DISCHARGE' }, { ja: '爆発', en: 'EXPLOSION' },
    { ja: '炎上', en: 'CONFLAGRATION' }, { ja: '延焼', en: 'SPREAD OF FIRE' }, { ja: '鎮火', en: 'EXTINGUISHING' },
    { ja: '救出', en: 'RESCUE' }, { ja: '救援', en: 'RELIEF' }, { ja: '救済', en: 'SALVATION' },
    { ja: '奪還', en: 'RECAPTURE' }, { ja: '奪取', en: 'SEIZURE' }, { ja: '強奪', en: 'ROBBERY' },
    { ja: '略奪', en: 'PLUNDER' }, { ja: '収奪', en: 'EXTRACTION' }, { ja: '搾取', en: 'EXPLOITATION' },
    { ja: '詐取', en: 'FRAUDULENT GAIN' }, { ja: '窃取', en: 'THEFT' }, { ja: '横領', en: 'EMBEZZLEMENT' },
    { ja: '着服', en: 'MISAPPROPRIATION' }, { ja: '隠匿', en: 'HARBORING' }, { ja: '秘匿', en: 'SECRECY' },
    { ja: '暴露', en: 'EXPOSURE' }, { ja: '露見', en: 'DISCOVERY' }, { ja: '発覚', en: 'COMING TO LIGHT' },
    { ja: '摘発', en: 'EXPOSE RAID' }, { ja: '検挙', en: 'ROUNDUP' }, { ja: '陰謀', en: 'CONSPIRACY' },
    { ja: '策謀', en: 'SCHEME' }, { ja: '謀略', en: 'STRATAGEM' }, { ja: '画策', en: 'MANEUVERING' },
    { ja: '暗躍', en: 'COVERT ACTION' }, { ja: '暗殺', en: 'ASSASSINATION' }, { ja: '抹殺', en: 'OBLITERATION' },
    { ja: '消息', en: 'WORD OF SOMEONE' }, { ja: '失踪', en: 'DISAPPEARANCE' }, { ja: '蒸発', en: 'VANISHING' },
    { ja: '誘拐', en: 'ABDUCTION' }, { ja: '拉致', en: 'KIDNAPPING' }, { ja: '人質', en: 'HOSTAGE' },
    { ja: '身代金', en: 'RANSOM' }, { ja: '脅迫', en: 'THREAT' }, { ja: '恐喝', en: 'EXTORTION' },
    { ja: '談合', en: 'COLLUSION' }, { ja: '汚職', en: 'GRAFT' }, { ja: '収賄', en: 'BRIBE TAKING' },
    { ja: '贈賄', en: 'BRIBE GIVING' }, { ja: '背任', en: 'BREACH OF TRUST' }, { ja: '脱税', en: 'TAX EVASION' },
    { ja: '粉飾', en: 'WINDOW DRESSING' }, { ja: '偽造', en: 'FORGERY' }, { ja: '変造', en: 'ALTERATION' },
    { ja: '改竄', en: 'TAMPERING' }, { ja: '買収', en: 'BUYING OFF' }, { ja: '癒着', en: 'COLLUSIVE TIE' },
    { ja: '圧力', en: 'PRESSURE' }, { ja: '介入', en: 'INTERVENTION' }, { ja: '干渉', en: 'INTERFERENCE' },
    { ja: '検閲', en: 'CENSORSHIP' }, { ja: '監視', en: 'SURVEILLANCE' }, { ja: '盗聴', en: 'WIRETAP' },
    { ja: '傍受', en: 'INTERCEPTION' }, { ja: '諜報', en: 'ESPIONAGE' }, { ja: '工作', en: 'COVERT OPERATION' },
    { ja: '撹乱', en: 'DISRUPTION' }, { ja: '内通', en: 'SECRET COMMUNICATION' }, { ja: '潜行', en: 'GOING UNDERGROUND' },
    { ja: '潜伏', en: 'LYING LOW' }, { ja: '密航', en: 'STOWING AWAY' }, { ja: '密漁', en: 'POACHING' },
    { ja: '密造', en: 'ILLICIT MANUFACTURE' }, { ja: '密売', en: 'ILLICIT SALE' }, { ja: '密会', en: 'SECRET MEETING' },
    { ja: '密談', en: 'SECRET TALK' }, { ja: '密通', en: 'CLANDESTINE AFFAIR' }, { ja: '密命', en: 'SECRET ORDERS' },
    { ja: '審理', en: 'HEARING' }, { ja: '起訴', en: 'INDICTMENT' }, { ja: '公判', en: 'TRIAL' },
    { ja: '判決', en: 'VERDICT' }, { ja: '量刑', en: 'SENTENCING' }, { ja: '求刑', en: 'DEMANDED SENTENCE' },
    { ja: '弁論', en: 'PLEADING' }, { ja: '抗告', en: 'OBJECTION' }, { ja: '上告', en: 'FINAL APPEAL' },
    { ja: '控訴', en: 'APPEAL' }, { ja: '再審', en: 'RETRIAL' }, { ja: '執行', en: 'EXECUTION OF SENTENCE' },
    { ja: '恩赦', en: 'AMNESTY' }, { ja: '時効', en: 'STATUTE OF LIMITATIONS' }, { ja: '冤罪', en: 'FALSE CHARGE' },
    { ja: '誤認', en: 'MISIDENTIFICATION' }, { ja: '自白', en: 'CONFESSION' }, { ja: '黙秘', en: 'RIGHT OF SILENCE' },
    { ja: '物証', en: 'PHYSICAL EVIDENCE' }, { ja: '目撃', en: 'SIGHTING' }, { ja: '検証', en: 'ON SITE INSPECTION' },
    { ja: '鑑識', en: 'FORENSICS' }, { ja: '検死', en: 'AUTOPSY' }, { ja: '押収', en: 'CONFISCATION' },
    { ja: '捜索', en: 'SEARCH' }, { ja: '尋問', en: 'INTERROGATION' }, { ja: '取調', en: 'QUESTIONING' },
    { ja: '内偵', en: 'COVERT INQUIRY' }, { ja: '潜入', en: 'INFILTRATION' }, { ja: '尾行', en: 'SHADOWING' },
    { ja: '張込', en: 'STAKEOUT' }, { ja: '自首', en: 'SURRENDER TO THE LAW' }, { ja: '出頭', en: 'APPEARANCE' },
    { ja: '保釈', en: 'BAIL' }, { ja: '仮釈放', en: 'PAROLE' }, { ja: '服役', en: 'PENAL SERVITUDE' },
    { ja: '収監', en: 'INCARCERATION' }, { ja: '面会', en: 'PRISON VISIT' }, { ja: '送検', en: 'REFERRAL' },
    { ja: '立件', en: 'BUILDING A CASE' }, { ja: '告訴', en: 'CRIMINAL COMPLAINT' }, { ja: '告発', en: 'ACCUSATION' },
    { ja: '密告', en: 'TIP OFF' }, { ja: '通報', en: 'REPORTING' }, { ja: '偽証', en: 'PERJURY' },
    { ja: '訴追', en: 'PROSECUTION' }, { ja: '免訴', en: 'DISMISSAL' }, { ja: '無罪', en: 'ACQUITTAL' },
    { ja: '有罪', en: 'CONVICTION' }, { ja: '死刑', en: 'CAPITAL PUNISHMENT' }, { ja: '終身刑', en: 'LIFE SENTENCE' },
    { ja: '執行猶予', en: 'SUSPENDED SENTENCE' }, { ja: '判例', en: 'PRECEDENT' }, { ja: '弁済', en: 'REPAYMENT' },
    { ja: '弁償', en: 'INDEMNITY' }, { ja: '供託', en: 'DEPOSIT IN TRUST' },
    { ja: '開戦', en: 'OUTBREAK OF WAR' }, { ja: '停戦', en: 'CEASEFIRE' }, { ja: '休戦', en: 'TRUCE' },
    { ja: '講和', en: 'PEACE ACCORD' }, { ja: '降伏', en: 'SURRENDER OF ARMS' }, { ja: '撤退', en: 'WITHDRAWAL' },
    { ja: '撤収', en: 'PULLOUT' }, { ja: '敗走', en: 'ROUT' }, { ja: '奇襲', en: 'SURPRISE ATTACK' },
    { ja: '強襲', en: 'ASSAULT' }, { ja: '突撃', en: 'CHARGE' }, { ja: '迎撃', en: 'INTERCEPT' },
    { ja: '反攻', en: 'COUNTEROFFENSIVE' }, { ja: '総攻撃', en: 'ALL OUT ATTACK' }, { ja: '死守', en: 'LAST DITCH DEFENSE' },
    { ja: '籠城', en: 'HOLDING THE WALLS' }, { ja: '玉砕', en: 'FIGHT TO THE DEATH' }, { ja: '出征', en: 'GOING TO THE FRONT' },
    { ja: '従軍', en: 'MILITARY SERVICE' }, { ja: '空襲', en: 'AIR RAID' }, { ja: '軍法', en: 'MILITARY LAW' },
    { ja: '軍規', en: 'MILITARY DISCIPLINE' }, { ja: '戦犯', en: 'WAR CRIME' }, { ja: '慰霊', en: 'CONSOLING THE DEAD' },
    { ja: '戦没', en: 'DEATH IN BATTLE' }, { ja: '報復', en: 'RETALIATION' }, { ja: '抗争', en: 'FEUD' },
    { ja: '内乱', en: 'CIVIL DISORDER' }, { ja: '内戦', en: 'CIVIL WAR' }, { ja: '粛清', en: 'PURGE' },
    { ja: '処刑', en: 'EXECUTION' }, { ja: '銃殺', en: 'FIRING SQUAD' }, { ja: '絞首', en: 'HANGING' },
    { ja: '惨劇', en: 'CARNAGE' }, { ja: '虐殺', en: 'MASSACRE' }, { ja: '犠牲', en: 'SACRIFICE' },
    { ja: '殉職', en: 'DEATH ON DUTY' }, { ja: '殉難', en: 'MARTYRDOM' }, { ja: '遺骨', en: 'REMAINS' },
    { ja: '戦跡', en: 'BATTLE SITE' }, { ja: '宿命', en: 'FATE' }, { ja: '運命', en: 'DESTINY' },
    { ja: '因果', en: 'KARMA' }, { ja: '応報', en: 'RETRIBUTION' }, { ja: '天命', en: 'MANDATE' },
    { ja: '摂理', en: 'PROVIDENCE' }, { ja: '予兆', en: 'PORTENT' }, { ja: '予言', en: 'PROPHECY' },
    { ja: '啓示', en: 'REVELATION' }, { ja: '救い', en: 'DELIVERANCE' }, { ja: '赦免', en: 'PARDON' },
    { ja: '恩讐', en: 'GRUDGE AND GRATITUDE' }, { ja: '遺恨', en: 'LINGERING GRUDGE' }, { ja: '宿怨', en: 'OLD ENMITY' },
    { ja: '怨恨', en: 'RANCOR' }, { ja: '報恩', en: 'REPAYING KINDNESS' }, { ja: '恩義', en: 'OBLIGATION' },
    { ja: '義理', en: 'DUTY' }, { ja: '人情', en: 'HUMAN FEELING' }, { ja: '情誼', en: 'FELLOW FEELING' },
    { ja: '節義', en: 'FIDELITY' }, { ja: '忠義', en: 'FEALTY' }, { ja: '献身', en: 'DEVOTION' },
    { ja: '覚悟', en: 'RESOLVE' }, { ja: '決断', en: 'DECISION' }, { ja: '逡巡', en: 'HESITATION' },
    { ja: '断念', en: 'RENUNCIATION OF HOPE' }, { ja: '奮起', en: 'ROUSING' }, { ja: '再起', en: 'COMEBACK' },
    { ja: '雪辱', en: 'REDEMPTION OF HONOR' }, { ja: '汚点', en: 'BLOT' }, { ja: '禍根', en: 'ROOT OF DISASTER' },
    { ja: '遺構', en: 'RUINED WORKS' }, { ja: '慣行', en: 'CUSTOMARY PRACTICE' }, { ja: '掟破り', en: 'BREACH OF THE CODE' }
  ],
  adj: [
    { ja: '血塗られた', en: 'BLOODSTAINED' }, { ja: '逃れられない', en: 'INESCAPABLE' },
    { ja: '選ばれし', en: 'CHOSEN' }, { ja: '呪われた', en: 'CURSED' },
    { ja: '生き残った', en: 'SURVIVING' }, { ja: '引き返せない', en: 'IRREVOCABLE' },
    { ja: '裁かれざる', en: 'UNJUDGED' },
    { ja: '撃ち抜かれた', en: 'PIERCED' }, { ja: '焼かれた', en: 'BURNED' }, { ja: '焼け残った', en: 'FIRE SPARED' },
    { ja: '焼け落ちた', en: 'BURNED DOWN' }, { ja: '沈められた', en: 'SUNKEN' }, { ja: '葬られた', en: 'BURIED AWAY' },
    { ja: '埋められた', en: 'INTERRED' }, { ja: '掘り返された', en: 'DUG UP' }, { ja: '暴かれた', en: 'EXPOSED' },
    { ja: '隠された', en: 'HIDDEN' }, { ja: '秘められた', en: 'CONCEALED' }, { ja: '封じられた', en: 'SEALED' },
    { ja: '閉ざされた', en: 'SHUT' }, { ja: '見放された', en: 'ABANDONED' }, { ja: '置き去りの', en: 'LEFT BEHIND' },
    { ja: '取り残された', en: 'STRANDED' }, { ja: '追われた', en: 'HUNTED' }, { ja: '追い詰められた', en: 'CORNERED' },
    { ja: '囲まれた', en: 'ENCIRCLED' }, { ja: '縛られた', en: 'BOUND' }, { ja: '繋がれた', en: 'CHAINED' },
    { ja: '囚われた', en: 'IMPRISONED' }, { ja: '捕らわれた', en: 'CAPTIVE' }, { ja: '奪われた', en: 'STOLEN AWAY' },
    { ja: '盗まれた', en: 'PILFERED' }, { ja: '消された', en: 'ERASED' }, { ja: '抹消された', en: 'EXPUNGED' },
    { ja: '改竄された', en: 'FALSIFIED' }, { ja: '偽られた', en: 'FEIGNED' }, { ja: '仕組まれた', en: 'RIGGED' },
    { ja: '仕掛けられた', en: 'PLANTED' }, { ja: '謀られた', en: 'PLOTTED AGAINST' }, { ja: '裏切られた', en: 'BETRAYED' },
    { ja: '売られた', en: 'SOLD OUT' }, { ja: '買われた', en: 'BOUGHT' }, { ja: '雇われた', en: 'HIRED' },
    { ja: '命じられた', en: 'ORDERED' }, { ja: '課せられた', en: 'IMPOSED' }, { ja: '許されざる', en: 'UNPARDONABLE' },
    { ja: '赦されない', en: 'UNABSOLVED' }, { ja: '償えない', en: 'UNATONABLE' }, { ja: '終わらない', en: 'NEVER ENDING' },
    { ja: '帰らない', en: 'NOT RETURNING' }, { ja: '戻らない', en: 'IRRETRIEVABLE' }, { ja: '消えない', en: 'INDELIBLE' },
    { ja: '癒えない', en: 'UNHEALED' }, { ja: '晴れない', en: 'UNCLEARED' }, { ja: '明けない', en: 'DAWNLESS' },
    { ja: '寝ずの', en: 'WITHOUT SLEEP' }, { ja: '誰も知らない', en: 'KNOWN TO NONE' }, { ja: '名を伏せた', en: 'NAME WITHHELD' },
    { ja: '答えのない', en: 'ANSWERLESS' }, { ja: '出口のない', en: 'EXITLESS' }, { ja: '逃げ場のない', en: 'WITH NO REFUGE' },
    { ja: '抗えない', en: 'IRRESISTIBLE' }, { ja: '避けられない', en: 'UNAVOIDABLE' }, { ja: '免れない', en: 'INEVITABLE' },
    { ja: '拭えない', en: 'INERADICABLE' }, { ja: '消せない', en: 'UNQUENCHABLE' }, { ja: '隠せない', en: 'UNCONCEALABLE' },
    { ja: '報われない', en: 'UNREQUITED' }, { ja: '裁けない', en: 'UNJUDGEABLE' }, { ja: '許せない', en: 'UNFORGIVABLE' },
    { ja: '忘れられない', en: 'UNFORGETTABLE' }, { ja: '数え切れない', en: 'COUNTLESS' }, { ja: '果たされない', en: 'UNFULFILLED' },
    { ja: '満たされない', en: 'UNSATED' }, { ja: '届かない', en: 'OUT OF REACH' }, { ja: '間に合わない', en: 'TOO LATE' },
    { ja: '取り返しのつかない', en: 'IRREPARABLE' }, { ja: '唯一の', en: 'SOLE' }, { ja: '無言の', en: 'WORDLESS' },
    { ja: '沈黙の', en: 'OF SILENCE' }, { ja: '静寂の', en: 'OF STILLNESS' }, { ja: '暗黒の', en: 'PITCH DARK' },
    { ja: '絶望の', en: 'OF DESPAIR' }, { ja: '決死の', en: 'DESPERATE' }, { ja: '訣別の', en: 'OF PARTING' },
    { ja: '不退転の', en: 'UNFLINCHING' }, { ja: '背水の', en: 'WITH NO RETREAT' }, { ja: '孤高の', en: 'ALOOF' },
    { ja: '孤独の', en: 'SOLITARY' }, { ja: '不朽の', en: 'IMPERISHABLE' }, { ja: '不滅の', en: 'IMMORTAL' },
    { ja: '不敗の', en: 'UNDEFEATED' }, { ja: '無敵の', en: 'INVINCIBLE' }, { ja: '無数の', en: 'MYRIAD' },
    { ja: '無名の', en: 'UNKNOWN' }, { ja: '匿名の', en: 'ANONYMOUS' }, { ja: '秘密の', en: 'SECRET' },
    { ja: '極秘の', en: 'TOP SECRET' }, { ja: '機密の', en: 'CLASSIFIED' }, { ja: '禁断の', en: 'FORBIDDEN' },
    { ja: '禁じられた', en: 'PROSCRIBED' }, { ja: '呪縛の', en: 'OF BINDING SPELL' }, { ja: '因縁の', en: 'FATED' },
    { ja: '宿命の', en: 'DESTINED' }, { ja: '運命の', en: 'OF DESTINY' }, { ja: '天命の', en: 'MANDATED' },
    { ja: '業火の', en: 'OF HELLFIRE' }, { ja: '灼熱の', en: 'SCALDING' }, { ja: '極寒の', en: 'FRIGID' },
    { ja: '極北の', en: 'FAR NORTHERN' }, { ja: '果ての', en: 'UTTERMOST' }, { ja: '辺境の', en: 'BORDERLAND' },
    { ja: '国境の', en: 'FRONTIER SIDE' }, { ja: '越境の', en: 'CROSS BORDER' }, { ja: '亡国の', en: 'OF A FALLEN STATE' },
    { ja: '廃都の', en: 'OF A DEAD CAPITAL' }, { ja: '荒廃した', en: 'DEVASTATED' }, { ja: '荒野の', en: 'OF THE WASTES' },
    { ja: '廃墟の', en: 'OF RUINS' }, { ja: '硝煙の', en: 'OF GUNSMOKE' }, { ja: '血染めの', en: 'BLOODDYED' },
    { ja: '血濡れの', en: 'BLOODWET' }, { ja: '返り血の', en: 'SPLATTERED' }, { ja: '傷だらけの', en: 'COVERED IN WOUNDS' },
    { ja: '泥まみれの', en: 'MUDCAKED' }, { ja: '埃まみれの', en: 'DUSTCAKED' }, { ja: '錆びついた', en: 'RUSTED' },
    { ja: '朽ち果てた', en: 'ROTTED AWAY' }, { ja: '崩れかけた', en: 'CRUMBLING' }, { ja: '傾いた', en: 'LEANING' },
    { ja: '軋む', en: 'CREAKING' }, { ja: '罅割れた', en: 'CRACKED' }, { ja: '凍てついた', en: 'FROZEN OVER' },
    { ja: '張り詰めた', en: 'TAUT' }, { ja: '研ぎ澄まされた', en: 'HONED' }, { ja: '鋭利な', en: 'KEEN' },
    { ja: '冷酷な', en: 'RUTHLESS' }, { ja: '冷徹な', en: 'COLDBLOODED' }, { ja: '非情な', en: 'PITILESS' },
    { ja: '無慈悲な', en: 'MERCILESS' }, { ja: '残酷な', en: 'CRUEL' }, { ja: '過酷な', en: 'HARSH' },
    { ja: '苛烈な', en: 'FIERCE' }, { ja: '熾烈な', en: 'INTENSE' }, { ja: '凄惨な', en: 'GRISLY' },
    { ja: '陰惨な', en: 'GRIM' }, { ja: '壮絶な', en: 'HARROWING' }, { ja: '悲惨な', en: 'TRAGIC' },
    { ja: '無残な', en: 'PITIFUL' }, { ja: '無情な', en: 'HEARTLESS' }, { ja: '無力な', en: 'POWERLESS' },
    { ja: '無謀な', en: 'RECKLESS' }, { ja: '卑劣な', en: 'DASTARDLY' }, { ja: '狡猾な', en: 'CUNNING' },
    { ja: '老獪な', en: 'WILY' }, { ja: '頑迷な', en: 'OBDURATE' }, { ja: '強情な', en: 'STUBBORN' },
    { ja: '不遜な', en: 'INSOLENT' }, { ja: '高潔な', en: 'NOBLE' }, { ja: '剛直な', en: 'UPRIGHT' },
    { ja: '実直な', en: 'HONEST' }, { ja: '律儀な', en: 'DUTIFUL' }, { ja: '寡黙な', en: 'TACITURN' },
    { ja: '無口な', en: 'RETICENT' }, { ja: '饒舌な', en: 'VOLUBLE' }, { ja: '冷ややかな', en: 'CHILLY' },
    { ja: '執拗な', en: 'PERSISTENT' }, { ja: '執念深い', en: 'VENGEFUL' }, { ja: '用心深い', en: 'WARY' },
    { ja: '疑い深い', en: 'DISTRUSTFUL' }, { ja: '罪深い', en: 'SINFUL' }, { ja: '情け深い', en: 'COMPASSIONATE' },
    { ja: '生き別れの', en: 'LONG SEPARATED' }, { ja: '血の繋がらない', en: 'NOT BY BLOOD' }, { ja: '名も知らぬ', en: 'OF UNKNOWN NAME' },
    { ja: '顔のない', en: 'FACELESS' }, { ja: '声なき', en: 'VOICELESS' }, { ja: '影のない', en: 'SHADOWLESS' },
    { ja: '帰る場所のない', en: 'HOMELESS' }, { ja: '行き場のない', en: 'WITH NOWHERE TO GO' }, { ja: '拠り所のない', en: 'UNANCHORED' },
    { ja: '身寄りのない', en: 'WITHOUT KIN' }, { ja: '頼るもののない', en: 'UNAIDED' }, { ja: '証しのない', en: 'UNPROVEN' },
    { ja: '記録されない', en: 'UNRECORDED' }, { ja: '語り継がれる', en: 'HANDED DOWN' }, { ja: '忘れ去られた', en: 'LONG FORGOTTEN' },
    { ja: '葬り去られた', en: 'BURIED IN SILENCE' }, { ja: '語り尽くせぬ', en: 'BEYOND TELLING' }, { ja: '果てしのない', en: 'WITHOUT END' },
    { ja: '底知れぬ', en: 'FATHOMLESS' }, { ja: '計り知れぬ', en: 'IMMEASURABLE' }, { ja: '目に見えぬ', en: 'INVISIBLE' },
    { ja: '音のない', en: 'SOUNDLESS' }, { ja: '光の届かない', en: 'LIGHTLESS' }, { ja: '剥き出しの', en: 'BARE' },
    { ja: '生々しい', en: 'RAW' }, { ja: '息詰まる', en: 'SUFFOCATING' }, { ja: '張り裂ける', en: 'BURSTING' },
    { ja: '焦げついた', en: 'SCORCHED' }, { ja: '濁った', en: 'TURBID' }, { ja: '澱んだ', en: 'STAGNANT' },
    { ja: '澄んだ', en: 'CLEAR' }, { ja: '荒れ果てた', en: 'DESOLATE' }, { ja: '打ち捨てられた', en: 'CAST ASIDE' },
    { ja: '打ちのめされた', en: 'CRUSHED' }, { ja: '打ち砕かれた', en: 'SHATTERED' }, { ja: '引き裂かれた', en: 'TORN APART' },
    { ja: '切り捨てられた', en: 'CUT LOOSE' }, { ja: '切羽詰まった', en: 'PRESSED TO THE WALL' }, { ja: '追い立てられた', en: 'DRIVEN' },
    { ja: '駆り立てられた', en: 'IMPELLED' }, { ja: '突き動かされた', en: 'PROPELLED' }, { ja: '揺さぶられた', en: 'SHAKEN' },
    { ja: '打ちひしがれた', en: 'PROSTRATE' }, { ja: '打ち沈んだ', en: 'DOWNCAST' }, { ja: '息を潜めた', en: 'HUSHED' },
    { ja: '押し殺した', en: 'STIFLED' }, { ja: '噛み殺した', en: 'BITTEN BACK' }, { ja: '抑えきれない', en: 'UNCONTAINABLE' },
    { ja: '溢れ出す', en: 'OVERFLOWING' }, { ja: '込み上げる', en: 'WELLING UP' }, { ja: '燃え尽きた', en: 'BURNT OUT' },
    { ja: '燃え上がる', en: 'BLAZING UP' }, { ja: '消え入る', en: 'FADING OUT' }, { ja: '立ち尽くす', en: 'STANDING FROZEN' },
    { ja: '立ち向かう', en: 'DEFIANT' }, { ja: '逃げ惑う', en: 'PANICKED' }, { ja: '彷徨う', en: 'ROVING' },
    { ja: '佇む', en: 'STILL STANDING' }, { ja: '息絶えた', en: 'LIFELESS' }, { ja: '生き延びた', en: 'OUTLIVING' },
    { ja: '生まれ変わる', en: 'REBORN' }, { ja: '蘇る', en: 'REVIVING' }, { ja: '目覚める', en: 'WAKING' },
    { ja: '十年目の', en: 'OF THE TENTH YEAR' }, { ja: '三度目の', en: 'THIRD' }, { ja: '最終の', en: 'FINAL' },
    { ja: '未明の', en: 'PREDAWN' }, { ja: '深夜の', en: 'LATE NIGHT' }, { ja: '明日なき', en: 'WITHOUT TOMORROW' },
    { ja: '昨日までの', en: 'UNTIL YESTERDAY' }, { ja: '今日限りの', en: 'FOR TODAY ONLY' }, { ja: '束の間の', en: 'FLEETING' },
    { ja: '報われぬ', en: 'THANKLESS' }, { ja: '名ばかりの', en: 'IN NAME ONLY' }, { ja: '筋書き通りの', en: 'TO THE SCRIPT' },
    { ja: '証拠なき', en: 'WITHOUT EVIDENCE' }, { ja: '前例なき', en: 'UNPRECEDENTED' }, { ja: '公にされない', en: 'UNDISCLOSED' },
    { ja: '闇に葬られた', en: 'BURIED IN THE DARK' }, { ja: '国を捨てた', en: 'STATELESS BY CHOICE' }, { ja: '故郷を失った', en: 'HOMELAND LOST' },
    { ja: '名を捨てた', en: 'HAVING CAST OFF A NAME' }, { ja: '罪を負った', en: 'GUILT LADEN' }, { ja: '銃を置いた', en: 'HAVING LAID DOWN ARMS' }
  ]
};
})(window.PF = window.PF || {});
