(function (PF) {
'use strict';
PF.COMMON_B = {
  famName: [
    { ja: '佐藤', en: 'SATO' }, { ja: '鈴木', en: 'SUZUKI' }, { ja: '高橋', en: 'TAKAHASHI' }, { ja: '田中', en: 'TANAKA' },
    { ja: '伊藤', en: 'ITO' }, { ja: '渡辺', en: 'WATANABE' }, { ja: '山本', en: 'YAMAMOTO' }, { ja: '中村', en: 'NAKAMURA' },
    { ja: '小林', en: 'KOBAYASHI' }, { ja: '加藤', en: 'KATO' }, { ja: '吉田', en: 'YOSHIDA' }, { ja: '山田', en: 'YAMADA' },
    { ja: '佐々木', en: 'SASAKI' }, { ja: '山口', en: 'YAMAGUCHI' }, { ja: '松本', en: 'MATSUMOTO' }, { ja: '井上', en: 'INOUE' },
    { ja: '木村', en: 'KIMURA' }, { ja: '林', en: 'HAYASHI' }, { ja: '斎藤', en: 'SAITO' }, { ja: '清水', en: 'SHIMIZU' },
    { ja: '山崎', en: 'YAMAZAKI' }, { ja: '森', en: 'MORI' }, { ja: '池田', en: 'IKEDA' }, { ja: '橋本', en: 'HASHIMOTO' },
    { ja: '阿部', en: 'ABE' }, { ja: '石川', en: 'ISHIKAWA' }, { ja: '山下', en: 'YAMASHITA' }, { ja: '中島', en: 'NAKAJIMA' },
    { ja: '石井', en: 'ISHII' }, { ja: '小川', en: 'OGAWA' }, { ja: '前田', en: 'MAEDA' }, { ja: '岡田', en: 'OKADA' },
    { ja: '長谷川', en: 'HASEGAWA' }, { ja: '藤田', en: 'FUJITA' }, { ja: '後藤', en: 'GOTO' }, { ja: '近藤', en: 'KONDO' },
    { ja: '村上', en: 'MURAKAMI' }, { ja: '遠藤', en: 'ENDO' }, { ja: '青木', en: 'AOKI' }, { ja: '坂本', en: 'SAKAMOTO' },
    { ja: '福田', en: 'FUKUDA' }, { ja: '太田', en: 'OTA' }, { ja: '西村', en: 'NISHIMURA' }, { ja: '藤井', en: 'FUJII' },
    { ja: '金子', en: 'KANEKO' }, { ja: '岡本', en: 'OKAMOTO' }, { ja: '藤原', en: 'FUJIWARA' }, { ja: '中野', en: 'NAKANO' },
    { ja: '三浦', en: 'MIURA' }, { ja: '原田', en: 'HARADA' }, { ja: '中川', en: 'NAKAGAWA' }, { ja: '松田', en: 'MATSUDA' },
    { ja: '竹内', en: 'TAKEUCHI' }, { ja: '小野', en: 'ONO' }, { ja: '田村', en: 'TAMURA' }, { ja: '中山', en: 'NAKAYAMA' },
    { ja: '和田', en: 'WADA' }, { ja: '石田', en: 'ISHIDA' }, { ja: '森田', en: 'MORITA' }, { ja: '上田', en: 'UEDA' },
    { ja: '原', en: 'HARA' }, { ja: '内田', en: 'UCHIDA' }, { ja: '柴田', en: 'SHIBATA' }, { ja: '酒井', en: 'SAKAI' },
    { ja: '宮崎', en: 'MIYAZAKI' }, { ja: '横山', en: 'YOKOYAMA' }, { ja: '高木', en: 'TAKAGI' }, { ja: '安藤', en: 'ANDO' },
    { ja: '宮本', en: 'MIYAMOTO' }, { ja: '大野', en: 'OHNO' }, { ja: '小島', en: 'KOJIMA' }, { ja: '谷口', en: 'TANIGUCHI' },
    { ja: '工藤', en: 'KUDO' }, { ja: '今井', en: 'IMAI' }, { ja: '高田', en: 'TAKADA' }, { ja: '増田', en: 'MASUDA' },
    { ja: '丸山', en: 'MARUYAMA' }, { ja: '杉山', en: 'SUGIYAMA' }, { ja: '村田', en: 'MURATA' }, { ja: '大塚', en: 'OTSUKA' },
    { ja: '平野', en: 'HIRANO' }, { ja: '菅原', en: 'SUGAWARA' }, { ja: '千葉', en: 'CHIBA' }, { ja: '久保', en: 'KUBO' },
    { ja: '松井', en: 'MATSUI' }, { ja: '小山', en: 'KOYAMA' }, { ja: '岩崎', en: 'IWASAKI' }, { ja: '桜井', en: 'SAKURAI' },
    { ja: '野口', en: 'NOGUCHI' }, { ja: '松尾', en: 'MATSUO' }, { ja: '野村', en: 'NOMURA' }, { ja: '菊地', en: 'KIKUCHI' },
    { ja: '佐野', en: 'SANO' }, { ja: '大西', en: 'ONISHI' }, { ja: '杉本', en: 'SUGIMOTO' }, { ja: '新井', en: 'ARAI' },
    { ja: '浜田', en: 'HAMADA' }, { ja: '市川', en: 'ICHIKAWA' }, { ja: '水野', en: 'MIZUNO' }, { ja: '小松', en: 'KOMATSU' },
    { ja: '島田', en: 'SHIMADA' }, { ja: '古川', en: 'FURUKAWA' }, { ja: '武田', en: 'TAKEDA' }, { ja: '上野', en: 'UENO' },
    { ja: '杉浦', en: 'SUGIURA' }, { ja: '本田', en: 'HONDA' }, { ja: '白石', en: 'SHIRAISHI' }, { ja: '荒木', en: 'ARAKI' },
    { ja: '秋山', en: 'AKIYAMA' }, { ja: '大橋', en: 'OHASHI' }, { ja: '平田', en: 'HIRATA' }, { ja: '吉川', en: 'YOSHIKAWA' },
    { ja: '岩本', en: 'IWAMOTO' }, { ja: '早川', en: 'HAYAKAWA' }, { ja: '松浦', en: 'MATSUURA' }, { ja: '大久保', en: 'OKUBO' },
    { ja: '松岡', en: 'MATSUOKA' }, { ja: '星野', en: 'HOSHINO' }, { ja: '黒田', en: 'KURODA' }, { ja: '川口', en: 'KAWAGUCHI' },
    { ja: '関口', en: 'SEKIGUCHI' }, { ja: '中田', en: 'NAKATA' }, { ja: '北村', en: 'KITAMURA' }, { ja: '安田', en: 'YASUDA' },
    { ja: '三宅', en: 'MIYAKE' }, { ja: '福島', en: 'FUKUSHIMA' }, { ja: '本間', en: 'HONMA' }, { ja: '川崎', en: 'KAWASAKI' },
    { ja: '岡崎', en: 'OKAZAKI' }, { ja: '沢田', en: 'SAWADA' }, { ja: '篠原', en: 'SHINOHARA' }, { ja: '高山', en: 'TAKAYAMA' },
    { ja: '内藤', en: 'NAITO' }, { ja: '小田', en: 'ODA' }, { ja: '川上', en: 'KAWAKAMI' }, { ja: '永井', en: 'NAGAI' },
    { ja: '松下', en: 'MATSUSHITA' }, { ja: '西田', en: 'NISHIDA' }, { ja: '矢野', en: 'YANO' }, { ja: '大島', en: 'OSHIMA' },
    { ja: '岩田', en: 'IWATA' }, { ja: '中西', en: 'NAKANISHI' }, { ja: '服部', en: 'HATTORI' }, { ja: '樋口', en: 'HIGUCHI' },
    { ja: '福井', en: 'FUKUI' }, { ja: '川村', en: 'KAWAMURA' }, { ja: '吉村', en: 'YOSHIMURA' }, { ja: '尾崎', en: 'OZAKI' },
    { ja: '三木', en: 'MIKI' }, { ja: '浅野', en: 'ASANO' }, { ja: '松村', en: 'MATSUMURA' }, { ja: '渡部', en: 'WATABE' },
    { ja: '山内', en: 'YAMAUCHI' }, { ja: '大石', en: 'OISHI' }, { ja: '高野', en: 'TAKANO' }, { ja: '生田', en: 'IKUTA' },
    { ja: '平井', en: 'HIRAI' }, { ja: '児玉', en: 'KODAMA' }, { ja: '富田', en: 'TOMITA' }, { ja: '大森', en: 'OMORI' },
    { ja: '加賀', en: 'KAGA' }, { ja: '鎌田', en: 'KAMATA' }, { ja: '白井', en: 'SHIRAI' }, { ja: '藤本', en: 'FUJIMOTO' },
    { ja: '三上', en: 'MIKAMI' }, { ja: '森本', en: 'MORIMOTO' }, { ja: '江口', en: 'EGUCHI' }, { ja: '堀', en: 'HORI' },
    { ja: '堀田', en: 'HOTTA' }, { ja: '西川', en: 'NISHIKAWA' }, { ja: '神田', en: 'KANDA' }, { ja: '若林', en: 'WAKABAYASHI' },
    { ja: '大谷', en: 'OTANI' }, { ja: '河野', en: 'KONO' }, { ja: '小池', en: 'KOIKE' }, { ja: '深沢', en: 'FUKAZAWA' },
    { ja: '石原', en: 'ISHIHARA' }, { ja: '山中', en: 'YAMANAKA' }, { ja: '田口', en: 'TAGUCHI' }, { ja: '越智', en: 'OCHI' },
    { ja: '森川', en: 'MORIKAWA' }, { ja: '塚本', en: 'TSUKAMOTO' }, { ja: '榎本', en: 'ENOMOTO' }, { ja: '川島', en: 'KAWASHIMA' },
    { ja: '内海', en: 'UTSUMI' }, { ja: '相原', en: 'AIHARA' }, { ja: '大川', en: 'OKAWA' }, { ja: '井口', en: 'IGUCHI' },
    { ja: '小森', en: 'KOMORI' }, { ja: '神谷', en: 'KAMIYA' }, { ja: '甲斐', en: 'KAI' }, { ja: '綾部', en: 'AYABE' },
    { ja: '志村', en: 'SHIMURA' }, { ja: '芦田', en: 'ASHIDA' }, { ja: '有田', en: 'ARITA' }, { ja: '生駒', en: 'IKOMA' },
    { ja: '磯部', en: 'ISOBE' }, { ja: '稲葉', en: 'INABA' }, { ja: '犬飼', en: 'INUKAI' }, { ja: '岩瀬', en: 'IWASE' },
    { ja: '上原', en: 'UEHARA' }, { ja: '宇野', en: 'UNO' }, { ja: '江藤', en: 'ETO' }, { ja: '大内', en: 'OUCHI' },
    { ja: '大迫', en: 'OSAKO' }, { ja: '岡部', en: 'OKABE' }, { ja: '奥村', en: 'OKUMURA' }, { ja: '尾上', en: 'ONOE' },
    { ja: '恩田', en: 'ONDA' }, { ja: '貝原', en: 'KAIHARA' }, { ja: '春日', en: 'KASUGA' }, { ja: '片桐', en: 'KATAGIRI' },
    { ja: '金城', en: 'KANESHIRO' }, { ja: '上川', en: 'KAMIKAWA' }, { ja: '亀井', en: 'KAMEI' }, { ja: '唐沢', en: 'KARASAWA' },
    { ja: '河原', en: 'KAWAHARA' }, { ja: '神崎', en: 'KANZAKI' }, { ja: '菊川', en: 'KIKUKAWA' }, { ja: '岸本', en: 'KISHIMOTO' },
    { ja: '北原', en: 'KITAHARA' }, { ja: '木津', en: 'KIZU' }, { ja: '京極', en: 'KYOGOKU' }, { ja: '桐山', en: 'KIRIYAMA' },
    { ja: '沓掛', en: 'KUTSUKAKE' }, { ja: '熊谷', en: 'KUMAGAI' }, { ja: '倉持', en: 'KURAMOCHI' }, { ja: '栗原', en: 'KURIHARA' },
    { ja: '黒木', en: 'KUROKI' }, { ja: '桑原', en: 'KUWABARA' }, { ja: '小泉', en: 'KOIZUMI' }, { ja: '上月', en: 'KOZUKI' },
    { ja: '香月', en: 'KATSUKI' }, { ja: '郷田', en: 'GODA' }, { ja: '五味', en: 'GOMI' }, { ja: '近江', en: 'OMI' },
    { ja: '西郷', en: 'SAIGO' }, { ja: '斎木', en: 'SAIKI' }, { ja: '榊原', en: 'SAKAKIBARA' }, { ja: '坂口', en: 'SAKAGUCHI' },
    { ja: '相良', en: 'SAGARA' }, { ja: '佐久間', en: 'SAKUMA' }, { ja: '笹川', en: 'SASAGAWA' }, { ja: '佐伯', en: 'SAEKI' },
    { ja: '猿渡', en: 'SARUWATARI' }, { ja: '塩谷', en: 'SHIOYA' }, { ja: '志賀', en: 'SHIGA' }, { ja: '重松', en: 'SHIGEMATSU' },
    { ja: '篠塚', en: 'SHINOZUKA' }, { ja: '渋沢', en: 'SHIBUSAWA' }, { ja: '島崎', en: 'SHIMAZAKI' }, { ja: '清野', en: 'SEINO' },
    { ja: '白川', en: 'SHIRAKAWA' }, { ja: '新谷', en: 'SHINTANI' }, { ja: '陶山', en: 'SUYAMA' }, { ja: '須賀', en: 'SUGA' },
    { ja: '杉田', en: 'SUGITA' }, { ja: '鈴村', en: 'SUZUMURA' }, { ja: '角田', en: 'TSUNODA' }, { ja: '瀬川', en: 'SEGAWA' },
    { ja: '関根', en: 'SEKINE' }, { ja: '妹尾', en: 'SENOO' }, { ja: '曽我', en: 'SOGA' }, { ja: '平良', en: 'TAIRA' },
    { ja: '高瀬', en: 'TAKASE' }, { ja: '高林', en: 'TAKABAYASHI' }, { ja: '滝川', en: 'TAKIGAWA' }, { ja: '田代', en: 'TASHIRO' },
    { ja: '谷本', en: 'TANIMOTO' }, { ja: '玉井', en: 'TAMAI' }, { ja: '千原', en: 'CHIHARA' }, { ja: '塚田', en: 'TSUKADA' },
    { ja: '辻', en: 'TSUJI' }, { ja: '土屋', en: 'TSUCHIYA' }, { ja: '津田', en: 'TSUDA' }, { ja: '鶴岡', en: 'TSURUOKA' },
    { ja: '出口', en: 'DEGUCHI' }, { ja: '寺田', en: 'TERADA' }, { ja: '土肥', en: 'DOI' }, { ja: '堂本', en: 'DOMOTO' },
    { ja: '徳永', en: 'TOKUNAGA' }, { ja: '戸田', en: 'TODA' }, { ja: '富岡', en: 'TOMIOKA' }, { ja: '鳥居', en: 'TORII' },
    { ja: '直井', en: 'NAOI' }, { ja: '長尾', en: 'NAGAO' }, { ja: '中原', en: 'NAKAHARA' }, { ja: '永田', en: 'NAGATA' },
    { ja: '中井', en: 'NAKAI' }, { ja: '那須', en: 'NASU' }, { ja: '生野', en: 'IKUNO' }, { ja: '楢崎', en: 'NARASAKI' },
    { ja: '成田', en: 'NARITA' }, { ja: '西尾', en: 'NISHIO' }, { ja: '二宮', en: 'NINOMIYA' }, { ja: '沼田', en: 'NUMATA' },
    { ja: '根岸', en: 'NEGISHI' }, { ja: '野上', en: 'NOGAMI' }, { ja: '野崎', en: 'NOZAKI' }, { ja: '萩原', en: 'HAGIWARA' },
    { ja: '橋詰', en: 'HASHIZUME' }, { ja: '蓮見', en: 'HASUMI' }, { ja: '花田', en: 'HANADA' }, { ja: '羽田', en: 'HANEDA' },
    { ja: '浜口', en: 'HAMAGUCHI' }, { ja: '早瀬', en: 'HAYASE' }, { ja: '原口', en: 'HARAGUCHI' }, { ja: '番場', en: 'BANBA' },
    { ja: '東', en: 'AZUMA' }, { ja: '樋渡', en: 'HIWATASHI' }, { ja: '日野', en: 'HINO' }, { ja: '平山', en: 'HIRAYAMA' },
    { ja: '広瀬', en: 'HIROSE' }, { ja: '深谷', en: 'FUKAYA' }, { ja: '福原', en: 'FUKUHARA' }, { ja: '藤川', en: 'FUJIKAWA' },
    { ja: '二見', en: 'FUTAMI' }, { ja: '船越', en: 'FUNAKOSHI' }, { ja: '古賀', en: 'KOGA' }, { ja: '別府', en: 'BEPPU' },
    { ja: '星', en: 'HOSHI' }, { ja: '細川', en: 'HOSOKAWA' }, { ja: '堀内', en: 'HORIUCHI' }, { ja: '本郷', en: 'HONGO' },
    { ja: '前川', en: 'MAEKAWA' }, { ja: '牧野', en: 'MAKINO' }, { ja: '増井', en: 'MASUI' }, { ja: '松原', en: 'MATSUBARA' },
    { ja: '真野', en: 'MANO' }, { ja: '三隅', en: 'MISUMI' }, { ja: '水口', en: 'MIZUGUCHI' }, { ja: '溝口', en: 'MIZOGUCHI' },
    { ja: '三谷', en: 'MITANI' }, { ja: '皆川', en: 'MINAGAWA' }, { ja: '峰岸', en: 'MINEGISHI' }, { ja: '宮沢', en: 'MIYAZAWA' },
    { ja: '宮下', en: 'MIYASHITA' }, { ja: '三輪', en: 'MIWA' }, { ja: '武藤', en: 'MUTO' }, { ja: '村瀬', en: 'MURASE' },
    { ja: '室井', en: 'MUROI' }, { ja: '目黒', en: 'MEGURO' }, { ja: '元木', en: 'MOTOKI' }, { ja: '桃井', en: 'MOMOI' },
    { ja: '森下', en: 'MORISHITA' }, { ja: '諸星', en: 'MOROBOSHI' }, { ja: '矢崎', en: 'YAZAKI' }, { ja: '安井', en: 'YASUI' },
    { ja: '柳沢', en: 'YANAGISAWA' }, { ja: '矢部', en: 'YABE' }, { ja: '山際', en: 'YAMAGIWA' }, { ja: '山路', en: 'YAMAJI' },
    { ja: '湯浅', en: 'YUASA' }, { ja: '結城', en: 'YUKI' }, { ja: '横川', en: 'YOKOKAWA' }, { ja: '吉岡', en: 'YOSHIOKA' },
    { ja: '吉沢', en: 'YOSHIZAWA' }, { ja: '米山', en: 'YONEYAMA' }, { ja: '若松', en: 'WAKAMATSU' }, { ja: '鷲尾', en: 'WASHIO' },
    { ja: '綿貫', en: 'WATANUKI' }, { ja: '秋葉', en: 'AKIBA' }, { ja: '朝倉', en: 'ASAKURA' }, { ja: '芦沢', en: 'ASHIZAWA' },
    { ja: '安達', en: 'ADACHI' }, { ja: '阿南', en: 'ANAN' }, { ja: '飯島', en: 'IIJIMA' }, { ja: '井坂', en: 'ISAKA' },
    { ja: '石橋', en: 'ISHIBASHI' }, { ja: '泉', en: 'IZUMI' }, { ja: '磯崎', en: 'ISOZAKI' }, { ja: '一色', en: 'ISSHIKI' },
    { ja: '伊丹', en: 'ITAMI' }, { ja: '稲村', en: 'INAMURA' }, { ja: '井原', en: 'IHARA' }, { ja: '今泉', en: 'IMAIZUMI' },
    { ja: '入江', en: 'IRIE' }, { ja: '岩井', en: 'IWAI' }, { ja: '上杉', en: 'UESUGI' }, { ja: '牛島', en: 'USHIJIMA' },
    { ja: '内山', en: 'UCHIYAMA' }, { ja: '梅原', en: 'UMEHARA' }, { ja: '浦野', en: 'URANO' }, { ja: '江川', en: 'EGAWA' },
    { ja: '遠山', en: 'TOYAMA' }, { ja: '大槻', en: 'OTSUKI' }, { ja: '大原', en: 'OHARA' }, { ja: '岡野', en: 'OKANO' },
    { ja: '荻野', en: 'OGINO' }, { ja: '奥田', en: 'OKUDA' }, { ja: '小関', en: 'OZEKI' }, { ja: '尾形', en: 'OGATA' },
    { ja: '鏡', en: 'KAGAMI' }, { ja: '笠原', en: 'KASAHARA' }, { ja: '梶原', en: 'KAJIWARA' }, { ja: '勝又', en: 'KATSUMATA' },
    { ja: '桂', en: 'KATSURA' }, { ja: '加納', en: 'KANO' }, { ja: '鎌倉', en: 'KAMAKURA' }, { ja: '上村', en: 'KAMIMURA' },
    { ja: '亀山', en: 'KAMEYAMA' }, { ja: '神原', en: 'KANBARA' }, { ja: '岸田', en: 'KISHIDA' }, { ja: '北川', en: 'KITAGAWA' },
    { ja: '木戸', en: 'KIDO' }, { ja: '君島', en: 'KIMIJIMA' }, { ja: '桐原', en: 'KIRIHARA' }, { ja: '日下', en: 'KUSAKA' },
    { ja: '久世', en: 'KUZE' }, { ja: '久米', en: 'KUME' }, { ja: '倉田', en: 'KURATA' }, { ja: '栗山', en: 'KURIYAMA' },
    { ja: '黒沢', en: 'KUROSAWA' }, { ja: '桑田', en: 'KUWATA' }, { ja: '小暮', en: 'KOGURE' }, { ja: '小杉', en: 'KOSUGI' },
    { ja: '小平', en: 'KODAIRA' }, { ja: '小峰', en: 'KOMINE' }, { ja: '近衛', en: 'KONOE' }, { ja: '佐分利', en: 'SABURI' },
    { ja: '沢村', en: 'SAWAMURA' }, { ja: '塩見', en: 'SHIOMI' }, { ja: '品川', en: 'SHINAGAWA' }, { ja: '篠田', en: 'SHINODA' },
    { ja: '柴崎', en: 'SHIBASAKI' }, { ja: '島本', en: 'SHIMAMOTO' }, { ja: '下村', en: 'SHIMOMURA' }, { ja: '庄司', en: 'SHOJI' },
    { ja: '新藤', en: 'SHINDO' }, { ja: '末永', en: 'SUENAGA' }, { ja: '菅野', en: 'KANNO' }, { ja: '杉江', en: 'SUGIE' },
    { ja: '須藤', en: 'SUDO' }, { ja: '瀬尾', en: 'SEO' }, { ja: '芹沢', en: 'SERIZAWA' }, { ja: '千田', en: 'SENDA' },
    { ja: '添田', en: 'SOEDA' }, { ja: '園田', en: 'SONODA' }, { ja: '高倉', en: 'TAKAKURA' }, { ja: '高松', en: 'TAKAMATSU' },
    { ja: '滝沢', en: 'TAKIZAWA' }, { ja: '竹村', en: 'TAKEMURA' }, { ja: '田島', en: 'TAJIMA' }, { ja: '立石', en: 'TATEISHI' },
    { ja: '谷川', en: 'TANIKAWA' }, { ja: '田原', en: 'TAHARA' }, { ja: '津久井', en: 'TSUKUI' }, { ja: '辻村', en: 'TSUJIMURA' },
    { ja: '堤', en: 'TSUTSUMI' }, { ja: '鶴田', en: 'TSURUTA' }, { ja: '寺内', en: 'TERAUCHI' }, { ja: '天野', en: 'AMANO' },
    { ja: '常盤', en: 'TOKIWA' }, { ja: '徳丸', en: 'TOKUMARU' }, { ja: '戸倉', en: 'TOKURA' }, { ja: '富永', en: 'TOMINAGA' },
    { ja: '鳥羽', en: 'TOBA' }, { ja: '中尾', en: 'NAKAO' }, { ja: '長崎', en: 'NAGASAKI' }, { ja: '中條', en: 'NAKAJO' },
    { ja: '永山', en: 'NAGAYAMA' }, { ja: '南部', en: 'NANBU' }, { ja: '新村', en: 'NIIMURA' }, { ja: '西岡', en: 'NISHIOKA' },
    { ja: '丹羽', en: 'NIWA' }, { ja: '沼倉', en: 'NUMAKURA' }, { ja: '根本', en: 'NEMOTO' }, { ja: '野田', en: 'NODA' },
    { ja: '萩野', en: 'HAGINO' }, { ja: '橋田', en: 'HASHIDA' }, { ja: '長谷部', en: 'HASEBE' }, { ja: '畑中', en: 'HATANAKA' },
    { ja: '花輪', en: 'HANAWA' }, { ja: '濱野', en: 'HAMANO' }, { ja: '林田', en: 'HAYASHIDA' }, { ja: '春田', en: 'HARUTA' },
    { ja: '坂東', en: 'BANDO' }, { ja: '東野', en: 'HIGASHINO' }, { ja: '檜山', en: 'HIYAMA' }, { ja: '平塚', en: 'HIRATSUKA' },
    { ja: '広川', en: 'HIROKAWA' }, { ja: '深井', en: 'FUKAI' }, { ja: '福永', en: 'FUKUNAGA' }, { ja: '藤沢', en: 'FUJISAWA' },
    { ja: '淵上', en: 'FUCHIGAMI' }, { ja: '古田', en: 'FURUTA' }, { ja: '保科', en: 'HOSHINA' }, { ja: '細野', en: 'HOSONO' },
    { ja: '堀江', en: 'HORIE' }, { ja: '本城', en: 'HONJO' }, { ja: '前原', en: 'MAEHARA' }, { ja: '牧田', en: 'MAKITA' },
    { ja: '松倉', en: 'MATSUKURA' }, { ja: '松永', en: 'MATSUNAGA' }, { ja: '真鍋', en: 'MANABE' }, { ja: '三沢', en: 'MISAWA' },
    { ja: '水島', en: 'MIZUSHIMA' }, { ja: '溝上', en: 'MIZOKAMI' }, { ja: '三田', en: 'MITA' }, { ja: '南', en: 'MINAMI' },
    { ja: '宮川', en: 'MIYAGAWA' }, { ja: '宮地', en: 'MIYACHI' }, { ja: '三好', en: 'MIYOSHI' }, { ja: '向井', en: 'MUKAI' },
    { ja: '村井', en: 'MURAI' }, { ja: '室伏', en: 'MUROFUSHI' }, { ja: '茂木', en: 'MOGI' }, { ja: '本山', en: 'MOTOYAMA' },
    { ja: '森岡', en: 'MORIOKA' }, { ja: '諸岡', en: 'MOROOKA' }, { ja: '矢島', en: 'YAJIMA' }, { ja: '安永', en: 'YASUNAGA' },
    { ja: '柳田', en: 'YANAGIDA' }, { ja: '山岸', en: 'YAMAGISHI' }, { ja: '山越', en: 'YAMAKOSHI' }, { ja: '山根', en: 'YAMANE' },
    { ja: '湯川', en: 'YUKAWA' }, { ja: '横井', en: 'YOKOI' }, { ja: '吉野', en: 'YOSHINO' }, { ja: '米倉', en: 'YONEKURA' },
    { ja: '若尾', en: 'WAKAO' }, { ja: '鷲田', en: 'WASHIDA' }, { ja: '相田', en: 'AIDA' }, { ja: '赤松', en: 'AKAMATSU' },
    { ja: '浅井', en: 'ASAI' }, { ja: '麻生', en: 'ASO' }, { ja: '阿久津', en: 'AKUTSU' }, { ja: '荒巻', en: 'ARAMAKI' },
    { ja: '飯田', en: 'IIDA' }, { ja: '池上', en: 'IKEGAMI' }, { ja: '石垣', en: 'ISHIGAKI' }, { ja: '磯野', en: 'ISONO' },
    { ja: '板垣', en: 'ITAGAKI' }, { ja: '市原', en: 'ICHIHARA' }, { ja: '一柳', en: 'ICHIYANAGI' }, { ja: '井手', en: 'IDE' },
    { ja: '稲田', en: 'INADA' }, { ja: '猪俣', en: 'INOMATA' }, { ja: '今村', en: 'IMAMURA' }, { ja: '岩渕', en: 'IWABUCHI' },
    { ja: '上坂', en: 'UESAKA' }, { ja: '宇佐美', en: 'USAMI' }, { ja: '臼井', en: 'USUI' }, { ja: '内村', en: 'UCHIMURA' },
    { ja: '梅田', en: 'UMEDA' }, { ja: '江原', en: 'EHARA' }, { ja: '大江', en: 'OE' }, { ja: '大城', en: 'OSHIRO' },
    { ja: '大貫', en: 'ONUKI' }, { ja: '岡村', en: 'OKAMURA' }, { ja: '小笠原', en: 'OGASAWARA' }, { ja: '沖田', en: 'OKITA' },
    { ja: '奥山', en: 'OKUYAMA' }, { ja: '落合', en: 'OCHIAI' }, { ja: '香川', en: 'KAGAWA' }, { ja: '柏木', en: 'KASHIWAGI' },
    { ja: '片山', en: 'KATAYAMA' }, { ja: '桂木', en: 'KATSURAGI' }, { ja: '金森', en: 'KANAMORI' }, { ja: '上条', en: 'KAMIJO' },
    { ja: '亀田', en: 'KAMEDA' }, { ja: '唐木', en: 'KARAKI' }, { ja: '河内', en: 'KOCHI' }, { ja: '神部', en: 'KANBE' },
    { ja: '岸', en: 'KISHI' }, { ja: '北野', en: 'KITANO' }, { ja: '木原', en: 'KIHARA' }, { ja: '木山', en: 'KIYAMA' },
    { ja: '桐谷', en: 'KIRITANI' }, { ja: '楠', en: 'KUSUNOKI' }, { ja: '国分', en: 'KOKUBUN' }, { ja: '久保田', en: 'KUBOTA' },
    { ja: '熊倉', en: 'KUMAKURA' }, { ja: '倉本', en: 'KURAMOTO' }, { ja: '栗田', en: 'KURITA' }, { ja: '黒岩', en: 'KUROIWA' },
    { ja: '桑名', en: 'KUWANA' }, { ja: '郡司', en: 'GUNJI' }, { ja: '小出', en: 'KOIDE' }, { ja: '香坂', en: 'KOSAKA' },
    { ja: '小塚', en: 'KOZUKA' }, { ja: '小柳', en: 'KOYANAGI' }, { ja: '紺野', en: 'KONNO' }, { ja: '西条', en: 'SAIJO' },
    { ja: '酒巻', en: 'SAKAMAKI' }, { ja: '桜田', en: 'SAKURADA' }, { ja: '笹本', en: 'SASAMOTO' }, { ja: '佐竹', en: 'SATAKE' },
    { ja: '里見', en: 'SATOMI' }, { ja: '沢井', en: 'SAWAI' }, { ja: '塩崎', en: 'SHIOZAKI' }, { ja: '志田', en: 'SHIDA' },
    { ja: '篠崎', en: 'SHINOZAKI' }, { ja: '柴山', en: 'SHIBAYAMA' }, { ja: '島村', en: 'SHIMAMURA' }, { ja: '下条', en: 'SHIMOJO' },
    { ja: '白木', en: 'SHIRAKI' }, { ja: '末吉', en: 'SUEYOSHI' }, { ja: '菅沼', en: 'SUGANUMA' }, { ja: '杉原', en: 'SUGIHARA' },
    { ja: '諏訪部', en: 'SUWABE' }, { ja: '瀬戸', en: 'SETO' }, { ja: '曽根', en: 'SONE' }, { ja: '田上', en: 'TAGAMI' },
    { ja: '竹本', en: 'TAKEMOTO' }, { ja: '立川', en: 'TACHIKAWA' }, { ja: '谷内', en: 'TANIUCHI' }, { ja: '種田', en: 'TANEDA' },
    { ja: '塚越', en: 'TSUKAGOSHI' }, { ja: '月岡', en: 'TSUKIOKA' }, { ja: '津野', en: 'TSUNO' }, { ja: '鶴見', en: 'TSURUMI' },
    { ja: '寺尾', en: 'TERAO' }, { ja: '徳田', en: 'TOKUDA' }, { ja: '富樫', en: 'TOGASHI' }, { ja: '豊島', en: 'TOYOSHIMA' },
    { ja: '鳥山', en: 'TORIYAMA' }, { ja: '直江', en: 'NAOE' }, { ja: '中垣', en: 'NAKAGAKI' }, { ja: '長沢', en: 'NAGASAWA' },
    { ja: '梨本', en: 'NASHIMOTO' }, { ja: '名取', en: 'NATORI' }, { ja: '成瀬', en: 'NARUSE' }, { ja: '新妻', en: 'NIIZUMA' },
    { ja: '西野', en: 'NISHINO' }, { ja: '二瓶', en: 'NIHEI' }, { ja: '沼尻', en: 'NUMAJIRI' }, { ja: '根津', en: 'NEZU' },
    { ja: '野々村', en: 'NONOMURA' }, { ja: '長谷', en: 'HASE' }, { ja: '秦', en: 'HATA' }, { ja: '花岡', en: 'HANAOKA' },
    { ja: '浜崎', en: 'HAMASAKI' }, { ja: '早坂', en: 'HAYASAKA' }, { ja: '半田', en: 'HANDA' }, { ja: '東山', en: 'HIGASHIYAMA' },
    { ja: '久松', en: 'HISAMATSU' }, { ja: '平岡', en: 'HIRAOKA' }, { ja: '広田', en: 'HIROTA' }, { ja: '福地', en: 'FUKUCHI' },
    { ja: '藤村', en: 'FUJIMURA' }, { ja: '二木', en: 'FUTAKI' }, { ja: '舟木', en: 'FUNAKI' }, { ja: '古谷', en: 'FURUYA' },
    { ja: '細谷', en: 'HOSOYA' }, { ja: '堀口', en: 'HORIGUCHI' }, { ja: '本橋', en: 'MOTOHASHI' }, { ja: '前島', en: 'MAEJIMA' },
    { ja: '牧原', en: 'MAKIHARA' }, { ja: '松丸', en: 'MATSUMARU' }, { ja: '松崎', en: 'MATSUZAKI' }, { ja: '丸田', en: 'MARUTA' },
    { ja: '三島', en: 'MISHIMA' }, { ja: '水谷', en: 'MIZUTANI' }, { ja: '三田村', en: 'MITAMURA' }, { ja: '宮田', en: 'MIYATA' },
    { ja: '村山', en: 'MURAYAMA' }, { ja: '森脇', en: 'MORIWAKI' }, { ja: '森山', en: 'MORIYAMA' }, { ja: '諸田', en: 'MOROTA' },
    { ja: '八木', en: 'YAGI' }, { ja: '矢口', en: 'YAGUCHI' }, { ja: '安西', en: 'ANZAI' }, { ja: '柳原', en: 'YANAGIHARA' },
    { ja: '山岡', en: 'YAMAOKA' }, { ja: '山城', en: 'YAMASHIRO' }, { ja: '山名', en: 'YAMANA' }, { ja: '山室', en: 'YAMAMURO' },
    { ja: '湯本', en: 'YUMOTO' }, { ja: '横田', en: 'YOKOTA' }, { ja: '吉井', en: 'YOSHII' }, { ja: '吉原', en: 'YOSHIWARA' },
    { ja: '米田', en: 'YONEDA' }, { ja: '若山', en: 'WAKAYAMA' }, { ja: '和気', en: 'WAKE' }, { ja: '渡瀬', en: 'WATASE' },
    { ja: '天城', en: 'AMAGI' }, { ja: '綾小路', en: 'AYANOKOJI' }, { ja: '有村', en: 'ARIMURA' }, { ja: '五代', en: 'GODAI' },
    { ja: '一条', en: 'ICHIJO' }, { ja: '宇治', en: 'UJI' }, { ja: '大鳥', en: 'OTORI' }, { ja: '小田切', en: 'OTAGIRI' },
    { ja: '折原', en: 'ORIHARA' }, { ja: '春日野', en: 'KASUGANO' }, { ja: '九条', en: 'KUJO' }, { ja: '黒瀬', en: 'KUROSE' },
    { ja: '御影', en: 'MIKAGE' }, { ja: '武蔵', en: 'MUSASHI' }, { ja: '八神', en: 'YAGAMI' }, { ja: '柚木', en: 'YUNOKI' },
    { ja: '四条', en: 'SHIJO' }, { ja: '西園寺', en: 'SAIONJI' }, { ja: '冷泉', en: 'REIZEI' }, { ja: '鷹司', en: 'TAKATSUKASA' },
    { ja: '東條', en: 'TOJO' }, { ja: '猪瀬', en: 'INOSE' }, { ja: '犬塚', en: 'INUZUKA' }, { ja: '鵜飼', en: 'UKAI' },
    { ja: '織部', en: 'ORIBE' }, { ja: '尾花', en: 'OBANA' }, { ja: '香山', en: 'KAYAMA' }, { ja: '鹿島', en: 'KASHIMA' },
    { ja: '神保', en: 'JINBO' }, { ja: '北条', en: 'HOJO' }, { ja: '剣持', en: 'KENMOCHI' }, { ja: '陣内', en: 'JINNOUCHI' },
    { ja: '千賀', en: 'SENGA' }, { ja: '高階', en: 'TAKASHINA' }, { ja: '千種', en: 'CHIGUSA' }, { ja: '月島', en: 'TSUKISHIMA' },
    { ja: '土門', en: 'DOMON' }, { ja: '十時', en: 'TOTOKI' }, { ja: '名倉', en: 'NAGURA' }, { ja: '錦織', en: 'NISHIKORI' },
    { ja: '貫井', en: 'NUKUI' }, { ja: '野々宮', en: 'NONOMIYA' }, { ja: '羽鳥', en: 'HATORI' }, { ja: '深見', en: 'FUKAMI' },
    { ja: '藤枝', en: 'FUJIEDA' }, { ja: '布施', en: 'FUSE' }, { ja: '逸見', en: 'HENMI' }, { ja: '帆足', en: 'HOASHI' },
    { ja: '真木', en: 'MAKI' }, { ja: '万代', en: 'MANDAI' }, { ja: '宗方', en: 'MUNAKATA' }, { ja: '明神', en: 'MYOJIN' },
    { ja: '最上', en: 'MOGAMI' }, { ja: '山吹', en: 'YAMABUKI' }, { ja: '雪村', en: 'YUKIMURA' }, { ja: '由良', en: 'YURA' },
    { ja: '依田', en: 'YODA' }, { ja: '鷲見', en: 'SUMI' }, { ja: '渡会', en: 'WATARAI' }, { ja: '飯尾', en: 'IIO' },
    { ja: '石動', en: 'ISURUGI' }, { ja: '井筒', en: 'IZUTSU' }, { ja: '岩城', en: 'IWAKI' }, { ja: '海老原', en: 'EBIHARA' },
    { ja: '大蔵', en: 'OKURA' }, { ja: '大隅', en: 'OSUMI' }, { ja: '柿沼', en: 'KAKINUMA' }, { ja: '梶谷', en: 'KAJITANI' },
    { ja: '兼松', en: 'KANEMATSU' }, { ja: '川端', en: 'KAWABATA' }, { ja: '木島', en: 'KIJIMA' }, { ja: '国枝', en: 'KUNIEDA' },
    { ja: '黒崎', en: 'KUROSAKI' }, { ja: '早田', en: 'SODA' }, { ja: '菅井', en: 'SUGAI' }, { ja: '瀬名', en: 'SENA' },
    { ja: '園山', en: 'SONOYAMA' }, { ja: '田丸', en: 'TAMARU' }, { ja: '塚原', en: 'TSUKAHARA' }, { ja: '津島', en: 'TSUSHIMA' },
    { ja: '飛田', en: 'TOBITA' }, { ja: '西丸', en: 'NISHIMARU' }, { ja: '納谷', en: 'NAYA' }, { ja: '樋上', en: 'HIGAMI' },
    { ja: '福光', en: 'FUKUMITSU' }, { ja: '船戸', en: 'FUNATO' }, { ja: '穂坂', en: 'HOSAKA' }, { ja: '真柄', en: 'MAGARA' },
    { ja: '水城', en: 'MIZUKI' }, { ja: '峰崎', en: 'MINEZAKI' }, { ja: '八重樫', en: 'YAEGASHI' }, { ja: '柳生', en: 'YAGYU' },
    { ja: '横堀', en: 'YOKOBORI' }, { ja: '吉良', en: 'KIRA' }, { ja: '若槻', en: 'WAKATSUKI' }, { ja: '安宅', en: 'ATAKA' },
    { ja: '射場', en: 'IBA' }, { ja: '牛尾', en: 'USHIO' }, { ja: '江尻', en: 'EJIRI' }, { ja: '奥野', en: 'OKUNO' },
    { ja: '葛西', en: 'KASAI' }, { ja: '金光', en: 'KANEMITSU' }, { ja: '北山', en: 'KITAYAMA' }, { ja: '串田', en: 'KUSHIDA' },
    { ja: '郡山', en: 'KORIYAMA' }, { ja: '古庄', en: 'FURUSHO' }, { ja: '猿橋', en: 'SARUHASHI' }, { ja: '潮田', en: 'USHIODA' },
    { ja: '蜷川', en: 'NINAGAWA' }, { ja: '根来', en: 'NEGORO' }, { ja: '筒井', en: 'TSUTSUI' }, { ja: '遠矢', en: 'TOYA' },
    { ja: '中溝', en: 'NAKAMIZO' }, { ja: '南木', en: 'NAGI' }, { ja: '韮沢', en: 'NIRASAWA' }, { ja: '沼野', en: 'NUMANO' },
    { ja: '花城', en: 'HANASHIRO' }, { ja: '飯山', en: 'IIYAMA' }
  ],
  giveName: [
    { ja: 'あいか', en: 'AIKA', soft: true }, { ja: 'あいり', en: 'AIRI', soft: true },
    { ja: 'あおば', en: 'AOBA', soft: true }, { ja: 'あかね', en: 'AKANE', soft: true },
    { ja: 'あき', en: 'AKI', soft: true }, { ja: 'あきな', en: 'AKINA', soft: true },
    { ja: 'あきほ', en: 'AKIHO', soft: true }, { ja: 'あこ', en: 'AKO', soft: true },
    { ja: 'あさぎ', en: 'ASAGI', soft: true }, { ja: 'あさな', en: 'ASANA', soft: true },
    { ja: 'あさみ', en: 'ASAMI', soft: true }, { ja: 'あすか', en: 'ASUKA', soft: true },
    { ja: 'あずき', en: 'AZUKI', soft: true }, { ja: 'あずさ', en: 'AZUSA', soft: true },
    { ja: 'あまね', en: 'AMANE', soft: true }, { ja: 'あみ', en: 'AMI', soft: true },
    { ja: 'あや', en: 'AYA', soft: true }, { ja: 'あやか', en: 'AYAKA', soft: true },
    { ja: 'あやの', en: 'AYANO', soft: true }, { ja: 'あゆ', en: 'AYU', soft: true },
    { ja: 'あゆみ', en: 'AYUMI', soft: true }, { ja: 'あんず', en: 'ANZU', soft: true },
    { ja: 'いおり', en: 'IORI', soft: true }, { ja: 'いくみ', en: 'IKUMI', soft: true },
    { ja: 'いずみ', en: 'IZUMI', soft: true }, { ja: 'いなほ', en: 'INAHO', soft: true },
    { ja: 'いのり', en: 'INORI', soft: true }, { ja: 'いよ', en: 'IYO', soft: true },
    { ja: 'うい', en: 'UI', soft: true }, { ja: 'うた', en: 'UTA', soft: true },
    { ja: 'うたの', en: 'UTANO', soft: true }, { ja: 'うみ', en: 'UMI', soft: true },
    { ja: 'えな', en: 'ENA', soft: true }, { ja: 'えみ', en: 'EMI', soft: true },
    { ja: 'えりか', en: 'ERIKA', soft: true }, { ja: 'おと', en: 'OTO', soft: true },
    { ja: 'おとは', en: 'OTOHA', soft: true }, { ja: 'かおる', en: 'KAORU', soft: true },
    { ja: 'かこ', en: 'KAKO', soft: true }, { ja: 'かすみ', en: 'KASUMI', soft: true },
    { ja: 'かずは', en: 'KAZUHA', soft: true }, { ja: 'かな', en: 'KANA', soft: true },
    { ja: 'かなえ', en: 'KANAE', soft: true }, { ja: 'かなた', en: 'KANATA', soft: true },
    { ja: 'かなみ', en: 'KANAMI', soft: true }, { ja: 'かのん', en: 'KANON', soft: true },
    { ja: 'かほ', en: 'KAHO', soft: true }, { ja: 'かや', en: 'KAYA', soft: true },
    { ja: 'かりん', en: 'KARIN', soft: true }, { ja: 'きさら', en: 'KISARA', soft: true },
    { ja: 'きよか', en: 'KIYOKA', soft: true }, { ja: 'きよら', en: 'KIYORA', soft: true },
    { ja: 'きらら', en: 'KIRARA', soft: true }, { ja: 'くみ', en: 'KUMI', soft: true },
    { ja: 'くらら', en: 'KURARA', soft: true }, { ja: 'くるり', en: 'KURURI', soft: true },
    { ja: 'くれは', en: 'KUREHA', soft: true }, { ja: 'けい', en: 'KEI', soft: true },
    { ja: 'ここな', en: 'KOKONA', soft: true }, { ja: 'こずえ', en: 'KOZUE', soft: true },
    { ja: 'こと', en: 'KOTO', soft: true }, { ja: 'ことは', en: 'KOTOHA', soft: true },
    { ja: 'こはる', en: 'KOHARU', soft: true }, { ja: 'こまち', en: 'KOMACHI', soft: true },
    { ja: 'こゆき', en: 'KOYUKI', soft: true }, { ja: 'こよみ', en: 'KOYOMI', soft: true },
    { ja: 'こうめ', en: 'KOUME', soft: true }, { ja: 'さあや', en: 'SAAYA', soft: true },
    { ja: 'さえ', en: 'SAE', soft: true }, { ja: 'さおり', en: 'SAORI', soft: true },
    { ja: 'さき', en: 'SAKI', soft: true }, { ja: 'さくら', en: 'SAKURA', soft: true },
    { ja: 'さくや', en: 'SAKUYA', soft: true }, { ja: 'ささら', en: 'SASARA', soft: true },
    { ja: 'さち', en: 'SACHI', soft: true }, { ja: 'さつき', en: 'SATSUKI', soft: true },
    { ja: 'さなえ', en: 'SANAE', soft: true }, { ja: 'さほ', en: 'SAHO', soft: true },
    { ja: 'さゆり', en: 'SAYURI', soft: true }, { ja: 'さらさ', en: 'SARASA', soft: true },
    { ja: 'さより', en: 'SAYORI', soft: true }, { ja: 'しいな', en: 'SHIINA', soft: true },
    { ja: 'しずか', en: 'SHIZUKA', soft: true }, { ja: 'しずく', en: 'SHIZUKU', soft: true },
    { ja: 'しの', en: 'SHINO', soft: true }, { ja: 'しのぶ', en: 'SHINOBU', soft: true },
    { ja: 'しほ', en: 'SHIHO', soft: true }, { ja: 'しゅり', en: 'SHURI', soft: true },
    { ja: 'すいれん', en: 'SUIREN', soft: true }, { ja: 'すず', en: 'SUZU', soft: true },
    { ja: 'すばる', en: 'SUBARU', soft: true }, { ja: 'すみか', en: 'SUMIKA', soft: true },
    { ja: 'せいか', en: 'SEIKA', soft: true }, { ja: 'せいな', en: 'SEINA', soft: true },
    { ja: 'せいら', en: 'SEIRA', soft: true }, { ja: 'せつな', en: 'SETSUNA', soft: true },
    { ja: 'せな', en: 'SENA', soft: true }, { ja: 'せり', en: 'SERI', soft: true },
    { ja: 'せんり', en: 'SENRI', soft: true }, { ja: 'そのか', en: 'SONOKA', soft: true },
    { ja: 'そよ', en: 'SOYO', soft: true }, { ja: 'そよか', en: 'SOYOKA', soft: true },
    { ja: 'そら', en: 'SORA', soft: true }, { ja: 'たえ', en: 'TAE', soft: true },
    { ja: 'たまき', en: 'TAMAKI', soft: true }, { ja: 'ちえ', en: 'CHIE', soft: true },
    { ja: 'ちか', en: 'CHIKA', soft: true }, { ja: 'ちぐさ', en: 'CHIGUSA', soft: true },
    { ja: 'ちさ', en: 'CHISA', soft: true }, { ja: 'ちさと', en: 'CHISATO', soft: true },
    { ja: 'ちづる', en: 'CHIZURU', soft: true }, { ja: 'ちとせ', en: 'CHITOSE', soft: true },
    { ja: 'ちなつ', en: 'CHINATSU', soft: true }, { ja: 'ちはや', en: 'CHIHAYA', soft: true },
    { ja: 'つかさ', en: 'TSUKASA', soft: true }, { ja: 'つき', en: 'TSUKI', soft: true },
    { ja: 'つくし', en: 'TSUKUSHI', soft: true }, { ja: 'つぐみ', en: 'TSUGUMI', soft: true },
    { ja: 'つづみ', en: 'TSUZUMI', soft: true }, { ja: 'つばき', en: 'TSUBAKI', soft: true },
    { ja: 'つばさ', en: 'TSUBASA', soft: true }, { ja: 'つゆり', en: 'TSUYURI', soft: true },
    { ja: 'てまり', en: 'TEMARI', soft: true }, { ja: 'とうか', en: 'TOKA', soft: true },
    { ja: 'とき', en: 'TOKI', soft: true }, { ja: 'ときは', en: 'TOKIHA', soft: true },
    { ja: 'ときわ', en: 'TOKIWA', soft: true }, { ja: 'ともえ', en: 'TOMOE', soft: true },
    { ja: 'ともか', en: 'TOMOKA', soft: true }, { ja: 'とわ', en: 'TOWA', soft: true },
    { ja: 'なお', en: 'NAO', soft: true }, { ja: 'なおみ', en: 'NAOMI', soft: true },
    { ja: 'なぎ', en: 'NAGI', soft: true }, { ja: 'なごみ', en: 'NAGOMI', soft: true },
    { ja: 'なずな', en: 'NAZUNA', soft: true }, { ja: 'なつき', en: 'NATSUKI', soft: true },
    { ja: 'なつは', en: 'NATSUHA', soft: true }, { ja: 'なつみ', en: 'NATSUMI', soft: true },
    { ja: 'なつめ', en: 'NATSUME', soft: true }, { ja: 'なでしこ', en: 'NADESHIKO', soft: true },
    { ja: 'なな', en: 'NANA', soft: true }, { ja: 'なのは', en: 'NANOHA', soft: true },
    { ja: 'なほ', en: 'NAHO', soft: true }, { ja: 'なみ', en: 'NAMI', soft: true },
    { ja: 'なるみ', en: 'NARUMI', soft: true }, { ja: 'にいな', en: 'NIINA', soft: true },
    { ja: 'にこ', en: 'NIKO', soft: true }, { ja: 'にじ', en: 'NIJI', soft: true },
    { ja: 'ねね', en: 'NENE', soft: true }, { ja: 'ねむ', en: 'NEMU', soft: true },
    { ja: 'のあ', en: 'NOA', soft: true }, { ja: 'のえる', en: 'NOERU', soft: true },
    { ja: 'のぞみ', en: 'NOZOMI', soft: true }, { ja: 'のばら', en: 'NOBARA', soft: true },
    { ja: 'のの', en: 'NONO', soft: true }, { ja: 'ののか', en: 'NONOKA', soft: true },
    { ja: 'えりな', en: 'ERINA', soft: true }, { ja: 'こころ', en: 'KOKORO', soft: true },
    { ja: 'ことり', en: 'KOTORI', soft: true }, { ja: 'さゆ', en: 'SAYU', soft: true },
    { ja: 'さきこ', en: 'SAKIKO', soft: true }, { ja: 'なつこ', en: 'NATSUKO', soft: true },
    { ja: 'はるの', en: 'HARUNO', soft: true }, { ja: 'ひとは', en: 'HITOHA', soft: true },
    { ja: 'まりも', en: 'MARIMO', soft: true }, { ja: 'みなこ', en: 'MINAKO', soft: true },
    { ja: 'ももこ', en: 'MOMOKO', soft: true }, { ja: 'ちはる', en: 'CHIHARU', soft: true },
    { ja: 'はつね', en: 'HATSUNE', soft: true }, { ja: 'はづき', en: 'HAZUKI', soft: true },
    { ja: 'はな', en: 'HANA', soft: true }, { ja: 'はなえ', en: 'HANAE', soft: true },
    { ja: 'はなび', en: 'HANABI', soft: true }, { ja: 'はやて', en: 'HAYATE', soft: true },
    { ja: 'はるな', en: 'HARUNA', soft: true }, { ja: 'はるひ', en: 'HARUHI', soft: true },
    { ja: 'ひいな', en: 'HIINA', soft: true }, { ja: 'ひいろ', en: 'HIIRO', soft: true },
    { ja: 'ひかる', en: 'HIKARU', soft: true }, { ja: 'ひな', en: 'HINA', soft: true },
    { ja: 'ひなこ', en: 'HINAKO', soft: true }, { ja: 'ひなの', en: 'HINANO', soft: true },
    { ja: 'ひばり', en: 'HIBARI', soft: true }, { ja: 'ひふみ', en: 'HIFUMI', soft: true },
    { ja: 'ひまり', en: 'HIMARI', soft: true }, { ja: 'ひめか', en: 'HIMEKA', soft: true },
    { ja: 'ふう', en: 'FU', soft: true }, { ja: 'ふうか', en: 'FUKA', soft: true },
    { ja: 'ふき', en: 'FUKI', soft: true }, { ja: 'ふたば', en: 'FUTABA', soft: true },
    { ja: 'ふみ', en: 'FUMI', soft: true }, { ja: 'ふみか', en: 'FUMIKA', soft: true },
    { ja: 'ふゆ', en: 'FUYU', soft: true }, { ja: 'ふゆか', en: 'FUYUKA', soft: true },
    { ja: 'ほたる', en: 'HOTARU', soft: true }, { ja: 'ほづみ', en: 'HOZUMI', soft: true },
    { ja: 'ほなみ', en: 'HONAMI', soft: true }, { ja: 'ほまれ', en: 'HOMARE', soft: true },
    { ja: 'まい', en: 'MAI', soft: true }, { ja: 'まき', en: 'MAKI', soft: true },
    { ja: 'まさき', en: 'MASAKI', soft: true }, { ja: 'まつり', en: 'MATSURI', soft: true },
    { ja: 'まどか', en: 'MADOKA', soft: true }, { ja: 'まな', en: 'MANA', soft: true },
    { ja: 'まなつ', en: 'MANATSU', soft: true }, { ja: 'まなみ', en: 'MANAMI', soft: true },
    { ja: 'まひろ', en: 'MAHIRO', soft: true }, { ja: 'まほろ', en: 'MAHORO', soft: true },
    { ja: 'まゆ', en: 'MAYU', soft: true }, { ja: 'まゆみ', en: 'MAYUMI', soft: true },
    { ja: 'まゆら', en: 'MAYURA', soft: true }, { ja: 'まりあ', en: 'MARIA', soft: true },
    { ja: 'まりな', en: 'MARINA', soft: true }, { ja: 'みう', en: 'MIU', soft: true },
    { ja: 'みおり', en: 'MIORI', soft: true }, { ja: 'みかげ', en: 'MIKAGE', soft: true },
    { ja: 'みき', en: 'MIKI', soft: true }, { ja: 'みく', en: 'MIKU', soft: true },
    { ja: 'みくり', en: 'MIKURI', soft: true }, { ja: 'みこと', en: 'MIKOTO', soft: true },
    { ja: 'みさ', en: 'MISA', soft: true }, { ja: 'みさき', en: 'MISAKI', soft: true },
    { ja: 'みずき', en: 'MIZUKI', soft: true }, { ja: 'みずな', en: 'MIZUNA', soft: true },
    { ja: 'みずほ', en: 'MIZUHO', soft: true }, { ja: 'みそら', en: 'MISORA', soft: true },
    { ja: 'みちる', en: 'MICHIRU', soft: true }, { ja: 'みつき', en: 'MITSUKI', soft: true },
    { ja: 'みつり', en: 'MITSURI', soft: true }, { ja: 'みなみ', en: 'MINAMI', soft: true },
    { ja: 'みのり', en: 'MINORI', soft: true }, { ja: 'みひろ', en: 'MIHIRO', soft: true },
    { ja: 'みほ', en: 'MIHO', soft: true }, { ja: 'みゆ', en: 'MIYU', soft: true },
    { ja: 'みゆき', en: 'MIYUKI', soft: true }, { ja: 'みらい', en: 'MIRAI', soft: true },
    { ja: 'むぎ', en: 'MUGI', soft: true }, { ja: 'むつき', en: 'MUTSUKI', soft: true },
    { ja: 'むつみ', en: 'MUTSUMI', soft: true }, { ja: 'めい', en: 'MEI', soft: true },
    { ja: 'めぐる', en: 'MEGURU', soft: true }, { ja: 'もえ', en: 'MOE', soft: true },
    { ja: 'もえぎ', en: 'MOEGI', soft: true }, { ja: 'もか', en: 'MOKA', soft: true },
    { ja: 'ももか', en: 'MOMOKA', soft: true }, { ja: 'ももせ', en: 'MOMOSE', soft: true },
    { ja: 'もみじ', en: 'MOMIJI', soft: true }, { ja: 'もも', en: 'MOMO', soft: true },
    { ja: 'やえ', en: 'YAE', soft: true }, { ja: 'やちよ', en: 'YACHIYO', soft: true },
    { ja: 'やよい', en: 'YAYOI', soft: true }, { ja: 'ゆあ', en: 'YUA', soft: true },
    { ja: 'ゆい', en: 'YUI', soft: true }, { ja: 'ゆいか', en: 'YUIKA', soft: true },
    { ja: 'ゆう', en: 'YU', soft: true }, { ja: 'ゆうき', en: 'YUUKI', soft: true },
    { ja: 'ゆうな', en: 'YUUNA', soft: true }, { ja: 'ゆうひ', en: 'YUHI', soft: true },
    { ja: 'ゆえ', en: 'YUE', soft: true }, { ja: 'ゆき', en: 'YUKI', soft: true },
    { ja: 'ゆきな', en: 'YUKINA', soft: true }, { ja: 'ゆきの', en: 'YUKINO', soft: true },
    { ja: 'ゆきは', en: 'YUKIHA', soft: true }, { ja: 'ゆず', en: 'YUZU', soft: true },
    { ja: 'ゆづき', en: 'YUZUKI', soft: true }, { ja: 'ゆな', en: 'YUNA', soft: true },
    { ja: 'ゆの', en: 'YUNO', soft: true }, { ja: 'ゆのは', en: 'YUNOHA', soft: true },
    { ja: 'ゆま', en: 'YUMA', soft: true }, { ja: 'ゆみ', en: 'YUMI', soft: true },
    { ja: 'ゆめ', en: 'YUME', soft: true }, { ja: 'ゆめの', en: 'YUMENO', soft: true },
    { ja: 'ゆら', en: 'YURA', soft: true }, { ja: 'ゆり', en: 'YURI', soft: true },
    { ja: 'ようか', en: 'YOKA', soft: true }, { ja: 'よしの', en: 'YOSHINO', soft: true },
    { ja: 'よつば', en: 'YOTSUBA', soft: true }, { ja: 'よもぎ', en: 'YOMOGI', soft: true },
    { ja: 'らん', en: 'RAN', soft: true }, { ja: 'りいさ', en: 'RIISA', soft: true },
    { ja: 'りお', en: 'RIO', soft: true }, { ja: 'りか', en: 'RIKA', soft: true },
    { ja: 'りこ', en: 'RIKO', soft: true }, { ja: 'りさ', en: 'RISA', soft: true },
    { ja: 'りつか', en: 'RITSUKA', soft: true }, { ja: 'りな', en: 'RINA', soft: true },
    { ja: 'りほ', en: 'RIHO', soft: true }, { ja: 'りりか', en: 'RIRIKA', soft: true },
    { ja: 'るい', en: 'RUI', soft: true }, { ja: 'るか', en: 'RUKA', soft: true },
    { ja: 'るな', en: 'RUNA', soft: true }, { ja: 'るみ', en: 'RUMI', soft: true },
    { ja: 'るり', en: 'RURI', soft: true }, { ja: 'れいか', en: 'REIKA', soft: true },
    { ja: 'れいな', en: 'REINA', soft: true }, { ja: 'れな', en: 'RENA', soft: true },
    { ja: 'れみ', en: 'REMI', soft: true }, { ja: 'れんげ', en: 'RENGE', soft: true },
    { ja: 'わかな', en: 'WAKANA', soft: true }, { ja: 'わかば', en: 'WAKABA', soft: true },
    { ja: 'わこ', en: 'WAKO', soft: true },
    { ja: '悠斗', en: 'YUTO' }, { ja: '陽翔', en: 'HARUTO' }, { ja: '蓮司', en: 'RENJI' },
    { ja: '大和', en: 'YAMATO' }, { ja: '颯太', en: 'SOTA' }, { ja: '陸', en: 'RIKU' },
    { ja: '岳', en: 'GAKU' }, { ja: '剛', en: 'GO' }, { ja: '猛', en: 'TAKESHI' },
    { ja: '進', en: 'SUSUMU' }, { ja: '亮', en: 'RYO' }, { ja: '涼介', en: 'RYOSUKE' },
    { ja: '誠司', en: 'SEIJI' }, { ja: '拓真', en: 'TAKUMA' }, { ja: '直樹', en: 'NAOKI' },
    { ja: '和樹', en: 'KAZUKI' }, { ja: '健吾', en: 'KENGO' }, { ja: '慎司', en: 'SHINJI' },
    { ja: '総一郎', en: 'SOICHIRO' }, { ja: '大河', en: 'TAIGA' }, { ja: '拓也', en: 'TAKUYA' },
    { ja: '達也', en: 'TATSUYA' }, { ja: '智也', en: 'TOMOYA' }, { ja: '直哉', en: 'NAOYA' },
    { ja: '春樹', en: 'HARUKI' }, { ja: '隼', en: 'SHUN' }, { ja: '秀樹', en: 'HIDEKI' },
    { ja: '史郎', en: 'SHIRO' }, { ja: '洋介', en: 'YOSUKE' }, { ja: '雄一', en: 'YUICHI' },
    { ja: '零士', en: 'REIJI' }, { ja: '新', en: 'ARATA' }, { ja: '蒼', en: 'SOU' },
    { ja: '暁', en: 'AKATSUKI' }, { ja: '郁', en: 'IKU' }, { ja: '一馬', en: 'KAZUMA' },
    { ja: '巌', en: 'IWAO' }, { ja: '剣', en: 'TSURUGI' }, { ja: '鷹', en: 'TAKA' },
    { ja: '隆', en: 'TAKASHI' }, { ja: '巽', en: 'TATSUMI' }, { ja: '時雨', en: 'SHIGURE' },
    { ja: '慧', en: 'SATOSHI' }, { ja: '玄', en: 'GEN' }, { ja: '錦', en: 'NISHIKI' },
    { ja: '銀次', en: 'GINJI' }, { ja: '九郎', en: 'KURO' }, { ja: '虎太郎', en: 'KOTARO' },
    { ja: '琥珀', en: 'KOHAKU' }, { ja: '京介', en: 'KYOSUKE' }, { ja: '健一', en: 'KENICHI' },
    { ja: '賢治', en: 'KENJI' }, { ja: '浩二', en: 'KOJI' }, { ja: '孝之', en: 'TAKAYUKI' },
    { ja: '勝彦', en: 'KATSUHIKO' }, { ja: '和彦', en: 'KAZUHIKO' }, { ja: '雅之', en: 'MASAYUKI' },
    { ja: '道夫', en: 'MICHIO' }, { ja: '光成', en: 'MITSUNARI' }, { ja: '基樹', en: 'MOTOKI' },
    { ja: '守', en: 'MAMORU' }, { ja: '昌平', en: 'SHOHEI' }, { ja: '翔太', en: 'SHOTA' },
    { ja: '将', en: 'MASARU' }, { ja: '聡', en: 'SATORU' }, { ja: '惣一', en: 'SOICHI' },
    { ja: '大輔', en: 'DAISUKE' }, { ja: '太一', en: 'TAICHI' }, { ja: '鉄也', en: 'TETSUYA' },
    { ja: '徹', en: 'TORU' }, { ja: '豊', en: 'YUTAKA' }, { ja: '斗真', en: 'TOMA' },
    { ja: '稔', en: 'MINORU' }, { ja: '竜之介', en: 'RYUNOSUKE' }, { ja: '龍馬', en: 'RYOMA' },
    { ja: '明', en: 'AKIRA' }, { ja: '将臣', en: 'MASAOMI' }, { ja: '右京', en: 'UKYO' },
    { ja: '左近', en: 'SAKON' }, { ja: '宗介', en: 'SOSUKE' }, { ja: '太郎', en: 'TARO' },
    { ja: '次郎', en: 'JIRO' }, { ja: '三郎', en: 'SABURO' }, { ja: '五郎', en: 'GORO' },
    { ja: '七海', en: 'NANAMI' }, { ja: '八雲', en: 'YAKUMO' }, { ja: '十蔵', en: 'JUZO' },
    { ja: '万里', en: 'BANRI' }, { ja: '勇作', en: 'YUSAKU' }, { ja: '勘助', en: 'KANSUKE' },
    { ja: '甚八', en: 'JINPACHI' }, { ja: '弦一郎', en: 'GENICHIRO' }, { ja: '源蔵', en: 'GENZO' },
    { ja: '十兵衛', en: 'JUBEI' }, { ja: '弥太郎', en: 'YATARO' }, { ja: '与一', en: 'YOICHI' },
    { ja: '勝之進', en: 'KATSUNOSHIN' }, { ja: '頼之', en: 'YORIYUKI' }, { ja: '篤', en: 'ATSUSHI' },
    { ja: '郁弥', en: 'IKUYA' }, { ja: '栄治', en: 'EIJI' }, { ja: '音也', en: 'OTOYA' },
    { ja: '快', en: 'KAI' }, { ja: '桐人', en: 'KIRITO' }, { ja: '匡', en: 'TADASHI' },
    { ja: '弘樹', en: 'HIROKI' }, { ja: '光輝', en: 'KOKI' }, { ja: '幸也', en: 'YUKIYA' },
    { ja: '忠明', en: 'TADAAKI' }, { ja: '毅', en: 'TSUYOSHI' }, { ja: '夏彦', en: 'NATSUHIKO' },
    { ja: '博文', en: 'HIROFUMI' }, { ja: '悠一郎', en: 'YUICHIRO' }, { ja: '雄大', en: 'YUDAI' },
    { ja: '洋平', en: 'YOHEI' }, { ja: '綾人', en: 'AYATO' }, { ja: '蘭丸', en: 'RANMARU' },
    { ja: '竜胆', en: 'RINDO' }, { ja: '怜央', en: 'REO' }, { ja: '禅', en: 'ZEN' },
    { ja: '蔵人', en: 'KURANDO' }, { ja: '主水', en: 'MONDO' }, { ja: '平蔵', en: 'HEIZO' },
    { ja: '半次郎', en: 'HANJIRO' }, { ja: '伝助', en: 'DENSUKE' }, { ja: '権兵衛', en: 'GONBEE' },
    { ja: '佐吉', en: 'SAKICHI' }, { ja: '才蔵', en: 'SAIZO' }, { ja: '獅子丸', en: 'SHISHIMARU' },
    { ja: '虎徹', en: 'KOTETSU' }, { ja: '焔', en: 'HOMURA' }, { ja: '朧', en: 'OBORO' },
    { ja: '陽炎', en: 'KAGERO' }, { ja: '篝', en: 'KAGARI' }, { ja: '銀', en: 'SHIROGANE' },
    { ja: '一誠', en: 'ISSEI' }, { ja: '悠介', en: 'YUSUKE' }, { ja: '拓斗', en: 'TAKUTO' },
    { ja: '慶太', en: 'KEITA' }, { ja: '遼太郎', en: 'RYOTARO' }, { ja: '蒼真', en: 'SOMA' },
    { ja: '律希', en: 'RITSUKI' }, { ja: '蓮太郎', en: 'RENTARO' }, { ja: '京太郎', en: 'KYOTARO' },
    { ja: '虎之助', en: 'TORANOSUKE' }, { ja: '銀之丞', en: 'GINNOJO' }, { ja: '千之助', en: 'SENNOSUKE' },
    { ja: '平次', en: 'HEIJI' }, { ja: '松之助', en: 'MATSUNOSUKE' }, { ja: '又八', en: 'MATAHACHI' },
    { ja: '弥七', en: 'YASHICHI' }, { ja: '伊佐次', en: 'ISAJI' }, { ja: '藤兵衛', en: 'TOBEE' },
    { ja: '喜八', en: 'KIHACHI' }, { ja: '治郎吉', en: 'JIROKICHI' }, { ja: '佐平次', en: 'SAHEIJI' },
    { ja: '清吉', en: 'SEIKICHI' }, { ja: '卯之吉', en: 'UNOKICHI' }, { ja: '辰五郎', en: 'TATSUGORO' },
    { ja: '瞳', en: 'HITOMI' }, { ja: '薫子', en: 'KAORUKO' }, { ja: '文乃', en: 'FUMINO' },
    { ja: '知世', en: 'TOMOYO' }, { ja: '真理', en: 'MARI' }, { ja: '綺羅', en: 'KIRA' },
    { ja: '朝顔', en: 'ASAGAO' }, { ja: '茉莉花', en: 'MARIKA' }, { ja: '夕子', en: 'YUKO' },
    { ja: '節子', en: 'SETSUKO' }, { ja: '京子', en: 'KYOKO' }, { ja: '和子', en: 'KAZUKO' },
    { ja: '幸子', en: 'SACHIKO' }, { ja: '桃代', en: 'MOMOYO' }, { ja: '千代', en: 'CHIYO' },
    { ja: '富士子', en: 'FUJIKO' }, { ja: '房子', en: 'FUSAKO' }, { ja: '時子', en: 'TOKIKO' },
    { ja: '波留', en: 'HARU' }, { ja: '文緒', en: 'FUMIO' }, { ja: '杏奈', en: 'ANNA' },
    { ja: '真央', en: 'MAO' }, { ja: '菜穂子', en: 'NAOKO' }, { ja: '沙都子', en: 'SATOKO' },
    { ja: '柚香', en: 'YUZUKA' }, { ja: '藍子', en: 'AIKO' }, { ja: '蝶子', en: 'CHOKO' },
    { ja: '雪絵', en: 'YUKIE' }, { ja: '澄子', en: 'SUMIKO' }, { ja: '菊乃', en: 'KIKUNO' },
    { ja: '慶子', en: 'KEIKO' }, { ja: '茅乃', en: 'CHINO' }, { ja: '千枝子', en: 'CHIEKO' },
    { ja: '縫', en: 'NUI' }, { ja: '綾女', en: 'AYAME' }, { ja: '真珠', en: 'SHINJU' },
    { ja: '翡翠', en: 'HISUI' }, { ja: '玻璃', en: 'HARI' }, { ja: '月詠', en: 'TSUKUYOMI' },
    { ja: '姫子', en: 'HIMEKO' }, { ja: '香織', en: 'KAORI' }, { ja: '奈津', en: 'NATSU' },
    { ja: '美鈴', en: 'MISUZU' }, { ja: '光子', en: 'MITSUKO' }, { ja: '里江', en: 'RIE' },
    { ja: '露子', en: 'TSUYUKO' }, { ja: '冴子', en: 'SAEKO' }, { ja: '操', en: 'MISAO' },
    { ja: '貴子', en: 'TAKAKO' }, { ja: '頼子', en: 'YORIKO' }, { ja: '好美', en: 'YOSHIMI' },
    { ja: '佳世', en: 'KAYO' }, { ja: '芙蓉', en: 'FUYO' }, { ja: '乙女', en: 'OTOME' },
    { ja: '織姫', en: 'ORIHIME' }, { ja: '月子', en: 'TSUKIKO' }, { ja: '陽子', en: 'YOKO' },
    { ja: '涼子', en: 'RYOKO' }, { ja: '初枝', en: 'HATSUE' }, { ja: '志津', en: 'SHIZU' },
    { ja: '佐和子', en: 'SAWAKO' }, { ja: '瑠璃子', en: 'RURIKO' }, { ja: '桜子', en: 'SAKURAKO' },
    { ja: '剛志', en: 'GOSHI' }, { ja: '彰久', en: 'AKIHISA' }, { ja: '昭雄', en: 'AKIO' },
    { ja: '淳', en: 'JUN' }, { ja: '純平', en: 'JUNPEI' }, { ja: '順一', en: 'JUNICHI' },
    { ja: '丈太郎', en: 'JOTARO' }, { ja: '慎太郎', en: 'SHINTARO' }, { ja: '省吾', en: 'SHOGO' },
    { ja: '昇', en: 'NOBORU' }, { ja: '信也', en: 'SHINYA' }, { ja: '真人', en: 'MASATO' },
    { ja: '政宗', en: 'MASAMUNE' }, { ja: '正嗣', en: 'MASATSUGU' }, { ja: '大悟', en: 'DAIGO' },
    { ja: '泰三', en: 'TAIZO' }, { ja: '孝太', en: 'KOTA' }, { ja: '知宏', en: 'TOMOHIRO' },
    { ja: '虎丸', en: 'TORAMARU' }, { ja: '直人', en: 'NAOTO' }, { ja: '仁志', en: 'HITOSHI' },
    { ja: '秀一', en: 'HIDEKAZU' }, { ja: '一之', en: 'KAZUYUKI' }, { ja: '文太', en: 'BUNTA' },
    { ja: '平助', en: 'HEISUKE' }, { ja: '穂高', en: 'HODAKA' }, { ja: '誠一郎', en: 'SEIICHIRO' },
    { ja: '牧人', en: 'MAKITO' }, { ja: '道長', en: 'MICHINAGA' }, { ja: '宗次郎', en: 'SOJIRO' },
    { ja: '八郎', en: 'HACHIRO' }, { ja: '弥彦', en: 'YAHIKO' }, { ja: '靖', en: 'YASUSHI' },
    { ja: '康平', en: 'KOHEI' }, { ja: '雄星', en: 'YUSEI' }, { ja: '洋二', en: 'YOJI' },
    { ja: '義隆', en: 'YOSHITAKA' }, { ja: '吉蔵', en: 'KICHIZO' }, { ja: '遼平', en: 'RYOHEI' },
    { ja: '朗人', en: 'AKIHITO' }, { ja: '和成', en: 'KAZUNARI' }, { ja: '渉', en: 'WATARU' },
    { ja: '一心', en: 'ISSHIN' }, { ja: '海斗', en: 'KAITO' }, { ja: '逸馬', en: 'ITSUMA' },
    { ja: '牛若', en: 'USHIWAKA' }, { ja: '影虎', en: 'KAGETORA' }, { ja: '神楽', en: 'KAGURA' },
    { ja: '狂四郎', en: 'KYOSHIRO' }, { ja: '金太', en: 'KINTA' }, { ja: '剣心', en: 'KENSHIN' },
    { ja: '玄斎', en: 'GENSAI' }, { ja: '朱雀', en: 'SUZAKU' }, { ja: '青龍', en: 'SEIRYU' },
    { ja: '白虎', en: 'BYAKKO' }, { ja: '玄武', en: 'GENBU' }, { ja: '天馬', en: 'TENMA' },
    { ja: '鉄之進', en: 'TETSUNOSHIN' }, { ja: '道玄', en: 'DOGEN' }, { ja: '不知火', en: 'SHIRANUI' },
    { ja: '無明', en: 'MUMYO' }, { ja: '夜叉丸', en: 'YASHAMARU' }, { ja: '雷蔵', en: 'RAIZO' },
    { ja: '六平太', en: 'ROPPEITA' }, { ja: '彩子', en: 'AYAKO' }, { ja: '郁子', en: 'IKUKO' },
    { ja: '市子', en: 'ICHIKO' }, { ja: '初', en: 'HATSU' }, { ja: '歌子', en: 'UTAKO' },
    { ja: '江里', en: 'ERI' }, { ja: '苑子', en: 'SONOKO' }, { ja: '寛子', en: 'HIROKO' },
    { ja: '絹代', en: 'KINUYO' }, { ja: '久美子', en: 'KUMIKO' }, { ja: '琴子', en: 'KOTOKO' },
    { ja: '小夜', en: 'SAYO' }, { ja: '沙羅', en: 'SARA' }, { ja: '静枝', en: 'SHIZUE' },
    { ja: '澄江', en: 'SUMIE' }, { ja: '節', en: 'SETSU' }, { ja: '田鶴子', en: 'TAZUKO' },
    { ja: '千賀子', en: 'CHIKAKO' }, { ja: '月乃', en: 'TSUKINO' }, { ja: '綴', en: 'TSUZURI' },
    { ja: '七緒', en: 'NANAO' }, { ja: '菜々子', en: 'NANAKO' }, { ja: '文子', en: 'FUMIKO' },
    { ja: '牡丹', en: 'BOTAN' }, { ja: '繭子', en: 'MAYUKO' }, { ja: '美代', en: 'MIYO' },
    { ja: '都', en: 'MIYAKO' }, { ja: '睦子', en: 'MUTSUKO' }, { ja: '八重子', en: 'YAEKO' },
    { ja: '百合子', en: 'YURIKO' }, { ja: '律子', en: 'RITSUKO' }, { ja: '麗子', en: 'REIKO' },
    { ja: '和歌子', en: 'WAKAKO' }, { ja: '音羽', en: 'OTOWA' }, { ja: '柏', en: 'KASHIWA' },
    { ja: '早蕨', en: 'SAWARABI' }, { ja: '白妙', en: 'SHIROTAE' }
  ],
  season: [
    '雨水', '啓蟄', '春分', '清明', '穀雨', '立夏', '小満', '芒種', '小暑', '大暑',
    '立秋', '処暑', '白露', '秋分', '寒露', '霜降', '立冬', '小雪', '大雪', '小寒', '大寒',
    '如月', '皐月', '神無月',
    '一月', '二月', '三月', '四月', '六月', '七月', '九月', '十一月', '十二月',
    '初春', '仲春', '晩春', '仲夏', '盛夏', '仲秋', '深秋', '仲冬', '晩冬',
    '新春', '陽春', '若夏', '常夏',
    '余寒', '春寒', '向暑', '向寒', '秋冷', '厳冬', '酷暑', '猛暑', '炎暑', '熱帯夜',
    '真夏日', '三寒四温', '寒の入り', '寒の戻り', '寒明け', '寒中', '冬ざれ', '冬支度',
    '夜寒', '朝寒', '肌寒',
    '空梅雨', '梅雨入り', '梅雨明け', '走り梅雨', '菜種梅雨', '梅雨寒', '五月雨', '五月晴れ',
    '秋雨', '秋晴れ', '秋の長雨', '小春日和', '木枯らし', '春一番', '春霞', '春疾風',
    '花曇り', '花散らし', '薄氷', '淡雪', '名残雪', '残雪', '雪解け', '吹雪', '粉雪',
    '初雪', '霜柱', '初霜', '初氷', '氷雨', '時雨', '村時雨', '青時雨', '蝉時雨',
    '夕立', '野分', '台風', '秋台風', '入道雲', '夕焼け', '朝焼け', '陽炎', '逃げ水',
    '蜃気楼', '花吹雪', '五月闇', '白夜', '極夜', '空っ風', '薫風', '青嵐',
    '南風', '東風', '北風', '秋風', '春風', '涼風',
    '土用', '土用波', '半夏生', '二百十日', '八十八夜', '節分', '彼岸', '彼岸明け',
    '大晦日', '元旦', '松の内', '小正月', '七草', '年明け', '年末', '年始', '新年',
    '旧正月', '初詣', '花見時', '若葉時', '青葉時', '新緑', '万緑', '麦秋', '紅葉時',
    '秋の夜長', '短夜', '遅日', '日永', '春眠', '春宵', '夏の宵', '秋の暮れ', '冬の朝',
    '夏の終わり', '夏休み', '桜前線', '花時',
    '中秋', '名月', '十六夜', '朧月', '朧夜', '星月夜', '天の川', '冬銀河', '虫時雨',
    '朝露', '夜露', '氷点下', '真冬日', '夏日', '新涼', '雪催い', '冬晴れ', '冬凪',
    '夕凪', '朝凪', '油照り', '炎天', '日照り', '朝霧', '夕霧', '川霧', '海霧',
    '七夕', 'お盆', '十五夜', '十三夜', '除夜', '初日の出', '鏡開き', '雛祭り', '端午',
    '七五三', '月見', '花見', '紅葉狩り', '潮干狩り', '海開き', '山開き', '川開き',
    '衣替え', '新茶', '新酒', '新米', '初鰹', '田植え時', '稲刈り', '種蒔き',
    '雪囲い', '雪下ろし'
  ],
  place: [
    '岬の突端', '砂丘', '磯場', '干潟', '遠浅の浜', '岩礁', '防波堤', '消波ブロックの上',
    '漁港', '船着き場', '海食洞', '貝殻だらけの浜', '潮溜まり', '汽水域', '三角州', '砂州',
    '河原', '中州', '川べり', '堰の上', '貯水池のほとり', '用水路', '水門', '取水塔',
    '桟橋', '浮桟橋', '沖の防波堤', '灯浮標のあたり', '海底トンネルの入口', 'フェリー乗り場',
    '客船のデッキ', '甲板の隅', '船倉', '漁船の上', '引き潮の浜', '満潮の岸壁', '海女小屋',
    '定置網の沖', '海鳥の営巣地', '断崖の上', '白亜の断崖', '海沿いの国道', '岬の灯台跡',
    '波打ち際', '荒磯', '内海', '外洋', '環礁', '珊瑚礁', '入り江の奥', '湾の最奥',
    '静かな瀬', '淵', '滝壺', '渓谷', '渓流', '沢の上流', '源流', '湧水池', '泉のほとり',
    '水源林', '池の畔', '沼地', '湿原', '泥炭地', '葦原', '蓮池', '溜池', '堀端',
    '城の外堀', '運河沿い', '水路の橋の下', '船溜まり', '川の合流点', '分水嶺', '洗い場',
    '洗濯場跡', '井戸端',
    '稜線', '尾根道', '谷底', '山頂', '中腹', '登山口', '避難小屋', '山小屋', '峠道',
    '峠の茶屋', '崖下', '岩場', '鎖場', '雪渓', '氷河の末端', '火口', '火口湖',
    '噴気孔のそば', '溶岩台地', '高原の牧場', '草原', '大草原', '荒野', '荒れ地',
    '岩砂漠', '砂漠のオアシス', '竹林', '杉並木', '雑木林', 'ブナの原生林', '松林',
    '防風林', '森の奥', '樹海', '苔むした森', '倒木の上', '切り株の広場', '木漏れ日の道',
    '林道', '獣道', 'けもの道の分岐', '山菜の斜面', '段々畑', '棚田', '田んぼの畦',
    '麦畑', '菜の花畑', '向日葵畑', 'ラベンダー畑', '茶畑', '果樹園の奥', '葡萄畑',
    'りんご畑', '蜜柑山', '芋畑', '田の水面', '用水の脇', '畑の真ん中', '干草の山',
    '牧草地', '放牧地', '馬場', '鶏舎の裏', '納屋', '藁小屋', '蔵の前', '母屋の縁側',
    '井戸のある庭', '裏山', '鎮守の森', '神社の参道', '境内', '石段の途中', '鳥居のむこう',
    '社の裏手', '祠のそば', '墓地', '無縁墓', '寺の山門', '鐘楼', '経堂',
    '駅前ロータリー', '地下街', '地下道', '高架下', '線路沿い', '踏切', '開かずの踏切',
    '車両基地', '操車場', '引き込み線', '貨物駅', '終着駅', '始発駅', '乗り換え通路',
    'ホームの端', '最終電車の車内', '始発待ちのホーム', '深夜のバス停', '高速バスの車内',
    'タクシー乗り場', '立体駐車場', '屋上駐車場', '高速道路の下', '首都高の分岐',
    'サービスエリア', '峠のドライブイン', 'ガソリンスタンド', '洗車場', '中古車置き場',
    '廃車置き場', '陸橋の上', '歩道橋', '交差点のど真ん中', 'スクランブル交差点', 'ビル街',
    '摩天楼の谷間', 'オフィス街', '官庁街', '金融街', '問屋街', '商店街のアーケード',
    'シャッター通り', '市場の路地', '朝市', '夜市', '屋台街', '飲み屋横丁', '路地裏',
    '袋小路', '迷路のような路地', '石畳の坂', '坂の上の町', '港町の坂道', '崖の上の住宅街',
    '団地の広場', '給水塔のふもと', '集合住宅の階段', '非常階段', 'ダストシュートの前',
    '屋上の給水槽', 'ビルの狭間', '換気口のそば', 'ネオンの下', '電飾看板の裏',
    '映画館の前', '名画座', '劇場の楽屋', '舞台袖', '客席の最後列', 'ライブハウス',
    'レコード店', '古本屋の奥', '図書室', '資料室', '書庫', '郷土資料館', '博物館の閉館後',
    '美術館の白い壁', '画廊', '骨董屋', '質屋の前', '銭湯', '銭湯の脱衣所',
    'コインランドリー', '深夜のコンビニ', '自販機の明かり', 'ゲームセンター', 'ボウリング場',
    '廃業したパチンコ屋', '喫茶店の窓際', '純喫茶', '屋台のラーメン', '立ち食いそば',
    '食堂の相席', '定食屋のカウンター', '洋菓子店の厨房', 'パン屋の朝', '花屋の店先',
    '金物屋', '文房具屋', '駄菓子屋',
    '教室の後ろ', '放課後の教室', '誰もいない廊下', '階段の踊り場', '音楽室', '理科室',
    '準備室', '美術室', '家庭科室', '視聴覚室', '保健室', '職員室の前', '部室',
    '部室棟の裏', '体育館', '体育倉庫', '校庭の隅', 'グラウンドのトラック', 'プールサイド',
    '更衣室', '屋上のフェンス', '通用門', '校門前', '通学路', '桜並木の通学路', '学食',
    '購買の列', '図書委員の机', '黒板の前', '掲示板の前', '下駄箱', '昇降口', '寮の相部屋',
    '寮の食堂', '二段ベッドの上', '下宿の窓', '六畳一間', 'ワンルームの床', '台所の椅子',
    '食卓の向かい', '冷蔵庫の前', '風呂場', '洗面所の鏡', '押し入れの中', '屋根裏',
    '縁の下', '物置', 'ベランダ', '洗濯物の下', '玄関先', '郵便受けの前', '階段の下',
    '廊下の突き当たり', '客間', '仏間', '寝室の窓辺', '書斎', '子供部屋',
    '段ボールだらけの部屋', '引っ越し前の部屋', '空き家', '誰も住まない実家', '縁側',
    '中庭', '裏庭', '庭の物干し', '犬小屋の横', '塀の上', '生垣の切れ目', '門柱の陰',
    '廃工場', '廃鉱', '坑道', '鉱山跡', '精錬所跡', '廃校', '廃村', '廃屋', '廃病院',
    '廃遊園地', '錆びた観覧車', '止まったメリーゴーランド', '遊具の墓場', '廃バス',
    '沈んだ村', 'ダム湖の底', '水没した町', '干上がった湖', '涸れ井戸', '使われない駅舎',
    '撤去前の団地', '取り壊し中のビル', '更地', '造成地', '埋立地', '処分場', 'ゴミ集積所',
    '資材置き場', '倉庫街', '冷凍倉庫', '貨物コンテナの間', '造船所', 'ドック',
    '製鉄所の夜', '発電所', '変電所', '送電塔の下', '風車の下', '石油タンクの列',
    '煙突の影', '高炉跡', 'トンネルの途中', '廃トンネル', '廃線跡の鉄橋', '枕木だけの道',
    '崩れかけた橋', '沈下橋', '吊り橋の真ん中', '峠の廃道', '検問所跡', '監視塔',
    '有刺鉄線の向こう', '立入禁止区域', '境界線上', '緩衝地帯', '地下壕', '防空壕',
    'シェルター', '地下シェルターの通路', '研究所の地下', '実験室', '培養室', '冷凍睡眠室',
    '管制室', '通信室', '発令所', '機関室', '隔離病棟', '霊安室', '焼却炉の前',
    '南の島の空港', '国境の町', '国境検問所', '砂漠の街道', 'キャラバンの野営地',
    'オアシスの井戸', '隊商宿', '城塞都市', '旧市街', '迷宮のようなスーク', '大聖堂の裏',
    '修道院', '尖塔の上', '鐘楼の階段', '石造りの広場', '噴水のある広場', '露天のカフェ',
    '石畳の路地裏', '運河の街', '水の都', '跳ね橋', '港の倉庫街', '灯台の螺旋階段',
    '島の教会', '断崖の修道院', '山岳の僧院', '遺跡の柱廊', '神殿跡', '円形闘技場',
    '地下墓地', '王宮の中庭', '離宮', '庭園の迷路', '温室の奥', '植物園', '動物園の閉園後',
    '水族館の暗がり', 'プラネタリウム', '天文台', '望遠鏡のドーム', '気象観測所',
    '灯台守の部屋', '無人島', '孤島の桟橋', '群島の渡し', '流氷の海', '極地の基地',
    '氷原', '雪原の一軒家', '針葉樹林の小屋', 'ツンドラの道', '大陸横断鉄道の車内',
    '寝台車の通路', '食堂車', '空港の乗り継ぎロビー', '深夜の空港', '滑走路の端',
    '格納庫', '気球のかご', '展望デッキ',
    '祭りの夜店', '花火大会の河川敷', '盆踊りの櫓', '神輿の通り道', '縁日の参道',
    '初詣の列', '除夜の鐘の下', '花見の宴', '潮干狩りの浜', '海水浴場の更衣所',
    'キャンプ場', '焚き火の周り', 'テントの中', '山荘のリビング', '露天風呂',
    '温泉街の路地', '湯けむりの坂', '旅館の広縁', '民宿の食堂', '峠の宿', '遍路道',
    '巡礼路', '街道の一里塚', '宿場町', '城下町の堀端', '蔵の街並み', '白壁の通り',
    '武家屋敷跡', '天守閣', '石垣の上', '空堀', '櫓門', '陣屋跡', '古戦場', '塚',
    '石仏の並ぶ道', '道祖神の辻', '六地蔵の前', '峠の地蔵堂', '追分', '三叉路',
    '十字路の真ん中', '一本道', '並木道', '銀杏並木', '桜のトンネル', '紫陽花の坂',
    '曼珠沙華の畦', '芒の原', '蓮田', '菖蒲園', '梅林', '桃畑', '花畑の真ん中',
    '温室の硝子越し', '大観覧車の頂点', '展望室', '屋上庭園', '非常口の外',
    '病院の待合室', '診察室', '手術室の前', '産科の廊下', 'リハビリ室',
    '老人ホームの談話室', '霊園の坂', '火葬場', '葬儀場の外', '教会の告解室', '礼拝堂',
    '鐘の鳴る丘', '修道院の菜園', '神学校', '寺子屋跡', '塾の自習室', '予備校の教室',
    '図書館の閉架', '大学の講堂', '研究棟の廊下', '実験棟の屋上', 'サークル棟',
    '学生寮の廊下', '就活会場', '面接室', '会議室', '社長室', '給湯室', '喫煙所',
    '非常階段の踊り場', '工場のライン', '検品室', '事務所の窓際', '倉庫の二階',
    '配送センター', '市場の競り場', '魚市場', '青果市場', '花市場', '精肉店の奥',
    '酒蔵', '醤油蔵', '味噌蔵', '麹室', '酒場のカウンター', '立ち飲み屋',
    'スナックの止まり木', 'バーの奥の席', 'クラブの控室', 'ホテルのロビー', '客室の窓',
    '非常口の階段', '屋上プール', 'スパの休憩室', 'カジノの裏口', '場外馬券売り場',
    '競馬場のスタンド', '競艇場', '賭場', '質流れ市', '露天商の並び', '蚤の市', '骨董市',
    '縁日の金魚すくい', '射的の屋台', 'サーカスのテント', '移動遊園地', '見世物小屋',
    '芝居小屋', '楽屋口', '稽古場', '道場', '剣道場の板の間', '相撲部屋', 'ボクシングジム',
    'プールの底', 'スケートリンク', 'スキー場のリフト', 'ゲレンデの端', '山頂駅',
    'ロープウェイの中', 'ケーブルカーの車内', '観光船のデッキ', '渡し船の上', '屋形船',
    '灯りの消えた遊覧船', 'カヌーの上', '桟橋の先端', '波間'
  ],
  emotion: [
    '無垢な', '純粋な', '素直な', '率直な', '従順な', '大胆な', '奔放な', '孤独な',
    '静謐な', '清らかな', '艶やかな', '華やかな', '鮮やかな', '密かな', 'しなやかな',
    'たおやかな', 'なめらかな', '柔らかな', '軽やかな', '晴れやかな', '伸びやかな',
    '健やかな', '賑やかな', '華奢な', '可憐な', '優美な', '優雅な', '淑やかな', '上品な',
    '不敵な', '不穏な', '不吉な', '不埒な', '不遜な', '不器用な', '不確かな', '不揃いな',
    '不用意な', '危険な', '過激な', '過剰な', '苛烈な', '峻烈な', '熾烈な', '猛烈な',
    '強烈な', '鮮烈な', '閑静な', '幽玄な', '神秘的な', '官能的な', '情熱的な', '献身的な',
    '刹那的な', '破滅的な', '退廃的な', '耽美的な', '叙情的な', '詩的な', '幻想的な',
    '牧歌的な', '悲劇的な', '喜劇的な', '演劇的な', '儀式的な', '直情的な', '衝動的な',
    '本能的な', '動物的な', '機械的な', '事務的な', '打算的な', '挑発的な', '扇情的な',
    '蠱惑的な', '魅惑的な', '無造作な', '無頓着な', '無感動な', '無表情な', '無愛想な',
    '無口な', '無言の', '無心な', '無我夢中の', '生真面目な', '生半可な', '生意気な',
    '意固地な', '頑固な', '強情な', '意地悪な', '天邪鬼な', '臆病な', '小心な', '豪快な',
    '快活な', '闊達な', '磊落な', '鷹揚な', '寛容な', '温厚な', '実直な', '律儀な',
    '謙虚な', '真摯な', '誠実な', '熱心な', '勤勉な', '果敢な', '勇敢な', '果断な',
    '慎重な', '冷静な', '沈着な', '冷淡な', '冷酷な', '残酷な', '酷薄な', '陰湿な',
    '陰鬱な', '憂鬱な', '凛とした', '毅然とした', '泰然とした', '悠然とした', '超然とした',
    '平然とした', '呆然とした', '恍惚とした', '陶然とした', '憮然とした', '憤然とした',
    '敢然とした', '決然とした', '漠然とした', '悄然とした', '粛然とした', '騒然とした',
    '索漠とした', '荒涼とした', '寂寞とした', '鬱蒼とした', '渾然とした', '鬱屈した',
    '屈折した', '倒錯した',
    '愛おしい', '慕わしい', '懐かしい', '恋しい', '待ち遠しい', 'もどかしい', 'やるせない',
    '切ない', 'やりきれない', 'いたたまれない', '落ち着かない', '手に負えない', '底知れない',
    '果てしない', 'とめどない', '限りない', 'たまらない', 'こらえきれない', '抑えきれない',
    '隠しきれない', '言い尽くせない', '例えようもない', '名状しがたい', '抗いがたい',
    '忘れがたい', '得がたい', '近寄りがたい', '侮りがたい', '初々しい', '瑞々しい',
    '猛々しい', '荒々しい', '慌ただしい', '甚だしい', '苦々しい', '忌々しい', '憎々しい',
    '清々しい', '図々しい', '白々しい', '空々しい', '痛々しい', '弱々しい', '毒々しい',
    '生々しい', '仰々しい', '華々しい', '騒がしい', 'やかましい', '好ましい', '望ましい',
    '微笑ましい', '頼もしい', '羨ましい', '妬ましい', '疎ましい', '恨めしい', '悔しい',
    '恥ずかしい', '気恥ずかしい', '照れくさい', '面映ゆい', 'くすぐったい', 'こそばゆい',
    'ものものしい', 'ものさびしい', 'もの憂い', 'もの狂おしい', '狂おしい', '悩ましい',
    '艶めかしい', '慎ましい', '奥ゆかしい', '麗しい', '美しい', '愛らしい', '可愛らしい',
    '憎らしい', 'いじらしい', 'たどたどしい', 'ぎこちない', 'あっけない', 'そっけない',
    '情けない', '心細い', '気忙しい', '気だるい', '物憂げな', '甘酸っぱい', 'ほろ苦い',
    '渋い', '生ぬるい', '生暖かい', 'まばゆい', '薄暗い', '仄暗い', '仄かな', '名残惜しい',
    '拗ねた', 'ふてくされた', '浮き足立った', '拗ねたような', 'むくれた', '尖った',
    '澄ました', '取り澄ました', '気取った', 'はしゃいだ', 'おどけた', 'とぼけた', 'ふざけた',
    'おびえた', '怯えきった', '泣きはらした', '泣き笑いの', '笑いをこらえた', '息を切らした',
    '息を潜めた', '肩の力が抜けた', '力の抜けた', '張り詰めた', '強張った', '緩んだ',
    'ほどけた', 'ほころんだ', '綻ぶような', 'とろけた', '蕩けるような', '溶けかけた',
    '熱を帯びた', '熱に浮かされた', '汗ばんだ', '火照った', '上気した', '紅潮した',
    '赤らんだ', '青ざめた', '血の気の引いた', '目を伏せた', '目を細めた', '目を見開いた',
    '目を逸らした', 'まばたきを忘れた', '見惚れた', '見上げた', '振り返った', '立ち止まった',
    '走り出した', '駆け出した', '飛び込んだ', '逃げ出した', '隠れた', 'うつむいた',
    '顔を上げた', '顔を隠した', '頬を寄せた', '寄り添った', '抱きしめた', '手を伸ばした',
    '指を絡めた', '髪をかき上げた', '唇を噛んだ', '笑みをこぼした', '微笑んだ', '吹き出した',
    '声を殺した', '声を上げた', '黙り込んだ', '言いよどんだ', '口ごもった', '言いかけた',
    '言い切った', '思いつめた', '覚悟を決めた', '腹をくくった', '開き直った', '割り切った',
    '諦めた', '諦めきれない', '吹っ切れた', '割り切れない', '未練がましい', '往生際の悪い',
    '浮かれた', '舞い上がった', '有頂天の', '上の空の', '心ここにあらずの',
    '地に足のつかない', '落ち着き払った', '肝の据わった', '度胸の据わった', 'すり切れた',
    '草臥れた', '疲れきった', '憔悴した', '消耗しきった', '荒んだ', '荒れた',
    'ささくれ立った', 'とげとげしい', '角の取れた', '丸くなった', '老いた', '若やいだ',
    '幼い', '幼げな', 'ませた', '大人ぶった',
    '夢のような', '嘘のような', '絵のような', '詩のような', '歌のような', '祈りのような',
    '囁きのような', 'ため息のような', '悲鳴のような', '独り言のような', '子供のような',
    '少女のような', '猫のような', '小鳥のような', '蝶のような', '硝子のような',
    '陶器のような', '絹のような', '蜜のような', '綿菓子のような', '真綿のような',
    '羽根のような', '泡のような', '露のような', '霧のような', '雪のような', '陽射しのような',
    '木漏れ日のような', '月明かりのような', '星屑のような', '線香花火のような',
    '打ち上げ花火のような', '遠雷のような', '夕立のような', '波のような', '潮騒のような',
    '春先のような', '真夏のような', '秋の日のような', '冬の朝のような', '初雪のような',
    '逃げ水のような', '蜃気楼のような', '白昼夢のような', 'まどろみのような',
    '寝ぼけまなこの', '寝起きの', '湯上がりの', '浴衣姿の', '素足の', '裸足の',
    '生まれたままの', 'ありのままの', 'そのままの', 'いつも通りの', 'いつもと違う',
    'ふだん着の', 'よそ行きの', '一張羅の', '借り物の', 'つくりものの', '作り笑いの',
    '上辺だけの', '建前だけの', '本音だけの', '嘘偽りのない', '掛け値なしの', '正真正銘の',
    '折り紙付きの', '押しも押されもせぬ', '言葉にならない', '言葉少なな', '口下手な',
    '舌足らずな', '甘えたがりの', '寂しがりの', '恥ずかしがりの', '怖がりの', '忘れっぽい',
    '惚れっぽい', '飽きっぽい', '熱しやすい', '冷めやすい', '傷つきやすい', '泣き虫の',
    '意地っ張りの', '負けん気の強い', '気の強い', '気の弱い', '押しの強い', '影めいた',
    '悪戯めいた', '冗談めいた', '芝居めいた', '謎めいた', '秘密めいた', '神託めいた',
    '予言めいた', '皮肉めいた', '挑発めいた', 'うつむきがちな', '伏し目がちな',
    '遠慮がちな', '途切れがちな', 'ためらいがちな', '忘れがちな', '憂いがちな', '曇りがちな',
    '泣きそうな', '笑い出しそうな', '消えそうな', '壊れそうな', '溢れそうな', '零れそうな',
    '弾けそうな', '眠りそうな', '触れそうな', '届きそうな', '今にも泣き出しそうな',
    '息が止まりそうな', '心臓が止まりそうな', '溶けてしまいそうな',
    'ひとりぼっちの', 'ふたりきりの', 'だれのものでもない', '誰にも見せない', '誰も知らない',
    '誰にも言えない', '言えずじまいの', '届かなかった', '届きそうで届かない',
    '最初で最後の', '一度きりの', '二度とない', '数えきれない', 'ほんの少しの', 'ありふれた',
    'ありきたりの', 'なんでもない', 'とるにたらない', 'かけがえのない', '二つとない',
    '世界でいちばんの', 'ここだけの', '内緒の', 'おあずけの', 'おねだりの', 'おすそわけの',
    'おまけの', 'ごほうびの', 'やけくその', 'なげやりの', '成り行きまかせの',
    '出たとこ勝負の', '一か八かの', '命がけの', '死に物狂いの', '捨て身の', '破れかぶれの',
    '悪あがきの', '瀬戸際の', '崖っぷちの', 'ぎりぎりの', '間一髪の', '危機一髪の',
    'すんでのところの', '紙一重の', '五分五分の', '互角の', '手加減なしの', '容赦のない',
    '遠慮のない', '果てのない', '底のない', '際限のない', '出口のない', '逃げ場のない',
    '引き返せない', '後戻りできない', '取り返しのつかない', '埋めようのない',
    '説明のつかない', '理由のない', '意味のない', '意味ありげな', '訳ありの', 'いわくつきの',
    '曰く言い難い', '名前のない', '名前も知らない', '顔も知らない', '声だけの', '影だけの',
    '面影だけの', '記憶の中の', '遠い日の', 'あの日の', 'いつかの', 'まだ見ぬ',
    'まだ知らない', 'もう戻れない', 'もう会えない', '会えなくなる前の', '別れぎわの',
    '去り際の', '帰り道の', '見送るだけの', '待ちぼうけの', '待ちきれない', '待ちわびた',
    '待たせすぎた', 'すれ違いの', '行き違いの', '噛み合わない', '分かり合えない',
    '分かち合えない', '通じ合った', '響き合う', '溶け合う', '寄り添うような', '支え合う',
    'もたれかかる', '甘えるような', '縋るような', '探るような', '試すような', '咎めるような',
    '許すような', '慈しむような', '労わるような', '諭すような', '睨むような', '射抜くような',
    '見透かすような', '覗き込むような', '焦がすような', '灼けつくような', '凍えるような',
    '息づくような', '脈打つような', 'ざわめくような', '揺らめくような', 'にじむような',
    '沈むような', '浮かぶような', '漂うような', '揺蕩うような'
  ]
};
})(window.PF = window.PF || {});
