(function (PF) {
'use strict';

PF.GENRE_POOLS = PF.GENRE_POOLS || {};

PF.GENRE_POOLS.game = {
  subject: [
    { ja: '麻雀', en: 'MAHJONG' }, { ja: '将棋', en: 'SHOGI' }, { ja: '詰将棋', en: 'SHOGI PROBLEMS' },
    { ja: '囲碁', en: 'GO' }, { ja: '詰碁', en: 'GO PROBLEMS' }, { ja: 'チェス', en: 'CHESS' },
    { ja: 'チェッカー', en: 'CHECKERS' }, { ja: 'リバーシ', en: 'REVERSI' }, { ja: '五目並べ', en: 'GOMOKU' },
    { ja: '連珠', en: 'RENJU' }, { ja: '花札', en: 'HANAFUDA' }, { ja: 'かるた', en: 'KARUTA' },
    { ja: '百人一首', en: 'HYAKUNIN ISSHU' }, { ja: 'トランプ', en: 'PLAYING CARDS' }, { ja: '大富豪', en: 'CARD KING' },
    { ja: '七並べ', en: 'SEVENS' }, { ja: '神経衰弱', en: 'CONCENTRATION' }, { ja: 'ババ抜き', en: 'OLD MAID' },
    { ja: 'ポーカー', en: 'POKER' }, { ja: 'バックギャモン', en: 'BACKGAMMON' }, { ja: 'ドミノ', en: 'DOMINOES' },
    { ja: '双六', en: 'SUGOROKU' }, { ja: 'ビンゴ', en: 'BINGO' }, { ja: 'ダーツ', en: 'DARTS' },
    { ja: 'ビリヤード', en: 'BILLIARDS' }, { ja: 'けん玉', en: 'KENDAMA' }, { ja: '独楽回し', en: 'SPINNING TOP' },
    { ja: 'あやとり', en: 'CATS CRADLE' }, { ja: 'お手玉', en: 'BEANBAGS' }, { ja: 'おはじき', en: 'MARBLE FLICK' },
    { ja: 'めんこ', en: 'MENKO' }, { ja: '将棋崩し', en: 'SHOGI TOPPLE' }, { ja: '挟み将棋', en: 'HASAMI SHOGI' },
    { ja: '軍人将棋', en: 'GUNJIN SHOGI' }, { ja: 'マンカラ', en: 'MANCALA' }, { ja: 'サイコロ', en: 'DICE' },
    { ja: 'じゃんけん', en: 'ROCK PAPER SCISSORS' }, { ja: 'あみだくじ', en: 'LADDER LOTTERY' }, { ja: '福笑い', en: 'FUKUWARAI' },
    { ja: 'だるま落とし', en: 'DARUMA DROP' }, { ja: '輪投げ', en: 'RING TOSS' }, { ja: '射的', en: 'SHOOTING GALLERY' },
    { ja: '紙相撲', en: 'PAPER SUMO' }, { ja: 'ベーゴマ', en: 'BEIGOMA' }, { ja: '石けり', en: 'HOPSCOTCH' },
    { ja: '鬼ごっこ', en: 'TAG' }, { ja: 'かくれんぼ', en: 'HIDE AND SEEK' }, { ja: '缶蹴り', en: 'KICK THE CAN' },

    { ja: '野球', en: 'BASEBALL' }, { ja: '草野球', en: 'SANDLOT BASEBALL' }, { ja: 'ソフトボール', en: 'SOFTBALL' },
    { ja: 'サッカー', en: 'SOCCER' }, { ja: 'フットサル', en: 'FUTSAL' }, { ja: 'テニス', en: 'TENNIS' },
    { ja: '卓球', en: 'TABLE TENNIS' }, { ja: 'バドミントン', en: 'BADMINTON' }, { ja: 'バレーボール', en: 'VOLLEYBALL' },
    { ja: 'バスケットボール', en: 'BASKETBALL' }, { ja: 'ハンドボール', en: 'HANDBALL' }, { ja: 'ラグビー', en: 'RUGBY' },
    { ja: 'アイスホッケー', en: 'ICE HOCKEY' }, { ja: 'ゴルフ', en: 'GOLF' }, { ja: 'ボウリング', en: 'BOWLING' },
    { ja: '釣り', en: 'FISHING' }, { ja: '渓流釣り', en: 'STREAM FISHING' }, { ja: '磯釣り', en: 'ROCK FISHING' },
    { ja: '船釣り', en: 'BOAT FISHING' }, { ja: 'ルアー釣り', en: 'LURE FISHING' }, { ja: '氷上釣り', en: 'ICE FISHING' },
    { ja: '登山', en: 'MOUNTAINEERING' }, { ja: '縦走', en: 'RIDGE TRAVERSE' }, { ja: '沢登り', en: 'STREAM CLIMBING' },
    { ja: '岩登り', en: 'ROCK CLIMBING' }, { ja: 'ボルダリング', en: 'BOULDERING' }, { ja: 'トレイルラン', en: 'TRAIL RUNNING' },
    { ja: 'マラソン', en: 'MARATHON' }, { ja: '駅伝', en: 'EKIDEN RELAY' }, { ja: '短距離走', en: 'SPRINT' },
    { ja: '走り高跳び', en: 'HIGH JUMP' }, { ja: '走り幅跳び', en: 'LONG JUMP' }, { ja: '砲丸投げ', en: 'SHOT PUT' },
    { ja: 'やり投げ', en: 'JAVELIN THROW' }, { ja: '棒高跳び', en: 'POLE VAULT' }, { ja: '競歩', en: 'RACE WALKING' },
    { ja: '水泳', en: 'SWIMMING' }, { ja: '飛び込み', en: 'PLATFORM DIVING' }, { ja: '水球', en: 'WATER POLO' },
    { ja: '遠泳', en: 'OPEN WATER SWIM' }, { ja: 'スキー', en: 'SKIING' }, { ja: 'スキージャンプ', en: 'SKI JUMPING' },
    { ja: 'スノーボード', en: 'SNOWBOARDING' }, { ja: 'フィギュアスケート', en: 'FIGURE SKATING' }, { ja: 'スピードスケート', en: 'SPEED SKATING' },
    { ja: 'カーリング', en: 'CURLING' }, { ja: 'そり滑り', en: 'SLEDDING' }, { ja: 'サーフィン', en: 'SURFING' },
    { ja: 'ダイビング', en: 'SCUBA DIVING' }, { ja: 'カヌー', en: 'CANOEING' }, { ja: 'ラフティング', en: 'RAFTING' },
    { ja: 'ヨット', en: 'SAILING' }, { ja: '相撲', en: 'SUMO' }, { ja: '柔道', en: 'JUDO' },
    { ja: '剣道', en: 'KENDO' }, { ja: '弓道', en: 'KYUDO' }, { ja: '空手', en: 'KARATE' },
    { ja: '合気道', en: 'AIKIDO' }, { ja: 'ボクシング', en: 'BOXING' }, { ja: 'レスリング', en: 'WRESTLING' },
    { ja: 'フェンシング', en: 'FENCING' }, { ja: 'アーチェリー', en: 'ARCHERY' }, { ja: '体操', en: 'GYMNASTICS' },
    { ja: '新体操', en: 'RHYTHMIC GYMNASTICS' }, { ja: 'トランポリン', en: 'TRAMPOLINE' }, { ja: 'なわとび', en: 'JUMP ROPE' },
    { ja: 'スケートボード', en: 'SKATEBOARDING' }, { ja: '自転車競技', en: 'CYCLING' }, { ja: '乗馬', en: 'HORSE RIDING' },
    { ja: '綱引き', en: 'TUG OF WAR' }, { ja: '玉入れ', en: 'BALL TOSS' }, { ja: '大縄跳び', en: 'LONG ROPE JUMP' },
    { ja: '騎馬戦', en: 'CAVALRY BATTLE' }, { ja: '徒競走', en: 'FOOT RACE' }, { ja: 'リレー', en: 'RELAY RACE' },

    { ja: '牧場', en: 'RANCH' }, { ja: '農場', en: 'FARM' }, { ja: '果樹園', en: 'ORCHARD' },
    { ja: '田んぼ', en: 'RICE PADDY' }, { ja: '養蜂', en: 'BEEKEEPING' }, { ja: '酪農', en: 'DAIRY FARMING' },
    { ja: '養鶏', en: 'POULTRY FARM' }, { ja: '養殖場', en: 'FISH FARM' }, { ja: '漁港', en: 'FISHING PORT' },
    { ja: '市場', en: 'MARKET' }, { ja: '商店街', en: 'SHOPPING STREET' }, { ja: '駄菓子屋', en: 'CANDY SHOP' },
    { ja: 'パン屋', en: 'BAKERY' }, { ja: 'ケーキ屋', en: 'CAKE SHOP' }, { ja: 'カフェ', en: 'CAFE' },
    { ja: '喫茶店', en: 'COFFEE HOUSE' }, { ja: '食堂', en: 'DINER' }, { ja: '定食屋', en: 'SET MEAL SHOP' },
    { ja: 'ラーメン屋', en: 'RAMEN SHOP' }, { ja: '寿司屋', en: 'SUSHI BAR' }, { ja: '蕎麦屋', en: 'SOBA SHOP' },
    { ja: '居酒屋', en: 'IZAKAYA' }, { ja: '屋台', en: 'FOOD STALL' }, { ja: '弁当屋', en: 'BENTO SHOP' },
    { ja: '花屋', en: 'FLORIST' }, { ja: '本屋', en: 'BOOKSTORE' }, { ja: '古書店', en: 'USED BOOKSTORE' },
    { ja: '文具店', en: 'STATIONERY SHOP' }, { ja: '雑貨店', en: 'GENERAL STORE' }, { ja: '洋品店', en: 'CLOTHING SHOP' },
    { ja: '靴屋', en: 'SHOE SHOP' }, { ja: '時計店', en: 'WATCH SHOP' }, { ja: '写真館', en: 'PHOTO STUDIO' },
    { ja: '理髪店', en: 'BARBERSHOP' }, { ja: '美容室', en: 'HAIR SALON' }, { ja: '銭湯', en: 'BATHHOUSE' },
    { ja: '温泉宿', en: 'HOT SPRING INN' }, { ja: '旅館', en: 'RYOKAN' }, { ja: '民宿', en: 'GUESTHOUSE' },
    { ja: 'ホテル', en: 'HOTEL' }, { ja: '山小屋', en: 'MOUNTAIN HUT' }, { ja: '遊園地', en: 'AMUSEMENT PARK' },
    { ja: '動物園', en: 'ZOO' }, { ja: '水族館', en: 'AQUARIUM' }, { ja: '博物館', en: 'MUSEUM' },
    { ja: '美術館', en: 'ART MUSEUM' }, { ja: '図書館', en: 'LIBRARY' }, { ja: '映画館', en: 'MOVIE THEATER' },
    { ja: '劇場', en: 'PLAYHOUSE' }, { ja: '百貨店', en: 'DEPARTMENT STORE' }, { ja: '鉄道会社', en: 'RAILWAY COMPANY' },
    { ja: '路線開発', en: 'LINE DEVELOPMENT' }, { ja: '駅前開発', en: 'STATION DEVELOPMENT' }, { ja: '空港', en: 'AIRPORT' },
    { ja: '港湾', en: 'HARBOR WORKS' }, { ja: 'バス会社', en: 'BUS COMPANY' }, { ja: '運送会社', en: 'FREIGHT COMPANY' },
    { ja: '工場', en: 'FACTORY' }, { ja: '造船所', en: 'SHIPYARD' }, { ja: '製鉄所', en: 'STEELWORKS' },
    { ja: '醸造所', en: 'BREWERY' }, { ja: '酒蔵', en: 'SAKE CELLAR' }, { ja: '味噌蔵', en: 'MISO CELLAR' },
    { ja: '醤油蔵', en: 'SOY SAUCE CELLAR' }, { ja: '陶芸窯', en: 'POTTERY KILN' }, { ja: '織物工房', en: 'WEAVING ATELIER' },
    { ja: '木工所', en: 'WOODWORKS' }, { ja: '鍛冶場', en: 'SMITHY' }, { ja: '街づくり', en: 'TOWN BUILDING' },
    { ja: '都市計画', en: 'CITY PLANNING' }, { ja: '村おこし', en: 'VILLAGE REVIVAL' }, { ja: '島おこし', en: 'ISLAND REVIVAL' },
    { ja: '学校経営', en: 'SCHOOL MANAGEMENT' }, { ja: '病院経営', en: 'HOSPITAL MANAGEMENT' }, { ja: '動物病院', en: 'ANIMAL CLINIC' },
    { ja: '保育園', en: 'NURSERY' }, { ja: '幼稚園', en: 'KINDERGARTEN' }, { ja: '消防団', en: 'FIRE BRIGADE' },
    { ja: '交番', en: 'POLICE BOX' }, { ja: '郵便局', en: 'POST OFFICE' }, { ja: '駅舎', en: 'STATION HOUSE' },
    { ja: '団地', en: 'HOUSING ESTATE' }, { ja: '下宿', en: 'BOARDING HOUSE' }, { ja: '寮生活', en: 'DORM LIFE' },
    { ja: '田舎暮らし', en: 'COUNTRY LIFE' }, { ja: '島暮らし', en: 'ISLAND LIFE' }, { ja: '山暮らし', en: 'MOUNTAIN LIFE' },
    { ja: '移住', en: 'RESETTLEMENT' }, { ja: '家計', en: 'HOUSEHOLD BUDGET' }, { ja: '買い物', en: 'SHOPPING' },
    { ja: '引っ越し', en: 'MOVING HOUSE' }, { ja: '掃除', en: 'CLEANING' }, { ja: '片付け', en: 'TIDYING UP' },
    { ja: '洗濯', en: 'LAUNDRY' }, { ja: '大掃除', en: 'DEEP CLEANING' },

    { ja: '漢字ドリル', en: 'KANJI DRILL' }, { ja: '計算ドリル', en: 'ARITHMETIC DRILL' }, { ja: '九九', en: 'TIMES TABLES' },
    { ja: '分数', en: 'FRACTIONS' }, { ja: '小数', en: 'DECIMALS' }, { ja: '図形', en: 'FIGURES' },
    { ja: '方程式', en: 'EQUATIONS' }, { ja: '関数', en: 'FUNCTIONS' }, { ja: '幾何', en: 'GEOMETRY' },
    { ja: '確率', en: 'PROBABILITY' }, { ja: '統計', en: 'STATISTICS' }, { ja: '暗算', en: 'MENTAL ARITHMETIC' },
    { ja: 'そろばん', en: 'ABACUS' }, { ja: '英単語', en: 'ENGLISH WORDS' }, { ja: '英文法', en: 'ENGLISH GRAMMAR' },
    { ja: '英会話', en: 'ENGLISH CONVERSATION' }, { ja: '聞き取り', en: 'LISTENING' }, { ja: '発音', en: 'PRONUNCIATION' },
    { ja: '熟語', en: 'COMPOUND WORDS' }, { ja: '四字熟語', en: 'FOUR CHARACTER IDIOMS' }, { ja: 'ことわざ', en: 'PROVERBS' },
    { ja: '慣用句', en: 'IDIOMS' }, { ja: '敬語', en: 'HONORIFICS' }, { ja: '作文', en: 'COMPOSITION' },
    { ja: '読解', en: 'READING COMPREHENSION' }, { ja: '音読', en: 'READING ALOUD' }, { ja: '書き取り', en: 'DICTATION' },
    { ja: '書道', en: 'CALLIGRAPHY' }, { ja: '硬筆', en: 'PEN LETTERING' }, { ja: '古文', en: 'CLASSICAL JAPANESE' },
    { ja: '漢文', en: 'CLASSICAL CHINESE' }, { ja: '俳句', en: 'HAIKU' }, { ja: '短歌', en: 'TANKA' },
    { ja: '日本史', en: 'JAPANESE HISTORY' }, { ja: '世界史', en: 'WORLD HISTORY' }, { ja: '年表', en: 'CHRONOLOGY TABLE' },
    { ja: '日本地理', en: 'JAPANESE GEOGRAPHY' }, { ja: '世界地理', en: 'WORLD GEOGRAPHY' }, { ja: '都道府県', en: 'PREFECTURES' },
    { ja: '県庁所在地', en: 'PREFECTURAL CAPITALS' }, { ja: '国旗', en: 'NATIONAL FLAGS' }, { ja: '地図記号', en: 'MAP SYMBOLS' },
    { ja: '理科実験', en: 'SCIENCE EXPERIMENT' }, { ja: '天体観測', en: 'STARGAZING' }, { ja: '星座', en: 'CONSTELLATIONS' },
    { ja: '気象', en: 'METEOROLOGY' }, { ja: '元素', en: 'ELEMENTS' }, { ja: '人体', en: 'HUMAN BODY' },
    { ja: '顕微鏡', en: 'MICROSCOPE' }, { ja: '化石', en: 'FOSSILS' }, { ja: '岩石', en: 'ROCKS' },
    { ja: '地層', en: 'STRATA' }, { ja: '植物図鑑', en: 'PLANT GUIDE' }, { ja: '昆虫図鑑', en: 'INSECT GUIDE' },
    { ja: 'プログラミング', en: 'PROGRAMMING' }, { ja: 'タイピング', en: 'TYPING' }, { ja: '論理', en: 'LOGIC' },
    { ja: '楽典', en: 'MUSIC THEORY' }, { ja: '楽譜読み', en: 'SIGHT READING' }, { ja: '手話', en: 'SIGN LANGUAGE' },
    { ja: '点字', en: 'BRAILLE' }, { ja: '交通ルール', en: 'TRAFFIC RULES' }, { ja: '防災', en: 'DISASTER PREPAREDNESS' },
    { ja: '応急手当', en: 'FIRST AID' }, { ja: '時計の読み方', en: 'TELLING TIME' }, { ja: 'カレンダー', en: 'CALENDAR' },
    { ja: '自由研究', en: 'SUMMER PROJECT' },

    { ja: '和太鼓', en: 'JAPANESE DRUMS' }, { ja: '三味線', en: 'SHAMISEN' }, { ja: '箏', en: 'KOTO' },
    { ja: '尺八', en: 'SHAKUHACHI' }, { ja: '篠笛', en: 'SHINOBUE' }, { ja: '琵琶', en: 'BIWA' },
    { ja: 'ドラム', en: 'DRUM KIT' }, { ja: 'ギター', en: 'GUITAR' }, { ja: 'ベース', en: 'BASS GUITAR' },
    { ja: 'ピアノ', en: 'PIANO' }, { ja: '鍵盤', en: 'KEYBOARD' }, { ja: 'バイオリン', en: 'VIOLIN' },
    { ja: 'チェロ', en: 'CELLO' }, { ja: 'トランペット', en: 'TRUMPET' }, { ja: 'トロンボーン', en: 'TROMBONE' },
    { ja: 'サックス', en: 'SAXOPHONE' }, { ja: 'フルート', en: 'FLUTE' }, { ja: 'クラリネット', en: 'CLARINET' },
    { ja: 'ハーモニカ', en: 'HARMONICA' }, { ja: 'ウクレレ', en: 'UKULELE' }, { ja: 'アコーディオン', en: 'ACCORDION' },
    { ja: 'リコーダー', en: 'RECORDER' }, { ja: 'タンバリン', en: 'TAMBOURINE' }, { ja: 'カスタネット', en: 'CASTANETS' },
    { ja: '木琴', en: 'XYLOPHONE' }, { ja: '鉄琴', en: 'GLOCKENSPIEL' }, { ja: '指揮', en: 'CONDUCTING' },
    { ja: '合唱', en: 'CHORUS' }, { ja: '吹奏楽', en: 'WIND ORCHESTRA' }, { ja: '管弦楽', en: 'ORCHESTRA' },
    { ja: '弾き語り', en: 'SOLO SINGING' }, { ja: '作曲', en: 'COMPOSING' }, { ja: '編曲', en: 'ARRANGING' },
    { ja: '打ち込み', en: 'SEQUENCING' }, { ja: 'ダンス', en: 'DANCE' }, { ja: '盆踊り', en: 'BON DANCE' },
    { ja: 'よさこい', en: 'YOSAKOI' }, { ja: '阿波踊り', en: 'AWA DANCE' }, { ja: '社交ダンス', en: 'BALLROOM DANCE' },
    { ja: 'タップダンス', en: 'TAP DANCE' }, { ja: 'チアダンス', en: 'CHEER DANCE' }, { ja: 'リズム体操', en: 'RHYTHM EXERCISE' },
    { ja: '手拍子', en: 'HAND CLAPPING' }, { ja: 'カラオケ', en: 'KARAOKE' }, { ja: '発声練習', en: 'VOICE TRAINING' },
    { ja: '口笛', en: 'WHISTLING' }, { ja: '鼻歌', en: 'HUMMING' },

    { ja: '落ち物', en: 'FALLING BLOCKS' }, { ja: 'ブロック消し', en: 'BLOCK BREAKING' }, { ja: '連鎖', en: 'CHAIN REACTION' },
    { ja: '数独', en: 'SUDOKU' }, { ja: 'クロスワード', en: 'CROSSWORD' }, { ja: 'ことば探し', en: 'WORD SEARCH' },
    { ja: 'しりとり', en: 'SHIRITORI' }, { ja: 'ジグソーパズル', en: 'JIGSAW PUZZLE' }, { ja: '絵合わせ', en: 'PICTURE MATCHING' },
    { ja: '間違い探し', en: 'SPOT THE DIFFERENCE' }, { ja: '迷路', en: 'MAZE' }, { ja: '知恵の輪', en: 'DISENTANGLEMENT PUZZLE' },
    { ja: '立体パズル', en: 'SOLID PUZZLE' }, { ja: 'スライドパズル', en: 'SLIDING PUZZLE' }, { ja: '積み木', en: 'BUILDING BLOCKS' },
    { ja: '一筆書き', en: 'UNICURSAL DRAWING' }, { ja: '塗り分け', en: 'MAP COLORING' }, { ja: 'お絵かきロジック', en: 'PICTURE LOGIC' },
    { ja: '数字並べ', en: 'NUMBER ORDERING' }, { ja: '色合わせ', en: 'COLOR MATCHING' }, { ja: '玉転がし', en: 'BALL ROLLING' },
    { ja: '玉落とし', en: 'BALL DROP' }, { ja: '歯車', en: 'GEARWORK' }, { ja: '配管', en: 'PIPELINE' },
    { ja: '水路', en: 'WATERWAY' }, { ja: '光線反射', en: 'LIGHT REFLECTION' }, { ja: '重力', en: 'GRAVITY' },
    { ja: '天秤', en: 'BALANCE SCALE' }, { ja: 'ドミノ倒し', en: 'DOMINO TOPPLING' }, { ja: '荷物押し', en: 'CRATE PUSHING' },
    { ja: '陣取り', en: 'TERRITORY CLAIM' }, { ja: '石積み', en: 'STONE STACKING' }, { ja: '橋渡し', en: 'BRIDGE BUILDING' },
    { ja: '論理パズル', en: 'LOGIC PUZZLE' }, { ja: '図形合わせ', en: 'SHAPE FITTING' }, { ja: '数当て', en: 'NUMBER GUESSING' },
    { ja: '言葉づくり', en: 'WORD BUILDING' }, { ja: '漢字パズル', en: 'KANJI PUZZLE' }, { ja: '立体迷路', en: 'SOLID MAZE' },

    { ja: '探偵', en: 'DETECTIVE' }, { ja: '名探偵', en: 'GREAT DETECTIVE' }, { ja: '事件簿', en: 'CASE FILES' },
    { ja: '密室', en: 'LOCKED ROOM' }, { ja: '不在証明', en: 'ALIBI' }, { ja: '証言', en: 'TESTIMONY' },
    { ja: '尋問', en: 'INTERROGATION' }, { ja: '捜査', en: 'INVESTIGATION' }, { ja: '鑑識', en: 'FORENSICS' },
    { ja: '刑事', en: 'INSPECTOR' }, { ja: '法廷', en: 'COURTROOM' }, { ja: '弁護', en: 'DEFENSE PLEA' },
    { ja: '裁判', en: 'TRIAL' }, { ja: '目撃者', en: 'WITNESS' }, { ja: '容疑者', en: 'SUSPECT' },
    { ja: '動機', en: 'MOTIVE' }, { ja: '犯行現場', en: 'CRIME SCENE' }, { ja: '暗号解読', en: 'CODE BREAKING' },
    { ja: '謎解き', en: 'RIDDLE SOLVING' }, { ja: '館脱出', en: 'MANSION ESCAPE' }, { ja: '廃屋探索', en: 'DERELICT SEARCH' },
    { ja: '心霊調査', en: 'PARANORMAL INQUIRY' }, { ja: '都市伝説', en: 'URBAN LEGEND' }, { ja: '怪奇現象', en: 'STRANGE PHENOMENA' },
    { ja: '妖怪', en: 'YOKAI' }, { ja: '幽霊屋敷', en: 'HAUNTED HOUSE' }, { ja: '失踪', en: 'DISAPPEARANCE' },
    { ja: '追跡', en: 'PURSUIT' }, { ja: '潜入', en: 'INFILTRATION' }, { ja: '変装', en: 'DISGUISE' },
    { ja: '怪盗', en: 'PHANTOM THIEF' }, { ja: '予告状', en: 'CALLING CARD' }, { ja: '尾行', en: 'TAILING' },

    { ja: '鉄道', en: 'RAILWAY' }, { ja: '新幹線', en: 'BULLET TRAIN' }, { ja: '蒸気機関車', en: 'STEAM LOCOMOTIVE' },
    { ja: '路面電車', en: 'TRAM' }, { ja: '地下鉄', en: 'SUBWAY' }, { ja: '貨物列車', en: 'FREIGHT TRAIN' },
    { ja: '寝台列車', en: 'SLEEPER TRAIN' }, { ja: '路線バス', en: 'ROUTE BUS' }, { ja: '観光バス', en: 'TOUR BUS' },
    { ja: 'トラック', en: 'TRUCK' }, { ja: 'タクシー', en: 'TAXI' }, { ja: '消防車', en: 'FIRE ENGINE' },
    { ja: '救急車', en: 'AMBULANCE' }, { ja: 'パトカー', en: 'PATROL CAR' }, { ja: '除雪車', en: 'SNOWPLOW' },
    { ja: 'ショベルカー', en: 'EXCAVATOR' }, { ja: 'ブルドーザー', en: 'BULLDOZER' }, { ja: 'クレーン車', en: 'CRANE TRUCK' },
    { ja: 'トラクター', en: 'TRACTOR' }, { ja: '耕運機', en: 'CULTIVATOR' }, { ja: 'フォークリフト', en: 'FORKLIFT' },
    { ja: 'ゴミ収集車', en: 'GARBAGE TRUCK' }, { ja: '飛行機', en: 'AIRPLANE' }, { ja: '旅客機', en: 'AIRLINER' },
    { ja: 'ヘリコプター', en: 'HELICOPTER' }, { ja: '気球', en: 'HOT AIR BALLOON' }, { ja: '飛行船', en: 'AIRSHIP' },
    { ja: 'グライダー', en: 'GLIDER' }, { ja: 'ロケット', en: 'ROCKET' }, { ja: '宇宙船', en: 'SPACECRAFT' },
    { ja: '宇宙基地', en: 'SPACE STATION' }, { ja: '潜水艦', en: 'SUBMARINE' }, { ja: '潜水艇', en: 'SUBMERSIBLE' },
    { ja: '客船', en: 'PASSENGER SHIP' }, { ja: '帆船', en: 'SAILING SHIP' }, { ja: '貨物船', en: 'CARGO SHIP' },
    { ja: '漁船', en: 'FISHING BOAT' }, { ja: '渡し船', en: 'FERRYBOAT' }, { ja: 'カート', en: 'GO KART' },
    { ja: 'ラリーカー', en: 'RALLY CAR' }, { ja: 'レーシングカー', en: 'RACING CAR' }, { ja: 'オートバイ', en: 'MOTORCYCLE' },
    { ja: 'スクーター', en: 'SCOOTER' }, { ja: '自転車', en: 'BICYCLE' }, { ja: '一輪車', en: 'UNICYCLE' },
    { ja: '人力車', en: 'RICKSHAW' }, { ja: '荷馬車', en: 'HORSE CART' },

    { ja: '子犬', en: 'PUPPY' }, { ja: '子猫', en: 'KITTEN' }, { ja: 'ウサギ', en: 'RABBIT' },
    { ja: 'ハムスター', en: 'HAMSTER' }, { ja: 'モルモット', en: 'GUINEA PIG' }, { ja: '小鳥', en: 'SMALL BIRD' },
    { ja: 'インコ', en: 'PARAKEET' }, { ja: '文鳥', en: 'JAVA SPARROW' }, { ja: '金魚', en: 'GOLDFISH' },
    { ja: 'メダカ', en: 'KILLIFISH' }, { ja: '熱帯魚', en: 'TROPICAL FISH' }, { ja: '亀', en: 'TURTLE' },
    { ja: 'カブトムシ', en: 'RHINOCEROS BEETLE' }, { ja: 'クワガタ', en: 'STAG BEETLE' }, { ja: '蝶', en: 'BUTTERFLY' },
    { ja: '蜜蜂', en: 'HONEYBEE' }, { ja: '蟻', en: 'ANT' }, { ja: '蛍', en: 'FIREFLY' },
    { ja: '鈴虫', en: 'BELL CRICKET' }, { ja: '馬', en: 'HORSE' }, { ja: '牛', en: 'COW' },
    { ja: '羊', en: 'SHEEP' }, { ja: '山羊', en: 'GOAT' }, { ja: '豚', en: 'PIG' },
    { ja: '鶏', en: 'CHICKEN' }, { ja: 'アヒル', en: 'DUCK' }, { ja: 'ペンギン', en: 'PENGUIN' },
    { ja: 'イルカ', en: 'DOLPHIN' }, { ja: 'クジラ', en: 'WHALE' }, { ja: 'アザラシ', en: 'SEAL' },
    { ja: 'ラッコ', en: 'SEA OTTER' }, { ja: 'パンダ', en: 'PANDA' }, { ja: 'コアラ', en: 'KOALA' },
    { ja: 'カンガルー', en: 'KANGAROO' }, { ja: 'ゾウ', en: 'ELEPHANT' }, { ja: 'キリン', en: 'GIRAFFE' },
    { ja: 'ライオン', en: 'LION' }, { ja: 'サル', en: 'MONKEY' }, { ja: 'リス', en: 'SQUIRREL' },
    { ja: 'キツネ', en: 'FOX' }, { ja: 'タヌキ', en: 'RACCOON DOG' }, { ja: 'フクロウ', en: 'OWL' },
    { ja: 'ハリネズミ', en: 'HEDGEHOG' }, { ja: '恐竜', en: 'DINOSAUR' }, { ja: '深海魚', en: 'DEEP SEA FISH' },
    { ja: 'サメ', en: 'SHARK' }, { ja: 'クラゲ', en: 'JELLYFISH' }, { ja: 'ヤドカリ', en: 'HERMIT CRAB' },
    { ja: 'カニ', en: 'CRAB' }, { ja: '野鳥', en: 'WILD BIRDS' },

    { ja: '和食', en: 'JAPANESE CUISINE' }, { ja: '洋食', en: 'WESTERN CUISINE' }, { ja: '中華料理', en: 'CHINESE CUISINE' },
    { ja: '家庭料理', en: 'HOME COOKING' }, { ja: 'お弁当', en: 'BENTO' }, { ja: '朝ごはん', en: 'BREAKFAST' },
    { ja: 'パン作り', en: 'BREAD MAKING' }, { ja: 'ケーキ作り', en: 'CAKE MAKING' }, { ja: 'お菓子作り', en: 'CONFECTIONERY' },
    { ja: '和菓子', en: 'JAPANESE SWEETS' }, { ja: '飴細工', en: 'CANDY CRAFT' }, { ja: 'チョコレート', en: 'CHOCOLATE' },
    { ja: 'アイスクリーム', en: 'ICE CREAM' }, { ja: 'ジャム作り', en: 'JAM MAKING' }, { ja: '漬物', en: 'PICKLES' },
    { ja: '味噌作り', en: 'MISO MAKING' }, { ja: '出汁', en: 'BROTH' }, { ja: '鍋料理', en: 'HOT POT' },
    { ja: '焼き鳥', en: 'YAKITORI' }, { ja: '串揚げ', en: 'KUSHIAGE' }, { ja: '天ぷら', en: 'TEMPURA' },
    { ja: '寿司握り', en: 'SUSHI MAKING' }, { ja: '蕎麦打ち', en: 'SOBA MAKING' }, { ja: 'うどん打ち', en: 'UDON MAKING' },
    { ja: 'ラーメン作り', en: 'RAMEN MAKING' }, { ja: 'カレー', en: 'CURRY' }, { ja: 'オムライス', en: 'OMURICE' },
    { ja: 'ハンバーグ', en: 'HAMBURG STEAK' }, { ja: '餃子', en: 'GYOZA' }, { ja: 'パスタ', en: 'PASTA' },
    { ja: 'ピザ', en: 'PIZZA' }, { ja: '焼き菓子', en: 'BAKED SWEETS' }, { ja: 'バーベキュー', en: 'BARBECUE' },
    { ja: '燻製', en: 'SMOKED FOOD' }, { ja: '保存食', en: 'PRESERVED FOOD' }, { ja: '発酵', en: 'FERMENTATION' },
    { ja: '珈琲焙煎', en: 'COFFEE ROASTING' }, { ja: '紅茶', en: 'BLACK TEA' }, { ja: '茶道', en: 'TEA CEREMONY' },
    { ja: '郷土料理', en: 'REGIONAL CUISINE' }, { ja: '精進料理', en: 'TEMPLE CUISINE' }, { ja: '駅弁', en: 'STATION BENTO' },

    { ja: '庭づくり', en: 'GARDEN MAKING' }, { ja: '花壇', en: 'FLOWER BED' }, { ja: '家庭菜園', en: 'KITCHEN GARDEN' },
    { ja: '盆栽', en: 'BONSAI' }, { ja: '苔玉', en: 'MOSS BALL' }, { ja: '多肉植物', en: 'SUCCULENTS' },
    { ja: '観葉植物', en: 'FOLIAGE PLANTS' }, { ja: '蘭', en: 'ORCHID' }, { ja: '薔薇', en: 'ROSE' },
    { ja: '朝顔', en: 'MORNING GLORY' }, { ja: '向日葵', en: 'SUNFLOWER' }, { ja: 'チューリップ', en: 'TULIP' },
    { ja: '紫陽花', en: 'HYDRANGEA' }, { ja: '桜', en: 'CHERRY BLOSSOM' }, { ja: '紅葉', en: 'AUTUMN LEAVES' },
    { ja: '山野草', en: 'WILD FLOWERS' }, { ja: 'ハーブ', en: 'HERBS' }, { ja: '球根', en: 'FLOWER BULBS' },
    { ja: '種まき', en: 'SOWING' }, { ja: '挿し木', en: 'CUTTINGS' }, { ja: '剪定', en: 'PRUNING' },
    { ja: '芝生', en: 'LAWN' }, { ja: '生垣', en: 'HEDGE' }, { ja: '温室', en: 'GREENHOUSE' },
    { ja: '水耕栽培', en: 'HYDROPONICS' }, { ja: 'きのこ栽培', en: 'MUSHROOM GROWING' }, { ja: '稲作', en: 'RICE GROWING' },
    { ja: '麦畑', en: 'WHEAT FIELD' }, { ja: '茶畑', en: 'TEA FIELD' }, { ja: '蜜柑畑', en: 'CITRUS GROVE' },
    { ja: '葡萄畑', en: 'VINEYARD' }, { ja: '苗木', en: 'SAPLING' }, { ja: '押し花', en: 'PRESSED FLOWERS' },
    { ja: '生け花', en: 'IKEBANA' },

    { ja: '写真', en: 'PHOTOGRAPHY' }, { ja: '風景写真', en: 'LANDSCAPE PHOTO' }, { ja: '野鳥撮影', en: 'BIRD PHOTOGRAPHY' },
    { ja: '星空撮影', en: 'ASTROPHOTOGRAPHY' }, { ja: '水中撮影', en: 'UNDERWATER PHOTO' }, { ja: '現像', en: 'FILM DEVELOPING' },
    { ja: '絵画', en: 'PAINTING' }, { ja: '水彩', en: 'WATERCOLOR' }, { ja: '油彩', en: 'OIL PAINTING' },
    { ja: '版画', en: 'PRINTMAKING' }, { ja: '切り絵', en: 'PAPER CUTTING' }, { ja: '折り紙', en: 'ORIGAMI' },
    { ja: '陶芸', en: 'POTTERY' }, { ja: '彫刻', en: 'SCULPTURE' }, { ja: '手芸', en: 'HANDICRAFT' },
    { ja: '編み物', en: 'KNITTING' }, { ja: '刺繍', en: 'EMBROIDERY' }, { ja: '裁縫', en: 'SEWING' },
    { ja: '染物', en: 'DYEING' }, { ja: '人形作り', en: 'DOLL MAKING' }, { ja: '模型', en: 'SCALE MODEL' },
    { ja: '鉄道模型', en: 'MODEL RAILWAY' }, { ja: 'ジオラマ', en: 'DIORAMA' }, { ja: 'ドールハウス', en: 'DOLLHOUSE' },
    { ja: '大工', en: 'CARPENTRY' }, { ja: '日曜大工', en: 'HOME WORKSHOP' }, { ja: '家具作り', en: 'FURNITURE MAKING' },
    { ja: 'ロボット工作', en: 'ROBOT BUILDING' }, { ja: '電子工作', en: 'ELECTRONICS CRAFT' }, { ja: '紙工作', en: 'PAPER CRAFT' },
    { ja: '万華鏡', en: 'KALEIDOSCOPE' }, { ja: '漫画', en: 'COMICS' }, { ja: '絵本', en: 'PICTURE BOOK' },
    { ja: 'アニメ制作', en: 'ANIMATION' }, { ja: '演劇', en: 'DRAMA' }, { ja: '落語', en: 'RAKUGO' },
    { ja: '漫才', en: 'MANZAI' }, { ja: '手品', en: 'MAGIC TRICKS' }, { ja: '大道芸', en: 'STREET PERFORMANCE' },
    { ja: 'ジャグリング', en: 'JUGGLING' }, { ja: '人形劇', en: 'PUPPET SHOW' }, { ja: '影絵', en: 'SHADOW PLAY' },
    { ja: '紙芝居', en: 'PAPER THEATER' }, { ja: '新聞作り', en: 'NEWSPAPER MAKING' }, { ja: '映画作り', en: 'FILM MAKING' },
    { ja: '小説執筆', en: 'NOVEL WRITING' }, { ja: '詩作', en: 'POETRY' },

    { ja: 'キャンプ', en: 'CAMPING' }, { ja: '焚き火', en: 'CAMPFIRE' }, { ja: '秘密基地', en: 'SECRET BASE' },
    { ja: '宝探し', en: 'TREASURE HUNT' }, { ja: '化石発掘', en: 'FOSSIL DIGGING' }, { ja: '遺跡発掘', en: 'EXCAVATION' },
    { ja: '昆虫採集', en: 'INSECT COLLECTING' }, { ja: '川遊び', en: 'RIVER PLAY' }, { ja: '海水浴', en: 'SEA BATHING' },
    { ja: '潮干狩り', en: 'CLAM DIGGING' }, { ja: '花火', en: 'FIREWORKS' }, { ja: '祭り', en: 'FESTIVAL' },
    { ja: '縁日', en: 'FAIR NIGHT' }, { ja: '初詣', en: 'NEW YEAR VISIT' }, { ja: '節分', en: 'SETSUBUN' },
    { ja: '雛祭り', en: 'DOLL FESTIVAL' }, { ja: '七夕', en: 'TANABATA' }, { ja: '月見', en: 'MOON VIEWING' },
    { ja: '餅つき', en: 'MOCHI POUNDING' }, { ja: '年賀状', en: 'NEW YEAR CARD' }, { ja: '運動会', en: 'SPORTS DAY' },
    { ja: '文化祭', en: 'SCHOOL FESTIVAL' }, { ja: '修学旅行', en: 'SCHOOL TRIP' }, { ja: '遠足', en: 'FIELD TRIP' },
    { ja: '林間学校', en: 'NATURE SCHOOL' }, { ja: '臨海学校', en: 'SEASIDE SCHOOL' }, { ja: '部活動', en: 'CLUB ACTIVITY' },
    { ja: '生徒会', en: 'STUDENT COUNCIL' }, { ja: '学級会', en: 'CLASS MEETING' }, { ja: '掃除当番', en: 'CLEANING DUTY' },
    { ja: '通学路', en: 'SCHOOL ROUTE' }, { ja: '保健室', en: 'NURSE ROOM' }, { ja: '屋上', en: 'ROOFTOP' },
    { ja: '放課後', en: 'AFTER SCHOOL' }, { ja: '転校生', en: 'TRANSFER STUDENT' }, { ja: '文通', en: 'PEN PALS' },
    { ja: 'おつかい', en: 'ERRAND' }, { ja: '郵便配達', en: 'MAIL DELIVERY' }, { ja: '新聞配達', en: 'NEWSPAPER DELIVERY' },
    { ja: '宅配', en: 'PARCEL DELIVERY' }, { ja: '道案内', en: 'GIVING DIRECTIONS' }, { ja: '観光案内', en: 'TOUR GUIDING' },
    { ja: '通訳', en: 'INTERPRETING' }, { ja: '看護', en: 'NURSING' }, { ja: '介護', en: 'CAREGIVING' },
    { ja: '保育', en: 'CHILDCARE' }, { ja: '美容師', en: 'HAIRDRESSING' }, { ja: 'ネイル', en: 'NAIL ART' },
    { ja: '着付け', en: 'KIMONO DRESSING' }, { ja: '洋裁', en: 'DRESSMAKING' }, { ja: '靴修理', en: 'SHOE REPAIR' },
    { ja: '時計修理', en: 'WATCH REPAIR' }, { ja: '便利屋', en: 'ODD JOBS' }, { ja: '山岳救助', en: 'MOUNTAIN RESCUE' },
    { ja: '灯台守', en: 'LIGHTHOUSE KEEPER' }, { ja: '車掌', en: 'TRAIN CONDUCTOR' }, { ja: '駅員', en: 'STATION STAFF' },
    { ja: '船長', en: 'SHIP CAPTAIN' }, { ja: '消防士', en: 'FIREFIGHTER' }, { ja: '森林保全', en: 'FOREST CONSERVATION' },
    { ja: '気象観測', en: 'WEATHER OBSERVATION' }, { ja: '南極観測', en: 'ANTARCTIC EXPEDITION' }, { ja: '無人島生活', en: 'DESERT ISLAND LIFE' },
    { ja: '世界一周', en: 'ROUND THE WORLD' }, { ja: '巡礼', en: 'PILGRIMAGE' }, { ja: '温泉巡り', en: 'HOT SPRING TOUR' },
    { ja: '城巡り', en: 'CASTLE TOUR' }, { ja: '切手収集', en: 'STAMP COLLECTING' }, { ja: '硬貨収集', en: 'COIN COLLECTING' },
    { ja: '標本作り', en: 'SPECIMEN MAKING' }, { ja: '天文台', en: 'OBSERVATORY' },

    { ja: '勇者', en: 'HERO' }, { ja: '魔王', en: 'DEMON LORD' }, { ja: '賢者', en: 'SAGE' },
    { ja: '騎士', en: 'KNIGHT' }, { ja: '聖剣', en: 'HOLY SWORD' }, { ja: '魔剣', en: 'CURSED BLADE' },
    { ja: '魔法', en: 'MAGIC' }, { ja: '呪文', en: 'SPELL' }, { ja: '魔導書', en: 'GRIMOIRE' },
    { ja: '錬金術', en: 'ALCHEMY' }, { ja: '精霊', en: 'SPIRIT' }, { ja: '幻獣', en: 'PHANTOM BEAST' },
    { ja: '竜騎士', en: 'DRAGOON' }, { ja: '城塞', en: 'CITADEL' }, { ja: '迷宮', en: 'LABYRINTH' },
    { ja: '地下迷宮', en: 'DUNGEON' }, { ja: '冒険者', en: 'ADVENTURER' }, { ja: 'ギルド', en: 'GUILD' },
    { ja: '神殿', en: 'TEMPLE' }, { ja: '祭壇', en: 'ALTAR' }, { ja: '封印', en: 'SEALING' },
    { ja: '予言', en: 'PROPHECY' }, { ja: '王家', en: 'ROYAL HOUSE' }, { ja: '帝国', en: 'EMPIRE' },
    { ja: '反乱軍', en: 'REBEL ARMY' }, { ja: '傭兵', en: 'MERCENARY' }, { ja: '暗殺者', en: 'ASSASSIN' },
    { ja: '弓兵', en: 'ARCHER UNIT' }, { ja: '僧侶', en: 'CLERIC' }, { ja: '盗賊', en: 'THIEF' },
    { ja: '聖女', en: 'SAINTESS' }, { ja: '巫女', en: 'SHRINE MAIDEN' }, { ja: '剣士', en: 'SWORDSMAN' },
    { ja: '秘宝', en: 'TREASURE RELIC' }, { ja: '古代文明', en: 'ANCIENT CIVILIZATION' }, { ja: '異世界', en: 'OTHER WORLD' },
    { ja: '結界', en: 'WARD BARRIER' }, { ja: '星読み', en: 'STAR READING' }, { ja: '召喚', en: 'SUMMONING' },
    { ja: '使い魔', en: 'FAMILIAR' }, { ja: '呪術', en: 'CURSE ARTS' }, { ja: '魔石', en: 'MAGIC STONE' },
    { ja: '霊峰', en: 'SACRED PEAK' }, { ja: '天空城', en: 'SKY CASTLE' }, { ja: '浮遊島', en: 'FLOATING ISLE' },
    { ja: '竜の巣', en: 'DRAGON NEST' }, { ja: '剣豪', en: 'MASTER SWORDSMAN' }, { ja: '忍者', en: 'NINJA' },
    { ja: '侍', en: 'SAMURAI' }, { ja: '陰陽師', en: 'ONMYOJI' }, { ja: '妖術', en: 'SORCERY' },
    { ja: '戦国', en: 'WARRING STATES' }, { ja: '合戦', en: 'PITCHED BATTLE' }, { ja: '城攻め', en: 'SIEGE' },
    { ja: '軍師', en: 'WAR STRATEGIST' }, { ja: '忍法', en: 'NINJA ARTS' }, { ja: '魔物', en: 'MONSTER' },
    { ja: '遺跡探索', en: 'RUIN DELVING' }, { ja: '宝箱', en: 'TREASURE CHEST' }, { ja: '呪われた森', en: 'CURSED FOREST' },
    { ja: '氷の城', en: 'ICE CASTLE' }, { ja: '炎の山', en: 'FLAME MOUNTAIN' }, { ja: '海底神殿', en: 'SUNKEN SHRINE' },
    { ja: '天界', en: 'HEAVENS' }, { ja: '魔界', en: 'NETHERWORLD' }, { ja: '精霊樹', en: 'SPIRIT TREE' },
    { ja: '賢者の塔', en: 'SAGE TOWER' }, { ja: '王女', en: 'PRINCESS' }, { ja: '王子', en: 'PRINCE' },
    { ja: '竜の卵', en: 'DRAGON EGG' }, { ja: '魔法学園', en: 'MAGIC ACADEMY' }, { ja: '錬金工房', en: 'ALCHEMY ATELIER' },
    { ja: '冒険酒場', en: 'ADVENTURER TAVERN' }, { ja: '聖杯', en: 'HOLY GRAIL' }, { ja: '銀の鎧', en: 'SILVER ARMOR' },
    { ja: '竜脈', en: 'DRAGON VEIN' }, { ja: '魔法陣', en: 'MAGIC CIRCLE' }, { ja: '神託', en: 'ORACLE' },
    { ja: '呪印', en: 'CURSE MARK' }
  ],
  category: [
    { ja: '伝説', en: 'LEGEND' }, { ja: '物語', en: 'TALE' }, { ja: '大冒険', en: 'GRAND ADVENTURE' },
    { ja: '冒険記', en: 'ADVENTURE LOG' }, { ja: 'クロニクル', en: 'CHRONICLE' }, { ja: '紀行', en: 'TRAVELOGUE' },
    { ja: '日誌', en: 'JOURNAL' }, { ja: '手帖', en: 'POCKETBOOK' }, { ja: '図鑑', en: 'PICTORIAL BOOK' },
    { ja: '大全', en: 'COMPENDIUM' }, { ja: '事典', en: 'DICTIONARY' }, { ja: '名鑑', en: 'DIRECTORY' },
    { ja: '番付', en: 'RANKING LIST' }, { ja: '名人戦', en: 'MASTERS SERIES' }, { ja: '選手権', en: 'CHAMPIONSHIP' },
    { ja: '大会', en: 'TOURNAMENT' }, { ja: '全国大会', en: 'NATIONAL MEET' }, { ja: '王座戦', en: 'TITLE MATCH' },
    { ja: '決勝戦', en: 'FINAL MATCH' }, { ja: 'リーグ', en: 'LEAGUE' }, { ja: 'カップ', en: 'CUP' },
    { ja: 'トロフィー', en: 'TROPHY' }, { ja: 'グランプリ', en: 'GRAND PRIX' }, { ja: 'ダービー', en: 'DERBY' },
    { ja: 'マッチ', en: 'MATCH' }, { ja: 'バトル', en: 'BATTLE' }, { ja: '対局', en: 'BOARD MATCH' },
    { ja: '対戦', en: 'VERSUS' }, { ja: '勝負', en: 'SHOWDOWN' }, { ja: '挑戦', en: 'CHALLENGE' },
    { ja: '修行', en: 'TRAINING' }, { ja: '特訓', en: 'INTENSIVE TRAINING' }, { ja: '道場', en: 'DOJO' },
    { ja: '教室', en: 'CLASSROOM' }, { ja: '塾', en: 'CRAM SCHOOL' }, { ja: '学園', en: 'ACADEMY' },
    { ja: '学校', en: 'SCHOOL' }, { ja: '講座', en: 'COURSE' }, { ja: '入門', en: 'PRIMER' },
    { ja: '手引き', en: 'HANDBOOK' }, { ja: '極意', en: 'SECRETS' }, { ja: '奥義', en: 'ULTIMATE ARTS' },
    { ja: '免許皆伝', en: 'FULL MASTERY' }, { ja: '段位', en: 'GRADE RANK' }, { ja: '検定', en: 'CERTIFICATION' },
    { ja: '試験', en: 'EXAMINATION' }, { ja: 'ドリル', en: 'DRILL' }, { ja: '練習帳', en: 'WORKBOOK' },
    { ja: '問題集', en: 'PROBLEM BOOK' }, { ja: '総復習', en: 'FULL REVIEW' },

    { ja: 'クエスト', en: 'QUEST' }, { ja: '探検', en: 'EXPLORATION' }, { ja: '探検隊', en: 'EXPEDITION TEAM' },
    { ja: '遠征', en: 'CAMPAIGN' }, { ja: '旅', en: 'JOURNEY' }, { ja: '大航海', en: 'GREAT VOYAGE' },
    { ja: '航海記', en: 'VOYAGE LOG' }, { ja: '漂流記', en: 'CASTAWAY LOG' }, { ja: '巡り', en: 'TOUR' },
    { ja: '道中', en: 'WAYFARING' }, { ja: '街道', en: 'HIGHWAY' }, { ja: '横断', en: 'CROSSING' },
    { ja: '一周', en: 'CIRCUIT' }, { ja: '発見', en: 'DISCOVERY' }, { ja: '調査団', en: 'SURVEY TEAM' },
    { ja: '観察日記', en: 'OBSERVATION DIARY' }, { ja: '研究所', en: 'LABORATORY' }, { ja: '実験室', en: 'EXPERIMENT ROOM' },
    { ja: '工房', en: 'ATELIER' }, { ja: '製作所', en: 'WORKS' }, { ja: '作業場', en: 'WORKSHOP' },
    { ja: '倉庫', en: 'WAREHOUSE' }, { ja: '商会', en: 'TRADING HOUSE' }, { ja: 'バザール', en: 'BAZAAR' },
    { ja: '屋台村', en: 'STALL VILLAGE' }, { ja: '喫茶室', en: 'TEA ROOM' }, { ja: '酒場', en: 'TAVERN' },
    { ja: '宿', en: 'INN' }, { ja: '湯屋', en: 'BATH HALL' }, { ja: '温泉郷', en: 'SPA TOWN' },
    { ja: '別荘', en: 'VILLA' }, { ja: '屋敷', en: 'MANSION' }, { ja: '御殿', en: 'PALACE' },
    { ja: '城', en: 'CASTLE' }, { ja: '砦', en: 'FORTRESS' }, { ja: '塔', en: 'TOWER' },
    { ja: '灯台', en: 'LIGHTHOUSE' }, { ja: '神社', en: 'SHRINE' }, { ja: '寺', en: 'MONASTERY' },
    { ja: '教会', en: 'CHURCH' }, { ja: '洞窟', en: 'CAVERN' }, { ja: '森', en: 'WOODS' },
    { ja: '島', en: 'ISLE' }, { ja: '岬', en: 'CAPE' }, { ja: '港', en: 'PORT' },
    { ja: '谷', en: 'VALLEY' }, { ja: '高原', en: 'PLATEAU' }, { ja: '山脈', en: 'RANGE' },
    { ja: '砂漠', en: 'DESERT' }, { ja: '氷原', en: 'ICEFIELD' }, { ja: '湿原', en: 'MARSH' },
    { ja: '草原', en: 'GRASSLAND' }, { ja: '湖畔', en: 'LAKESIDE' }, { ja: '河口', en: 'ESTUARY' },
    { ja: '海岸', en: 'COAST' }, { ja: '浜辺', en: 'BEACH' }, { ja: '町', en: 'TOWNSHIP' },
    { ja: '村', en: 'VILLAGE' }, { ja: '里', en: 'HOMELAND' }, { ja: '都', en: 'CAPITAL' },
    { ja: '都市', en: 'CITY' }, { ja: '王国', en: 'KINGDOM' }, { ja: '公国', en: 'PRINCIPALITY' },
    { ja: '共和国', en: 'REPUBLIC' }, { ja: '連邦', en: 'FEDERATION' }, { ja: '領地', en: 'FIEF' },
    { ja: '世界', en: 'WORLD' }, { ja: '惑星', en: 'PLANET' }, { ja: '宇宙', en: 'UNIVERSE' },
    { ja: '星系', en: 'STAR SYSTEM' }, { ja: '次元', en: 'DIMENSION' }, { ja: '領域', en: 'REALM' },
    { ja: '楽園', en: 'PARADISE' }, { ja: '桃源郷', en: 'UTOPIA' }, { ja: '秘境', en: 'HINTERLAND' },
    { ja: '辺境', en: 'FRONTIER' }, { ja: '未踏地', en: 'UNTRODDEN LAND' },

    { ja: 'パーク', en: 'PARK' }, { ja: 'ランド', en: 'LAND' }, { ja: 'アイランド', en: 'ISLAND' },
    { ja: 'タウン', en: 'TOWN' }, { ja: 'スタジアム', en: 'STADIUM' }, { ja: 'アリーナ', en: 'ARENA' },
    { ja: 'コロシアム', en: 'COLOSSEUM' }, { ja: 'リンク', en: 'RINK' }, { ja: 'コート', en: 'COURT' },
    { ja: 'グラウンド', en: 'GROUND' }, { ja: '球場', en: 'BALLPARK' }, { ja: '道', en: 'THE WAY' },

    { ja: 'コレクション', en: 'COLLECTION' }, { ja: 'セレクション', en: 'SELECTION' }, { ja: 'アンソロジー', en: 'ANTHOLOGY' },
    { ja: 'アーカイブ', en: 'ARCHIVE' }, { ja: 'ボックス', en: 'BOX' }, { ja: 'パック', en: 'PACK' },
    { ja: 'セット', en: 'SET' }, { ja: '詰め合わせ', en: 'ASSORTMENT' },

    { ja: '祭典', en: 'GALA' }, { ja: '博覧会', en: 'EXPO' }, { ja: '見本市', en: 'TRADE FAIR' },
    { ja: '品評会', en: 'SHOW CONTEST' }, { ja: '発表会', en: 'RECITAL' }, { ja: '演奏会', en: 'CONCERT' },

    { ja: '記録', en: 'RECORD' }, { ja: '日記', en: 'DIARY' }, { ja: '手記', en: 'MEMOIR' },
    { ja: '覚書', en: 'MEMORANDUM' }, { ja: '台帳', en: 'REGISTER' }, { ja: '名簿', en: 'ROSTER' },
    { ja: '書簡', en: 'LETTERS' },

    { ja: '奮闘記', en: 'STRUGGLE LOG' }, { ja: '繁盛記', en: 'PROSPERITY LOG' }, { ja: '開拓記', en: 'PIONEER LOG' },
    { ja: '経営', en: 'MANAGEMENT' }, { ja: '開拓', en: 'PIONEERING' }, { ja: '復興', en: 'RECONSTRUCTION' },
    { ja: '建設', en: 'CONSTRUCTION' }, { ja: '育成', en: 'NURTURING' }, { ja: '飼育', en: 'BREEDING' },
    { ja: '栽培', en: 'CULTIVATION' }, { ja: '収穫', en: 'HARVEST' }, { ja: '生活', en: 'LIFE' },
    { ja: '暮らし', en: 'LIVING' }, { ja: '日常', en: 'EVERYDAY' }, { ja: '一日', en: 'ONE DAY' },
    { ja: '四季', en: 'FOUR SEASONS' }, { ja: '十二か月', en: 'TWELVE MONTHS' }, { ja: '一年', en: 'ONE YEAR' },
    { ja: '三代記', en: 'THREE GENERATIONS' }, { ja: '一族', en: 'CLAN' }, { ja: '家族', en: 'FAMILY' },
    { ja: '仲間', en: 'COMPANIONS' }, { ja: '友情', en: 'FRIENDSHIP' }, { ja: '青春', en: 'YOUTH DAYS' },
    { ja: '卒業', en: 'GRADUATION' },

    { ja: '革命', en: 'REVOLUTION' }, { ja: '維新', en: 'RESTORATION' }, { ja: '争奪戦', en: 'SCRAMBLE' },
    { ja: '攻防', en: 'ATTACK AND DEFENSE' }, { ja: '逆転', en: 'REVERSAL' }, { ja: '大逆転', en: 'GRAND REVERSAL' },
    { ja: '下剋上', en: 'UPSET' },

    { ja: '騒動', en: 'COMMOTION' }, { ja: '珍道中', en: 'COMIC JOURNEY' }, { ja: '大作戦', en: 'GRAND OPERATION' },
    { ja: '作戦', en: 'OPERATION' }, { ja: '計画', en: 'PLAN' }, { ja: '陰謀', en: 'CONSPIRACY' },
    { ja: '事件', en: 'INCIDENT' }, { ja: '事変', en: 'AFFAIR' }, { ja: '秘密', en: 'SECRET' },
    { ja: '謎', en: 'MYSTERY' }, { ja: '真実', en: 'TRUTH' },

    { ja: '教本', en: 'TEXTBOOK' }, { ja: '読本', en: 'READER' }, { ja: '絵日記', en: 'PICTURE DIARY' },
    { ja: '図解', en: 'ILLUSTRATED GUIDE' },

    { ja: '放浪記', en: 'WANDERING LOG' }, { ja: '成長記', en: 'GROWTH LOG' }, { ja: '挑戦記', en: 'CHALLENGE LOG' },
    { ja: '開店', en: 'SHOP OPENING' }, { ja: '開業', en: 'OPENING DAY' }, { ja: '繁盛', en: 'PROSPERITY' },
    { ja: '商売', en: 'TRADE' }, { ja: '稼業', en: 'FAMILY TRADE' }, { ja: '職人', en: 'ARTISAN' },
    { ja: '名人', en: 'MASTER' }, { ja: '達人', en: 'EXPERT' }, { ja: '師範', en: 'INSTRUCTOR' },
    { ja: '見習い', en: 'APPRENTICE' }, { ja: '弟子', en: 'DISCIPLE' }, { ja: '一門', en: 'LINEAGE SCHOOL' },
    { ja: '流派', en: 'STYLE' }, { ja: '秘伝', en: 'SECRET TRADITION' }, { ja: '心得', en: 'PRECEPTS' },
    { ja: '作法', en: 'ETIQUETTE' }, { ja: '手順', en: 'PROCEDURE' }, { ja: '型', en: 'FORM' },
    { ja: '技', en: 'TECHNIQUE' }, { ja: '術', en: 'ARTS' }, { ja: '法', en: 'METHOD' },
    { ja: '論', en: 'THEORY' }, { ja: '学', en: 'STUDIES' }, { ja: '誌', en: 'GAZETTE' },
    { ja: '報', en: 'BULLETIN' }, { ja: '便り', en: 'TIDINGS' }, { ja: '通信', en: 'CORRESPONDENCE' },
    { ja: '放送', en: 'BROADCAST' },

    { ja: '演芸場', en: 'VARIETY HALL' }, { ja: '舞台', en: 'STAGE' }, { ja: '演目', en: 'PROGRAM' },
    { ja: '幕', en: 'ACT' }, { ja: '場', en: 'SCENE' }, { ja: '楽章', en: 'MOVEMENT' },
    { ja: '組曲', en: 'SUITE' }, { ja: '序章', en: 'PROLOGUE' }, { ja: '終章', en: 'EPILOGUE' },
    { ja: '番外編', en: 'SIDE STORY' }, { ja: '外伝', en: 'GAIDEN' }, { ja: '前日譚', en: 'PREQUEL' },
    { ja: '後日譚', en: 'SEQUEL TALE' }, { ja: '新章', en: 'NEW CHAPTER' }, { ja: '完結編', en: 'FINALE' },

    { ja: '天国', en: 'HEAVEN' }, { ja: '広場', en: 'PLAZA' }, { ja: '遊技場', en: 'ARCADE' },
    { ja: '遊園', en: 'PLEASURE GARDEN' }, { ja: '庭', en: 'GARDEN' }, { ja: '農園', en: 'PLANTATION' },
    { ja: '農村', en: 'FARM VILLAGE' }, { ja: '漁村', en: 'FISHING VILLAGE' }, { ja: '山村', en: 'MOUNTAIN VILLAGE' },
    { ja: '港町', en: 'PORT TOWN' }, { ja: '城下町', en: 'CASTLE TOWN' }, { ja: '宿場町', en: 'POST TOWN' },

    { ja: '組合', en: 'UNION' }, { ja: '同好会', en: 'SOCIETY' }, { ja: '部', en: 'CLUB' },
    { ja: '会', en: 'ASSOCIATION' }, { ja: '団', en: 'TROUPE' }, { ja: '隊', en: 'SQUAD' },
    { ja: '軍団', en: 'CORPS' },

    { ja: '書庫', en: 'STACK ROOM' }, { ja: '標本室', en: 'SPECIMEN ROOM' }, { ja: '展示室', en: 'EXHIBIT ROOM' },
    { ja: '資料室', en: 'REFERENCE ROOM' }, { ja: '待合室', en: 'WAITING ROOM' }, { ja: '談話室', en: 'LOUNGE' },
    { ja: '屋根裏', en: 'ATTIC' }, { ja: '地下室', en: 'CELLAR' }, { ja: '中庭', en: 'COURTYARD' },
    { ja: '縁側', en: 'VERANDA' }, { ja: '土間', en: 'EARTHEN FLOOR' }, { ja: '井戸端', en: 'WELLSIDE' },
    { ja: '路地', en: 'ALLEY' }, { ja: '横丁', en: 'SIDE STREET' }, { ja: '通り', en: 'AVENUE' },
    { ja: '十字路', en: 'CROSSROADS' }, { ja: '坂道', en: 'SLOPE' }, { ja: '石段', en: 'STONE STEPS' },
    { ja: '並木道', en: 'TREE LINED ROAD' }, { ja: '河原', en: 'RIVERBED' }, { ja: '堤防', en: 'EMBANKMENT' },
    { ja: '用水路', en: 'IRRIGATION CANAL' }, { ja: '峠', en: 'MOUNTAIN PASS' }, { ja: '分岐点', en: 'JUNCTION' },
    { ja: '名場面', en: 'HIGHLIGHTS' }, { ja: '総覧', en: 'OVERVIEW' }, { ja: '案内所', en: 'INFORMATION DESK' },
    { ja: '見取り図', en: 'FLOOR PLAN' }, { ja: '集会所', en: 'MEETING HALL' }
  ],
  scaleWord: [
    'DX', 'EX', 'GO', 'NEO', 'MAX', 'PLUS', 'PRO', 'LITE', 'MINI', 'ZERO',
    'ONE', 'TWO', 'THREE', 'R', 'S', 'X', 'Z', 'HD', 'ARCADE', 'ADVANCE',
    'BURST', 'BLAST', 'RUSH', 'DASH', 'DRIVE', 'JAM', 'MIX', 'PARTY', 'FEVER', 'MANIA',
    'FRENZY', 'SPARK', 'SHINE', 'WORLD', 'GLOBAL', 'PLANET', 'COSMOS', 'INFINITY', 'ETERNAL', 'FOREVER',
    'AGAIN', 'RETURNS', 'REVIVAL', 'REBOOT', 'REMIX', 'ENCORE', 'BEYOND', 'OVER', 'ULTIMATE', 'PREMIUM',
    'ROYAL', 'IMPERIAL', 'CLASSIC', 'MASTERS', 'EVOLUTION', 'REVOLUTION', 'GENERATION', 'SECOND', 'THIRD', 'FINAL',
    'NEXT', 'TURBO', 'HYPER', 'SUPER', 'ULTRA', 'MEGA', 'GIGA', 'TERA', 'OMEGA', 'DELTA',
    'SIGMA', 'PRIME', 'CORE', 'EDGE', 'PEAK', 'SUMMIT', 'ORBIT', 'VOLT', 'FLASH', 'STORM',
    'TIDE', 'BLOOM', 'CIRCLE', 'CROSS', 'LINK', 'STEP', 'JUMP', 'TRIAL', 'GRAND', 'BRAVE',
    'ネクスト', 'ワールド', 'ポータブル', 'ターボ', 'マックス', 'グランド', 'スーパー', 'ハイパー', 'ウルトラ', 'メガ',
    'ギガ', 'オメガ', 'アルファ', 'ゼータ', 'ゼロ', 'ダブル', 'トリプル', 'プラス', 'リミックス', 'リターンズ',
    'リバイバル', 'リブート', 'リメイク', 'リマスター', 'アンコール', 'アゲイン', 'フォーエバー', 'インフィニティ', 'エターナル', 'アドバンス',
    'エボリューション', 'レボリューション', 'ジェネレーション', 'セカンド', 'サード', 'ファイナル', 'ビヨンド', 'アルティメット', 'プレミアム', 'ロイヤル',
    'インペリアル', 'クラシック', 'マスターズ', 'オールスターズ', 'ミラクルスターズ', 'ドリームスターズ', 'ワンダースターズ', 'スーパースターズ', 'フルコース', 'フルセット',
    'ミラクル', 'ワンダー', 'ドリーム', 'レインボー', 'クリスタル', 'ダイヤモンド', 'ゴールド', 'シルバー', 'プラチナ', 'ルビー',
    'サファイア', 'エメラルド', 'パール', 'オパール', 'トパーズ', 'アメジスト',
    '大集合', '大集結', '総出動', '完全版', '決定版', '新装版', '増補版', '改訂版', '特別版', '拡張版',
    '統合版', '総合版', '上級編', '初級編', '中級編', '応用編', '基礎編', '入門編', '実践編', '発展編',
    '特訓編', '総集編', '最終編', '前編', '後編', '続編', '第二幕', '第三幕',
    '２', '３', '４', '５', '６', '７', '８', '９', 'II', 'III',
    'IV', 'V', 'VI', 'VII', 'VIII', 'IX',
    '極', '真', '改', '零', '壱', '弐', '参', '双', '超', '極上',
    '至高', '究極', '最強', '無双', '無限', '千', '万', '全', '総', '大',
    '特', '新', '続', '完'
  ],
  lifeWord: [
    'わくわく生活', 'のんびり暮らし', 'ゆったり暮らし', 'まったり生活', 'ほのぼの日和',
    'きらきら毎日', 'にぎやか横丁', 'みんなの広場', '毎日たのしく', 'ゆかいな仲間たち',
    'なかよし広場', 'たのしい毎日', 'しあわせ日和', 'ぽかぽか暮らし', 'てくてく散歩',
    'ころころ日記', 'ふわふわ生活', 'もふもふ暮らし', 'すくすく育ち', 'せっせと開拓',
    'もりもり収穫', 'ぐんぐん成長', 'どきどき冒険', 'わいわい合宿', 'ほくほく食堂',
    'ぬくぬく部屋', 'さらさら日和', 'ゆるり暮らし', 'のほほん生活', 'てんてこ舞い',
    'ばたばた毎日', 'こつこつ商店', 'ぴかぴか大掃除', 'ごろごろ休日', 'うきうき遠足',
    'にこにこ教室', 'ぷかぷか船旅', 'ざぶざぶ川遊び', 'さくさく作業', 'とことこ旅路',
    'ぶらぶら散策', 'ひらひら花畑', 'ちょきちょき散髪', 'ぱたぱた工房', 'ことこと台所',
    'ぐつぐつ鍋', 'ふつふつ発酵', 'もくもく煙突', 'きゅうきゅう救助', 'ぴょんぴょん広場',
    'とんとん拍子', 'すいすい泳ぎ', 'ぐるぐる観覧車', 'ゆらゆら吊り橋', 'ちくちく手芸',
    'ざくざく発掘', 'ほりほり庭仕事', 'ぽたぽた雨宿り', 'しとしと梅雨', 'さわさわ木漏れ日',
    'そよそよ風の丘', 'きんきん氷菓', 'ほかほか湯けむり', 'つやつや稲穂', 'ぴちぴち漁港',
    'もぐもぐ食卓', 'ぱりぱり焼きたて', 'ふんわり寝床', 'どんどん建設', 'てきぱき仕事',
    'のびのび放課後', 'いきいき毎日', 'はきはき挨拶', 'すやすや夜', 'ぼんやり午後',
    'うとうと昼寝', 'きょろきょろ探検', 'そわそわ発表会', 'どたばた運動会', 'わちゃわちゃ教室',
    'ほろほろ夕暮れ', 'しんしん雪の夜', 'からから晴れ空', 'ぱらぱら通り雨', 'ぴかぴか新学期',
    'ころりん転がり坂', 'ぽかぽか縁側', 'ぬくもり食堂', 'まんまる満月', 'ふらふら寄り道',
    'たっぷり休日', 'どっさり収穫祭', 'ばっちり準備', 'ぴったり相棒', 'すっきり片付け',
    'ぐっすり夜更け', 'ゆっくり湯上がり', 'しっかり自由研究', 'こっそり秘密基地', 'のんびり温泉',
    'ほんのり甘い時間', 'じっくり煮込み', 'さっぱり夏の日', 'ひんやり氷の朝',
    'みんなでいっしょ', 'ふたりの毎日', 'ひとりの時間', '家族のかたち', '隣町までの道',
    '屋根の下の日々', '小さな暮らし', '大きな夢', '明日はいい日', '今日もいい天気',
    'おかえりなさいの街', 'ただいまの家', 'いってきますの朝', 'おやすみの前に', '朝いちばんの光',
    '夕暮れの帰り道', '週末のたのしみ', '春夏秋冬のうた', '春のはじまり', '夏のまんなか',
    '秋のおわり', '冬のあいだ', '三日月の夜', '満天の星の下', '雨の日の過ごし方',
    '晴れの日の約束', '雪の日のごちそう', '風の強い日', '台風のあとで', '虹の出た朝',
    '木曜日のおやつ', '日曜日の朝市', '月曜日のはじまり', '土曜日の工作', '金曜日の映画会',
    '火曜日の花壇', '水曜日の合唱', '十二時のおひるね', '三時のおやつ', '六時の鐘',
    '真夜中の台所', '明け方の港', '正午の広場', '黄昏の商店街', '夜更けの屋台',
    '二階の窓から', '縁側のひなたぼっこ', '台所のうた', '食卓のまんなか', '玄関のかたすみ',
    '庭のすみっこ', '屋根の上の風', '坂の上の家', '坂の下の店', '川べりの散歩',
    '海の見える丘', '山の見える窓', '湖のほとりで', '森のはずれで', '畑のまんなかで',
    '田んぼの一本道', '港のはずれの店', '駅までの近道', 'バスを待つ時間', '電車の窓ぎわ',
    '自転車で行く道', '歩いて十分の町', 'となりの席の子', '同じ班の友だち', 'はじめての仲間',
    'おなじみの常連', '顔なじみの店主', '名もない野の花', '一輪の花のために', 'ふたつの季節',
    'みっつの願い', 'よっつの約束', 'いつつの贈り物', '百のありがとう', '千の朝',
    '小さな勇気', 'ささやかな幸せ', 'ちいさなお店', 'ちいさな駅', 'ちいさな島',
    'ちいさな旅', 'はじめてのおつかい', 'はじめての料理', 'はじめての夜更かし', 'はじめての遠出',
    '二度目の春', '三度目の挑戦', 'いつかの夏', 'あの日の空', 'これからの毎日',
    'ずっとこのまま', 'もう少しだけ', 'あとひとつだけ', 'きっと大丈夫', 'たぶん晴れる',
    'たしかな足あと', '手のひらの温度', '胸のおくの灯', '背中のぬくもり', '足もとの草',
    'まぶたのうらの海', 'ポケットの宝物', 'かばんの中の地図', '引き出しの秘密', '本棚のすきま',
    '押し入れの探検', '屋根裏のたからもの', '冷蔵庫のむこう', '湯呑みのふち', 'おわんの湯気',
    'まないたの音', 'ほうきのあと', '洗濯物のにおい', '布団のなか', '枕もとのラジオ',
    '目覚まし時計の朝', 'カレンダーの丸印', '日めくりの毎日', '貯金箱の重さ', '通知表の日',
    '上履きの音', 'ランドセルの重み', '学校のかえりみち', '給食のじかん', '掃除のあと',
    '部活のあとで', '放課後の教室', '卒業までの日々', '夏休みのしおり', '冬休みのしゅくだい',
    '春休みの計画', '連休のすごしかた', '遠足のまえの日', '運動会のあさ', '文化祭のよる',
    '発表会のまえ', '大掃除のひ', 'おおみそかの夜', '元日のあさ', '七草のかゆ',
    '節分のまめ', '花見のべんとう', '夏祭りのゆかた', '十五夜のだんご', '冬至のゆず',
    '誕生日のろうそく', 'いつもの朝ごはん', 'いつもの帰り道'
  ],
  imperative: [
    'がんばれ', 'たたかえ', 'すすめ', 'あつまれ', 'つくろう', 'めざせ', 'とびだせ', 'かけぬけろ',
    'さがせ', 'みつけろ', 'まもれ', 'とどけ', 'つなげ', 'ひろげ', 'きわめろ', 'いどめ',
    'かけろ', 'とべ', 'はしれ', 'およげ', 'のぼれ', 'くだれ', 'まわせ', 'ならべ',
    'うて', 'なげろ', 'けれ', 'ふれ', 'たたけ', 'ひけ', 'おせ', 'ひっぱれ',
    'はこべ', 'あつめろ', 'そだてろ', 'そろえろ', 'まぜろ', 'にぎれ', 'きざめ', 'いそげ',
    'まて', 'きけ', 'みろ', 'かんがえろ', 'おもいだせ', 'えらべ', 'きめろ', 'こたえろ',
    'あばけ', 'つきとめろ', 'にげろ', 'かくれろ', 'おいかけろ', 'つかまえろ', 'ふりかえれ', 'たちあがれ',
    'ふみだせ', 'のりこめ', 'きりひらけ', 'うちやぶれ', 'のりこえろ', 'かちとれ', 'まきかえせ', 'たてなおせ',
    'きずけ', 'きたえろ', 'みがけ', 'ととのえろ', 'かたづけろ', 'さばけ', 'もりつけろ', 'いろどれ',
    'てらせ', 'ならせ', 'ひびかせろ', 'とどろけ', 'かがやけ', 'はばたけ', 'まいあがれ', 'まきおこせ',
    'ときはなて', 'よびさませ', 'めざめろ', 'いきぬけ', 'わらえ', 'うたえ', 'おどれ', 'さけべ',
    'となえろ', 'つげろ', 'つづれ', 'しるせ', 'えがけ', 'のこせ', 'つたえろ', 'まけるな',
    'あきらめるな', 'ふりむくな', 'とまるな', 'まような', 'おそれるな', 'ゆだんするな', 'にがすな', 'たべよう',
    'あそぼう', 'まなぼう', 'かぞえよう', 'おぼえよう', 'かこう', 'うたおう', 'おどろう', 'ならそう',
    'そだてよう', 'かざろう', 'つなごう', 'ひろげよう', 'さがそう', 'たしかめよう', 'ためそう', 'はじめよう',
    'つづけよう', 'とどけよう', 'まもろう', 'いこう', 'かえろう', 'のぼろう', 'わたろう', 'まわろう',
    'めぐろう', 'たびだとう', 'つりあげろ', 'ほりあてろ', 'ひろいあつめろ', 'ならびかえろ', 'いいあてろ', 'ときあかせ',
    'よみとけ', 'かぞえろ', 'はかれ', 'くみたてろ', 'つみあげろ', 'わたりきれ', 'とびこえろ', 'すべりおりろ',
    'こぎだせ', 'ふみしめろ', 'かけあがれ', 'かけおりろ', 'たどりつけ', 'まちうけろ'
  ],
  subtitleWord: [
    { ja: 'はじまりの章', en: 'THE FIRST CHAPTER' }, { ja: '終わりの章', en: 'THE LAST CHAPTER' },
    { ja: '序章の風', en: 'WIND OF THE PROLOGUE' }, { ja: '最終章の空', en: 'SKY OF THE FINAL CHAPTER' },
    { ja: '新たなる旅立ち', en: 'A NEW DEPARTURE' }, { ja: '旅立ちの朝', en: 'MORNING OF DEPARTURE' },
    { ja: '旅の途中で', en: 'MIDWAY ON THE ROAD' }, { ja: '帰り道の灯', en: 'LAMP ON THE WAY HOME' },
    { ja: 'めぐりあいの日', en: 'THE DAY OF MEETING' }, { ja: '別れの季節', en: 'SEASON OF PARTING' },
    { ja: '再会の丘', en: 'HILL OF REUNION' }, { ja: '約束の場所', en: 'THE PROMISED PLACE' },
    { ja: '交わした約束', en: 'THE PROMISE WE MADE' }, { ja: '遠い約束', en: 'A DISTANT PROMISE' },
    { ja: '最初の一歩', en: 'THE FIRST STEP' }, { ja: '最後の一歩', en: 'THE FINAL STEP' },
    { ja: '果てなき航路', en: 'THE ENDLESS COURSE' }, { ja: '帰らざる航海', en: 'THE VOYAGE OF NO RETURN' },
    { ja: '未知への扉', en: 'DOOR TO THE UNKNOWN' }, { ja: '明日への道', en: 'ROAD TO TOMORROW' },
    { ja: '昨日への手紙', en: 'LETTER TO YESTERDAY' }, { ja: '明日の地図', en: 'MAP OF TOMORROW' },
    { ja: '消えた地図', en: 'THE VANISHED MAP' }, { ja: '忘れられた小径', en: 'THE FORGOTTEN PATH' },
    { ja: '名もなき道', en: 'THE NAMELESS ROAD' }, { ja: '迷い道の先', en: 'BEYOND THE STRAY PATH' },
    { ja: '峠のむこう', en: 'OVER THE PASS' }, { ja: '海の向こうへ', en: 'BEYOND THE SEA' },
    { ja: '空の果てまで', en: 'TO THE END OF THE SKY' }, { ja: '地の果ての街', en: 'TOWN AT THE END OF THE WORLD' },
    { ja: '世界のはじまり', en: 'THE BEGINNING OF THE WORLD' }, { ja: '世界のかたすみ', en: 'A CORNER OF THE WORLD' },
    { ja: '旅路の果て', en: 'END OF THE JOURNEY' }, { ja: '帰還の日', en: 'THE DAY OF RETURN' },
    { ja: '出発の合図', en: 'THE DEPARTURE SIGNAL' },

    { ja: '失われた記憶', en: 'THE LOST MEMORY' }, { ja: '消えぬ記憶', en: 'THE MEMORY THAT REMAINS' },
    { ja: '記憶のかけら', en: 'FRAGMENTS OF MEMORY' }, { ja: '忘れえぬ夏', en: 'THE UNFORGETTABLE SUMMER' },
    { ja: '遠い日の歌', en: 'SONG OF DISTANT DAYS' }, { ja: 'あの日の約束', en: 'THE PROMISE OF THAT DAY' },
    { ja: '十年後の手紙', en: 'A LETTER TEN YEARS ON' }, { ja: '百年の樹', en: 'THE HUNDRED YEAR TREE' },
    { ja: '千の足跡', en: 'A THOUSAND FOOTPRINTS' }, { ja: '万の灯り', en: 'TEN THOUSAND LIGHTS' },
    { ja: '一日の終わりに', en: 'AT THE END OF A DAY' }, { ja: '夜明けまでの時間', en: 'THE HOURS UNTIL DAWN' },
    { ja: '静かなる夜明け', en: 'THE SILENT DAWN' }, { ja: '目覚めの朝', en: 'THE MORNING OF WAKING' },
    { ja: '眠りの前に', en: 'BEFORE SLEEP' }, { ja: '時を越えて', en: 'ACROSS TIME' },
    { ja: '巡る季節', en: 'THE TURNING SEASONS' }, { ja: '止まった時計', en: 'THE STOPPED CLOCK' },
    { ja: '動きだす歯車', en: 'THE GEARS BEGIN TO TURN' }, { ja: '砂時計の底', en: 'THE BOTTOM OF THE HOURGLASS' },
    { ja: '三度目の朝', en: 'THE THIRD MORNING' }, { ja: '七日間の記録', en: 'SEVEN DAYS OF RECORD' },
    { ja: '最後の一日', en: 'THE LAST DAY' }, { ja: 'はじめての夜', en: 'THE FIRST NIGHT' },
    { ja: '長い夜のあとで', en: 'AFTER THE LONG NIGHT' }, { ja: '夜明け前の静けさ', en: 'STILLNESS BEFORE DAWN' },
    { ja: '黄昏の刻', en: 'THE HOUR OF TWILIGHT' }, { ja: '真昼の影', en: 'THE MIDDAY SHADOW' },
    { ja: '深夜の来訪者', en: 'THE MIDNIGHT CALLER' }, { ja: '明け方の便り', en: 'WORD AT DAYBREAK' },
    { ja: '記憶の底', en: 'THE DEPTHS OF MEMORY' }, { ja: '忘却の岸', en: 'THE SHORE OF OBLIVION' },
    { ja: '追憶の庭', en: 'THE GARDEN OF REMEMBRANCE' }, { ja: '郷愁の丘', en: 'THE HILL OF LONGING' },
    { ja: '過ぎた夏の色', en: 'THE COLOR OF A PAST SUMMER' },

    { ja: '決戦の刻', en: 'THE HOUR OF DECISION' }, { ja: '最後の一手', en: 'THE FINAL MOVE' },
    { ja: '逆転の一投', en: 'THE TURNING PITCH' }, { ja: '起死回生の一撃', en: 'THE COMEBACK BLOW' },
    { ja: '勝負の分かれ目', en: 'THE DIVIDING POINT' }, { ja: '王手の局面', en: 'THE CHECKMATE POSITION' },
    { ja: '終盤の読み', en: 'READING THE ENDGAME' }, { ja: '定石をこえて', en: 'BEYOND THE STANDARD LINE' },
    { ja: '一手の重み', en: 'THE WEIGHT OF ONE MOVE' }, { ja: '延長戦の空', en: 'SKY OF EXTRA TIME' },
    { ja: '九回裏の風', en: 'WIND OF THE FINAL INNING' }, { ja: '最終ラップ', en: 'THE FINAL LAP' },
    { ja: 'ゴールの向こう', en: 'BEYOND THE FINISH' }, { ja: '記録への挑戦', en: 'CHALLENGE TO THE RECORD' },
    { ja: '頂への道', en: 'THE ROAD TO THE SUMMIT' }, { ja: '山頂の朝日', en: 'SUNRISE AT THE SUMMIT' },
    { ja: '頂上決戦', en: 'THE SUMMIT SHOWDOWN' }, { ja: '総力戦', en: 'THE ALL OUT CONTEST' },
    { ja: '一騎打ち', en: 'THE SINGLE COMBAT' }, { ja: '挑戦者の朝', en: 'MORNING OF THE CHALLENGER' },
    { ja: '王者の条件', en: 'WHAT MAKES A CHAMPION' }, { ja: '無敗の記録', en: 'THE UNBEATEN RECORD' },
    { ja: '敗者の誇り', en: 'THE PRIDE OF THE DEFEATED' }, { ja: '再挑戦の日', en: 'THE DAY OF THE REMATCH' },
    { ja: '決着の時', en: 'THE TIME OF SETTLEMENT' }, { ja: '譲れぬ一戦', en: 'THE MATCH THAT CANNOT BE LOST' },
    { ja: '好敵手', en: 'THE WORTHY RIVAL' }, { ja: '宿命の対決', en: 'THE FATED CONFRONTATION' },
    { ja: '静かなる戦い', en: 'THE QUIET CONTEST' }, { ja: '盤上の宇宙', en: 'THE UNIVERSE ON THE BOARD' },
    { ja: '一局の重み', en: 'THE WEIGHT OF ONE GAME' }, { ja: '読みの果て', en: 'THE END OF CALCULATION' },
    { ja: '攻防の果て', en: 'THE END OF THE EXCHANGE' }, { ja: '逆転の終盤', en: 'THE ENDGAME REVERSAL' },
    { ja: '千日の稽古', en: 'A THOUSAND DAYS OF PRACTICE' }, { ja: '稽古の朝', en: 'THE MORNING TRAINING' },
    { ja: '汗の記録', en: 'THE RECORD OF SWEAT' }, { ja: '涙の後で', en: 'AFTER THE TEARS' },
    { ja: '栄光への階段', en: 'THE STAIRWAY TO GLORY' }, { ja: '頂点の景色', en: 'THE VIEW FROM THE TOP' },
    { ja: '敗北のあとに', en: 'AFTER THE DEFEAT' }, { ja: '勝利の作法', en: 'THE MANNER OF VICTORY' },
    { ja: '全力の一日', en: 'A DAY AT FULL POWER' }, { ja: '最速の記録', en: 'THE FASTEST RECORD' },
    { ja: '最長の一戦', en: 'THE LONGEST MATCH' },

    { ja: '小さな店の一年', en: 'A YEAR OF THE LITTLE SHOP' }, { ja: '開店前の朝', en: 'MORNING BEFORE OPENING' },
    { ja: '満席の午後', en: 'A FULL HOUSE AFTERNOON' }, { ja: '常連たちの席', en: 'THE SEATS OF THE REGULARS' },
    { ja: '看板の灯る頃', en: 'WHEN THE SIGN LIGHTS UP' }, { ja: 'のれんの重み', en: 'THE WEIGHT OF THE SHOP CURTAIN' },
    { ja: '三代目の決断', en: 'CHOICE OF THE THIRD GENERATION' }, { ja: '継ぐということ', en: 'ON INHERITING THE TRADE' },
    { ja: '味を守る日々', en: 'DAYS OF KEEPING THE FLAVOR' }, { ja: '仕込みの朝', en: 'THE MORNING PREPARATION' },
    { ja: '収穫の日', en: 'THE DAY OF HARVEST' }, { ja: '種まきの朝', en: 'THE MORNING OF SOWING' },
    { ja: '苗床の春', en: 'SPRING AT THE SEEDBED' }, { ja: '実りの秋', en: 'THE FRUITFUL AUTUMN' },
    { ja: '雪解けの季節', en: 'THE THAWING SEASON' }, { ja: '花咲く丘で', en: 'ON THE BLOOMING HILL' },
    { ja: '夏の終わりに', en: 'AT THE END OF SUMMER' }, { ja: '秋のはじまり', en: 'THE START OF AUTUMN' },
    { ja: '冬支度の日', en: 'THE DAY OF WINTER PREPARATION' }, { ja: '春を待つ町', en: 'THE TOWN AWAITING SPRING' },
    { ja: '雨上がりの道', en: 'THE ROAD AFTER RAIN' }, { ja: '風の通る道', en: 'THE PATH THE WIND TAKES' },
    { ja: '陽だまりの椅子', en: 'THE CHAIR IN THE SUN' }, { ja: '木漏れ日の午後', en: 'AFTERNOON IN DAPPLED LIGHT' },
    { ja: '夕焼けの合図', en: 'THE SIGNAL OF SUNSET' }, { ja: '朝もやの港', en: 'THE PORT IN MORNING MIST' },
    { ja: '潮騒の便り', en: 'TIDINGS OF THE TIDE' }, { ja: '波音の記録', en: 'THE RECORD OF WAVES' },
    { ja: '山あいの村', en: 'THE VILLAGE IN THE HILLS' }, { ja: '谷底の泉', en: 'THE SPRING AT THE VALLEY FLOOR' },
    { ja: '湖畔の宿', en: 'THE INN BY THE LAKE' }, { ja: '森のささやき', en: 'THE WHISPER OF THE FOREST' },
    { ja: '土の匂い', en: 'THE SCENT OF EARTH' }, { ja: '石畳の記憶', en: 'MEMORY OF THE COBBLESTONES' },
    { ja: '屋根裏の宝物', en: 'THE TREASURE IN THE ATTIC' }, { ja: '引き出しの手紙', en: 'THE LETTER IN THE DRAWER' },
    { ja: '押し入れの地図', en: 'THE MAP IN THE CLOSET' }, { ja: '台所の魔法', en: 'THE MAGIC OF THE KITCHEN' },
    { ja: '食卓のうた', en: 'THE SONG OF THE TABLE' }, { ja: '湯気の向こう', en: 'BEYOND THE STEAM' },
    { ja: '焼きたての朝', en: 'THE FRESHLY BAKED MORNING' }, { ja: '一杯の湯', en: 'A SINGLE CUP' },
    { ja: '明かりの消えた店', en: 'THE SHOP WITH LIGHTS OUT' }, { ja: '賑わいの戻る日', en: 'THE DAY LIVELINESS RETURNS' },
    { ja: '商店街の朝礼', en: 'THE MORNING GATHERING OF THE ARCADE' },

    { ja: '教室のすみで', en: 'IN THE CORNER OF THE CLASSROOM' }, { ja: '黒板の落書き', en: 'THE DOODLE ON THE BLACKBOARD' },
    { ja: '転校生の秘密', en: 'SECRET OF THE TRANSFER STUDENT' }, { ja: '放課後の約束', en: 'THE AFTER SCHOOL PROMISE' },
    { ja: '屋上の風', en: 'THE WIND ON THE ROOFTOP' }, { ja: '部室のかぎ', en: 'THE CLUBROOM KEY' },
    { ja: '最後の大会', en: 'THE LAST TOURNAMENT' }, { ja: '一年生の夏', en: 'THE FIRST YEAR SUMMER' },
    { ja: '三年目の秋', en: 'THE THIRD AUTUMN' }, { ja: '卒業式の朝', en: 'THE MORNING OF GRADUATION' },
    { ja: '制服のポケット', en: 'THE UNIFORM POCKET' }, { ja: '靴箱の手紙', en: 'THE LETTER IN THE SHOE LOCKER' },
    { ja: '名簿の最後の名前', en: 'THE LAST NAME ON THE ROLL' }, { ja: '給食のあとで', en: 'AFTER THE SCHOOL LUNCH' },
    { ja: '掃除の時間', en: 'THE CLEANING HOUR' }, { ja: '学級新聞', en: 'THE CLASS NEWSPAPER' },
    { ja: '図工の時間', en: 'THE CRAFT LESSON' }, { ja: '音楽室の午後', en: 'AFTERNOON IN THE MUSIC ROOM' },
    { ja: '理科室の実験', en: 'THE EXPERIMENT IN THE SCIENCE ROOM' }, { ja: '図書室のすみ', en: 'THE CORNER OF THE READING ROOM' },
    { ja: '校庭の白線', en: 'THE WHITE LINES ON THE GROUND' }, { ja: '運動会の空', en: 'THE SKY OF SPORTS DAY' },
    { ja: '文化祭の夜', en: 'THE NIGHT OF THE SCHOOL FESTIVAL' }, { ja: '修学旅行の朝', en: 'THE MORNING OF THE SCHOOL TRIP' },
    { ja: '夏休みの自由研究', en: 'THE SUMMER PROJECT' }, { ja: '宿題のかたすみ', en: 'THE MARGIN OF THE HOMEWORK' },
    { ja: '通学路の猫', en: 'THE CAT ON THE SCHOOL ROUTE' }, { ja: 'ともだちの条件', en: 'WHAT MAKES A FRIEND' },
    { ja: 'けんかのあとで', en: 'AFTER THE QUARREL' }, { ja: '仲直りの日', en: 'THE DAY OF MAKING UP' },
    { ja: 'はじめての友だち', en: 'THE FIRST FRIEND' }, { ja: '秘密の合言葉', en: 'THE SECRET PASSWORD' },
    { ja: 'ふたりだけの地図', en: 'THE MAP FOR TWO' }, { ja: 'みんなの合唱', en: 'THE CHORUS OF EVERYONE' },
    { ja: '声を合わせて', en: 'VOICES IN UNISON' }, { ja: '手をつないで', en: 'HAND IN HAND' },
    { ja: '背くらべの柱', en: 'THE PILLAR OF HEIGHT MARKS' }, { ja: '落とし物の主', en: 'THE OWNER OF THE LOST ITEM' },
    { ja: '忘れ物の教室', en: 'THE CLASSROOM OF FORGOTTEN THINGS' }, { ja: '帰りの会', en: 'THE CLOSING MEETING' },

    { ja: '消えた証人', en: 'THE VANISHED WITNESS' }, { ja: '密室の鍵', en: 'THE KEY TO THE LOCKED ROOM' },
    { ja: '三つのアリバイ', en: 'THREE ALIBIS' }, { ja: '最後の証言', en: 'THE FINAL TESTIMONY' },
    { ja: '犯人の足跡', en: 'FOOTPRINTS OF THE CULPRIT' }, { ja: '暗号の答え', en: 'THE ANSWER TO THE CIPHER' },
    { ja: '招かれざる客', en: 'THE UNINVITED GUEST' }, { ja: '十三番目の椅子', en: 'THE THIRTEENTH CHAIR' },
    { ja: '開かずの扉', en: 'THE DOOR THAT NEVER OPENS' }, { ja: '沈黙の証拠', en: 'THE SILENT EVIDENCE' },
    { ja: '嘘の輪郭', en: 'THE OUTLINE OF A LIE' }, { ja: '見えない糸', en: 'THE INVISIBLE THREAD' },
    { ja: '二重の顔', en: 'THE DOUBLE FACE' }, { ja: '真夜中の電話', en: 'THE MIDNIGHT CALL' },
    { ja: '消えた一日', en: 'THE MISSING DAY' }, { ja: '誰も見ていない', en: 'NOBODY WAS WATCHING' },
    { ja: '動かぬ証拠', en: 'THE IRREFUTABLE PROOF' }, { ja: '影の告発', en: 'THE ACCUSATION FROM THE SHADOWS' },
    { ja: '遺された言葉', en: 'THE WORDS LEFT BEHIND' }, { ja: '予告された事件', en: 'THE ANNOUNCED CRIME' },
    { ja: '怪盗の置き手紙', en: 'NOTE OF THE PHANTOM THIEF' }, { ja: '直前の真実', en: 'THE TRUTH JUST BEFORE' },
    { ja: '目撃者の朝', en: 'MORNING OF THE WITNESS' }, { ja: '疑いの街', en: 'THE TOWN OF SUSPICION' },
    { ja: '名探偵の休日', en: 'DAY OFF OF THE DETECTIVE' }, { ja: '迷宮入りの箱', en: 'THE UNSOLVED BOX' },
    { ja: '忘れられた事件簿', en: 'THE FORGOTTEN CASEBOOK' }, { ja: '廃駅の怪', en: 'THE MYSTERY OF THE ABANDONED STATION' },
    { ja: '霧の館', en: 'THE MANSION IN THE FOG' }, { ja: '鏡のむこうの部屋', en: 'THE ROOM BEYOND THE MIRROR' },
    { ja: '消えた肖像', en: 'THE MISSING PORTRAIT' }, { ja: '地下室の音', en: 'THE SOUND FROM THE CELLAR' },
    { ja: '七つの手がかり', en: 'SEVEN CLUES' }, { ja: '最後の推理', en: 'THE FINAL DEDUCTION' },
    { ja: '犯行の順序', en: 'THE ORDER OF THE DEED' }, { ja: '告白の夜', en: 'THE NIGHT OF CONFESSION' },
    { ja: '真相の在処', en: 'WHERE THE TRUTH LIES' }, { ja: '幕切れの合図', en: 'THE CURTAIN SIGNAL' },
    { ja: '静かな部屋の記録', en: 'RECORD OF A QUIET ROOM' }, { ja: '灯の消えた館', en: 'THE MANSION WITH NO LIGHT' },

    { ja: '失われし王国', en: 'THE LOST KINGDOM' }, { ja: '選ばれし者たち', en: 'THE CHOSEN ONES' },
    { ja: '封印の書', en: 'THE BOOK OF SEALING' }, { ja: '蒼き聖域', en: 'THE AZURE SANCTUM' },
    { ja: '竜の目覚め', en: 'THE AWAKENING OF THE DRAGON' }, { ja: '星の導き', en: 'THE GUIDANCE OF STARS' },
    { ja: '光の継承者', en: 'THE HEIR OF LIGHT' }, { ja: '闇の帰還', en: 'THE RETURN OF DARKNESS' },
    { ja: '天空の門', en: 'THE GATE OF THE HEAVENS' }, { ja: '深き森の主', en: 'THE LORD OF THE DEEP WOODS' },
    { ja: '氷結の谷', en: 'THE FROZEN VALLEY' }, { ja: '焔の玉座', en: 'THE THRONE OF FLAME' },
    { ja: '忘れられた神々', en: 'THE FORGOTTEN GODS' }, { ja: '滅びの塔', en: 'THE TOWER OF RUIN' },
    { ja: '誓いの剣', en: 'THE SWORD OF OATHS' }, { ja: '呪われし血脈', en: 'THE CURSED BLOODLINE' },
    { ja: '三つの鍵', en: 'THE THREE KEYS' }, { ja: '五つの試練', en: 'THE FIVE TRIALS' },
    { ja: '七つの丘', en: 'THE SEVEN HILLS' }, { ja: '四季の精霊', en: 'THE SPIRITS OF THE SEASONS' },
    { ja: '月夜の約束', en: 'THE PROMISE ON A MOONLIT NIGHT' }, { ja: '星の降る夜', en: 'THE NIGHT OF FALLING STARS' },
    { ja: '世界樹の下で', en: 'BENEATH THE WORLD TREE' }, { ja: '黄金の羅針盤', en: 'THE GOLDEN COMPASS' },
    { ja: '銀の鍵穴', en: 'THE SILVER KEYHOLE' }, { ja: 'いにしえの誓い', en: 'THE ANCIENT OATH' },
    { ja: '王の帰還', en: 'THE RETURN OF THE KING' }, { ja: '影の軍勢', en: 'THE HOST OF SHADOWS' },
    { ja: '最果ての砦', en: 'FORTRESS AT THE EDGE OF THE WORLD' }, { ja: '天翔ける船', en: 'THE SHIP THAT SAILS THE SKY' },
    { ja: '沈める都', en: 'THE SUNKEN CITY' }, { ja: '眠れる巨人', en: 'THE SLEEPING GIANT' },
    { ja: '空を継ぐもの', en: 'THE ONE WHO INHERITS THE SKY' }, { ja: '灰の王座', en: 'THE THRONE OF ASH' },
    { ja: '名を持たぬ者', en: 'THE ONE WITHOUT A NAME' }, { ja: '双子の月', en: 'THE TWIN MOONS' },
    { ja: '涯なき荒野', en: 'THE ENDLESS WASTE' }, { ja: '竜と少年', en: 'THE DRAGON AND THE BOY' },
    { ja: '魔女の弟子', en: 'APPRENTICE OF THE WITCH' }, { ja: '錬金術師の朝', en: 'MORNING OF THE ALCHEMIST' },
    { ja: '剣を継ぐ日', en: 'THE DAY THE SWORD IS PASSED ON' }, { ja: '勇者のいない街', en: 'THE TOWN WITHOUT A HERO' },
    { ja: '神々の遊戯', en: 'THE PLAY OF THE GODS' }, { ja: '星読みの塔', en: 'THE TOWER OF STAR READERS' },
    { ja: '亡国の旗', en: 'THE FLAG OF A FALLEN NATION' }, { ja: '城塞の夜明け', en: 'DAWN AT THE CITADEL' },
    { ja: '誓いの果てに', en: 'AT THE END OF THE OATH' }, { ja: '光と影の境', en: 'THE BORDER OF LIGHT AND SHADE' },
    { ja: '血の代償', en: 'THE PRICE OF BLOOD' }, { ja: '静かなる侵攻', en: 'THE SILENT INVASION' },
    { ja: '最果ての灯台', en: 'THE LIGHTHOUSE AT THE END' }, { ja: '幻の大陸', en: 'THE PHANTOM CONTINENT' },
    { ja: '天涯の花', en: 'THE FLOWER AT THE EDGE OF THE SKY' }, { ja: '遥かなる約束の地', en: 'THE FAR PROMISED LAND' },
    { ja: '石の記憶', en: 'THE MEMORY OF STONE' }, { ja: '風の継ぐ者', en: 'THE HEIR OF THE WIND' },
    { ja: '炎を宿す者', en: 'THE ONE WHO BEARS FLAME' }, { ja: '大地の鼓動', en: 'THE PULSE OF THE EARTH' },
    { ja: '海鳴りの都', en: 'THE CITY OF THE ROARING SEA' }, { ja: '終焉の序曲', en: 'THE OVERTURE OF THE END' },

    { ja: '音の重なる場所', en: 'WHERE THE SOUNDS MEET' }, { ja: 'はじめての合奏', en: 'THE FIRST ENSEMBLE' },
    { ja: '一小節の勇気', en: 'THE COURAGE OF ONE BAR' }, { ja: '拍を刻む手', en: 'THE HAND THAT KEEPS TIME' },
    { ja: '舞台の袖で', en: 'IN THE WINGS' }, { ja: '幕が上がる前', en: 'BEFORE THE CURTAIN RISES' },
    { ja: '拍手のあとで', en: 'AFTER THE APPLAUSE' }, { ja: '歌のとどく場所', en: 'WHERE THE SONG REACHES' },
    { ja: '声のかたち', en: 'THE SHAPE OF A VOICE' }, { ja: '弦の記憶', en: 'THE MEMORY OF STRINGS' },
    { ja: '鍵盤のうえの朝', en: 'MORNING ON THE KEYS' }, { ja: '太鼓の鳴る夜', en: 'THE NIGHT THE DRUMS SOUND' },
    { ja: '祭囃子の遠く', en: 'THE DISTANT FESTIVAL MUSIC' }, { ja: '踊る足あと', en: 'DANCING FOOTPRINTS' },
    { ja: 'リズムのはじまり', en: 'THE BIRTH OF RHYTHM' }, { ja: '沈黙のあとの音', en: 'THE SOUND AFTER SILENCE' },
    { ja: '描きかけの絵', en: 'THE UNFINISHED PAINTING' }, { ja: '一枚の写真から', en: 'FROM A SINGLE PHOTOGRAPH' },
    { ja: '現像の夜', en: 'THE NIGHT OF DEVELOPING' }, { ja: '光を待つ時間', en: 'THE TIME OF WAITING FOR LIGHT' },
    { ja: '筆の運び', en: 'THE STROKE OF THE BRUSH' }, { ja: '窯出しの朝', en: 'THE MORNING OF THE KILN OPENING' },
    { ja: '織りなす色', en: 'THE WOVEN COLORS' }, { ja: '一本の糸から', en: 'FROM A SINGLE THREAD' },
    { ja: '縫い目のむこう', en: 'BEYOND THE SEAM' }, { ja: '木のこえを聞く', en: 'LISTENING TO THE WOOD' },
    { ja: '削り出す形', en: 'THE FORM CARVED OUT' }, { ja: '組み上がる日', en: 'THE DAY IT COMES TOGETHER' },
    { ja: '完成の合図', en: 'THE SIGNAL OF COMPLETION' }, { ja: '手のあとの残る品', en: 'THE PIECE THAT KEEPS THE HAND' },
    { ja: '小さな相棒', en: 'THE LITTLE PARTNER' }, { ja: '名前をつけた日', en: 'THE DAY WE GAVE A NAME' },
    { ja: 'はじめての散歩', en: 'THE FIRST WALK' }, { ja: 'ひなたの寝顔', en: 'SLEEPING FACE IN THE SUN' },
    { ja: '帰りを待つもの', en: 'THE ONE WHO WAITS' }, { ja: 'ちいさな足あと', en: 'LITTLE FOOTPRINTS' },
    { ja: '巣立ちの朝', en: 'THE MORNING OF LEAVING THE NEST' }, { ja: '群れのゆくえ', en: 'WHERE THE FLOCK GOES' },
    { ja: '冬をこえて', en: 'THROUGH THE WINTER' }, { ja: '春を告げる声', en: 'THE VOICE THAT ANNOUNCES SPRING' },
    { ja: '森の見張り番', en: 'THE WATCHER OF THE FOREST' }, { ja: '川をのぼる日', en: 'THE DAY OF SWIMMING UPSTREAM' },
    { ja: '深海の灯', en: 'THE LIGHT OF THE DEEP SEA' }, { ja: 'まだ見ぬ生きもの', en: 'THE CREATURE YET UNSEEN' },
    { ja: '図鑑の空欄', en: 'THE BLANK IN THE FIELD GUIDE' }, { ja: '標本箱の午後', en: 'AFTERNOON OF THE SPECIMEN BOX' },
    { ja: '顕微鏡のむこう', en: 'BEYOND THE MICROSCOPE' }, { ja: '星をかぞえる夜', en: 'THE NIGHT OF COUNTING STARS' },
    { ja: '空を測る', en: 'MEASURING THE SKY' }, { ja: '雲の名前', en: 'THE NAMES OF CLOUDS' },
    { ja: '雨のできる場所', en: 'WHERE THE RAIN IS BORN' }, { ja: '地層の下の海', en: 'THE SEA BENEATH THE STRATA' },
    { ja: '化石になる前', en: 'BEFORE BECOMING A FOSSIL' }, { ja: '大陸の動く音', en: 'THE SOUND OF DRIFTING LANDS' },
    { ja: '数のむこう側', en: 'THE FAR SIDE OF NUMBERS' }, { ja: '答えのない問い', en: 'THE QUESTION WITHOUT AN ANSWER' },
    { ja: '解けない問題', en: 'THE UNSOLVED PROBLEM' }, { ja: '定理のかたち', en: 'THE SHAPE OF A THEOREM' },
    { ja: 'ひとつの答え', en: 'A SINGLE ANSWER' }, { ja: '百のまちがい', en: 'A HUNDRED MISTAKES' },
    { ja: '覚えるという冒険', en: 'THE ADVENTURE OF LEARNING' }, { ja: '言葉のはじまり', en: 'THE ORIGIN OF WORDS' },
    { ja: '辞書のすきま', en: 'THE GAP IN THE DICTIONARY' }, { ja: '綴りの迷路', en: 'THE MAZE OF SPELLING' },
    { ja: '発音の壁', en: 'THE WALL OF PRONUNCIATION' }, { ja: '通じたひとこと', en: 'THE WORD THAT GOT THROUGH' },
    { ja: '世界の地図をひらく', en: 'OPENING THE WORLD MAP' }, { ja: '国境をこえる線', en: 'THE LINE ACROSS BORDERS' },
    { ja: '川のむこうの国', en: 'THE COUNTRY ACROSS THE RIVER' }, { ja: '旗のいわれ', en: 'THE ORIGIN OF THE FLAG' },
    { ja: '年表のすきま', en: 'THE GAP IN THE CHRONOLOGY' }, { ja: '歴史のうらがわ', en: 'THE UNDERSIDE OF HISTORY' },
    { ja: '古い文字の声', en: 'THE VOICE OF OLD LETTERS' }, { ja: '墨のかおり', en: 'THE SCENT OF INK' },
    { ja: '一字の重み', en: 'THE WEIGHT OF ONE CHARACTER' }, { ja: '書きはじめの朝', en: 'THE MORNING OF FIRST WRITING' },
    { ja: '走る速さの理由', en: 'WHY WE RUN FAST' }, { ja: '泳ぎきる日', en: 'THE DAY OF SWIMMING ACROSS' },
    { ja: '山に登る理由', en: 'WHY WE CLIMB' }, { ja: '糸をたらして', en: 'CASTING THE LINE' },
    { ja: '静かな水面', en: 'THE QUIET WATER' }, { ja: 'かかった手ごたえ', en: 'THE FEEL OF THE STRIKE' },
    { ja: '逃した大物', en: 'THE ONE THAT GOT AWAY' }, { ja: '帰港の灯', en: 'THE LIGHT OF THE RETURNING PORT' },
    { ja: '潮のかわり目', en: 'THE TURNING OF THE TIDE' }, { ja: '線路のつづく先', en: 'WHERE THE RAILS LEAD' },
    { ja: '終着駅の朝', en: 'MORNING AT THE LAST STATION' }, { ja: '発車の合図', en: 'THE DEPARTURE WHISTLE' },
    { ja: '車窓のむこう', en: 'BEYOND THE TRAIN WINDOW' }, { ja: '峠を越える列車', en: 'THE TRAIN OVER THE PASS' },
    { ja: '一番列車', en: 'THE FIRST TRAIN' }, { ja: '最終便の空', en: 'THE SKY OF THE LAST FLIGHT' },
    { ja: '滑走路の朝', en: 'MORNING ON THE RUNWAY' }, { ja: '雲の上の道', en: 'THE ROAD ABOVE THE CLOUDS' },
    { ja: '空港の待合', en: 'THE AIRPORT WAITING AREA' }, { ja: '港のかたすみ', en: 'A CORNER OF THE HARBOR' },
    { ja: '舵をとる手', en: 'THE HAND ON THE HELM' }, { ja: '錨をあげる日', en: 'THE DAY OF WEIGHING ANCHOR' },
    { ja: 'まだ見ぬ港へ', en: 'TO A PORT YET UNSEEN' }, { ja: 'その先の景色', en: 'THE VIEW BEYOND' }
  ],
  latinReading: [
    'THE LEGEND OF', 'THE TALE OF', 'THE ART OF', 'THE WAY OF', 'THE HOUSE OF',
    'THE ISLAND OF', 'THE GARDEN OF', 'THE BOOK OF', 'THE SONG OF', 'THE HEART OF',
    'MASTERS OF', 'KINGS OF', 'ECHOES OF', 'SONGS OF', 'DAYS OF',
    'SEASONS OF', 'TALES FROM', 'LETTERS FROM', 'NOTES FROM', 'VOICES OF',
    'LIGHT OF', 'SHADOW OF', 'RISE OF', 'RETURN OF', 'DAWN OF',
    'EDGE OF', 'SOUL OF', 'SPIRIT OF', 'PATH OF', 'ROAD TO',
    'JOURNEY TO', 'GATEWAY TO', 'BRIDGE TO', 'KEY TO', 'SECRETS OF',
    'WONDERS OF', 'MYSTERIES OF', 'CHRONICLES OF', 'RECORDS OF', 'ANNALS OF',
    'MEMORIES OF', 'DREAMS OF', 'COLORS OF', 'SOUNDS OF', 'RHYTHM OF',
    'PULSE OF', 'BREATH OF', 'TASTE OF', 'SCENT OF', 'TOUCH OF',
    'SHAPE OF', 'WEIGHT OF', 'SPEED OF', 'DEPTH OF', 'HEIGHT OF',
    'CIRCLE OF', 'CROWN OF', 'BANNER OF', 'BLADE OF', 'FLAME OF',
    'FROST OF', 'TIDE OF', 'WIND OF', 'STORM OF', 'STAR OF',
    'MOON OF', 'SUN OF', 'GUARDIANS OF', 'KEEPERS OF', 'CHILDREN OF',
    'SEEKERS OF', 'BUILDERS OF', 'MAKERS OF', 'RIDERS OF', 'SAILORS OF',
    'ADVENTURE', 'COLLECTION', 'CHRONICLE', 'WORLD', 'EXPEDITION',
    'VOYAGE', 'HARVEST', 'WORKSHOP', 'ATELIER', 'GALLERY',
    'ORCHESTRA', 'RHYTHM', 'MELODY', 'HARMONY', 'PUZZLE',
    'MYSTERY', 'DETECTIVE', 'CASEBOOK', 'ALMANAC', 'FIELD NOTES',
    'ENCYCLOPEDIA', 'DIRECTORY', 'HANDBOOK', 'PRIMER', 'ACADEMY',
    'CLASSROOM', 'DOJO', 'ARENA', 'STADIUM', 'CIRCUIT',
    'LEAGUE', 'CHAMPIONS', 'TOURNAMENT', 'TRAINING', 'MASTERY',
    'CRAFT', 'FORGE', 'KITCHEN', 'RECIPE', 'BAKERY',
    'FARM', 'RANCH', 'ORCHARD', 'GREENHOUSE', 'AQUARIUM',
    'ZOOLOGY', 'BOTANY', 'ASTRONOMY', 'GEOLOGY', 'METEOROLOGY',
    'CARTOGRAPHY', 'NAVIGATION', 'RAILWAY', 'LOCOMOTIVE', 'AIRSHIP',
    'SUBMARINE', 'ORBIT', 'GRAVITY', 'FRONTIER', 'HOMESTEAD',
    'VILLAGE', 'TOWNSCAPE', 'HARBOR', 'LIGHTHOUSE', 'SANCTUARY',
    'LABYRINTH', 'DUNGEON', 'CITADEL', 'KINGDOM', 'EMPIRE',
    'ODYSSEY', 'PILGRIMAGE', 'WANDERER', 'TRAVELER', 'EXPLORER',
    'INVENTOR', 'ARTISAN', 'GARDENER', 'ANGLER', 'CLIMBER',
    'RUNNER', 'SWIMMER', 'SKATER', 'DANCER', 'SINGER',
    'PAINTER', 'POTTER', 'WEAVER', 'BAKER', 'BREWER',
    'FARMER', 'SHEPHERD', 'KEEPER', 'GUARDIAN', 'HERALD',
    'ORACLE', 'ALCHEMIST', 'ASTRONOMER', 'ARCHIVIST', 'CURATOR',
    'CONDUCTOR', 'NAVIGATOR', 'ENGINEER', 'ARCHITECT', 'MECHANIC',
    'CARPENTER', 'BLACKSMITH', 'INNKEEPER', 'MERCHANT', 'SCHOLAR',
    'BEYOND THE HORIZON', 'ACROSS THE SEA', 'INTO THE WOODS', 'UNDER THE STARS', 'OVER THE MOUNTAIN',
    'THROUGH THE SEASONS', 'ALONG THE RIVER', 'AROUND THE WORLD', 'BENEATH THE WAVES', 'ABOVE THE CLOUDS',
    'AT THE CROSSROADS', 'BEFORE THE DAWN', 'AFTER THE RAIN', 'BETWEEN TWO SHORES', 'WITHIN THE WALLS',
    'TOWARD THE LIGHT', 'HOMEWARD BOUND', 'ONWARD AND UPWARD', 'FIRST STEPS', 'LAST STAND',
    'NEW HORIZONS', 'OPEN ROAD', 'QUIET DAYS', 'GOLDEN HOURS', 'LITTLE THINGS',
    'EVERYDAY WONDERS', 'SIMPLE JOYS', 'SMALL WORLD', 'GREAT JOURNEY', 'LONG WAY HOME',
    'ONE MORE ROUND', 'PLAY TOGETHER', 'MAKE AND SHARE', 'GROW AND HARVEST', 'BUILD AND BLOOM',
    'LEARN AND PLAY', 'TRAIN AND TRIUMPH', 'SEEK AND FIND', 'RISE AND SHINE', 'READY AND STEADY',
    'THE GRAND TOUR', 'THE LONG SEASON', 'THE FINAL ROUND', 'THE QUIET HOUR', 'THE OPEN FIELD',
    'THE SILENT SEA', 'THE HIDDEN VALLEY', 'THE DISTANT SHORE', 'THE NARROW PATH', 'THE HIGH ROAD',
    'THE OLD TOWN', 'THE NEW WORLD', 'THE FIRST LIGHT', 'THE LAST PAGE', 'THE NEXT CHAPTER'
  ]
};
})(window.PF = window.PF || {});
