(function (PF) {
'use strict';

const TITLE_LEGACY = [
  '{attrWord}{attrWord}{noun}',
  '{attrWord}／{attrWord}／{attrWord}',
  '{adj}{noun}、{n:scenes}連発',
  '{seriesWord}',
  '{noun}＆{tail}',
  '{noun}×{noun}×{noun}',
  '【{attrWord}】{noun}',
  '{noun}＜{attrWord}＞',
  '{attrWord}{noun}{tail}',
  '{adj}{tail}{attrWord}'
];

const TITLE_D1 = [
  '{crown}{personAttr}{personAttr}{situation}{attrWord}{attrWord}{recordWord}{quantityWord}',
  '{crown}{personAttr}{situation}{situation}{attrWord}{attrWord}{recordWord}{quantityWord}',
  '{crown}{crown}{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{personAttr}{personAttr}{personAttr}{situation}{attrWord}{attrWord}{recordWord}{quantityWord}',
  '{crown}{personAttr}{attrWord}{personAttr}{attrWord}{situation}{recordWord}{quantityWord}',
  '{crown}{situation}{personAttr}{personAttr}{attrWord}{recordWord}{quantityWord}{bonusWord}',
  '{crown}{personAttr}{situation}{attrWord}{attrWord}{attrWord}{recordWord}{quantityWord}',
  '{crown}{personAttr}{personAttr}{attrWord}{quantityWord}{situation}{attrWord}{recordWord}',
  '{personAttr}{attrWord}{personAttr}{attrWord}{personAttr}{attrWord}{recordWord}{quantityWord}',
  '{crown}{personAttr}{personAttr}{personAttr}{personAttr}{situation}{recordWord}{quantityWord}',
  '{crown}{attrWord}{personAttr}{situation}{attrWord}{quantityWord}{recordWord}{bonusWord}',
  '{crown}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}{formatWord}',
  '{personAttr}{situation}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{crown}{personAttr}{attrWord}{situation}{situation}{quantityWord}{recordWord}',
  '{crown}{personAttr}{personAttr}{situation}{situation}{situation}{recordWord}{quantityWord}',
  '【{crown}】{personAttr}×{personAttr}／{situation}／{attrWord}／{recordWord}{quantityWord}',
  '【{crown}】{personAttr}{attrWord}／{personAttr}{attrWord}／{situation}／{quantityWord}',
  '【{crown}】{situation}／{situation}／{attrWord}／{personAttr}{recordWord}{quantityWord}',
  '【{crown}】{personAttr}{personAttr}{personAttr}／{attrWord}／{recordWord}／{quantityWord}',
  '【{crown}】{attrWord}{personAttr}／{situation}{attrWord}／{quantityWord}{recordWord}',
  '【{crown}】{personAttr}／{situation}／{attrWord}／{attrWord}／{quantityWord}／{bonusWord}',
  '【{crown}】{personAttr}{situation}{attrWord}／{recordWord}{quantityWord}／{formatWord}',
  '【{crown}】{crown}{personAttr}{attrWord}{situation}／{recordWord}{quantityWord}',
  '【{attrWord}】{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '【{attrWord}】【{attrWord}】{personAttr}{personAttr}{situation}{recordWord}{quantityWord}',
  '＜{crown}＞{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '＜{attrWord}＞{personAttr}{situation}{situation}{attrWord}{recordWord}{quantityWord}',
  '＜{crown}＞{personAttr}{attrWord}＜{attrWord}＞{situation}{recordWord}{quantityWord}',
  '{personAttr}{situation}＜{attrWord}＞{attrWord}{recordWord}{quantityWord}{bonusWord}',
  '＜{crown}＞{situation}{personAttr}{personAttr}{attrWord}{attrWord}{quantityWord}',
  '{personAttr}×{personAttr}×{personAttr}／{situation}／{attrWord}／{recordWord}{quantityWord}',
  '{personAttr}×{personAttr}×{situation}×{attrWord}×{attrWord}／{recordWord}{quantityWord}',
  '{crown}{personAttr}×{crown}{personAttr}／{situation}{attrWord}／{quantityWord}',
  '{attrWord}×{attrWord}×{attrWord}／{personAttr}{situation}{recordWord}{quantityWord}',
  '{situation}×{situation}×{situation}／{personAttr}{attrWord}{recordWord}{quantityWord}',
  '{personAttr}×{situation}×{attrWord}×{recordWord}／{quantityWord}／{bonusWord}',
  '{crown}／{personAttr}×{personAttr}／{attrWord}×{attrWord}／{situation}{quantityWord}',
  '{personAttr}×{personAttr}／{situation}×{situation}／{recordWord}{quantityWord}',
  '{crown}{personAttr}／{situation}／{attrWord}／{recordWord}／{quantityWord}／{bonusWord}',
  '{personAttr}／{personAttr}／{personAttr}／{situation}／{attrWord}／{recordWord}{quantityWord}',
  '{attrWord}／{attrWord}／{attrWord}／{attrWord}／{personAttr}{situation}{quantityWord}',
  '{situation}／{attrWord}／{personAttr}／{recordWord}／{quantityWord}／{formatWord}',
  '{crown}／{attrWord}／{situation}／{personAttr}{personAttr}／{recordWord}{quantityWord}',
  '{personAttr}／{situation}／{situation}／{attrWord}／{attrWord}／{quantityWord}',
  '{crown}／{personAttr}{attrWord}／{personAttr}{attrWord}／{situation}{recordWord}',
  '{personAttr}{attrWord}＋{personAttr}{attrWord}＋{situation}{recordWord}{quantityWord}',
  '{situation}＋{situation}＋{attrWord}＋{personAttr}／{recordWord}{quantityWord}',
  '{crown}＋{personAttr}＋{situation}＋{attrWord}＋{recordWord}＋{quantityWord}',
  '{attrWord}＋{attrWord}＋{attrWord}＋{personAttr}{situation}／{quantityWord}{recordWord}',
  '{personAttr}＋{personAttr}＋{personAttr}＋{situation}{attrWord}{recordWord}{quantityWord}',
  '{personAttr}{situation}＆{personAttr}{situation}／{attrWord}{recordWord}{quantityWord}',
  '{crown}{personAttr}＆{attrWord}{personAttr}／{situation}／{recordWord}{quantityWord}',
  '{attrWord}{personAttr}＆{attrWord}{personAttr}＆{situation}{recordWord}{quantityWord}',
  '{situation}＆{situation}／{personAttr}{attrWord}／{quantityWord}／{bonusWord}',
  '{crown}{personAttr}、{personAttr}、{personAttr}、{situation}{attrWord}{recordWord}{quantityWord}',
  '{personAttr}、{situation}、{attrWord}、{recordWord}、{quantityWord}、{bonusWord}',
  '{crown}、{personAttr}{attrWord}、{situation}{attrWord}、{recordWord}{quantityWord}',
  '{attrWord}、{attrWord}、{attrWord}、{personAttr}{situation}{recordWord}{quantityWord}',
  '{personAttr}{personAttr}、{situation}{situation}、{attrWord}{recordWord}{quantityWord}',
  '{crown}{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}！！',
  '{crown}{personAttr}{situation}{attrWord}{attrWord}{quantityWord}{recordWord}！！',
  '{personAttr}{personAttr}{personAttr}{situation}{attrWord}{attrWord}{recordWord}{quantityWord}！！',
  '【{crown}】{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}！！',
  '{personAttr}×{personAttr}×{personAttr}／{situation}{attrWord}{recordWord}{quantityWord}！！',
  '{crown}{attrWord}{personAttr}{situation}{recordWord}{quantityWord}、ついに{bonusWord}',
  '{crown}{personAttr}{personAttr}{situation}{attrWord}{recordWord}、待望の{quantityWord}',
  '{crown}{personAttr}{personAttr}{attrWord}{situation}、史上初の{quantityWord}',
  '{personAttr}{situation}{attrWord}{attrWord}{recordWord}、前代未聞の{quantityWord}',
  '{crown}{personAttr}{situation}{attrWord}{recordWord}、文句なしの{quantityWord}',
  '{crown}{personAttr}{personAttr}{situation}{attrWord}／全{n:scenes}／{recordWord}{quantityWord}',
  '{crown}{personAttr}{situation}{attrWord}{attrWord}／{n:minutes}／{recordWord}{quantityWord}',
  '{personAttr}{personAttr}{situation}{attrWord}{recordWord}／全{n:scenes}／{n:minutes}',
  '【{crown}】{personAttr}{situation}{attrWord}／{n:hours}／全{n:scenes}／{recordWord}',
  '{personAttr}×{personAttr}／{situation}{attrWord}／全{n:scenes}{recordWord}{quantityWord}',
  '{crown}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}／{n:minutes}／{bonusWord}',
  '{crown}{personAttr}{personAttr}{situation}{attrWord}{recordWord}／{n:hours}{quantityWord}',
  '{attrWord}{attrWord}{personAttr}{situation}／{n:minutes}／{quantityWord}／{formatWord}',
  '{crown}{personAttr}{situation}{attrWord}{quantityWord}{recordWord}／{bonusWord}／{formatWord}',
  '{personAttr}{personAttr}{situation}{attrWord}{attrWord}／{bonusWord}／{quantityWord}',
  '{crown}{personAttr}{attrWord}{situation}{recordWord}{quantityWord}／{formatWord}／{bonusWord}',
  '{crown}{crown}{personAttr}{personAttr}{personAttr}{situation}{situation}{attrWord}{attrWord}{recordWord}{quantityWord}',
  '【{crown}】{personAttr}{personAttr}{personAttr}{situation}{situation}{attrWord}{attrWord}{quantityWord}{recordWord}{bonusWord}',
  '{crown}{personAttr}{attrWord}／{personAttr}{attrWord}／{personAttr}{attrWord}／{situation}{situation}／{recordWord}{quantityWord}',
  '{personAttr}×{personAttr}×{personAttr}×{personAttr}／{situation}×{situation}／{attrWord}{recordWord}{quantityWord}',
  '{crown}{situation}{situation}{situation}{personAttr}{personAttr}{attrWord}{attrWord}{recordWord}{quantityWord}！！',
  '{crown}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}、さらに{bonusWord}{formatWord}',
  '{crown}{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}、そのすべてを{formatWord}',
  '{crown}{personAttr}{situation}{attrWord}{attrWord}{recordWord}、まるごと{quantityWord}',
  '{crown}{personAttr}{personAttr}{situation}{attrWord}、ぜんぶ{recordWord}{quantityWord}',
  '{crown}{personAttr}{situation}{situation}{attrWord}、一挙{quantityWord}{recordWord}',
  '{crown}総勢{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '厳選{personAttr}{personAttr}{situation}{attrWord}{attrWord}{recordWord}{quantityWord}',
  '完全{recordWord}{crown}{personAttr}{situation}{attrWord}{attrWord}{quantityWord}',
  '徹底{recordWord}／{crown}{personAttr}{personAttr}{situation}{attrWord}{quantityWord}',
  '独占{recordWord}／{personAttr}{personAttr}{situation}{attrWord}{attrWord}{quantityWord}',
  '密着{recordWord}／{crown}{personAttr}{situation}{situation}{attrWord}{quantityWord}',
  '{crown}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}【{bonusWord}】',
  '{crown}{personAttr}{personAttr}{attrWord}{situation}{quantityWord}【{formatWord}】',
  '{personAttr}{situation}{attrWord}{attrWord}{recordWord}{quantityWord}＜{bonusWord}＞',
  '{crown}{personAttr}{situation}{attrWord}{recordWord}＜{quantityWord}＞{formatWord}',
  '{crown}{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}・{bonusWord}',
  '{crown}{personAttr}・{personAttr}・{personAttr}／{situation}{attrWord}{recordWord}{quantityWord}',
  '{situation}・{situation}・{attrWord}・{personAttr}{personAttr}{recordWord}{quantityWord}',
  '{attrWord}・{attrWord}・{attrWord}／{crown}{personAttr}{situation}{quantityWord}',
  '{crown}{personAttr}{attrWord}{situation}{recordWord}{quantityWord}｜{bonusWord}｜{formatWord}',
  '{crown}{personAttr}{personAttr}{situation}｜{attrWord}{attrWord}｜{recordWord}{quantityWord}',
  '{personAttr}{situation}｜{personAttr}{situation}｜{attrWord}{recordWord}{quantityWord}',
  '{crown}｜{personAttr}{personAttr}{attrWord}｜{situation}{situation}｜{quantityWord}',
  '{attrWord}｜{personAttr}｜{situation}｜{recordWord}｜{quantityWord}｜{bonusWord}',
  '{crown}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}、{bonusWord}{formatWord}付'
];

const TITLE_D2 = [
  '{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}まで{recordWord}{quantityWord}',
  '{situation}で{event}、{outcome}を{attrWord}{recordWord}{quantityWord}',
  '{crown}{personAttr}が{situation}で{event}、{outcome}を{recordWord}',
  '{situation}で{event}、{outcome}、そのすべてを{recordWord}{quantityWord}',
  '{situation}で{event}、{outcome}を余さず{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}をまるごと{recordWord}',
  '{situation}で{event}、{outcome}をぜんぶ{recordWord}{quantityWord}',
  '{personAttr}を{situation}に迎え、{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}を{situation}へ連れ出し、{event}、{outcome}を{recordWord}',
  '{personAttr}を{situation}で待ち受け、{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}に現れた{personAttr}、{event}、そして{outcome}を{recordWord}',
  '{situation}を訪ねた{personAttr}が{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}を選んだ{personAttr}、{event}から{outcome}までを{recordWord}',
  '{situation}に集まった{personAttr}が{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}で出会った{personAttr}、{event}を経て{outcome}を{recordWord}',
  '{situation}で見つけた{personAttr}が{event}、{outcome}を{attrWord}{recordWord}',
  '{personAttr}が{situation}に挑み、{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}が{situation}を明かし、{event}、{outcome}まで{recordWord}',
  '{personAttr}が{situation}を打ち明け、{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}に至るまでを{recordWord}',
  '{personAttr}が{situation}で{event}、{outcome}へ向かう{recordWord}{quantityWord}',
  '{situation}で{event}、{outcome}へ辿り着くまでを{recordWord}{quantityWord}',
  '{situation}で{event}、{outcome}を迎えるまでの{recordWord}{quantityWord}',
  '{crown}{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{crown}{personAttr}が{situation}で{event}、{outcome}を{attrWord}{recordWord}',
  '【{crown}】{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '【{crown}】{personAttr}が{situation}で{event}、{outcome}を{recordWord}',
  '＜{crown}＞{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{attrWord}{personAttr}が{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{attrWord}{situation}で{event}、{outcome}を{attrWord}{recordWord}{quantityWord}',
  '{personAttr}が{attrWord}{situation}で{event}、{outcome}を{recordWord}',
  '{situation}で{event}、{attrWord}{outcome}を{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}／{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}／{bonusWord}',
  '{situation}で{event}、{outcome}を{recordWord}／{n:minutes}／全{n:scenes}',
  '{situation}で{event}、{outcome}を{recordWord}／{quantityWord}／{formatWord}',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}{quantityWord}／{bonusWord}',
  '{n:hours}、{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{n:minutes}、{personAttr}が{situation}で{event}、{outcome}を{recordWord}',
  '{situation}で{event}、{outcome}を{recordWord}した{n:minutes}{quantityWord}',
  '{situation}で{event}、{outcome}まで{n:hours}{recordWord}{quantityWord}',
  '{situation}で{event}、{outcome}を全{n:scenes}に{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}！！',
  '{situation}で{event}、{outcome}を{recordWord}{quantityWord}！！',
  '{crown}{situation}で{event}、{outcome}を{recordWord}{quantityWord}！！',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}、{quantityWord}！！',
  '{situation}で{event}、{outcome}を{attrWord}{recordWord}{quantityWord}！！',
  '{situation}で{event}、{outcome}を{recordWord}した{personAttr}の{quantityWord}',
  '{situation}で{event}、{outcome}を選んだ{personAttr}を{recordWord}{quantityWord}',
  '{situation}で{event}、{outcome}を受け入れた{personAttr}の{recordWord}',
  '{situation}で{event}、{outcome}を隠さない{personAttr}を{recordWord}{quantityWord}',
  '{situation}で{event}、{outcome}を語り出した{personAttr}の{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を明かした{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を見せた{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を残した{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を越えた{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を掴んだ{recordWord}{quantityWord}',
  '{situation}で{event}、{outcome}。その一部始終を{recordWord}{quantityWord}',
  '{situation}で{event}、{outcome}。すべてを{attrWord}{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}。{recordWord}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}。{quantityWord}／{bonusWord}',
  '{situation}で{event}、{outcome}。{attrWord}{recordWord}／{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}した{attrWord}{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}する{attrWord}{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}し続けた{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}しきった{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}、{bonusWord}{quantityWord}',
  '{personAttr}を{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}を{situation}に呼び出し、{event}、{outcome}を{recordWord}',
  '{personAttr}を{situation}で追いかけ、{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}を{situation}まで見送り、{event}、{outcome}を{recordWord}',
  '{personAttr}を{situation}で見届け、{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}を{situation}に置き去りにして、{event}、{outcome}を{recordWord}',
  '{personAttr}と{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}と{personAttr}が{situation}で{event}、{outcome}を{recordWord}',
  '{personAttr}と{personAttr}、{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}に{situation}を任せ、{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}へ{situation}を持ちかけ、{event}、{outcome}を{recordWord}',
  '{situation}のはずが{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}のつもりが{event}、{outcome}まで{recordWord}{quantityWord}',
  '{situation}だけの約束が{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}で終わるはずが{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}を断れず{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}に流されて{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}をきっかけに{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}をめぐって{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}に誘われて{event}、{outcome}を{recordWord}{quantityWord}',
  '{situation}に立ち会って{event}、{outcome}を{recordWord}{quantityWord}',
  '{crown}{personAttr}、{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{crown}{personAttr}、{situation}を経て{event}、{outcome}を{recordWord}',
  '{personAttr}、{situation}、{event}、{outcome}、そして{recordWord}{quantityWord}',
  '{personAttr}、{situation}で{event}。{outcome}を{recordWord}{quantityWord}',
  '{personAttr}／{situation}／{event}／{outcome}／{recordWord}／{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}した{personAttr}{personAttr}{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}／{attrWord}／{quantityWord}／{formatWord}',
  '{crown}{personAttr}が{situation}で{event}、{outcome}を{recordWord}{quantityWord}／{bonusWord}',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}。{attrWord}{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}。{bonusWord}／{formatWord}',
  '{situation}で{event}、{outcome}を{recordWord}した{n:hours}{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}した全{n:scenes}',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}｜{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}｜{attrWord}｜{quantityWord}',
  '{situation}で{event}、{outcome}を{recordWord}＜{quantityWord}＞',
  '{situation}で{event}、{outcome}を{recordWord}【{bonusWord}】{quantityWord}',
  '{personAttr}が{situation}で{event}、{outcome}を{recordWord}【{quantityWord}】',
  '{attrWord}{personAttr}を{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{personAttr}が{attrWord}{situation}で{event}、{attrWord}{outcome}を{recordWord}{quantityWord}'
];

const TITLE_D3 = [
  '{seriesWord} {personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{seriesWord} {personAttr}{personAttr}{situation}{attrWord}{attrWord}{recordWord}',
  '{seriesWord} {crown}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{seriesWord} {personAttr}{situation}{situation}{recordWord}{quantityWord}',
  '{seriesWord}／{personAttr}{attrWord}{situation}{attrWord}{recordWord}{quantityWord}',
  '{seriesWord}／{personAttr}×{personAttr}／{situation}{recordWord}{quantityWord}',
  '{seriesWord}｜{personAttr}{personAttr}{situation}{attrWord}｜{recordWord}{quantityWord}',
  '【{seriesWord}】{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '＜{seriesWord}＞{personAttr}{situation}{recordWord}{quantityWord}{bonusWord}',
  '{seriesWord} 通算{n:count}作目 {personAttr}{situation}{recordWord}{quantityWord}',
  '{seriesWord} 通算{n:count}作目／{personAttr}{attrWord}{situation}{recordWord}{quantityWord}',
  '{seriesWord}｜{n:edition}｜{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{seriesWord}／{n:edition}／{personAttr}{personAttr}{situation}{recordWord}{quantityWord}',
  '{seriesWord} 祝・{n:anniversary}周年 {personAttr}{situation}{recordWord}{quantityWord}',
  '{seriesWord} {n:anniversary}周年記念／{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{seriesWord} {personAttr}{situation}で{event}、{outcome}を{recordWord}',
  '{seriesWord} {personAttr}が{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{seriesWord}／{situation}で{event}、{outcome}を{recordWord}{quantityWord}',
  '{seriesWord} {situation}から{outcome}まで、{personAttr}を{recordWord}{quantityWord}',
  '{seriesWord} {personAttr}{situation}{attrWord}{recordWord}／全{n:scenes}／{n:minutes}',
  '{seriesWord} {personAttr}{situation}{attrWord}{recordWord}／{n:hours}／{quantityWord}',
  '{seriesWord} {personAttr}{personAttr}{situation}{attrWord}{quantityWord}／{bonusWord}',
  '{seriesWord} {crown}{personAttr}{personAttr}{attrWord}{situation}{recordWord}{quantityWord}！！',
  '{seriesWord} {personAttr}{situation}{attrWord}{recordWord}{quantityWord}！！',
  '{seriesWord}、ついに{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{seriesWord}、待望の{personAttr}{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{seriesWord}、史上最多の{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{seriesWord}、最長{n:minutes}の{personAttr}{situation}{recordWord}{quantityWord}',
  '{seriesWord} {personAttr}{situation}{attrWord}{recordWord}【{bonusWord}】',
  '{seriesWord} {personAttr}{situation}{recordWord}{quantityWord}＜{formatWord}＞',
  '{seriesWord} {attrWord}{attrWord}{personAttr}{situation}{recordWord}{quantityWord}',
  '{seriesWord}／{crown}／{personAttr}{situation}／{attrWord}／{recordWord}{quantityWord}',
  '{seriesWord} 総勢{personAttr}{personAttr}{situation}{attrWord}{quantityWord}',
  '{seriesWord} 厳選{personAttr}{situation}{attrWord}{recordWord}{quantityWord}',
  '{seriesWord} {personAttr}{situation}{attrWord}{recordWord}{quantityWord}、そして{bonusWord}'
];

const TITLE_D4 = [
  '{situation}から{outcome}まで、{personAttr}をすべて{recordWord}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}{personAttr}を{recordWord}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}を{attrWord}{recordWord}{quantityWord}',
  '{situation}から{outcome}まで、{attrWord}{personAttr}を{recordWord}{quantityWord}',
  '{situation}から{event}、{outcome}まで、{personAttr}を{recordWord}',
  '{situation}から{event}を経て{outcome}まで、{personAttr}を{recordWord}{quantityWord}',
  '{crown}{situation}から{outcome}まで、{personAttr}を{recordWord}{quantityWord}',
  '【{crown}】{situation}から{outcome}まで、{personAttr}を{recordWord}{quantityWord}',
  '{attrWord}{personAttr}の{situation}から{outcome}までを{recordWord}{quantityWord}',
  '{personAttr}の{situation}から{outcome}まで、{attrWord}{recordWord}{quantityWord}',
  '{personAttr}が{situation}から{outcome}へ至るまでを{recordWord}{quantityWord}',
  '{situation}から{outcome}へ、{personAttr}{personAttr}の{recordWord}{quantityWord}',
  '{situation}から{outcome}へ、{attrWord}{attrWord}{personAttr}を{recordWord}',
  '{n:hours}、{situation}から{outcome}まで{personAttr}を{recordWord}{quantityWord}',
  '{n:minutes}、{situation}から{outcome}まで{personAttr}を{recordWord}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}を{recordWord}した{n:minutes}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}を全{n:scenes}に{recordWord}',
  '{situation}から{outcome}まで、{personAttr}を{recordWord}／{n:minutes}／{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}を{recordWord}／{bonusWord}／{formatWord}',
  '{situation}から{outcome}まで、{personAttr}を{recordWord}{quantityWord}！！',
  '{situation}から{outcome}まで、{personAttr}を余さず{recordWord}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}をまるごと{recordWord}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}をぜんぶ{recordWord}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}を一挙{recordWord}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}を徹底{recordWord}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}を密着{recordWord}{quantityWord}',
  '{situation}のはじまりから{outcome}のおわりまで、{personAttr}を{recordWord}',
  '{situation}の当日から{outcome}の翌朝まで、{personAttr}を{recordWord}{quantityWord}',
  '{situation}の直前から{outcome}の直後まで、{personAttr}を{recordWord}{quantityWord}',
  '{situation}の初日から{outcome}の最終日まで、{personAttr}を{recordWord}',
  '{situation}の朝から{outcome}の夜まで、{personAttr}{personAttr}を{recordWord}{quantityWord}',
  '{situation}から{event}まで、{outcome}を{recordWord}した{personAttr}{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}を{recordWord}｜{attrWord}｜{quantityWord}',
  '{situation}から{outcome}まで、{personAttr}を{recordWord}【{bonusWord}】{quantityWord}',
  '{crown}{situation}から{outcome}まで、{personAttr}{personAttr}を{attrWord}{recordWord}{quantityWord}',
  '{seriesWord}／{situation}から{outcome}まで、{personAttr}を{recordWord}{quantityWord}'
];

const MEGA_SPEC = [
  '{n:minutes}／全{n:scenes}／{attrWord}／{bonusWord}',
  '{n:code}／{n:minutes}／{formatWord}／{attrWord}',
  '本編{n:minutes}＋特典{n:bonusMinutes}／全{n:scenes}／{attrWord}',
  '{seriesWord}／{bonusWord}／{n:minutes}／全{n:scenes}',
  '{attrWord}＋{attrWord}＋{attrWord}／{n:minutes}',
  '{n:hours}収録／{bonusWord}／{formatWord}／全{n:scenes}',
  '{n:minutes}／全{n:scenes}／{bonusWord}／{formatWord}',
  '{n:minutes}／全{n:scenes}／{attrWord}／{formatWord}',
  '{n:minutes}／全{n:scenes}／{recordWord}／{bonusWord}',
  '{n:minutes}／全{n:scenes}／{quantityWord}／{attrWord}',
  '{n:minutes}／{attrWord}／{attrWord}／{bonusWord}',
  '{n:minutes}／{formatWord}／{bonusWord}／{attrWord}',
  '{n:minutes}／{recordWord}／{quantityWord}／{formatWord}',
  '{n:minutes}｜全{n:scenes}｜{attrWord}｜{bonusWord}',
  '{n:minutes}｜{formatWord}｜{attrWord}｜{recordWord}',
  '{n:minutes}｜{bonusWord}｜{quantityWord}｜{attrWord}',
  '{n:minutes}・全{n:scenes}・{attrWord}・{bonusWord}',
  '{n:minutes}・{formatWord}・{bonusWord}・{recordWord}',
  '収録時間 {n:minutes}／全{n:scenes}／{attrWord}／{bonusWord}',
  '収録時間 {n:minutes}／{formatWord}／{attrWord}／{bonusWord}',
  '収録時間 {n:minutes}／{bonusWord}／{quantityWord}',
  '収録時間 {n:minutes}｜全{n:scenes}｜{formatWord}',
  '収録時間 {n:minutes}／{n:code}／{attrWord}',
  '総収録{n:minutes}／全{n:scenes}／{attrWord}／{bonusWord}',
  '総収録{n:minutes}／{bonusWord}／{formatWord}／{attrWord}',
  '総収録{n:minutes}／{recordWord}／{quantityWord}',
  '長尺{n:minutes}／全{n:scenes}／{attrWord}／{bonusWord}',
  '長尺{n:minutes}／{bonusWord}／{formatWord}／{recordWord}',
  '{n:minutes}／全{n:scenes}／{attrWord}／{attrWord}／{bonusWord}',
  '{n:minutes}／全{n:scenes}／{bonusWord}／{n:code}',
  '{n:code}／{n:minutes}／全{n:scenes}／{attrWord}',
  '{n:code}／{n:minutes}／{bonusWord}／{formatWord}',
  '{n:code}／{n:minutes}／{recordWord}／{quantityWord}',
  '{n:code}／全{n:scenes}／{attrWord}／{bonusWord}',
  '{n:code}／{formatWord}／{attrWord}／{quantityWord}',
  '{n:code}｜{n:minutes}｜全{n:scenes}｜{attrWord}',
  '{n:code}｜{n:minutes}｜{bonusWord}｜{formatWord}',
  '{n:code}｜{formatWord}｜{recordWord}｜{attrWord}',
  '{n:code}・{n:minutes}・全{n:scenes}・{bonusWord}',
  '{n:code}・{formatWord}・{attrWord}・{bonusWord}',
  '品番 {n:code}／{n:minutes}／全{n:scenes}／{attrWord}',
  '品番 {n:code}／{n:minutes}／{bonusWord}',
  '品番 {n:code}／{formatWord}／{quantityWord}',
  '品番 {n:code}｜{n:minutes}｜{formatWord}',
  '品番 {n:code}／全{n:scenes}／{recordWord}',
  '規格 {formatWord}／{n:code}／{n:minutes}／{attrWord}',
  '規格 {formatWord}／{n:minutes}／全{n:scenes}',
  '規格 {formatWord}／{bonusWord}／{quantityWord}',
  '{n:code}／{seriesWord}／{n:minutes}／{attrWord}',
  '{n:code}／{seriesWord}／{formatWord}',
  '本編{n:minutes}＋特典{n:bonusMinutes}／{formatWord}／{attrWord}',
  '本編{n:minutes}＋特典{n:bonusMinutes}／{bonusWord}／{recordWord}',
  '本編{n:minutes}＋特典{n:bonusMinutes}／{n:code}／{attrWord}',
  '本編{n:minutes}＋特典{n:bonusMinutes}／{quantityWord}／{attrWord}',
  '本編{n:minutes}＋特典{n:bonusMinutes}｜全{n:scenes}｜{formatWord}',
  '本編{n:minutes}＋特典{n:bonusMinutes}｜{attrWord}｜{bonusWord}',
  '本編{n:minutes}＋特典{n:bonusMinutes}・全{n:scenes}・{attrWord}',
  '本編{n:minutes}／特典{n:bonusMinutes}／全{n:scenes}／{attrWord}',
  '本編{n:minutes}／特典{n:bonusMinutes}／{bonusWord}／{formatWord}',
  '本編{n:minutes}／特典{n:bonusMinutes}／{recordWord}／{quantityWord}',
  '本編{n:minutes}／全{n:scenes}／{attrWord}／{bonusWord}',
  '本編{n:minutes}／全{n:scenes}／{formatWord}／{recordWord}',
  '本編{n:minutes}／{n:code}／{attrWord}／{bonusWord}',
  '本編{n:minutes}｜特典{n:bonusMinutes}｜{formatWord}｜{attrWord}',
  '本編{n:minutes}＋特典{n:bonusMinutes}＋{bonusWord}／{attrWord}',
  '本編＋特典 計{n:minutes}／全{n:scenes}／{attrWord}',
  '本編＋特典 計{n:minutes}／{bonusWord}／{formatWord}',
  '本編＋特典 計{n:minutes}｜{attrWord}｜{quantityWord}',
  '特典{n:bonusMinutes}追加／本編{n:minutes}／全{n:scenes}',
  '特典{n:bonusMinutes}追加／{attrWord}／{bonusWord}／{formatWord}',
  '特典映像{n:bonusMinutes}／本編{n:minutes}／{attrWord}',
  '特典映像{n:bonusMinutes}／{formatWord}／{quantityWord}',
  '特典ディスク付／本編{n:minutes}／全{n:scenes}／{attrWord}',
  '特典ディスク付／{n:minutes}／{formatWord}／{recordWord}',
  '{n:hours}／全{n:scenes}／{attrWord}／{bonusWord}',
  '{n:hours}／{formatWord}／{bonusWord}／{attrWord}',
  '{n:hours}／{recordWord}／{quantityWord}／{attrWord}',
  '{n:hours}／{n:code}／{attrWord}／{bonusWord}',
  '{n:hours}｜全{n:scenes}｜{attrWord}｜{formatWord}',
  '{n:hours}｜{bonusWord}｜{recordWord}｜{quantityWord}',
  '{n:hours}・全{n:scenes}・{bonusWord}・{attrWord}',
  '{n:hours}収録／全{n:scenes}／{attrWord}／{quantityWord}',
  '{n:hours}収録／{n:code}／{formatWord}／{attrWord}',
  '{n:hours}収録／{recordWord}／{bonusWord}／{attrWord}',
  '{n:hours}超／全{n:scenes}／{attrWord}／{bonusWord}',
  '{n:hours}超／{formatWord}／{recordWord}／{quantityWord}',
  '{n:hours}／{n:minutes}追加／{attrWord}／{bonusWord}',
  '{n:hours}ノーカット／全{n:scenes}／{attrWord}',
  '{n:hours}ノーカット／{bonusWord}／{formatWord}',
  '{n:hours}一挙／全{n:scenes}／{recordWord}／{attrWord}',
  '{n:hours}一挙／{quantityWord}／{bonusWord}',
  '{n:hours}／{seriesWord}／{attrWord}／{bonusWord}',
  '{n:hours}／{seriesWord}／{formatWord}／{quantityWord}',
  '{attrWord}／{attrWord}／{n:minutes}／全{n:scenes}',
  '{attrWord}／{attrWord}／{bonusWord}／{formatWord}',
  '{attrWord}／{attrWord}／{recordWord}／{quantityWord}',
  '{attrWord}／{bonusWord}／{n:minutes}／全{n:scenes}',
  '{attrWord}／{bonusWord}／{formatWord}／{n:code}',
  '{attrWord}／{formatWord}／{n:minutes}／{quantityWord}',
  '{attrWord}｜{attrWord}｜{n:minutes}｜{bonusWord}',
  '{attrWord}｜{bonusWord}｜{formatWord}｜全{n:scenes}',
  '{attrWord}｜{recordWord}｜{quantityWord}｜{n:minutes}',
  '{attrWord}・{attrWord}・{bonusWord}・{n:minutes}',
  '{attrWord}＋{bonusWord}＋{formatWord}／{n:minutes}',
  '{attrWord}＋{attrWord}／全{n:scenes}／{bonusWord}',
  '{bonusWord}／{n:minutes}／全{n:scenes}／{attrWord}',
  '{bonusWord}／{formatWord}／{n:minutes}／{recordWord}',
  '{bonusWord}／{attrWord}／{quantityWord}／{n:code}',
  '{bonusWord}／{bonusWord}／{n:minutes}／{formatWord}',
  '{bonusWord}｜{n:minutes}｜全{n:scenes}｜{formatWord}',
  '{bonusWord}｜{attrWord}｜{recordWord}｜{n:hours}',
  '{bonusWord}・{n:minutes}・{attrWord}・{formatWord}',
  '{formatWord}／{n:minutes}／全{n:scenes}／{attrWord}',
  '{formatWord}／{n:code}／{n:minutes}／{bonusWord}',
  '{formatWord}／{attrWord}／{quantityWord}／{recordWord}',
  '{formatWord}／{bonusWord}／{n:hours}／{attrWord}',
  '{formatWord}｜{n:minutes}｜{attrWord}｜{bonusWord}',
  '{formatWord}｜全{n:scenes}｜{recordWord}｜{quantityWord}',
  '{formatWord}・{n:minutes}・{bonusWord}・{attrWord}',
  '{formatWord}＋{bonusWord}／{n:minutes}／全{n:scenes}',
  '{recordWord}／{n:minutes}／全{n:scenes}／{attrWord}',
  '{recordWord}／{quantityWord}／{bonusWord}／{formatWord}',
  '{recordWord}／{attrWord}／{n:hours}／{n:code}',
  '{recordWord}｜{n:minutes}｜{bonusWord}｜{attrWord}',
  '{recordWord}・{quantityWord}・{n:minutes}・{formatWord}',
  '{quantityWord}／{n:minutes}／{attrWord}／{bonusWord}',
  '{quantityWord}／全{n:scenes}／{formatWord}／{recordWord}',
  '{quantityWord}／{attrWord}／{n:hours}／{bonusWord}',
  '{quantityWord}｜{n:minutes}｜{formatWord}｜{attrWord}',
  '{quantityWord}・{bonusWord}・{n:minutes}・全{n:scenes}',
  '{seriesWord}／{n:minutes}／全{n:scenes}／{attrWord}',
  '{seriesWord}／{n:code}／{n:minutes}／{bonusWord}',
  '{seriesWord}／{attrWord}／{formatWord}／{quantityWord}',
  '{seriesWord}／{n:hours}／{bonusWord}／{recordWord}',
  '{seriesWord}｜{n:minutes}｜{attrWord}｜{bonusWord}',
  '{seriesWord}｜全{n:scenes}｜{formatWord}｜{recordWord}',
  '{seriesWord}・{n:minutes}・{bonusWord}・{attrWord}',
  '全{n:scenes}／{n:minutes}／{attrWord}／{bonusWord}',
  '全{n:scenes}／{n:code}／{formatWord}／{recordWord}',
  '全{n:scenes}／{attrWord}／{bonusWord}／{quantityWord}',
  '全{n:scenes}／{n:hours}／{formatWord}／{attrWord}',
  '全{n:scenes}｜{n:minutes}｜{bonusWord}｜{attrWord}',
  '全{n:scenes}｜{recordWord}｜{formatWord}｜{quantityWord}',
  '全{n:scenes}収録／{n:minutes}／{attrWord}／{bonusWord}',
  '全{n:scenes}収録／{formatWord}／{recordWord}',
  '全{n:scenes}一挙／{n:minutes}／{bonusWord}／{attrWord}',
  '全{n:scenes}厳選／{n:hours}／{formatWord}',
  '{n:minutes}／{n:code}／{n:date}発売',
  '{n:minutes}／全{n:scenes}／{n:price}（税込）',
  '{n:code}／{n:minutes}／{n:price}（税込）／{attrWord}'
];

const MEGA_TAIL = [
  '{makerName}｜{n:code}',
  '{labelName}／{n:code}',
  '{makerName}　{n:date}発売',
  '{labelName}｜{seriesWord}',
  '{makerName}／{labelName}',
  '{makerName}／{n:code}',
  '{makerName}・{n:code}',
  '{makerName}　{n:code}',
  '{labelName}｜{n:code}',
  '{labelName}・{n:code}',
  '{labelName}　{n:code}',
  '{makerName}／品番 {n:code}',
  '{labelName}／品番 {n:code}',
  '{makerName}｜品番 {n:code}',
  '{labelName}｜品番 {n:code}',
  '品番 {n:code}／{makerName}',
  '品番 {n:code}／{labelName}',
  '品番 {n:code}｜{makerName}',
  '品番 {n:code}｜{labelName}',
  '{makerName}／{labelName}／{n:code}',
  '{makerName}｜{labelName}｜{n:code}',
  '{makerName}・{labelName}・{n:code}',
  '{labelName}／{makerName}／{n:code}',
  '{labelName}｜{makerName}',
  '{labelName}・{makerName}',
  '{makerName}　{labelName}',
  '発売元 {makerName}｜{n:minutes}',
  '発売元 {labelName}｜{n:minutes}',
  '発売元 {makerName}／{n:code}',
  '発売元 {labelName}／{n:code}',
  '販売元 {makerName}／{labelName}',
  '販売元 {labelName}｜{n:code}',
  '販売元 {makerName}／{n:code}',
  '企画 {makerName}／{n:code}',
  '企画 {labelName}／{n:code}',
  '企画・制作 {makerName}／{n:code}',
  '企画・制作 {labelName}／{n:minutes}',
  '制作 {makerName}／{n:code}',
  '制作 {labelName}／{n:code}',
  '提供 {makerName}／{labelName}',
  'レーベル {labelName}｜{n:minutes}',
  'レーベル {labelName}／{n:code}',
  'レーベル {labelName}｜{seriesWord}',
  '{makerName}｜{seriesWord}',
  '{makerName}／{seriesWord}',
  '{makerName}・{seriesWord}',
  '{labelName}／{seriesWord}',
  '{labelName}・{seriesWord}',
  '{seriesWord}／{makerName}',
  '{seriesWord}／{labelName}',
  '{seriesWord}｜{n:code}',
  '{seriesWord}／{n:code}',
  '{seriesWord}｜{makerName}',
  '{seriesWord}｜{labelName}',
  '{makerName}　{n:date}',
  '{labelName}　{n:date}',
  '{makerName}／{n:date}発売',
  '{labelName}／{n:date}発売',
  '{makerName}｜{n:date}発売',
  '{labelName}｜{n:date}発売',
  '{n:date}発売／{makerName}',
  '{n:date}発売／{labelName}',
  '{n:date}発売｜{n:code}',
  '{n:code}／{n:date}発売',
  '{n:code}｜{n:date}発売',
  '{n:code}／{makerName}',
  '{n:code}／{labelName}',
  '{n:code}｜{makerName}',
  '{n:code}｜{labelName}',
  '{n:code}・{makerName}',
  '{makerName}／{n:price}（税込）',
  '{labelName}／{n:price}（税込）',
  '{n:code}／{n:price}（税込）',
  '{n:price}（税込）／{makerName}',
  '{n:price}（税込）／{labelName}',
  '{makerName}／{formatWord}',
  '{labelName}／{formatWord}',
  '{makerName}｜{formatWord}',
  '{labelName}｜{formatWord}',
  '{formatWord}／{makerName}',
  '{formatWord}／{labelName}',
  '{formatWord}／{n:code}',
  '{formatWord}｜{n:code}',
  '{makerName}／{bonusWord}',
  '{labelName}／{bonusWord}',
  '{bonusWord}／{makerName}',
  '{bonusWord}／{labelName}',
  '{bonusWord}｜{n:code}',
  '{makerName}／{labelName}／{seriesWord}',
  '{makerName}｜{labelName}｜{seriesWord}',
  '{makerName}｜{n:year}｜{n:code}',
  '{makerName}／{n:year}／{n:code}',
  '{labelName}｜{n:code}｜{n:year}',
  '{makerName}／{n:code}／{formatWord}',
  '{labelName}／{n:code}／{formatWord}',
  '{makerName}／{n:code}／{bonusWord}',
  '{labelName}／{n:code}／{bonusWord}',
  '{seriesWord}／{n:code}／{makerName}',
  '{seriesWord}｜{n:code}｜{labelName}',
  '{makerName} 企画・制作／{n:code}',
  '{labelName} 企画・制作',
  '{makerName} 制作／{n:code}',
  '{labelName} 制作／{n:code}',
  '{makerName} 提供／{n:code}',
  '{labelName} 提供／{n:code}',
  '{makerName}　{n:price}（税込）',
  '{labelName}　{n:price}（税込）',
  '{n:code}　{n:price}（税込）',
  '{n:code}　{n:minutes}収録',
  '{makerName}／{n:minutes}収録',
  '{labelName}／{n:minutes}収録',
  '{n:code}／{n:minutes}／{makerName}',
  '{n:code}｜{n:minutes}｜{labelName}',
  '{makerName}／{n:edition}／{n:code}',
  '{labelName}／{n:edition}',
  '{n:edition}／{n:code}',
  '{n:edition}｜{makerName}｜{n:code}',
  '{n:edition}｜{labelName}｜{n:code}',
  '{makerName}／{n:year}制作',
  '{labelName}／{n:year}制作',
  '{n:year}制作／{n:code}'
];

const TAG = [
  '{seriesWord}', '{makerName}／{labelName}', '{labelName}', '{makerName}',
  '{labelName}｜{seriesWord}', '{makerName}｜{seriesWord}', '{seriesWord}／{labelName}',
  '{seriesWord}／{makerName}', '{labelName}／{seriesWord}', '{makerName}・{labelName}',
  '{labelName}・{seriesWord}', '{makerName}　{seriesWord}', '{labelName}　{seriesWord}',
  '{seriesWord}｜{n:edition}', '{seriesWord}／{n:edition}', '{seriesWord} 第{n:seriesNo}弾',
  '{seriesWord} 通算{n:count}作目', '{seriesWord} {n:anniversary}周年', '{seriesWord} 最新作',
  '{makerName} {seriesWord}', '{labelName} {seriesWord}', '{makerName} 最新作',
  '{labelName} 最新作', '{makerName} 新作', '{labelName} 新作',
  '{makerName} 企画', '{labelName} 企画', '{makerName} 制作',
  '{labelName} 制作', '{makerName} 提供', '{labelName} 提供',
  '発売元 {makerName}', '発売元 {labelName}', '販売元 {makerName}',
  'レーベル {labelName}', '企画・制作 {makerName}', '企画・制作 {labelName}',
  '{crown} {seriesWord}', '{crown}／{seriesWord}', '{crown}｜{labelName}',
  '{crown}｜{makerName}', '{attrWord}／{seriesWord}', '{attrWord}｜{labelName}',
  '{seriesWord}｜{attrWord}', '{seriesWord}／{attrWord}', '{seriesWord}｜{bonusWord}',
  '{seriesWord}／{bonusWord}', '{seriesWord}｜{formatWord}', '{seriesWord}／{formatWord}',
  '{labelName}｜{formatWord}', '{makerName}｜{formatWord}', '{labelName}／{bonusWord}',
  '{makerName}／{bonusWord}', '{seriesWord}｜{n:code}', '{seriesWord}／{n:code}',
  '{labelName}｜{n:code}', '{makerName}｜{n:code}', '{n:code}／{seriesWord}',
  '{seriesWord} 待望の続編', '{seriesWord} ついに再始動', '{seriesWord} 続篇登場',
  '{seriesWord}／{n:date}', '{labelName}／{n:date}', '{makerName}／{n:date}',
  '{seriesWord}　{n:minutes}', '{labelName}　{n:minutes}', '{makerName}　全{n:scenes}',
  '{seriesWord}｜全{n:scenes}', '{seriesWord}／{n:hours}', '{labelName}｜{n:hours}',
  '{crown}{seriesWord}', '{crown}{labelName}', '{crown}{makerName}',
  '{seriesWord}｜{quantityWord}', '{seriesWord}／{recordWord}', '{labelName}｜{recordWord}',
  '{makerName}／{recordWord}', '{makerName}｜{quantityWord}', '{labelName}／{quantityWord}',
  '{seriesWord}｜{personAttr}', '{seriesWord}／{situation}'
];

const BADGE = [
  '{sashWord}',
  '{sashWord}！！', '【{crown}】{sashWord}', '{crown}／{sashWord}',
  '{crown}！！{sashWord}', '{sashWord}／{crown}', '{sashWord}｜{crown}',
  '{sashWord}／{quantityWord}', '{sashWord}｜{quantityWord}', '{quantityWord}／{sashWord}',
  '{sashWord}／{attrWord}', '{sashWord}｜{attrWord}', '{attrWord}／{sashWord}',
  '{sashWord}／{bonusWord}', '{sashWord}｜{bonusWord}', '{bonusWord}／{sashWord}',

  '{crown}！！', '{crown}、ついに！！', '{crown}が到着！！',
  '{crown}を冠して登場！！', '{crown}、堂々登場！！', '{crown}、緊急発売！！',
  '{quantityWord}！！', '{quantityWord}を一挙収録！！', '{quantityWord}、達成！！',
  '{quantityWord}を突破！！', '{quantityWord}で登場！！', '{quantityWord}、堂々収録！！',
  '{attrWord}！！', '{attrWord}、ついに解禁！！', '{attrWord}で登場！！',
  '{attrWord}を全編に！！', '{attrWord}＋{attrWord}！！', '{attrWord}／{attrWord}！！',
  '{recordWord}！！', '{recordWord}、ついに完成！！', '{recordWord}で登場！！',
  '{bonusWord}！！', '{bonusWord}付で登場！！', '{bonusWord}、数量限定！！',
  '{formatWord}！！', '{formatWord}で登場！！', '{formatWord}に対応！！',

  '全{n:scenes}収録！！', '全{n:scenes}を一挙！！', '全{n:scenes}、完全収録！！',
  '全{n:scenes}まるごと！！', '全{n:scenes}すべて新規！！', '全{n:scenes}を厳選！！',
  '{n:minutes}収録！！', '{n:minutes}の大容量！！', '{n:minutes}ノーカット！！',
  '{n:minutes}を一本に！！', '本編{n:minutes}！！', '本編＋特典{n:minutes}！！',
  '{n:hours}収録！！', '{n:hours}ぶっ通し！！', '{n:hours}の大容量！！',
  '{n:hours}一気に！！', '{n:hours}を超える収録！！', '{n:hours}ノーカット！！',
  '特典{n:bonusMinutes}追加！！', '特典映像{n:bonusMinutes}！！', '未公開{n:bonusMinutes}追加！！',

  '祝・{n:anniversary}周年！！', '{n:anniversary}周年記念！！', '{n:anniversary}周年の特別企画！！',
  'シリーズ第{n:seriesNo}弾！！', '待望の第{n:seriesNo}弾！！', '第{n:seriesNo}弾、始動！！',
  'シリーズ通算{n:count}作目！！', '累計{n:count}作を突破！！', 'シリーズ{n:count}作目！！',
  '{n:week}売上第一位！！', '{n:week}上位を維持！！', '{n:price}（税込）！！',
  '{n:date} 発売！！', '{n:date} 一斉発売！！', '{n:date} 解禁！！',
  '品番 {n:code}！！', '{n:edition} 登場！！', '{n:edition} 発売中！！',

  'ついに解禁！！', 'ついに登場！！', 'ついに完成！！',
  'ついに商品化！！', 'いよいよ登場！！', 'いよいよ解禁！！',
  '待望の登場！！', '待望の続編！！', '待望の完全版！！',
  '緊急発売決定！！', '緊急増産決定！！', '緊急出荷！！',
  '数量限定！！', '数量限定でお届け！！', '限定{n:count}本！！',
  '在庫僅少！！', '在庫限り！！', '完売必至！！',
  '予約受付中！！', '予約殺到中！！', '予約はお早めに！！',
  '好評につき再入荷！！', '好評につき増産！！', '好評発売中！！',
  '発売即完売！！', '発売初週で完売！！', '再入荷分も残りわずか！！',
  '見逃し厳禁！！', '買い逃し厳禁！！', '要チェック！！',
  '完全保存版！！', '永久保存版！！', '完全版！！',
  '総集編！！', '新装版！！', '再編集版！！',
  '増補版！！', '決定版！！', '最新作！！',
  'シリーズ最新作！！', 'シリーズ最長！！', 'シリーズ最多！！',
  'シリーズ最大！！', 'シリーズ最高評価！！', 'シリーズ屈指！！',
  '初回限定！！', '初回限定特典付！！', '初回盤のみ！！',
  '店舗限定！！', '通販限定！！', '数量限定特典付！！',
  '全国一斉！！', '全国同時発売！！', '全国主要店舗で展開！！',
  '配信同時開始！！', '配信先行公開中！！', 'パッケージ版・配信版 同時！！',
  '価格据え置き！！', '特別価格！！', 'この価格は今回限り！！',
  '過去最長！！', '過去最多！！', '過去最大！！',
  '前作超え！！', '前作を大きく上回る！！', '前作比{n:few}倍！！',
  '大ヒット御礼！！', '話題沸騰中！！', '注目度は今期随一！！',
  'ノーカット収録！！', '無編集収録！！', '完全収録！！',
  '一挙収録！！', 'まるごと収録！！', '余さず収録！！',
  '厳選収録！！', '徹底収録！！', '密着収録！！',
  '独占収録！！', '未公開分を追加！！', '新規収録あり！！',
  '再販未定！！', '追加生産なし！！', '次回未定！！',
  'いま買うべき一本！！', 'この機を逃さずに！！', 'お早めにどうぞ！！'
];

const CREDIT = [
  '{makerName}／{labelName}',
  '出演 {person}　{makerName}',
  '出演 {person}\n{makerName}／{labelName}',
  '出演 {person}',
  '出演 {person}　{person}',
  '出演 {person}　{person}　{person}',
  '出演 {person}／{makerName}',
  '出演 {person}｜{labelName}',
  '出演 {person}　{labelName}',
  '出演 {person}　{person}／{makerName}',
  '出演 {person}　{person}｜{labelName}',
  '出演 {person}\n{makerName}',
  '出演 {person}\n{labelName}',
  '出演 {person}　{person}\n{makerName}／{labelName}',
  '出演 {person}　{person}　{person}\n{makerName}',
  '出演者 {person}／{makerName}',
  '出演者 {person}　{person}',
  '出演者 {person}　{person}　{person}',
  '{person}　{makerName}',
  '{person}　{labelName}',
  '{person}／{makerName}',
  '{person}｜{labelName}',
  '{person}　{person}／{makerName}',
  '{person}　{person}　{person}／{labelName}',
  '{person}\n{makerName}／{labelName}',
  '{person}　{person}\n{makerName}／{labelName}',
  '{person}　{makerName}／{n:code}',
  '{person}　{labelName}／{n:code}',
  '出演 {person}　品番 {n:code}',
  '出演 {person}　{makerName}／{n:code}',
  '出演 {person}　{labelName}／{n:code}',
  '出演 {person}／{seriesWord}',
  '出演 {person}　{seriesWord}',
  '出演 {person}\n{seriesWord}／{makerName}',
  '{makerName}｜{labelName}',
  '{makerName}・{labelName}',
  '{makerName}　{labelName}',
  '{makerName}／{labelName}／{n:code}',
  '{makerName}｜{labelName}｜{n:code}',
  '発売元 {makerName}',
  '発売元 {makerName}／{labelName}',
  '発売元 {makerName}　販売元 {labelName}',
  '販売元 {labelName}',
  '企画・制作 {makerName}',
  '企画・制作 {makerName}／{labelName}',
  '企画 {makerName}　制作 {labelName}',
  '制作 {makerName}',
  '制作 {labelName}／{n:code}',
  '提供 {makerName}／{labelName}',
  'レーベル {labelName}',
  'レーベル {labelName}／{makerName}',
  '出演 {person}\n発売元 {makerName}',
  '出演 {person}\n企画・制作 {labelName}',
  '出演 {person}　{person}\n発売元 {makerName}',
  '出演 {person}\n{makerName}／{labelName}／{n:code}',
  '出演 {person}　{person}　{person}\n{labelName}',
  '{person}　{person}　{person}　{makerName}',
  '{person}　{person}　{person}　{person}',
  '{person}　{person}　{person}　{person}／{makerName}',
  '出演 {person}　{person}　{person}　{person}'
];

const RELEASE = [
  '収録時間 {n:minutes}　{n:date}発売　{n:price}（税込）',
  '本編{n:minutes}＋特典{n:bonusMinutes}　{n:date}発売',
  '{n:hours} 収録／{n:date}／{n:price}（税込）',
  '{n:minutes}／{n:date}／{n:price}（税込）',
  '{n:code}／{n:minutes}／{n:date}発売',
  '{n:code}／{n:minutes}／{n:price}（税込）',
  '{n:code}／{n:date}発売／{n:price}（税込）',
  '{n:code}｜{n:minutes}｜{n:price}（税込）',
  '{n:code}　{n:minutes}　{n:date}発売',
  '品番 {n:code}／収録 {n:minutes}／{n:price}（税込）',
  '品番 {n:code}／{n:date}発売／{n:price}（税込）',
  '品番 {n:code}　{n:minutes}　{n:price}（税込）',
  '品番 {n:code}／{n:minutes}／全{n:scenes}',
  '品番 {n:code}｜{n:date}発売',
  '品番 {n:code}｜{n:price}（税込）',
  '収録時間 {n:minutes}／{n:date}発売',
  '収録時間 {n:minutes}／{n:price}（税込）',
  '収録時間 {n:minutes}／{n:code}',
  '収録時間 {n:minutes}／全{n:scenes}／{n:price}（税込）',
  '収録時間 {n:minutes}　全{n:scenes}　{n:date}発売',
  '収録 {n:hours}／{n:date}発売／{n:price}（税込）',
  '収録 {n:hours}／{n:code}／{n:price}（税込）',
  '{n:hours}／{n:date}発売／{n:code}',
  '{n:hours}／全{n:scenes}／{n:price}（税込）',
  '{n:hours}　{n:date}発売　{n:price}（税込）',
  '本編{n:minutes}＋特典{n:bonusMinutes}／{n:price}（税込）',
  '本編{n:minutes}＋特典{n:bonusMinutes}／{n:code}',
  '本編{n:minutes}＋特典{n:bonusMinutes}／全{n:scenes}',
  '本編{n:minutes}／特典{n:bonusMinutes}／{n:date}発売',
  '本編{n:minutes}／特典{n:bonusMinutes}／{n:price}（税込）',
  '本編{n:minutes}　特典{n:bonusMinutes}　{n:code}',
  '本編＋特典 計{n:minutes}／{n:date}発売',
  '本編＋特典 計{n:minutes}／{n:price}（税込）',
  '本編＋特典 計{n:minutes}／{n:code}',
  '全{n:scenes}／{n:minutes}／{n:date}発売',
  '全{n:scenes}／{n:minutes}／{n:price}（税込）',
  '全{n:scenes}／{n:code}／{n:price}（税込）',
  '全{n:scenes}　{n:minutes}　{n:code}',
  '全{n:scenes}収録／{n:minutes}／{n:date}発売',
  '全{n:scenes}収録／{n:hours}／{n:price}（税込）',
  '{n:date}発売　{n:price}（税込）　{n:minutes}',
  '{n:date}発売　{n:price}（税込）　{n:code}',
  '{n:date}発売／{n:minutes}／{n:code}',
  '{n:date}発売／{n:hours}／{n:code}',
  '{n:date}発売／全{n:scenes}／{n:price}（税込）',
  '{n:date}発売　収録時間 {n:minutes}',
  '{n:date}発売　品番 {n:code}',
  '{n:date}発売　{n:price}（税込）',
  '{n:date} 一斉発売／{n:minutes}／{n:price}（税込）',
  '{n:date} 全国発売／{n:code}／{n:minutes}',
  '{n:price}（税込）／{n:minutes}／{n:code}',
  '{n:price}（税込）／{n:date}発売／{n:minutes}',
  '{n:price}（税込）／全{n:scenes}／{n:code}',
  '{n:price}（税込）　{n:minutes}　{n:date}発売',
  '価格 {n:price}（税込）／収録 {n:minutes}',
  '価格 {n:price}（税込）／品番 {n:code}',
  '価格 {n:price}（税込）／{n:date}発売',
  '希望小売価格 {n:price}（税込）',
  '希望小売価格 {n:price}（税込）／{n:code}',
  '{formatWord}／{n:minutes}／{n:price}（税込）',
  '{formatWord}／{n:code}／{n:date}発売',
  '{formatWord}／{n:minutes}／{n:code}',
  '{formatWord}｜{n:date}発売｜{n:price}（税込）',
  '規格 {formatWord}／{n:code}／{n:minutes}',
  '規格 {formatWord}／{n:price}（税込）',
  '{n:code}／{n:minutes}／{n:date}／{n:price}（税込）',
  '{n:code}｜{n:minutes}｜{n:date}｜{n:price}',
  '{makerName}／{n:code}／{n:date}発売',
  '{labelName}／{n:code}／{n:price}（税込）',
  '{makerName}／{n:minutes}／{n:price}（税込）',
  '{labelName}／{n:minutes}／{n:date}発売',
  '発売元 {makerName}／{n:date}発売',
  '発売元 {labelName}／{n:price}（税込）',
  '{seriesWord}／{n:code}／{n:date}発売',
  '{seriesWord}／{n:minutes}／{n:price}（税込）',
  '{n:edition}／{n:code}／{n:price}（税込）',
  '{n:edition}／{n:minutes}／{n:date}発売',
  '{n:year}制作／{n:minutes}／{n:code}',
  '{n:year}制作／{n:date}発売／{n:price}（税込）',
  '{bonusWord}／{n:minutes}／{n:price}（税込）',
  '{bonusWord}／{n:code}／{n:date}発売'
];

const EXTRA = [
  '{noticeWord}', '{noticeWord}／{n:code}', '{formatWord}', '{makerName}',
  '{noticeWord}｜{n:code}', '{noticeWord}／{makerName}', '{noticeWord}｜{makerName}',
  '{noticeWord}／{labelName}', '{noticeWord}｜{labelName}', '{noticeWord}／{formatWord}',
  '{noticeWord}｜{formatWord}', '{noticeWord}／{n:date}', '{noticeWord}｜{n:year}',
  '{noticeWord}　{n:code}', '{noticeWord}　{makerName}', '{noticeWord}　{labelName}',
  '18歳未満の方は購入できません', '18歳未満の方への販売は行いません', '18歳未満の方の購入・鑑賞は禁止です',
  '18歳未満の方は購入できません／{n:code}', '18歳未満の方は購入できません｜{makerName}', '年齢確認が必要な商品です',
  '年齢制限のある商品です', '対象年齢をご確認のうえお求めください', '成人向け商品です',
  '成人向け商品につき取扱にご注意ください', '本商品は成人を対象としています', '出演者は全て20歳以上です',
  '出演者は全て20歳以上であることを確認済です', '出演者の年齢確認を実施しています', '本作品はフィクションです',
  '本作品はフィクションであり実在の人物とは関係ありません', '登場する人物・団体はすべて架空です', '本作品の内容はすべて創作です',
  '商品の仕様は予告なく変更になる場合があります', '収録内容は予告なく変更になる場合があります', 'パッケージ写真は実物と異なる場合があります',
  '画像は実物と異なる場合があります', '価格は予告なく変更になる場合があります', '特典は数量限定です',
  '特典は無くなり次第終了します', '無断複製・上映・貸与を禁じます', '無断転載を禁じます',
  '複製・配布を禁じます', '個人利用の範囲でお楽しみください', '業務用利用はできません',
  '再生には対応機器が必要です', '一部映像に補正処理を行っています', '一部に伏せ字表記があります',
  '表記の一部を変更しています', '画質は収録素材に依存します', '音量差が生じる場合があります',
  '{n:code}', '{n:code}／{formatWord}', '{n:code}｜{makerName}',
  '{labelName}', '{labelName}／{formatWord}', '{makerName}／{labelName}'
];

const CLAUSE_A = [
  '{bonusWord}', '{seriesWord}', '{formatWord}',
  '本編{n:minutes}', '全{n:scenes}収録', '品番 {n:code}',
  '{labelName} 制作', '{n:date} 発売', '{n:week}売上第一位',
  '{n:edition} 発売中', 'パッケージ版・配信版 同時展開', '特典ディスク付',
  '収録時間 {n:minutes}', 'シリーズ累計{n:count}作', '新装ジャケット仕様',
  '通常版も同日発売', '予約受付中', 'オンライン先行公開',
  '本編＋特典 計{n:minutes}', '出演者コメント収録', '{n:few}作連続リリース',
  '好評につき再入荷', 'デジタル版 配信中', 'ジャケット違い{n:few}種',
  '店舗特典あり', '長編{n:minutes}', '未収録カット追加', '在庫僅少',

  '本編のみで{n:minutes}', '総収録{n:minutes}', '総尺{n:minutes}',
  '長尺{n:minutes}', '収録時間は{n:minutes}', '{n:hours}収録',
  '{n:hours}超の長編', '{n:hours}を一気に収録', '{n:hours}ノーカット収録',
  '全{n:scenes}を一挙収録', '全{n:scenes}を厳選収録', '全{n:scenes}の見どころ',
  '本編＋特典で{n:minutes}', '本編{n:minutes}＋特典{n:bonusMinutes}', '特典映像{n:bonusMinutes}収録',
  '特典{n:bonusMinutes}を追加収録', '未収録カット{n:bonusMinutes}追加', '追加収録{n:bonusMinutes}',
  '未公開部分{n:bonusMinutes}収録', '分割なしで{n:minutes}収録', '{n:few}枚組で{n:minutes}',
  '{n:few}部構成で{n:minutes}', '全{n:scenes}を{n:few}枚に収録', '収録内容を全面的に再構成',
  '編集を一から組み直し', '尺の都合で未収録だった場面も追加', '新規収録{n:bonusMinutes}',
  '既発分{n:minutes}に追加収録', '全編{n:minutes}', '全編ノーカット',
  '全編を通しで収録', '通しで{n:hours}', '章立て{n:few}部構成',
  '全{n:few}章構成', '見どころを全{n:scenes}に整理', '無編集で{n:minutes}',
  '収録は{n:few}日間', '撮影日数{n:few}日', '{n:few}日間の収録から抜粋',
  '収録量を大幅に増補', '前作比で{n:minutes}増', '前作より{n:bonusMinutes}長い収録',
  '高画質のまま{n:minutes}', '高音質で{n:minutes}', '{n:minutes}を一本に集約',

  '品番 {n:code} で登録', '規格 {formatWord}', '{formatWord}仕様',
  '{formatWord}で収録', '両面ジャケット仕様', '特製スリーブ仕様',
  '紙ジャケット仕様', '{n:few}面デジパック仕様', '差し替えジャケット同梱',
  'ケース背に品番表示', '品番は {n:code}', '規格表記は{formatWord}',
  '{formatWord}／{formatWord} の{n:few}規格', '{n:few}枚組ケース入り', '厚型ケース仕様',
  '薄型ケース仕様', 'スリムケース採用', '外箱付きの特装仕様',
  '帯付き初回仕様', '再生環境の目安を記載', 'メニュー画面から章送り可能',
  '字幕の表示切替に対応', '音声の切替に対応', '静止画資料を同梱',

  '{n:date} 全国一斉発売', '{n:date} より順次発売', '{n:date} 出荷開始',
  '{n:date} 店頭に並びます', '全国主要店舗で展開', '主要店舗で先行展開',
  '取扱店舗は順次拡大', '通信販売のみの取扱', '一部店舗のみの取扱',
  '専門店限定の取扱', '予約は各店で受付中', '予約受付は{n:date}まで',
  '発売前から予約多数', '店頭在庫は残りわずか', '追加出荷を手配中',
  '出荷本数を追加', '再出荷は{n:date}予定', '流通在庫は限定数',
  '一般流通に先行して展開', '発売日は地域により前後', '入荷数は店舗により異なります',
  '取り置き対応の店舗あり', '全国{n:count}店舗で展開', '{n:count}店舗で先行販売',

  'シリーズ通算{n:count}作目', 'シリーズ第{n:seriesNo}弾', 'シリーズ{n:anniversary}周年',
  '前作から{n:few}か月', '続編{n:few}作同時展開', '姉妹作も同時発売',
  'シリーズ既刊{n:count}作', 'シリーズ全{n:count}作を継続中', '第{n:seriesNo}弾として登場',
  '{n:anniversary}周年記念作', '{n:anniversary}周年の節目に', 'シリーズ初の{formatWord}',
  'シリーズ初の{n:minutes}', 'シリーズ通算{n:count}作到達', '通算{n:count}作目の節目',
  '前作の続きを収録', '前作と併せて楽しめる構成', '第{n:seriesNo}弾までを再編集',
  'シリーズ第{n:seriesNo}弾を同時発売', '過去作からも抜粋収録', 'シリーズ順の通し番号付',
  '関連作は全{n:count}作', 'シリーズ共通の仕様', 'シリーズを通して品番連番',

  '初回封入特典あり', '特典ディスク同梱', '店舗別特典あり',
  '予約特典あり', '早期購入特典付', '解説書封入',
  'ブックレット封入', 'ポストカード封入', '生写真封入',
  '特製ケース入り', '特典は数量限定', '特典は無くなり次第終了',
  '初回出荷分のみ特典付', '購入特典を店頭で配布', '応募券封入',
  '特典応募は{n:date}まで', '通販限定特典あり', '特典映像を追加',
  '特典音声を追加', '特典画像データ同梱', '特典は初回盤のみ',
  '{bonusWord}を同梱', '{bonusWord}を封入', '{bonusWord}が付属',
  '特典内容は予告なく変更の場合あり', '特典は{n:few}種から選択', '特典ステッカー封入',

  '{labelName} 提供', '{makerName} 企画', '{makerName} 制作',
  '{makerName}／{labelName} 共同制作', '企画・制作 {labelName}', '完全撮り下ろし',
  '撮り下ろし{n:few}日間', 'インタビュー同時収録', 'メイキング同時収録',
  '未公開部分を再編集', '出演者本人の解説付', '出演者選定に{n:few}か月',
  '企画立案から{n:few}年', '制作体制を一新', '制作は{labelName}が担当',
  '{makerName} の新機軸', '{labelName} の看板企画', '{makerName} が総力を投入',
  '編集は本編と別班が担当', '撮影は{n:few}班体制', '企画会議を{n:count}回',

  '配信先行公開中', '配信版も同時公開', '配信は{n:date}開始',
  '高画質版も配信中', 'ダウンロード版同時発売', '配信版は特典映像なし',
  '配信版とパッケージ版で内容が一部異なります', '配信は主要各所で展開', '見放題の対象作品',
  '単品配信にも対応', '配信版の品番は別番号', 'パッケージ版のみの映像あり',
  '配信開始と同時に話題', '配信ランキング上位', '配信は{n:count}か所で展開',

  '{n:week}売上上位', '発売即完売', '予約殺到',
  '問い合わせ多数', '増産決定', '緊急増産',
  '出荷本数が想定を超過', '発売初週で完売の店舗多数', '再入荷分も即完売',
  '各所で話題沸騰', '発売前から注目度が高い一本', '{n:count}店舗で在庫切れ',
  '同時期の話題作', '{n:week}上位を維持', '売上{n:count}位以内を継続',
  '前作を超える初動', '注文数は前作の{n:few}倍', '想定の{n:few}倍の出荷',

  '新装版', '再編集版', '廉価版として再発売',
  '通常版は{n:date}発売', '初回盤と通常盤の{n:few}形態', '限定盤は数量限定',
  '装丁を一新して再登場', '旧版から内容を追加', '旧版の品番から変更',
  '版を改めて再発売', '仕様変更版として登場', '再プレス分を出荷',
  '完全版として再構成', '総集編として再編集', '未収録分を加えた増補版',
  '{n:edition} として発売', '{n:edition} を同時展開', '旧版をお持ちの方にも新規映像あり',

  '数量限定', '限定{n:count}本', '価格 {n:price}（税込）',
  '特別価格 {n:price}', '価格据え置き', '{n:price} で発売',
  '税込 {n:price}', '希望小売価格 {n:price}', '本体価格は税別表示',
  '限定数に達し次第終了', '在庫限りの取扱', '追加生産の予定なし',
  '再販の予定は未定', '価格改定前の最終出荷', '同時購入割引あり',
  '{n:few}本同時購入で割引', 'まとめ買い対応', '送料込みの通販価格',

  '{attrWord}を収録', '{attrWord}／{attrWord} を併録', '{attrWord}で構成',
  '{recordWord}として収録', '{recordWord}を軸に構成', '{quantityWord}を確保',
  '{quantityWord}に到達', '{crown}として登場', '{crown}を冠した一本',
  '{personAttr}が登場', '{personAttr}{personAttr} が出演', '{personAttr}を起用',
  '{situation}を舞台に収録', '{situation}を中心に構成', '{situation}／{situation} を収録',
  '{event}を収録', '{outcome}まで収録', '{event}から{outcome}までを収録',

  '発売日確定', '仕様確定', '内容確定',
  '情報解禁', '{n:date} 情報解禁', '本日より情報公開',
  'ジャケット公開', '収録内容を公開', '一部映像を先行公開',
  '予告映像を公開中', '見本盤を各店に配布', '店頭見本の設置あり',
  '公式情報は随時更新', '仕様は決定次第告知', '発売延期の予定なし',

  '{n:year}の話題作', '{n:year}{n:date} 発売', '年内最後の新作',
  '年始第一弾', '今期の目玉', '今期最多の収録量',
  '今月の新作', '今月{n:count}作目', '月{n:few}作の展開',
  '四半期の目玉企画', '上半期の話題作', '下半期の目玉',

  '再生には対応機器が必要です', '一部映像に補正処理あり', '画質は収録素材によります',
  '音声は収録時のままです', '一部に伏せ字表記あり', '表記の一部を変更しています',
  '編集の都合で場面が前後します', '原素材の状態により画質が変動します', '収録機材の都合で音量差があります',

  '{formatWord}／{bonusWord} の組合せ', '{formatWord}と{attrWord}を両立', '{bonusWord}と{attrWord}を同時収録',
  '{seriesWord}／{formatWord}', '{seriesWord}｜{bonusWord}', '{seriesWord}と同時展開',
  '{labelName}｜{n:code}', '{makerName}｜{n:date}', '{labelName}／{n:price}（税込）',

  '{n:minutes}／{n:price}（税込）', '{n:code}／{n:date}', '全{n:scenes}／{n:minutes}',
  '{n:hours}／{n:price}（税込）', '本編{n:minutes}／特典{n:bonusMinutes}', '{n:date}／{n:code}',

  '注目の一本', '今期の注目作', '各所で紹介された一本',
  '取扱店から反響多数', '購入者からの反響多数', '感想が続々',
  '評価が定着した一本', '評価の高い企画', '定番として定着',
  '継続して展開中の企画', '長く支持される構成', '安定した人気の一本',

  '構成を刷新', '見どころを凝縮', '見どころを余さず収録',
  '要所を厳選', '要点を整理して収録', '流れがわかる構成',
  '章ごとに整理', '場面ごとに区切って収録', '早送りせずに見られる構成',
  '通して見られる長さ', '区切りよく視聴できる構成', '章送りで見たい場面へ',

  '出演{n:few}名', '総勢{n:count}名が参加', '出演者は全{n:few}名',
  '{personAttr}を{n:few}名起用', '{personAttr}が{n:count}名参加', '出演者を公募',
  '出演者情報は順次公開', '出演者名はケース裏に記載', '出演者の詳細は本編内で紹介',

  '{n:code} として登録済', '{n:code}｜{n:minutes}', '{n:code}｜全{n:scenes}',
  '{n:code}／{formatWord}', '{n:code}／{bonusWord}', '{n:code}・{n:price}（税込）',

  '固定カメラと手持ちの併用', 'カメラ{n:few}台で同時収録', '{n:few}方向から同時収録',
  '据置と可動の{n:few}系統で収録', '長回しを多用した構成', '寄りと引きを織り交ぜた構成',
  '照明を場面ごとに変更', '自然光を活かした収録', '暗所も明るく補正',
  '手ぶれ補正を適用', '色調整を全編に実施', '発色を調整して再収録',
  '音声は別収録して同期', '環境音を整理して収録', '雑音を低減して収録',
  '解像度を上げて再収録', '既存素材を高精細化', '旧作素材を修復して収録',

  '購入者アンケートを実施', '反響を受けて追加展開', '要望の多かった構成',
  '要望に応えた{n:minutes}', '寄せられた意見を反映', '前作の反省点を改善',
  '見づらかった箇所を再編集', '指摘のあった箇所を修正', '仕様を見直して再登場',

  '保存用の予備をおすすめ', '長期保存に向く仕様', 'コレクション向けの装丁',
  '通し番号入りの限定仕様', 'シリアル入り初回盤', '背表紙を揃えられる装丁',
  '棚に並べて楽しめる背デザイン', 'シリーズで統一した意匠', '連番で揃う品番表記',

  'ケース裏に収録内容を記載', 'ケース裏に品番表示', 'ケース裏に注記を記載',
  '外装に年齢制限表示', '外装フィルムに注意書き', '帯に収録時間を記載',
  '帯に発売日と価格を記載', 'ジャケット表に規格表記', 'ジャケット裏に章立てを記載',

  '{crown}{personAttr} が登場', '{crown}／{attrWord}', '{crown}｜{recordWord}',
  '{attrWord}｜{attrWord}', '{attrWord}／{quantityWord}', '{attrWord}／{recordWord}',
  '{recordWord}／{quantityWord}', '{quantityWord}／{bonusWord}', '{recordWord}｜{formatWord}',
  '{situation}を{recordWord}', '{event}を{recordWord}', '{outcome}を{recordWord}',
  '{personAttr}を{recordWord}', '{personAttr}／{situation}', '{situation}／{event}',
  '{event}／{outcome}', '{personAttr}×{personAttr}', '{situation}×{situation}',

  '本編は章立てで進行', '構成は{n:few}部に分割', '前半と後半で構成を変更',
  '導入部を新規に収録', '締めの場面を追加', '幕間の映像を追加',
  '冒頭に解説を追加', '巻末に資料を追加', '各章に見出しを付与',

  '発売元の在庫は限定数', '取次経由でも取扱', '一部地域は取扱なし',
  '海外向けの取扱なし', '国内流通のみ', '正規流通品のみの取扱',
  '中古流通は対象外', '返品交換は不良品のみ', '初期不良は交換対応',

  '{n:date} 予約開始', '{n:date} 予約締切', '{n:date} 出荷分より仕様変更',
  '{n:date} まで特別価格', '{n:date} 以降は通常価格', '{n:date} 情報追加',
  '{n:date} 店頭展開開始', '{n:date} 通販開始', '{n:date} 配信終了予定',

  '{n:count}名の制作陣が参加', '制作期間{n:few}か月', '編集期間{n:few}週間',
  '企画から発売まで{n:few}年', '準備に{n:few}か月', '検討を{n:count}回重ねた企画',

  '見どころは全{n:scenes}', '注目場面を全{n:scenes}に収録', '厳選した{n:scenes}を収録',
  '{n:scenes}すべてが新規', '{n:scenes}中{n:few}が未公開', '未公開分を{n:few}割追加',

  '価格は税込表示', '価格は変更となる場合があります', '価格は発売時点のものです',
  '仕様は予告なく変更となる場合があります', '収録内容は変更となる場合があります', '画像は実物と異なる場合があります',

  '同時発売作あり', '同時発売は{n:few}作', '関連作も同日発売',
  '併売作品あり', '前作も同時展開', '過去作も再出荷',

  '本編の再生に必要な容量を記載', '章一覧をケース内に封入', '収録順は本編内で表示',
  '{makerName} の最新企画', '{labelName} の新シリーズ', '{makerName}／{labelName} 共同企画',
  '{makerName} が{n:anniversary}周年', '{labelName} が{n:count}作目', '{seriesWord} と同一規格',
  '{bonusWord}｜{formatWord}', '{bonusWord}／{n:minutes}', '{formatWord}／全{n:scenes}',
  '{n:minutes}／{bonusWord}', '{n:hours}／{formatWord}', '全{n:scenes}／{attrWord}',
  '{n:price}（税込）／{formatWord}'
];

const CLAUSE_B = [
  '見逃し厳禁', '数量限定につきお早めに', '待望の登場',
  'いま、話題沸騰', 'シリーズ最高評価', '完全保存版',
  'ファン必携の一本', '徹底収録', '永久保存の決定版',
  'ついに解禁', '大ヒット御礼', '緊急増産',
  '今すぐチェック', '発売即完売', '待たせすぎた最新作',
  '全国一斉展開', '予約受付中', '特典なくなり次第終了',
  '文句なしの決定版', 'この一本で完結', 'シリーズ屈指の収録量',
  '見どころ満載', '初回盤のみの仕様', '再販未定',
  'コレクター必見', '圧倒的な収録量', '価格据え置き',
  '販売店舗限定',

  '在庫限りの特別価格', 'シリーズ最多の収録数', 'シリーズ最長の収録時間',
  'シリーズ最大の企画', 'シリーズ最多の出演者数', 'シリーズ最厚の解説書付',
  'シリーズ最速の完売ペース', 'シリーズ史上の分量', 'シリーズを代表する一本',
  'シリーズの決定版', 'シリーズの集大成', 'シリーズの総決算',
  'シリーズの原点', 'シリーズの到達点', 'シリーズ最新の仕様',

  '保存必至の一本', '手元に置きたい一本', '棚に並べたい一本',
  '買い逃し厳禁', '取り置き推奨', '早めの確保をおすすめ',
  '完売前にお求めください', '在庫のあるうちに', '売り切れ必至',
  '追加生産の予定なし', '再入荷は未定', '次回出荷は未定',
  '限定数のみの出荷', '限りある在庫', '今回限りの出荷分',

  '文句のつけようがない構成', '妥協なしの構成', '手抜きなしの構成',
  '出し惜しみなし', '出し惜しみのない収録量', '余すところなく収録',
  'まるごと収録', 'ぜんぶ収録', '一部始終を収録',
  '通しで楽しめる一本', '最後まで目が離せない', '最初から最後まで',

  'いま最も注目の一本', '各所で話題', '評価急上昇中',
  '感想が続々到着', '購入者の評価が高い一本', 'リピーター続出',
  '追加注文が止まらない', '問い合わせが殺到', '取扱店から反響多数',
  '注目度は今期随一', '今期の話題を独占', '注目を集める一本',

  '待望の続編', '待ちに待った一本', 'ようやくの登場',
  'いよいよ登場', 'ついに登場', 'ついに完成',
  'ついに商品化', 'ついに規格化', 'ついにパッケージ化',
  '構想から{n:few}年', '{n:few}年ぶりの新作', '{n:count}作目にして最高峰',

  '初回盤限定の特別仕様', '初回盤のみの特典付', '初回出荷分限定',
  '初回分は特別価格', '初回限定の装丁', '初回のみの封入特典',
  '限定盤は数量限りの出荷', '限定仕様につきお早めに', '通常盤との違いは特典',
  '通常盤も同時展開', '通常盤は後日発売', '両形態とも数量限定',

  '{n:minutes}の大容量', '{n:hours}の大容量', '全{n:scenes}の充実',
  '本編{n:minutes}の長編', '特典{n:bonusMinutes}を追加', '本編＋特典で{n:minutes}',
  '{n:minutes}を一本に', '{n:hours}を一気に', '全{n:scenes}を一挙に',
  '{n:minutes}分の見応え', '{n:hours}分の見応え', '見応えのある{n:minutes}',

  '{n:price}（税込）で登場', '{n:price} は据え置き', '価格以上の収録量',
  '価格改定前の最終出荷', 'この価格でこの分量', 'お求めやすい価格設定',
  '税込 {n:price} のまま', '価格そのままで増量', '実質値下げの増量版',

  '品番 {n:code} で登場', '{n:code} でお求めください', '品番のお間違いなく',
  '{n:date} 発売', '{n:date} 一斉発売', '{n:date} をお楽しみに',
  '発売日は {n:date}', '{n:date} より順次', '{n:date} 店頭へ',

  '{makerName} の自信作', '{labelName} の自信作', '{makerName} の総力作',
  '{labelName} の看板作', '{makerName} が贈る一本', '{labelName} が贈る最新作',
  '{makerName} の最高峰', '{labelName} の最高傑作', '{makerName}／{labelName} の共作',

  '{bonusWord}付', '{bonusWord}で登場', '{bonusWord}を同梱',
  '{formatWord}で登場', '{formatWord}に対応', '{formatWord}を採用',
  '{attrWord}の決定版', '{attrWord}を徹底', '{attrWord}で構成',
  '{seriesWord}として登場', '{seriesWord}が到着', '{quantityWord}を実現',
  '{recordWord}として完成', '{crown}の名にふさわしい一本', '{personAttr}が勢揃い',

  'この分量でこの価格', 'この構成は他にない', 'ここまでやった一本',
  'ここでしか見られない構成', 'ほかでは手に入らない仕様', '唯一無二の構成',
  '前例のない収録量', '前作を大きく上回る', '前作超えは確実',
  '過去最大の企画', '過去最長の収録', '過去最多の出演者',

  '納得の一本', '満足度の高い一本', '損をしない一本',
  '間違いのない選択', '安心して選べる一本', '迷ったらこの一本',
  'まず手に取るべき一本', '最初の一本に最適', '入門にも最適',
  '長く楽しめる一本', '何度でも見返せる構成', '見返すたびに発見',

  'お早めにどうぞ', 'ぜひお手元に', 'ぜひご確認ください',
  'この機会をお見逃しなく', 'この機を逃さずに', '早い者勝ち',
  'お求めはお早めに', '今回限りの機会', '次はいつになるか未定',

  '完全版として登場', '総集編として登場', '増補版として登場',
  '新装版として登場', '再編集版として登場', '決定版として登場',
  '保存版として登場', '完全収録版', '無編集収録版',

  '全国の主要店舗で', '取扱店舗は各所で拡大中', '通販でもお求めいただけます',
  '一部店舗のみの取扱', '専門店でのみお取扱', '取扱店にてご確認ください',
  '在庫は各店にお問い合わせください', '取り寄せ対応の店舗あり', '予約はお近くの店舗で',

  '見た人から広がる評判', '口コミで拡大中', '紹介記事が続々',
  '取り上げられる機会が増加', '注目の集まる企画', '評価が定着した一本',
  '定番として定着', '長く支持される一本', '安定した人気',

  '一切の妥協なし', '細部まで作り込み', '仕上げまで丁寧に',
  '編集にこだわった一本', '構成にこだわった一本', '画質にこだわった一本',
  '音質にこだわった一本', '装丁にこだわった一本', '仕様にこだわった一本',

  '{n:week}上位を継続', '{n:count}店舗で完売', '出荷{n:count}本を突破',
  '予約数が前作の{n:few}倍', '想定の{n:few}倍の反響', '初動は前作超え',
  '発売初週で在庫僅少', '発売{n:few}日で追加出荷', '再入荷分も残りわずか',

  'これ以上ない構成', 'これ以上望めない収録量', 'これで決まり',
  'これが本命', 'これが本編', 'これがすべて',
  'まさに決定版', 'まさに保存版', 'まさに集大成',

  'お見逃しなく', '要チェック', '要確認',
  '必見', '必携', '必収蔵',
  '見て損なし', '買って損なし', '持っていて損なし',

  '{n:anniversary}周年の記念作', '{n:anniversary}周年記念の特別仕様', '{n:anniversary}周年を飾る一本',
  '通算{n:count}作目の到達点', '第{n:seriesNo}弾にして最高', 'シリーズ第{n:seriesNo}弾も準備中',
  '次回作にもご期待ください', '続編も企画進行中', 'シリーズはまだ続きます',

  '完全収録でお届け', 'ノーカットでお届け', '一挙にお届け',
  'まとめてお届け', '余さずお届け', '丸ごとお届け',
  '厳選してお届け', '整理してお届け', '見やすくしてお届け',

  '手に取ればわかる一本', '見ればわかる分量', '比べればわかる差',
  '数字で見てもわかる収録量', '仕様表を見れば一目瞭然', '内容量は表記のとおり',
  '誇張なしの収録量', '表記どおりの分量', '中身で勝負',

  '内容は本編でご確認ください', '詳細は収録内容をご覧ください', '仕様は外装の表記をご確認ください',
  '年齢制限表示をご確認のうえお求めください', '購入前に注記をご確認ください', '対象年齢をご確認ください',

  '{attrWord}｜{attrWord}', '{attrWord}／{bonusWord}', '{bonusWord}／{formatWord}',
  '{recordWord}／{attrWord}', '{quantityWord}／{attrWord}', '{formatWord}／{quantityWord}',

  '文句なしの分量', '文句なしの仕様', '文句なしの構成',
  '納得の収録量', '納得の価格', '納得の仕上がり',
  '期待を超える一本', '期待どおりの一本', '期待以上の分量',

  '本命の一本', '筆頭の一本', '一番手の一本',
  '今期の本命', '今期の筆頭', '今期の目玉',
  '年間の目玉企画', '年間屈指の分量', '年間を代表する一本',

  'いまなら在庫あり', 'いまなら特典付', 'いまなら特別価格',
  'いまが買い時', 'いま手に入る最後の機会', 'いま押さえるべき一本',

  '{situation}を余さず', '{event}まで収録', '{outcome}まで到達',
  '{personAttr}の全て', '{personAttr}を余さず', '{situation}から{outcome}まで',

  '完成度で選ぶならこれ', '分量で選ぶならこれ', '価格で選ぶならこれ',
  '仕様で選ぶならこれ', '構成で選ぶならこれ', '保存性で選ぶならこれ',

  '取り扱い各店で好評', '各店で品薄', '各店で追加発注',
  '店頭で目立つ装丁', '棚映えする装丁', '手に取りやすい仕様',

  '長尺だから見応えあり', '大容量だから満足', '多収録だから飽きない',
  '章立てだから見やすい', '整理されているから探しやすい', '通しでも分割でも',

  'この一本で十分', 'この一本があれば', 'この一本から',
  '最初に選ぶならこれ', '最後まで残しておきたい一本', '手放せない一本',

  '待望の一本がここに', '待望の企画が実現', '待望の仕様で登場',
  '念願の商品化', '念願の長尺化', '念願の再収録',
  '悲願の完全版', '悲願のシリーズ化', '悲願の増補',

  '在庫を確保しました', '十分な数をご用意', '数に限りがあります',
  '追加分をご用意', '再入荷分をご用意', '予約枠を拡大しました',
  '出荷を前倒ししました', '出荷数を増やしました', '生産数を引き上げました',

  '{n:minutes}を余すことなく', '{n:hours}を余すことなく', '全{n:scenes}を余すことなく',
  '{n:minutes}まるごと', '{n:hours}まるごと', '全{n:scenes}まるごと',
  '{n:minutes}ぶっ通し', '{n:hours}ぶっ通し', '全{n:scenes}を一息に',

  '構成に無駄なし', '編集に無駄なし', '尺に無駄なし',
  '中身の詰まった一本', '密度の高い構成', '濃密な収録量',
  '間延びしない構成', '飽きさせない構成', 'テンポのよい構成',

  '完成度の高い一本', '完成度で選ばれる一本', '完成度は折り紙付き',
  '仕上がりは上々', '仕上がりに自信あり', '仕上がりをご確認ください',
  '出来映えは保証します', '出来は前作以上', '出来のよさが評判',

  '売れ行き好調', '売れ行きは想定以上', '売行き上位を維持',
  '受注好調につき増産', '受注は前作を上回る', '受注状況は好調',
  '注文が絶えない一本', '注文数は右肩上がり', '注文はお早めに',

  '装丁も見どころ', '装丁が話題', '装丁に注目',
  'ジャケットも保存価値あり', 'ジャケット違いも展開', 'ジャケットは{n:few}種展開',
  '外装まで作り込み', '外装も特別仕様', '外装の質感にもこだわり',

  '{crown}にふさわしい分量', '{crown}を冠する一本', '{crown}の名は伊達ではない',
  '{personAttr}が集結', '{personAttr}が総登場', '{personAttr}を一挙に',
  '{situation}を丸ごと', '{event}まで一挙に', '{outcome}まで一気に',
  '{attrWord}を極めた一本', '{recordWord}の決定版', '{quantityWord}の決定版',

  '見どころだけを凝縮', '見どころを外さない構成', '見どころは全編',
  '要所を押さえた構成', '要点を外さない編集', '要望どおりの構成',
  '狙いどおりの仕上がり', '狙いを絞った企画', '狙いが明確な一本',

  '価格以上の満足度', '価格以上の分量', '価格に見合う内容',
  '値段以上の中身', '費用対効果の高い一本', 'お買い得の一本',
  'この価格なら迷わない', 'この価格は今回限り', 'この価格での提供は最後',

  '評価は発売後さらに上昇', '評判は上々', '評判が広がる一本',
  '評価の高さが証明', '高評価を継続中', '高い評価を維持',
  '好評につき継続展開', '好評につき追加展開', '好評につき増枠',

  '記録的な収録量', '記録更新の分量', '記録に残る一本',
  '記憶に残る一本', '語り継がれる一本', '後々まで残る一本',
  '定番入り確実', '名作入り確実', '代表作となる一本',

  '手元に一本', '棚に一本', '保存に一本',
  '観賞用と保存用に', '予備の確保をおすすめ', '複数本のご用意を',
  '贈答にも向く装丁', '揃えて楽しむシリーズ', '並べて完成する意匠',

  '{formatWord}だから扱いやすい', '{formatWord}で長く保存', '{formatWord}なら安心',
  '{bonusWord}まで含めて完全版', '{bonusWord}込みでこの価格', '{bonusWord}は今回限り',
  '{seriesWord}の中でも屈指', '{seriesWord}の最新仕様', '{seriesWord}を締めくくる一本',

  'ここから始めるのもよし', 'ここで揃えるのもよし', 'ここが買い時',
  '迷う理由がない', '選ばない理由がない', '外す理由がない',
  '文句のない選択', '間違いない選択', '後悔しない選択',

  '在庫状況は各店へ', '取扱状況は店頭で', '販売状況は随時更新',
  '完売の際はご容赦ください', '品切れの際はご了承ください', '入荷待ちの場合があります',

  '{n:date} を見逃さずに', '{n:date} に間に合わせて', '{n:date} からお求めいただけます',
  '{n:code} をお控えください', '{n:code} でご注文ください', '{n:code} で在庫照会を',
  '{n:price}（税込）でご提供', '{n:price} でのご提供は今回限り', '税込 {n:price} でお届け',

  '{makerName} からの最新作', '{labelName} からの新作', '{makerName} の代表作',
  '{labelName} の代表作', '{makerName} が総力を挙げた一本', '{labelName} が満を持して',

  '内容量で選ぶならこれ', '長さで選ぶならこれ', '本数で選ぶならこれ',
  '仕様で比べても優位', '分量で比べても優位', '価格で比べても優位',

  '締めくくりにふさわしい一本', '幕開けにふさわしい一本', '節目にふさわしい一本',
  '記念にふさわしい仕様', '記念すべき一本', '節目の一本'
];

const CONNECTIVE = [
  'さらに', 'しかも', 'もちろん', 'なお', 'そのうえ', '加えて',
  'そして', 'いよいよ', 'ついに', 'いまなお', 'あわせて', 'ならびに',
  'さらには', 'そのまま', 'まずは', 'いっぽうで', 'このたび', 'ただいま',
  '今回も', '今回はさらに', 'なんと', 'それでいて', 'そればかりか', 'おまけに',
  'ここでも', 'ここからは', 'そのため', 'だからこそ', 'いまだけ', 'いまなら',
  'ひきつづき', 'あらためて', 'ふたたび', 'あわせまして', 'そのほか', 'このほか',
  'とりわけ', 'なかでも', 'ちなみに', 'ついでに', 'そのうえで', 'そのかわり'
];

const NOMINAL = [
  '{labelName}｜{seriesWord}', '{bonusWord}／{formatWord}', '{n:minutes}／{n:code}',
  '{seriesWord}｜{bonusWord}', '{formatWord}｜全{n:scenes}', '{labelName}／{n:date}',
  '{bonusWord}｜{n:minutes}｜{n:code}', '{seriesWord}／{n:edition}',

  '{makerName}｜{seriesWord}', '{makerName}／{labelName}', '{makerName}｜{n:code}',
  '{makerName}／{n:date}', '{makerName}｜{n:minutes}', '{makerName}／{formatWord}',
  '{labelName}／{makerName}', '{labelName}｜{n:code}', '{labelName}／{formatWord}',
  '{labelName}｜{n:minutes}', '{labelName}／{bonusWord}', '{labelName}｜{n:price}（税込）',
  '{makerName}／{n:price}（税込）', '{makerName}｜{bonusWord}', '{makerName}／{seriesWord}',

  '{seriesWord}｜{n:code}', '{seriesWord}／{formatWord}', '{seriesWord}｜{n:minutes}',
  '{seriesWord}／{n:date}', '{seriesWord}｜{makerName}', '{seriesWord}／{labelName}',
  '{seriesWord}｜{attrWord}', '{seriesWord}／{quantityWord}', '{seriesWord}｜{recordWord}',
  '{seriesWord}／全{n:scenes}', '{seriesWord}｜{n:hours}', '{seriesWord}／{n:price}（税込）',

  '{bonusWord}／{n:minutes}', '{bonusWord}｜{n:code}', '{bonusWord}／全{n:scenes}',
  '{bonusWord}｜{formatWord}', '{bonusWord}／{attrWord}', '{bonusWord}｜{quantityWord}',
  '{bonusWord}／{seriesWord}', '{bonusWord}｜{n:date}', '{bonusWord}／{n:hours}',
  '{bonusWord}｜{recordWord}', '{bonusWord}／{makerName}', '{bonusWord}｜{labelName}',

  '{formatWord}／{n:minutes}', '{formatWord}｜{n:code}', '{formatWord}／全{n:scenes}',
  '{formatWord}｜{bonusWord}', '{formatWord}／{attrWord}', '{formatWord}｜{quantityWord}',
  '{formatWord}／{seriesWord}', '{formatWord}｜{n:date}', '{formatWord}／{n:hours}',
  '{formatWord}｜{recordWord}', '{formatWord}／{makerName}', '{formatWord}｜{labelName}',

  '{attrWord}／{attrWord}', '{attrWord}｜{bonusWord}', '{attrWord}／{formatWord}',
  '{attrWord}｜{n:minutes}', '{attrWord}／全{n:scenes}', '{attrWord}｜{n:code}',
  '{attrWord}／{recordWord}', '{attrWord}｜{quantityWord}', '{attrWord}／{seriesWord}',
  '{attrWord}｜{n:hours}', '{attrWord}／{crown}', '{attrWord}｜{personAttr}',

  '{recordWord}／{quantityWord}', '{recordWord}｜{n:minutes}', '{recordWord}／全{n:scenes}',
  '{recordWord}｜{formatWord}', '{recordWord}／{bonusWord}', '{recordWord}｜{attrWord}',
  '{recordWord}／{n:code}', '{recordWord}｜{n:hours}', '{recordWord}／{seriesWord}',
  '{recordWord}｜{crown}', '{recordWord}／{personAttr}', '{recordWord}｜{situation}',

  '{quantityWord}／{n:minutes}', '{quantityWord}｜全{n:scenes}', '{quantityWord}／{formatWord}',
  '{quantityWord}｜{bonusWord}', '{quantityWord}／{attrWord}', '{quantityWord}｜{n:code}',
  '{quantityWord}／{recordWord}', '{quantityWord}｜{n:hours}', '{quantityWord}／{seriesWord}',
  '{quantityWord}｜{makerName}', '{quantityWord}／{labelName}', '{quantityWord}｜{n:price}（税込）',

  '{crown}｜{personAttr}', '{crown}／{situation}', '{crown}｜{attrWord}',
  '{crown}／{recordWord}', '{crown}｜{quantityWord}', '{crown}／{seriesWord}',
  '{crown}｜{n:minutes}', '{crown}／全{n:scenes}', '{crown}｜{bonusWord}',
  '{crown}／{formatWord}', '{crown}｜{makerName}', '{crown}／{labelName}',

  '{personAttr}｜{situation}', '{personAttr}／{event}', '{personAttr}｜{outcome}',
  '{personAttr}／{attrWord}', '{personAttr}｜{recordWord}', '{personAttr}／{quantityWord}',
  '{personAttr}×{personAttr}', '{personAttr}｜{n:minutes}', '{personAttr}／全{n:scenes}',
  '{personAttr}｜{crown}', '{personAttr}／{seriesWord}', '{personAttr}｜{formatWord}',

  '{situation}／{event}', '{situation}｜{outcome}', '{situation}／{personAttr}',
  '{situation}×{situation}', '{situation}｜{recordWord}', '{situation}／{quantityWord}',
  '{situation}｜{attrWord}', '{situation}／{n:minutes}', '{situation}｜全{n:scenes}',
  '{situation}／{crown}', '{situation}｜{seriesWord}', '{situation}／{formatWord}',

  '{event}／{outcome}', '{event}｜{recordWord}', '{event}／{personAttr}',
  '{event}｜{situation}', '{event}／{attrWord}', '{event}｜{quantityWord}',
  '{event}／{n:minutes}', '{event}｜全{n:scenes}', '{event}／{crown}',
  '{outcome}／{recordWord}', '{outcome}｜{personAttr}', '{outcome}／{quantityWord}',
  '{outcome}｜{attrWord}', '{outcome}／{n:minutes}', '{outcome}｜全{n:scenes}',

  '{n:minutes}／全{n:scenes}', '{n:minutes}｜{n:code}', '{n:minutes}／{n:price}（税込）',
  '{n:minutes}｜{n:date}', '{n:minutes}／{formatWord}', '{n:minutes}｜{bonusWord}',
  '{n:minutes}／{attrWord}', '{n:minutes}｜{recordWord}', '{n:minutes}／{quantityWord}',
  '本編{n:minutes}／特典{n:bonusMinutes}', '本編{n:minutes}｜全{n:scenes}', '本編{n:minutes}／{n:code}',
  '特典{n:bonusMinutes}／{formatWord}', '特典{n:bonusMinutes}｜{bonusWord}', '特典{n:bonusMinutes}／{n:code}',

  '{n:hours}／全{n:scenes}', '{n:hours}｜{n:code}', '{n:hours}／{formatWord}',
  '{n:hours}｜{bonusWord}', '{n:hours}／{attrWord}', '{n:hours}｜{recordWord}',
  '{n:hours}／{n:price}（税込）', '{n:hours}｜{n:date}', '{n:hours}／{quantityWord}',

  '全{n:scenes}／{n:code}', '全{n:scenes}｜{formatWord}', '全{n:scenes}／{bonusWord}',
  '全{n:scenes}｜{attrWord}', '全{n:scenes}／{recordWord}', '全{n:scenes}｜{quantityWord}',
  '全{n:scenes}／{n:price}（税込）', '全{n:scenes}｜{n:date}', '全{n:scenes}／{seriesWord}',

  '{n:code}／{n:date}', '{n:code}｜{n:price}（税込）', '{n:code}／{formatWord}',
  '{n:code}｜{bonusWord}', '{n:code}／{attrWord}', '{n:code}｜{seriesWord}',
  '{n:code}／{makerName}', '{n:code}｜{labelName}', '{n:code}／{recordWord}',

  '{n:date}／{n:price}（税込）', '{n:date}｜{formatWord}', '{n:date}／{bonusWord}',
  '{n:date}｜{makerName}', '{n:date}／{labelName}', '{n:date}｜{seriesWord}',
  '{n:price}（税込）／{formatWord}', '{n:price}（税込）｜{bonusWord}', '{n:price}（税込）／{makerName}',

  '{n:edition}／{n:code}', '{n:edition}｜{seriesWord}', '{n:edition}／{formatWord}',
  '{n:edition}｜{makerName}', '{n:edition}／{labelName}', '{n:edition}｜{n:minutes}',
  '{n:edition}／{bonusWord}', '{n:edition}｜{attrWord}', '{n:edition}／全{n:scenes}',

  '品番 {n:code}／{n:minutes}', '品番 {n:code}｜{formatWord}', '品番 {n:code}／{n:date}',
  '収録時間 {n:minutes}／全{n:scenes}', '収録時間 {n:minutes}｜{formatWord}', '収録時間 {n:minutes}／{n:code}',
  '発売元 {makerName}／{n:code}', '発売元 {labelName}｜{n:date}', '企画・制作 {makerName}',
  'レーベル {labelName}／{seriesWord}', '規格 {formatWord}／{n:code}', '価格 {n:price}（税込）',

  '{seriesWord}｜{personAttr}', '{seriesWord}／{situation}', '{seriesWord}｜{crown}',
  '{makerName}｜{attrWord}', '{makerName}／{recordWord}', '{makerName}｜{quantityWord}',
  '{labelName}／{attrWord}', '{labelName}｜{recordWord}', '{labelName}／{quantityWord}',
  '{labelName}｜{crown}', '{makerName}／{crown}', '{makerName}｜{personAttr}',

  '{attrWord}＋{attrWord}', '{attrWord}＋{bonusWord}', '{bonusWord}＋{formatWord}',
  '{personAttr}＋{situation}', '{situation}＋{event}', '{event}＋{outcome}',
  '{recordWord}＋{quantityWord}', '{crown}＋{attrWord}', '{seriesWord}＋{bonusWord}',

  '{attrWord}×{attrWord}', '{situation}×{event}', '{personAttr}×{situation}',
  '{crown}×{personAttr}', '{recordWord}×{quantityWord}', '{seriesWord}×{formatWord}',
  '{bonusWord}×{formatWord}', '{attrWord}×{quantityWord}', '{personAttr}×{attrWord}',

  '{attrWord}・{attrWord}・{attrWord}', '{personAttr}・{personAttr}・{personAttr}', '{situation}・{situation}・{situation}',
  '{n:minutes}・全{n:scenes}・{n:code}', '{formatWord}・{bonusWord}・{attrWord}', '{makerName}・{labelName}・{n:code}',
  '{seriesWord}・{n:edition}・{n:code}', '{recordWord}・{quantityWord}・{attrWord}', '{crown}・{personAttr}・{situation}',

  '{n:count}作目｜{seriesWord}', '通算{n:count}作｜{makerName}', '第{n:seriesNo}弾｜{labelName}',
  '{n:anniversary}周年｜{seriesWord}', '{n:anniversary}周年／{makerName}', '第{n:seriesNo}弾／{n:code}',
  '{n:week}｜{seriesWord}', '{n:year}｜{makerName}', '{n:year}／{n:code}',

  '{noticeWord}／{n:code}', '{noticeWord}｜{makerName}', '{noticeWord}／{formatWord}',
  '{sashWord}', '{sashWord}／{n:code}', '{sashWord}｜{seriesWord}',

  '{sashWord}／{quantityWord}', '{sashWord}｜{attrWord}', '{sashWord}／{makerName}',
  '{noticeWord}／{labelName}', '{noticeWord}｜{n:date}', '{noticeWord}／{n:price}（税込）',
  '{crown}｜{n:code}', '{crown}／{n:date}', '{crown}｜{n:price}（税込）',
  '{personAttr}｜{n:code}', '{personAttr}／{n:date}', '{situation}｜{n:code}',
  '{event}｜{n:minutes}', '{outcome}｜{n:code}', '{recordWord}／{n:date}',
  '{quantityWord}｜{n:date}', '{attrWord}／{n:date}', '{attrWord}｜{n:price}（税込）',
  '{bonusWord}／{n:price}（税込）', '{formatWord}｜{n:price}（税込）', '{seriesWord}｜{n:price}（税込）',
  '{recordWord}｜{n:price}（税込）', '{quantityWord}／{n:code}', '{crown}／{n:code}',
  '{personAttr}｜{quantityWord}', '{situation}／{recordWord}', '{event}／{quantityWord}',
  '{outcome}／{attrWord}'
];

const SCALE = [
  'シリーズ最長{n:minutes}', '累計{n:count}作を突破', '{n:week}売上第一位',
  '全国主要店舗で展開中', '公式配信も同時開始',

  'シリーズ最長の{n:hours}', 'シリーズ最多の全{n:scenes}', 'シリーズ最多{n:count}名が出演',
  'シリーズ最大の{n:minutes}', 'シリーズ最厚の解説書', 'シリーズ最速で完売',
  'シリーズ最高の収録量', 'シリーズ最新の{n:code}', 'シリーズ通算{n:count}作目',
  'シリーズ累計{n:count}作を達成', 'シリーズ{n:anniversary}周年', 'シリーズ第{n:seriesNo}弾に到達',
  'シリーズ史上最長の収録', 'シリーズ史上最多の場面数', 'シリーズ史上最大の企画',
  'シリーズ全{n:count}作を継続', 'シリーズ既刊{n:count}作', 'シリーズ関連{n:count}作を展開',

  '累計{n:count}万本を出荷', '累計出荷{n:count}万本', '累計{n:count}店舗で展開',
  '累計{n:count}名が出演', '累計収録{n:hours}', '累計{n:count}作を制作',
  '通算{n:count}作目の到達点', '通算{n:count}回目の企画', '通算{n:count}名を起用',

  '{n:minutes}の大容量', '{n:hours}の大容量', '全{n:scenes}の大容量',
  '{n:minutes}を一本に集約', '{n:hours}を一挙収録', '全{n:scenes}を一挙収録',
  '本編{n:minutes}＋特典{n:bonusMinutes}', '本編＋特典で{n:minutes}', '特典だけで{n:bonusMinutes}',
  '{n:minutes}中{n:bonusMinutes}が新規', '{n:few}枚組{n:minutes}', '{n:few}部構成{n:hours}',

  '{n:week}上位を維持', '{n:week}売上上位', '{n:week}連続で在庫僅少',
  '発売{n:few}日で完売', '発売初週で{n:count}店舗が完売', '初動は前作の{n:few}倍',
  '予約数が前作の{n:few}倍', '受注は想定の{n:few}倍', '出荷を{n:few}倍に増強',

  '全国{n:count}店舗で展開', '全国一斉展開', '主要{n:count}店舗で先行展開',
  '取扱店舗{n:count}を突破', '通販{n:count}か所で展開', '配信{n:count}か所で同時開始',
  '全国の主要店舗で先行', '全国で同時発売', '全国規模の展開',

  '{makerName} 史上最長の{n:minutes}', '{makerName} 史上最大の企画', '{makerName} 最多の{n:scenes}',
  '{labelName} 最長の収録時間', '{labelName} 最多の出演者数', '{labelName} 史上最大規模',
  '{makerName} が総力を投入', '{labelName} が総力を投入', '{makerName}／{labelName} 共同で最大規模',

  '{n:anniversary}周年記念の特別企画', '{n:anniversary}周年記念の{n:minutes}', '{n:anniversary}周年を飾る最大企画',
  '第{n:seriesNo}弾にして最長', '第{n:seriesNo}弾にして最多', '第{n:seriesNo}弾の集大成',

  '出演総勢{n:count}名', '総勢{n:count}名が集結', '出演者{n:count}名を起用',
  '{personAttr}を{n:count}名収録', '{personAttr}が{n:few}組登場', '{personAttr}を総勢{n:count}名',

  '制作期間{n:few}年', '準備に{n:few}か月', '撮影{n:few}日間',
  '編集に{n:few}か月', '企画会議{n:count}回', '検討{n:count}回を経て完成',

  '過去最長の{n:minutes}', '過去最多の全{n:scenes}', '過去最大の企画規模',
  '過去最高の収録量', '過去最速の完売', '過去最多の出荷数',
  '前作を{n:minutes}上回る', '前作より{n:bonusMinutes}長い', '前作比{n:few}倍の分量',

  '年間屈指の{n:minutes}', '年間最多の全{n:scenes}', '年間最大級の企画',
  '今期最長の収録時間', '今期最多の場面数', '今期最大の企画',
  '月間{n:count}作の展開', '四半期{n:count}作を制作', '年{n:count}作を継続',

  '{n:price}（税込）でこの分量', '{n:price} でこの収録量', '価格据え置きで{n:minutes}',
  '価格そのままで{n:bonusMinutes}増', '実質{n:few}割の増量', '同価格で{n:few}倍の分量',

  '{n:code} で登録の最大規格', '{formatWord} で最大容量', '{formatWord} 最長の収録',
  '{bonusWord} を含めて{n:minutes}', '{bonusWord} だけで{n:bonusMinutes}', '{attrWord} を全編に',

  '全{n:scenes}すべてが新規', '全{n:scenes}中{n:few}が未公開', '未公開分が{n:few}割',
  '新規収録が{n:few}割', '再編集分が{n:few}割', '追加分だけで{n:bonusMinutes}',

  '{n:count}件の反響', '{n:count}件の問い合わせ', '{n:count}件の予約',
  '{n:count}名から要望', '{n:count}店舗から追加発注', '{n:count}回の増産',

  '大容量{n:hours}', '長編{n:minutes}', '多収録 全{n:scenes}',
  '大規模企画', '大型企画', '特大企画',
  '最大級の分量', '最大級の収録量', '最大級の規模',

  '{n:year}最大の企画', '{n:year}最長の{n:minutes}', '{n:year}を代表する規模',
  '{n:date} 一斉展開', '{n:date} 全国同時', '{n:date} 配信同時開始',

  '{seriesWord} 最長の{n:minutes}', '{seriesWord} 最多の全{n:scenes}', '{seriesWord} 最大規模',
  '{quantityWord} を実現', '{quantityWord} に到達', '{recordWord} として最大規模',

  '{n:hours}を超える収録', '{n:minutes}を超える本編', '全{n:scenes}を超える構成',
  '{n:count}作を超えるシリーズ', '{n:count}名を超える出演者', '{n:count}店舗を超える展開'
];

const FORMS = [
  { id: 'AbarB', t: '[A]｜[B]', w: 20, len: 'short' },
  { id: 'AslashB', t: '[A]／[B]', w: 14, len: 'short' },
  { id: 'BA', t: '[B]。[A]', w: 12, len: 'short' },
  { id: 'N', t: '[N]', w: 14, len: 'short' },
  { id: 'SN', t: '[S]｜[N]', w: 10, len: 'short' },
  { id: 'S', t: '[S]', w: 10, len: 'short' },
  { id: 'SslashB', t: '[S]／[B]', w: 12, len: 'short' },
  { id: 'AplusS', t: '[A]＋[S]', w: 10, len: 'short' },
  { id: 'NslashB', t: '[N]／[B]', w: 12, len: 'short' },
  { id: 'SdotA', t: '[S]。[A]', w: 10, len: 'short' },
  { id: 'AbangB', t: '[A]！！[B]', w: 12, len: 'short' },
  { id: 'AAB', t: '[A]／[A]／[B]', w: 16, len: 'mid' },
  { id: 'AAA', t: '[A]｜[A]｜[A]', w: 14, len: 'mid' },
  { id: 'SAB', t: '[S]／[A]／[B]', w: 12, len: 'mid' },
  { id: 'NAB', t: '[N]｜[A]｜[B]', w: 10, len: 'mid' },
  { id: 'ASN', t: '[A]／[S]／[N]', w: 10, len: 'mid' },
  { id: 'ANB', t: '[A]、[N]、[B]', w: 10, len: 'mid' },
  { id: 'ACB', t: '[A]。[C]、[B]', w: 10, len: 'long' },
  { id: 'ACSB', t: '[A]。[C][S]、[B]', w: 6, len: 'long' },
  { id: 'NCB', t: '[N]。[C][B]', w: 8, len: 'long' }
];

PF.GENRE_TEXT = PF.GENRE_TEXT || {};
PF.GENRE_TEXT.adult = {
  patterns: {
    title: TITLE_LEGACY.concat(TITLE_D1, TITLE_D2, TITLE_D3, TITLE_D4),
    megaSpec: MEGA_SPEC,
    megaTail: MEGA_TAIL,
    tag: TAG,
    badge: BADGE,
    credit: CREDIT,
    release: RELEASE,
    extra: EXTRA
  },
  register: {
    person: 'none',
    tone: 'promo',
    clauseA: CLAUSE_A,
    clauseB: CLAUSE_B,
    connective: CONNECTIVE,
    nominal: NOMINAL,
    scale: SCALE,
    forms: FORMS
  }
};
})(window.PF = window.PF || {});
