"""
WebSocket Event Data Flow Map
Each entry maps:event->direction,data fields,TS type,emit sources

Fields:
  event:    Event name
  direction:"server_to_client"|"client_to_server"|"bidirectional"
  ts_type:  TypeScript type from WebSocketEventMap
  data_fields:Dict of field_name->python_type_hint
  room:     Room scope ("project:{id}","sid","global")
  sources:  List of"file::function" where this event is emitted
"""

WS_EVENTS=[
    {
        "event":"connection:state_sync",
        "direction":"server_to_client",
        "ts_type":"StateSyncData",
        "data_fields":{
            "status":"Optional[str]",
            "sid":"Optional[str]",
            "project":"Optional[dict]",
            "agents":"Optional[list]",
            "checkpoints":"Optional[list]",
            "metrics":"Optional[dict]",
            "logs":"Optional[list]",
        },
        "room":"sid",
        "sources":[
            "handlers/websocket.py::connect",
            "handlers/websocket.py::subscribe_project",
        ],
    },
    {
        "event":"error:state",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "message":"str",
            "code":"str",
        },
        "room":"sid",
        "sources":[
            "handlers/websocket.py::subscribe_project",
            "handlers/websocket.py::checkpoint_resolve",
        ],
    },
    {
        "event":"project:updated",
        "direction":"server_to_client",
        "ts_type":"{projectId: string; updates: Partial<Project>}",
        "data_fields":{
            "id":"str",
            "name":"str",
            "status":"str",
        },
        "room":"global",
        "sources":[
            "handlers/project.py::create_project",
            "handlers/project.py::update_project",
            "handlers/project.py::update_project_ai_services",
            "handlers/project.py::update_project_ai_service",
        ],
    },
    {
        "event":"project:status_changed",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "projectId":"str",
            "status":"str",
            "previousStatus":"str",
            "retriedAgents":"Optional[int]",
        },
        "room":"global",
        "sources":[
            "handlers/project.py::start_project",
            "handlers/project.py::pause_project",
            "handlers/project.py::resume_project",
            "handlers/project.py::brushup_project",
        ],
    },
    {
        "event":"project:initialized",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "projectId":"str",
        },
        "room":"global",
        "sources":[
            "handlers/project.py::initialize_project",
        ],
    },
    {
        "event":"project:paused",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "projectId":"str",
            "reason":"str",
            "interventionId":"str",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/intervention.py::create_intervention",
        ],
    },
    {
        "event":"agent:paused",
        "direction":"server_to_client",
        "ts_type":"AgentEventData",
        "data_fields":{
            "agentId":"str",
            "projectId":"str",
            "agent":"dict",
            "reason":"Optional[str]",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/agent.py::pause_agent",
            "handlers/intervention.py::create_intervention",
        ],
    },
    {
        "event":"agent:resumed",
        "direction":"server_to_client",
        "ts_type":"AgentEventData",
        "data_fields":{
            "agentId":"str",
            "projectId":"str",
            "agent":"dict",
            "reason":"Optional[str]",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/agent.py::resume_agent",
            "handlers/intervention.py::respond_to_intervention",
        ],
    },
    {
        "event":"agent:activated",
        "direction":"server_to_client",
        "ts_type":"AgentEventData",
        "data_fields":{
            "agentId":"str",
            "projectId":"str",
            "agent":"dict",
            "previousStatus":"Optional[str]",
            "interventionId":"str",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/intervention.py::create_intervention",
        ],
    },
    {
        "event":"agent:waiting_response",
        "direction":"server_to_client",
        "ts_type":"AgentEventData",
        "data_fields":{
            "agentId":"str",
            "projectId":"str",
            "agent":"dict",
            "interventionId":"str",
            "question":"str",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/intervention.py::agent_question",
        ],
    },
    {
        "event":"checkpoint:resolved",
        "direction":"server_to_client",
        "ts_type":"CheckpointResolvedData",
        "data_fields":{
            "checkpointId":"str",
            "projectId":"str",
            "agentId":"str",
            "resolution":"str",
            "feedback":"Optional[str]",
            "agentStatus":"Optional[str]",
            "checkpoint":"Optional[dict]",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/checkpoint.py::resolve_checkpoint",
            "handlers/websocket.py::checkpoint_resolve",
        ],
    },
    {
        "event":"asset:updated",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "projectId":"str",
            "asset":"dict",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/metrics.py::update_project_asset",
        ],
    },
    {
        "event":"assets:bulk_updated",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "projectId":"str",
            "assets":"list",
            "status":"str",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/metrics.py::bulk_update_assets",
        ],
    },
    {
        "event":"asset:regeneration_requested",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "projectId":"str",
            "assetId":"str",
            "feedback":"str",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/metrics.py::request_asset_regeneration",
        ],
    },
    {
        "event":"intervention:created",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "interventionId":"str",
            "projectId":"str",
            "intervention":"dict",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/intervention.py::create_intervention",
        ],
    },
    {
        "event":"intervention:acknowledged",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "interventionId":"str",
            "projectId":"str",
            "intervention":"dict",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/intervention.py::acknowledge_intervention",
        ],
    },
    {
        "event":"intervention:processed",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "interventionId":"str",
            "projectId":"str",
            "intervention":"dict",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/intervention.py::process_intervention",
        ],
    },
    {
        "event":"intervention:deleted",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "interventionId":"str",
            "projectId":"str",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/intervention.py::delete_intervention",
        ],
    },
    {
        "event":"intervention:response_added",
        "direction":"server_to_client",
        "ts_type":None,
        "data_fields":{
            "interventionId":"str",
            "projectId":"str",
            "intervention":"dict",
            "sender":"str",
            "agentId":"Optional[str]",
        },
        "room":"project:{id}",
        "sources":[
            "handlers/intervention.py::respond_to_intervention",
            "handlers/intervention.py::agent_question",
        ],
    },
    {
        "event":"navigator:message",
        "direction":"server_to_client",
        "ts_type":"{speaker: string; text: string; priority: MessagePriority; source: 'server'}",
        "data_fields":{
            "speaker":"str",
            "text":"str",
            "priority":"str",
            "source":"str",
        },
        "room":"project:{id} | global",
        "sources":[
            "handlers/websocket.py::broadcast_navigator_message",
        ],
    },
    {
        "event":"system_log:created",
        "direction":"server_to_client",
        "ts_type":"{projectId: string; log: ApiSystemLog}",
        "data_fields":{
            "projectId":"str",
            "log":"dict",
        },
        "room":"project:{id}",
        "sources":[
            "datastore.py::_add_system_log_internal",
        ],
    },

    {
        "event":"subscribe:project",
        "direction":"client_to_server",
        "ts_type":"{projectId: string}",
        "data_fields":{
            "projectId":"str",
        },
        "room":"",
        "sources":[],
    },
    {
        "event":"unsubscribe:project",
        "direction":"client_to_server",
        "ts_type":"{projectId: string}",
        "data_fields":{
            "projectId":"str",
        },
        "room":"",
        "sources":[],
    },
    {
        "event":"checkpoint:resolve",
        "direction":"client_to_server",
        "ts_type":"{checkpointId: string; resolution: string; feedback?: string}",
        "data_fields":{
            "checkpointId":"str",
            "resolution":"str",
            "feedback":"Optional[str]",
        },
        "room":"",
        "sources":[],
    },
]
