export const API_ENDPOINTS={
 projects:{
  list:'/api/projects',
  create:'/api/projects',
  get:(id:string)=>`/api/projects/${id}`,
  update:(id:string)=>`/api/projects/${id}`,
  delete:(id:string)=>`/api/projects/${id}`,
  start:(id:string)=>`/api/projects/${id}/start`,
  pause:(id:string)=>`/api/projects/${id}/pause`,
  resume:(id:string)=>`/api/projects/${id}/resume`,
  initialize:(id:string)=>`/api/projects/${id}/initialize`,
  brushup:(id:string)=>`/api/projects/${id}/brushup`,
  brushupSuggestImages:(id:string)=>`/api/projects/${id}/brushup/suggest-images`,
  agents:(id:string)=>`/api/projects/${id}/agents`,
  agentsRetryable:(id:string)=>`/api/projects/${id}/agents/retryable`,
  agentsInterrupted:(id:string)=>`/api/projects/${id}/agents/interrupted`,
  agentsLeaders:(id:string)=>`/api/projects/${id}/agents/leaders`,
  checkpoints:(id:string)=>`/api/projects/${id}/checkpoints`,
  metrics:(id:string)=>`/api/projects/${id}/metrics`,
  logs:(id:string)=>`/api/projects/${id}/logs`,
  assets:(id:string)=>`/api/projects/${id}/assets`,
  asset:(projectId:string,assetId:string)=>`/api/projects/${projectId}/assets/${assetId}`,
  assetRegenerate:(projectId:string,assetId:string)=>`/api/projects/${projectId}/assets/${assetId}/regenerate`,
  assetsBulk:(projectId:string)=>`/api/projects/${projectId}/assets/bulk`,
  interventions:(id:string)=>`/api/projects/${id}/interventions`,
  files:(id:string)=>`/api/projects/${id}/files`,
  filesBatch:(id:string)=>`/api/projects/${id}/files/batch`,
  tree:(id:string)=>`/api/projects/${id}/tree`,
  treeDownload:(id:string)=>`/api/projects/${id}/tree/download`,
  treeReplace:(id:string)=>`/api/projects/${id}/tree/replace`,
  treeDownloadAll:(id:string)=>`/api/projects/${id}/tree/download-all`,
  aiRequests:(id:string)=>`/api/projects/${id}/ai-requests/stats`,
  traces:(id:string)=>`/api/projects/${id}/traces`,
  autoApprovalRules:(id:string)=>`/api/projects/${id}/auto-approval-rules`,
  settings:{
   qualityCheck:(id:string)=>`/api/projects/${id}/settings/quality-check`,
   qualityCheckAgent:(projectId:string,agentType:string)=>`/api/projects/${projectId}/settings/quality-check/${agentType}`,
   qualityCheckBulk:(id:string)=>`/api/projects/${id}/settings/quality-check/bulk`,
   qualityCheckReset:(id:string)=>`/api/projects/${id}/settings/quality-check/reset`,
   output:(id:string)=>`/api/projects/${id}/settings/output`,
   cost:(id:string)=>`/api/projects/${id}/settings/cost`,
   aiProviders:(id:string)=>`/api/projects/${id}/settings/ai-providers`
  },
  aiServices:(id:string)=>`/api/projects/${id}/ai-services`,
  aiService:(projectId:string,serviceType:string)=>`/api/projects/${projectId}/ai-services/${serviceType}`
 },
 agents:{
  get:(id:string)=>`/api/agents/${id}`,
  workers:(id:string)=>`/api/agents/${id}/workers`,
  logs:(id:string)=>`/api/agents/${id}/logs`,
  retry:(id:string)=>`/api/agents/${id}/retry`,
  pause:(id:string)=>`/api/agents/${id}/pause`,
  resume:(id:string)=>`/api/agents/${id}/resume`,
  cancel:(id:string)=>`/api/agents/${id}/cancel`,
  sequence:(id:string)=>`/api/agents/${id}/sequence`,
  execute:(id:string)=>`/api/agents/${id}/execute`,
  executeWithWorkers:(id:string)=>`/api/agents/${id}/execute-with-workers`,
  traces:(id:string)=>`/api/agents/${id}/traces`,
  systemPrompt:(id:string)=>`/api/agents/${id}/system-prompt`
 },
 checkpoints:{
  resolve:(id:string)=>`/api/checkpoints/${id}/resolve`
 },
 interventions:{
  get:(id:string)=>`/api/interventions/${id}`,
  acknowledge:(id:string)=>`/api/interventions/${id}/acknowledge`,
  process:(id:string)=>`/api/interventions/${id}/process`,
  delete:(id:string)=>`/api/interventions/${id}`,
  respond:(id:string)=>`/api/interventions/${id}/respond`
 },
 files:{
  get:(id:string)=>`/api/files/${id}`,
  delete:(id:string)=>`/api/files/${id}`,
  download:(id:string)=>`/api/files/${id}/download`
 },
 traces:{
  get:(id:string)=>`/api/traces/${id}`
 },
 llmJobs:{
  get:(id:string)=>`/api/llm-jobs/${id}`
 },
 aiProviders:{
  list:'/api/ai-providers',
  get:(id:string)=>`/api/ai-providers/${id}`,
  models:(id:string)=>`/api/ai-providers/${id}/models`,
  test:'/api/ai-providers/test',
  serviceTypes:'/api/ai-service-types'
 },
 ai:{
  chat:'/api/ai/chat',
  chatStream:'/api/ai/chat/stream'
 },
 aiServices:{
  list:'/api/ai-services',
  get:(type:string)=>`/api/ai-services/${type}`,
  master:'/api/config/ai-services'
 },
 config:{
  projectOptions:'/api/config/project-options',
  fileExtensions:'/api/config/file-extensions',
  agents:'/api/config/agents',
  websocket:'/api/config/websocket',
  costSettingsDefaults:'/api/config/cost-settings/defaults',
  outputSettingsDefaults:'/api/config/output-settings/defaults',
  uiSettings:'/api/config/ui-settings',
  agentServiceMap:'/api/config/agent-service-map',
  pricing:'/api/config/pricing'
 },
 brushup:{
  options:'/api/brushup/options'
 },
 settings:{
  qualityCheckDefaults:'/api/settings/quality-check/defaults'
 },
 agentDefinitions:'/api/agent-definitions',
 languages:'/api/languages',
 backups:{
  list:'/api/backups',
  create:'/api/backups',
  restore:(name:string)=>`/api/backups/${name}/restore`,
  delete:(name:string)=>`/api/backups/${name}`
 },
 archives:{
  stats:'/api/archive/stats',
  cleanup:'/api/archive/cleanup',
  estimate:'/api/archive/estimate',
  retention:'/api/archive/retention',
  export:'/api/archive/export',
  exportAndCleanup:'/api/archive/export-and-cleanup',
  autoArchive:'/api/archive/auto-archive',
  list:'/api/archives',
  delete:(name:string)=>`/api/archives/${name}`,
  download:(name:string)=>`/api/archives/${name}/download`
 },
 recovery:{
  status:'/api/recovery/status',
  retryAll:'/api/recovery/retry-all'
 },
 system:{
  stats:'/api/system/stats'
 },
 apiKeys:{
  list:'/api/api-keys',
  save:(providerId:string)=>`/api/api-keys/${providerId}`,
  delete:(providerId:string)=>`/api/api-keys/${providerId}`,
  validate:(providerId:string)=>`/api/api-keys/${providerId}/validate`
 },
 providers:{
  health:'/api/providers/health',
  healthCheck:(providerId:string)=>`/api/providers/${providerId}/health`
 },
 navigator:{
  message:'/api/navigator/message',
  broadcast:'/api/navigator/broadcast'
 },
 globalCost:{
  settings:'/api/config/global-cost-settings',
  budgetStatus:'/api/cost/budget-status'
 },
 cost:{
  history:'/api/cost/history',
  summary:'/api/cost/summary',
  exportCsv:'/api/cost/export/csv',
  exportJson:'/api/cost/export/json'
 }
}as const
